packages/plasma-ui/src/components/Carousel/Carousel.tsx
packages/plasma-web/src/components/Carousel/Carousel.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.66.1-canary.20.2336920085.0
npm install @salutejs/plasma-core@1.58.1-canary.20.2336920085.0
npm install @salutejs/plasma-temple@1.67.2-canary.20.2336920085.0
npm install @salutejs/plasma-typo@0.5.1-canary.20.2336920085.0
npm install @salutejs/plasma-ui@1.103.2-canary.20.2336920085.0
npm install @salutejs/plasma-web@1.101.1-canary.20.2336920085.0
npm install @salutejs/plasma-cy-utils@0.11.1-canary.20.2336920085.0
yarn add @salutejs/plasma-b2c@1.66.1-canary.20.2336920085.0
yarn add @salutejs/plasma-core@1.58.1-canary.20.2336920085.0
yarn add @salutejs/plasma-temple@1.67.2-canary.20.2336920085.0
yarn add …
```

fix(plasma-ui, plasma-web): fix carousel context

---

packages/plasma-icons/package-lock.json
packages/plasma-icons/package.json

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.67.1-canary.24.2351066338.0
npm install @salutejs/plasma-icons@1.83.1-canary.24.2351066338.0
npm install @salutejs/plasma-temple@1.68.1-canary.24.2351066338.0
npm install @salutejs/plasma-ui@1.104.1-canary.24.2351066338.0
npm install @salutejs/plasma-web@1.102.1-canary.24.2351066338.0
yarn add @salutejs/plasma-b2c@1.67.1-canary.24.2351066338.0
yarn add @salutejs/plasma-icons@1.83.1-canary.24.2351066338.0
yarn add @salutejs/plasma-temple@1.68.1-canary.24.2351066338.0
yarn add @salutejs/plasma-ui@1.104.1-canary.24.2351066338.0
yarn add @salutejs/plasma-web@1.102.1-canary.24.2351066338.0
```
</details>

ci(plasma-icons): fix deps

---

website/plasma-ui-docs/versionsArchived.json
website/plasma-web-docs/versionsArchived.json

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.67.1-canary.23.2351610100.0
npm install @salutejs/plasma-icons@1.83.1-canary.23.2351610100.0
npm install @salutejs/plasma-temple@1.68.1-canary.23.2351610100.0
npm install @salutejs/plasma-ui@1.104.1-canary.23.2351610100.0
npm install @salutejs/plasma-web@1.102.1-canary.23.2351610100.0
yarn add @salutejs/plasma-b2c@1.67.1-canary.23.2351610100.0
yarn add @salutejs/plasma-icons@1.83.1-canary.23.2351610100.0
yarn add @salutejs/plasma-temple@1.68.1-canary.23.2351610100.0
yarn add @salutejs/plasma-ui@1.104.1-canary.23.2351610100.0
yarn add @salutejs/plasma-web@1.102.1-canary.23.2351610100.0
```
</details>

docs(plasma-web,plasma-ui): fix old versions url

---

packages/plasma-core/src/index.ts

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.67.1-canary.25.2351958186.0
npm install @salutejs/plasma-core@1.59.1-canary.25.2351958186.0
npm install @salutejs/plasma-icons@1.83.1-canary.25.2351958186.0
npm install @salutejs/plasma-temple@1.68.1-canary.25.2351958186.0
npm install @salutejs/plasma-typo@0.6.1-canary.25.2351958186.0
npm install @salutejs/plasma-ui@1.104.1-canary.25.2351958186.0
npm install @salutejs/plasma-web@1.102.1-canary.25.2351958186.0
npm install @salutejs/plasma-cy-utils@0.12.1-canary.25.2351958186.0
npm install @salutejs/plasma-sb-utils@0.58.1-canary.25.2351958186.0
yarn add @salutejs/plasma-b2c@1.67.1-canary.25.2351958186.0
yarn …
```

fix(plasma-core): unnecessary Price export

---

packages/plasma-ui/src/components/ProductCard/ProductCard.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.72.2-canary.61.2461820009.0
npm install @salutejs/plasma-ui@1.108.2-canary.61.2461820009.0
yarn add @salutejs/plasma-temple@1.72.2-canary.61.2461820009.0
yarn add @salutejs/plasma-ui@1.108.2-canary.61.2461820009.0
```
</details>

fix(plasma-ui): Fix overflow issue in `ProductCard` with media component

---

packages/plasma-ui/src/components/Pickers/TimePicker.tsx

Переоткрыл https://github.com/salute-developers/plasma/pull/32
До
После
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.71.0-canary.55.2448596215.0
npm install @salutejs/plasma-core@1.61.0-canary.55.2448596215.0
npm install @salutejs/plasma-icons@1.85.0-canary.55.2448596215.0
npm install @salutejs/plasma-temple@1.71.0-canary.55.2448596215.0
npm install @salutejs/plasma-typo@0.8.0-canary.55.2448596215.0
npm install @salutejs/plasma-ui@1.107.0-canary.55.2448596215.0
npm install @salutejs/plasma-web@1.106.0-canary.55.2448596215.0
npm install @salutejs/plasma-cy-utils@0.14.0-canary.55.2448596215.0
npm install …
```

feat(plasma-ui): TimePicker render optimization

---

packages/plasma-ui/src/components/ProductCard/ProductCard.tsx
packages/plasma-ui/src/components/ProductCard/ProductCardStepper.tsx

Переоткрыл https://github.com/salute-developers/plasma/pull/40
Вынес constant elements в переменные.
Добавил мемоизацию к styled component.
Использовал оптимизированный Stepper (он в отдельном PR).
До 3.8 ms
После 1.8 ms
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.74.0-canary.53.2517224761.0
npm install @salutejs/plasma-ui@1.110.0-canary.53.2517224761.0
yarn add @salutejs/plasma-temple@1.74.0-canary.53.2517224761.0
yarn add @salutejs/plasma-ui@1.110.0-canary.53.2517224761.0
```
</details>

feat(plasma-ui): ProductCard render optimization

---

packages/plasma-ui/src/components/Stepper/Stepper.hooks.ts
packages/plasma-ui/src/components/Stepper/Stepper.stories.tsx
packages/plasma-ui/src/components/Stepper/StepperButton.tsx

Переоткрыл: https://github.com/salute-developers/plasma/pull/43
Добавил мемоизацию в кнопки.
И убрал зависимость мемоизации функций, обработчиков нажатий, от значения степера.
До: 1ms
После: 0.5ms
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.74.0-canary.50.2516594509.0
npm install @salutejs/plasma-ui@1.110.0-canary.50.2516594509.0
yarn add @salutejs/plasma-temple@1.74.0-canary.50.2516594509.0
yarn add @salutejs/plasma-ui@1.110.0-canary.50.2516594509.0
```
</details>

feat(plasma-ui): Stepper render optimization

---

packages/plasma-ui/src/components/Tabs/TabItem.tsx
packages/plasma-ui/src/components/Tabs/Tabs.stories.tsx
packages/plasma-ui/src/components/Tabs/Tabs.tsx

Оптимизайия Tabs.
До :2.8 ms
После: 1.6 ms
Поправлен "баг" с потерей ключей - Создание элементом заменено на клонирование.
Переписана история, так чтобы сократить количество  перерисовок.
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.78.0-canary.76.2549466437.0
npm install @salutejs/plasma-temple@1.77.0-canary.76.2549466437.0
npm install @salutejs/plasma-ui@1.113.0-canary.76.2549466437.0
npm install @salutejs/plasma-web@1.113.0-canary.76.2549466437.0
yarn add @salutejs/plasma-b2c@1.78.0-canary.76.2549466437.0
yarn add @salutejs/plasma-temple@1.77.0-canary.76.2549466437.0
yarn add @salutejs/plasma-ui@1.113.0-canary.76.2549466437.0
yarn add …
```

feat(plasma-ui): Tabs render optimization

---

packages/plasma-b2c/package-lock.json
packages/plasma-b2c/package.json

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.78.1-canary.82.2571193920.0
yarn add @salutejs/plasma-b2c@1.78.1-canary.82.2571193920.0
```
</details>

fix(plasma-b2c): missing react-draggable dep

---

packages/plasma-ui/.storybook/main.js
packages/plasma-ui/.storybook/preview.js
packages/plasma-ui/package-lock.json
packages/plasma-ui/package.json
packages/plasma-ui/src/components/Stepper/Stepper.stories.tsx
packages/plasma-ui/src/components/Stepper/performance-results/controls-stepper--custom-assembly.json

Добавил  addon performance для Stepper
Написал Interactions для переключения значения
Зафиксировал результаты прогона аддона на сбилженном сторебуке.
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.79.0-canary.84.2577315189.0
npm install @salutejs/plasma-core@1.63.0-canary.84.2577315189.0
npm install @salutejs/plasma-icons@1.88.0-canary.84.2577315189.0
npm install @salutejs/plasma-temple@1.78.0-canary.84.2577315189.0
npm install @salutejs/plasma-typo@0.10.0-canary.84.2577315189.0
npm install @salutejs/plasma-ui@1.114.0-canary.84.2577315189.0
npm install @salutejs/plasma-web@1.114.0-canary.84.2577315189.0
npm install …
```

feat(plasma-ui): Performance addon for Stepper

---

packages/plasma-ui/src/components/Tabs/Tabs.stories.tsx
packages/plasma-ui/src/components/Tabs/performance-results/controls-tabs--default.json

Добавил https://storybook.js.org/addons/storybook-addon-performance
Написал Interactions для переключения табов
Зафиксировал результаты прогона  аддона на сбилженном сторебуке.
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.81.0-canary.80.2590033861.0
npm install @salutejs/plasma-temple@1.81.0-canary.80.2590033861.0
npm install @salutejs/plasma-ui@1.116.0-canary.80.2590033861.0
npm install @salutejs/plasma-web@1.116.0-canary.80.2590033861.0
yarn add @salutejs/plasma-b2c@1.81.0-canary.80.2590033861.0
yarn add @salutejs/plasma-temple@1.81.0-canary.80.2590033861.0
yarn add @salutejs/plasma-ui@1.116.0-canary.80.2590033861.0
yarn add …
```

feat(plasma-ui): Performance addon for Tabs

---

packages/plasma-web/src/components/Calendar/CalendarBase.tsx
packages/plasma-web/src/components/Calendar/CalendarMonths.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.83.1-canary.89.2636049096.0
npm install @salutejs/plasma-web@1.117.1-canary.89.2636049096.0
yarn add @salutejs/plasma-b2c@1.83.1-canary.89.2636049096.0
yarn add @salutejs/plasma-web@1.117.1-canary.89.2636049096.0
```
</details>

fix(plasma-web): Fix `Calendar` problems: unexpected popup close; don't updated change year and month  

---

packages/plasma-web/src/components/Input/Input.tsx
packages/plasma-web/src/components/TextArea/TextArea.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.84.1-canary.103.2702507967.0
npm install @salutejs/plasma-web@1.118.1-canary.103.2702507967.0
yarn add @salutejs/plasma-b2c@1.84.1-canary.103.2702507967.0
yarn add @salutejs/plasma-web@1.118.1-canary.103.2702507967.0
```
</details>

fix(plasma-web): Fix border visible for `TextField` and `TextArea`

---

packages/plasma-core/src/components/Tabs/TabItem.tsx
packages/plasma-core/src/components/Tabs/Tabs.component-test.tsx
packages/plasma-ui/src/components/Tabs/Tabs.component-test.tsx
packages/plasma-web/src/components/Tabs/Tabs.component-test.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.85.1-canary.106.2718047501.0
npm install @salutejs/plasma-core@1.64.3-canary.106.2718047501.0
npm install @salutejs/plasma-icons@1.90.2-canary.106.2718047501.0
npm install @salutejs/plasma-temple@1.84.3-canary.106.2718047501.0
npm install @salutejs/plasma-typo@0.11.3-canary.106.2718047501.0
npm install @salutejs/plasma-ui@1.118.3-canary.106.2718047501.0
npm install @salutejs/plasma-web@1.118.3-canary.106.2718047501.0
npm install @salutejs/plasma-cy-utils@0.17.3-canary.106.2718047501.0
npm install @salutejs/plasma-sb-utils@0.63.3-canary.106.2718047501.0
yarn add …
```

fix(plasma-core): Fix `Tab` control behavior for Safari

---

packages/plasma-b2c/src/components/Modal/Modal.stories.mdx

```
WARN Module build failed (from ./node_modules/babel-loader/lib/index.js):
WARN SyntaxError: Projects/plasma/packages/plasma-b2c/src/components/Modal/Modal.stories.mdx: Identifier '_LiveDemo_' has already been declared. (98:13)
WARN 
WARN    96 | _LiveDemo_.storyName = 'LiveDemo';
WARN    97 |
WARN >  98 | export const _LiveDemo_ = stories.LiveDemo;
WARN       |              ^
WARN    99 | _LiveDemo_.storyName = 'LiveDemo';
WARN   100 |
WARN   101 | const componentMeta = { title: 'Controls/Modal', decorators: [InSpacingDecorator], component: Modal, includeStories: ["_LiveDemo_","_LiveDemo_"],  };
```
<details>
<br />
```bash
npm install …
```

ci(plasma-b2c): fix storybook build

---

packages/plasma-web/src/components/Modal/Modal.stories.tsx
packages/plasma-web/src/components/Modal/Modal.tsx
packages/plasma-web/src/components/Modal/ModalView.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.87.1-canary.126.2838696273.0
npm install @salutejs/plasma-web@1.120.1-canary.126.2838696273.0
yarn add @salutejs/plasma-b2c@1.87.1-canary.126.2838696273.0
yarn add @salutejs/plasma-web@1.120.1-canary.126.2838696273.0
```
</details>

fix(plasma-web): fix modal height on ios safari

---

packages/plasma-ui/src/components/Confirm/Confirm.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.87.1-canary.131.2861368107.0
npm install @salutejs/plasma-core@1.65.1-canary.131.2861368107.0
npm install @salutejs/plasma-icons@1.91.1-canary.131.2861368107.0
npm install @salutejs/plasma-temple@1.86.1-canary.131.2861368107.0
npm install @salutejs/plasma-typo@0.12.1-canary.131.2861368107.0
npm install @salutejs/plasma-ui@1.120.1-canary.131.2861368107.0
npm install @salutejs/plasma-web@1.120.1-canary.131.2861368107.0
npm install @salutejs/plasma-cy-utils@0.18.1-canary.131.2861368107.0
npm install @salutejs/plasma-sb-utils@0.64.1-canary.131.2861368107.0
yarn add …
```

fix(plasma-ui): Fix gap issue between buttons in `Confirm` component

---

packages/plasma-ui/src/components/Marquee/Marquee.tsx
packages/plasma-ui/src/components/Slider/SliderBase.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.87.1-canary.132.2865600299.0
npm install @salutejs/plasma-core@1.65.1-canary.132.2865600299.0
npm install @salutejs/plasma-icons@1.91.1-canary.132.2865600299.0
npm install @salutejs/plasma-temple@1.86.1-canary.132.2865600299.0
npm install @salutejs/plasma-typo@0.12.1-canary.132.2865600299.0
npm install @salutejs/plasma-ui@1.120.1-canary.132.2865600299.0
npm install @salutejs/plasma-web@1.120.1-canary.132.2865600299.0
npm install @salutejs/plasma-cy-utils@0.18.1-canary.132.2865600299.0
npm install @salutejs/plasma-sb-utils@0.64.1-canary.132.2865600299.0
yarn add …
```

fix(plasma-ui): Replace useLayoutEffect to useIsomorphicLayoutEffect for `Slider` and `Marquee`

---

packages/plasma-ui/src/components/Cell/Cell.tsx
packages/plasma-ui/src/components/Header/Header.tsx
packages/plasma-ui/src/components/Header/HeaderRoot.tsx
packages/plasma-ui/src/components/Header/NeuHeader.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.88.0-canary.143.2925472697.0
npm install @salutejs/plasma-ui@1.122.0-canary.143.2925472697.0
yarn add @salutejs/plasma-temple@1.88.0-canary.143.2925472697.0
yarn add @salutejs/plasma-ui@1.122.0-canary.143.2925472697.0
```
</details>

feat(plasma-ui): Add forwardRef for `Header`,`NeuHeader` and `Cell` components

---

packages/plasma-ui/src/hooks/useRemoteListener.ts

<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.90.0-canary.146.2948397596.0
npm install @salutejs/plasma-ui@1.124.0-canary.146.2948397596.0
yarn add @salutejs/plasma-temple@1.90.0-canary.146.2948397596.0
yarn add @salutejs/plasma-ui@1.124.0-canary.146.2948397596.0
```
</details>

feat(plasma-ui): Add options for eventListeners in useRemoteListener hook

---

packages/plasma-ui/src/components/Pickers/TimePicker.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.90.2-canary.151.2963356147.0
npm install @salutejs/plasma-ui@1.124.2-canary.151.2963356147.0
yarn add @salutejs/plasma-temple@1.90.2-canary.151.2963356147.0
yarn add @salutejs/plasma-ui@1.124.2-canary.151.2963356147.0
```
</details>

fix(plasma-ui): Fix setState while rendering other component for `TimePicker` component

---

packages/plasma-ui/src/components/Device/DeviceDetection.tsx

<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.90.2-canary.153.2969385840.0
npm install @salutejs/plasma-ui@1.124.2-canary.153.2969385840.0
yarn add @salutejs/plasma-temple@1.90.2-canary.153.2969385840.0
yarn add @salutejs/plasma-ui@1.124.2-canary.153.2969385840.0
```
</details>

fix(plasma-ui): Add sizes style for responsive typo in `DeviceThemeProvider`

---

packages/plasma-web/src/components/Typography/Headline/index.ts

fixes #140 
[colors--canary.164.3051066417.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.164.3051066417.xml)  
[PlasmaTokensColor--canary.164.3051066417.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.164.3051066417.swift)
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.93.1-canary.164.3051066417.0
npm install @salutejs/plasma-web@1.126.1-canary.164.3051066417.0
yarn add @salutejs/plasma-b2c@1.93.1-canary.164.3051066417.0
yarn add @salutejs/plasma-web@1.126.1-canary.164.3051066417.0
```
</details>

fix(plasma-web): Headline5 tag h5

---

packages/plasma-core/src/components/Carousel/utils.ts

[colors--canary.162.3045568868.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.162.3045568868.xml)  
[PlasmaTokensColor--canary.162.3045568868.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.162.3045568868.swift)
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.93.1-canary.162.3045568868.0
npm install @salutejs/plasma-core@1.70.1-canary.162.3045568868.0
npm install @salutejs/plasma-icons@1.96.1-canary.162.3045568868.0
npm install @salutejs/plasma-temple@1.93.1-canary.162.3045568868.0
npm install …
```

fix(plasma-ui): restore scroll in translateToIndex

---

packages/plasma-ui/src/components/Carousel/Carousel.stories.tsx
packages/plasma-ui/src/components/Device/DeviceDetection.tsx
packages/plasma-ui/src/components/Pickers/Picker.tsx
packages/plasma-ui/src/components/ProductCard/ProductCard.tsx
packages/plasma-ui/src/components/Slider/SliderBase.tsx
packages/plasma-ui/src/hooks/index.ts
packages/plasma-ui/src/hooks/useDeviceKind.ts
packages/plasma-ui/src/hooks/useThemeContext.ts
packages/plasma-ui/src/utils/deviceDetection.ts
packages/plasma-ui/src/utils/index.ts

В **storybook** методы типа `isSberBox` не реагировали на изменения типа устройства.
Теперь у нас есть централизованный способ получения типа устройства на основе контекста темы.
[sbermarket_ios-swift--canary.177.3187477830.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.177.3187477830.swift)  
[sbermarket_kotlin--canary.177.3187477830.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.177.3187477830.kt)  
[sbermarket_react-native--canary.177.3187477830.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.177.3187477830.ts) …

feat(plasma-ui): device kind processing

---

packages/plasma-icons/package-lock.json
packages/plasma-icons/package.json
utils/plasma-sb-utils/package-lock.json
utils/plasma-sb-utils/package.json

@Yeti-or @neretin-trike 
В мастере сейчас из-за того что у 2 пакетов, `plasma-sb-utils` и `plasma-icons` стоит версия 1.74.0 не проходят pipelines в моих PR.   
[sbermarket_ios-swift--canary.179.3189458800.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.179.3189458800.swift)  
[sbermarket_kotlin--canary.179.3189458800.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.179.3189458800.kt)  
[sbermarket_react-native--canary.179.3189458800.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.179.3189458800.ts)  
[colors--canary.179.3189458800.xml](https://github.com/salute-developer …

chore: bump @salutejs/plasma-core version for plasma-sb-utils/plasma-icons

---

packages/plasma-ui/src/components/Carousel/Carousel.stories.tsx
packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx

addDecorator в новых версиях (см https://github.com/salute-developers/plasma/pull/194) добавляет декораторы строго глобально, и при текущем использовании будет навешиваться на стори несколько раз. Это вызывает выполнение сразу нескольких бенчмарков одновременно для текущей стори, что аффектит измерения. Не меняет поведение на текущей версии
[colors--canary.248.3564455048.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.248.3564455048.xml)  
[color_sbermarket_ios-swift--canary.248.3564455048.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.248.3564455048.swift)  
[color_sbermarket_kotlin--canary.248.3564455048.kt](https://github.com/salute- …

fix(plasma-ui): fix using sb-addon-performance usages for future storybook versions

---

packages/plasma-tokens-b2b/data/ds.ts
packages/plasma-tokens-b2c/data/ds.ts
packages/plasma-tokens-web/data/ds.ts
packages/plasma-tokens/data/ds.ts

Добавляем новые токены для overlay в **plasma-tokens/-web/-b2c/-b2b**
Команда `npm run build` выдает результат для новых токенов: 
```js
exports.overlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.overlayHard = 'rgba(8, 8, 8, 0.9)';
exports.overlayBlur = 'rgba(35, 35, 35, 0.2)';
exports.darkOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.darkOverlayHard = 'rgba(8, 8, 8, 0.9)';
exports.darkOverlayBlur = 'rgba(35, 35, 35, 0.2)';
exports.lightOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.lightOverlayHard = 'rgba(8, 8, 8, 0.9)';
exports.lightOverlayBlur = 'rgba(35, 35, 35, 0.28)';
exports.inverseOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.inverseOverlayHard = 'rgba(8, 8, 8, 0.9)';
exports.inverseOverlayBlur = 'rgba(35, 35, 35, 0.28)';
``` 
```css
"--plasma-colors-overlaySoft": "rgba(8, 8, 8, 0.56)", …
```

feat(plasma-tokens-web/b2b/b2c/ui): Add overlay tokens

---

packages/plasma-tokens-b2b/data/ds.ts
packages/plasma-tokens-b2c/data/ds.ts
packages/plasma-tokens-web/data/ds.ts
packages/plasma-tokens/data/ds.ts
utils/plasma-tokens-utils/src/types.ts

Необходимо изменить значения для токена overlay в plasma-tokens/-web/-b2c/-b2b. 
Новые значения для: 
dark theme 
```js
exports.overlayBlur = 'rgba(23, 23, 23, 0.28)';
exports.darkOverlayBlur = 'rgba(23, 23, 23, 0.28)';
exports.lightOverlayBlur = 'rgba(23, 23, 23, 0.28)';
exports.inverseOverlayBlur = 'rgba(23, 23, 23, 0.28)';
exports.overlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.overlayHard = 'rgba(8, 8, 8, 0.9)';
exports.darkOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.darkOverlayHard = 'rgba(8, 8, 8, 0.9)';
exports.lightOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.lightOverlayHard = 'rgba(8, 8, 8, 0.9)';
exports.inverseOverlaySoft = 'rgba(8, 8, 8, 0.56)';
exports.inverseOverlayHard = 'rgba(8, 8, 8, 0.9)';
```
light theme 
```js
exports.overlayBlur = 'rgba(35, 35, 35, 0.2)'; …
```

fix(plasma-tokens-web/b2b/b2c/ui): Change overlay tokens

---

package.json
packages/plasma-b2c/package.json
packages/plasma-core/package.json
packages/plasma-temple/package.json
packages/plasma-ui/package.json
packages/plasma-web/package.json
utils/plasma-cy-utils/package.json

[colors--canary.282.3947329431.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.282.3947329431.xml)  
[color_metro_ios-swift--canary.282.3947329431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.282.3947329431.swift)  
[color_metro_kotlin--canary.282.3947329431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.282.3947329431.kt)  
[color_metro_react-native--canary.282.3947329431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.282.3947329431.ts)  
[color_sbermarket_ios-swift--canary.282.3947329431.swift](https://github.com/ …

ci: improve ts-coverage report

---

packages/plasma-web/src/components/Calendar/Calendar.stories.tsx

В примере для storybook необходимо показать как можно скрыть нативный date picker для браузера Safari. 
Было: 
Стало:
[colors--canary.287.3993143077.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.287.3993143077.xml)  
[color_metro_ios-swift--canary.287.3993143077.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.287.3993143077.swift)  
[color_metro_kotlin--canary.287.3993143077.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.287.3993143077.kt)  
[color_metro_react-native--canary.287.3993143077.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_r …

fix(plasma-web): prevent default safari datepicker appearance

---

packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
packages/plasma-b2c/src/components/TextField/TextField.tsx
packages/plasma-ui/src/components/TextField/TextField.stories.tsx
packages/plasma-ui/src/components/TextField/TextField.tsx
packages/plasma-web/src/components/Input/Input.tsx
packages/plasma-web/src/components/TextField/TextField.stories.tsx
packages/plasma-web/src/components/TextField/TextField.tsx

Необходимо добавить для компонентов TextField и Input обработку события по нажатию клавиши Enter. 
По [мотивам ant-design Input](https://github.com/ant-design/ant-design/blob/master/components/input/Search.tsx#L72-L77)
**Раньше:** 
Пользователю приходилось писать каждый раз **свою реализацию** такого обработчика.
**Стало:** 
```jsx
<TextField value={value} onSearch={onSearch} />
```
[colors--canary.294.4060402146.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.294.4060402146.xml)  
[color_metro_ios-swift--canary.294.4060402146.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.294.4060402146.swift) …

feat(plasma-web/ui): Handling the onSearch event on pressing Enter

---

packages/plasma-b2c/src/components/Toast/Toast.stories.tsx
packages/plasma-b2c/src/components/Toast/index.ts
packages/plasma-core/src/components/Toast/Toast.types.ts
packages/plasma-core/src/components/Toast/ToastBase.component-test.tsx
packages/plasma-core/src/components/Toast/ToastContext.tsx
packages/plasma-core/src/components/Toast/ToastProvider.tsx
packages/plasma-ui/src/components/Toast/Toast.stories.tsx
packages/plasma-web/src/components/Toast/Toast.stories.tsx
packages/plasma-web/src/components/Toast/index.ts
website/plasma-ui-docs/docs/components/Toast.mdx
website/plasma-web-docs/docs/components/Toast.mdx

Добавленна возможность прокинуть callback на hideToast.  
Так же сделали overload метода `showToast`.
Так же возможность прокинуть `onHide` есть только в новой версии showToast.
Было: Аргументы передовались **inline**
Стало: Теперь как объект.
-----------------------------
[colors--canary.319.4163108583.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.319.4163108583.xml)  
[color_metro_ios-swift--canary.319.4163108583.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.319.4163108583.swift)  
[color_metro_kotlin--canary.319.4163108583.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.319.416 …

feat(plasma-core/ui): Pass onHide callback for hideToast handler

---

packages/plasma-core/src/utils/react.ts

– раньше ф-ия проверяла наличие `flushSync` но она присутствует уже в 16 реакте. Теперь мы проверяем совпадение по мажорной версии
[colors--canary.380.4322277405.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.380.4322277405.xml)  
[color_metro_ios-swift--canary.380.4322277405.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.380.4322277405.swift)  
[color_metro_kotlin--canary.380.4322277405.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.380.4322277405.kt)  
[color_metro_react-native--canary.380.4322277405.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/ …

fix(plasma-core): fix IS_REACT_18

---

cypress/config/b2b-config.json
cypress/config/b2c-config.json
cypress/config/ui-config.json
cypress/config/web-config.json

Временно выключаем проверки доступность в **cypress** тестах. 
Чуть позже включим уже с другой конфигурацией и понятным отчетом.     
[colors--canary.403.4401566688.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.403.4401566688.xml)  
[color_metro_ios-swift--canary.403.4401566688.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.403.4401566688.swift)  
[color_metro_kotlin--canary.403.4401566688.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.403.4401566688.kt)  
[color_metro_react-native--canary.403.4401566688.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-cana …

chore(plasma-*): disabled axe check

---

package.json

В этом PR исправляется неправильный формат скрипта установленный в #417. 
` [[ -z $CI ]] && husky install || echo skip husky` 
--------
`test ! -n \"$CI\" && husky install || echo skip husky`
--------

ci: skip husky when run CI pipeline

---

packages/plasma-ui/src/components/Header/HeaderLogo.tsx

В React 18 и начиная с @types/react@18.0.25 появились типы:
**onResize**: An [Event handler](https://react.dev/reference/react-dom/components/common#event-handler) function. Fires when video changes size.
**onResizeCapture**: A version of onResize that fires in the [capture phase.](https://react.dev/learn/responding-to-events#capture-phase-events)
**nonce**:  [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce)
Для пользователей оставшихся на, как пример: 
```json
{
"@types/react": "16.9.38",
"react": "17.0.2",
"react-dom": "17.0.2"
}
``` 
ломается компилция TS 
Явно сузить тип для `HeaderLogoProps` и исключить ` 'onResize' | 'onResizeCapture' | 'nonce'`. 
Так как под капотом TS через Pick выбирает все свойства и атрибуты у `Pick<import("@salutejs/plasma-core") …

fix(plasma-ui): Omit types for HeaderLogo

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-hope/api/plasma-hope.api.md
packages/plasma-hope/src/components/Grid/Container.tsx
packages/plasma-web/api/plasma-web.api.md

Добавлено прокидывание всех пропсов в компонент, т.к. стилизация (а именно className и style) не применяются, если его оборачивать в style-component. 
Так же компонент обёрнут в forwardRef для возможности использовать свойство `ref`.
[colors--canary.446.4535244348.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.446.4535244348.xml)  
[color_metro_ios-swift--canary.446.4535244348.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.446.4535244348.swift)  
[color_metro_kotlin--canary.446.4535244348.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.446.4535244348.kt) …

fix(plasmas-hope): Fix `Container` component for rest props in Grid

---

website/plasma-website/components/main/Product.tsx
website/plasma-website/components/main/ProductList.tsx
website/plasma-website/components/roster/Main.tsx

После дизайн ревью были исправлены следующие места:
1. Добавлен отступ снизу главного блока;
2. Уменьшенно расстояние между версией релиза и датой;
3. Исправлена страница с икокнами: раньше свойство для грида не применялось, поэтому вместо `as`  использовал `forwardedAs`
[colors--canary.452.4545613906.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.452.4545613906.xml)  
[color_metro_ios-swift--canary.452.4545613906.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.452.4545613906.swift)  
[color_metro_kotlin--canary.452.4545613906.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.452.45456 …

fix(plasma-website): Fix by design review

---

packages/plasma-hope/src/components/Tooltip/Tooltip.tsx

При изменения позиции контейнера, где находиться компонент с `Tooltip` при его появление **рассчитывались неправильные отступы**.
[update-forceupdate-and-state](https://popper.js.org/react-popper/v2/hook/#update-forceupdate-and-state)
[Instance](https://popper.js.org/docs/v2/constructors/#instance)   
[colors--canary.461.4604191287.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.461.4604191287.xml)  
[color_sberHealth_ios-swift--canary.461.4604191287.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.461.4604191287.swift)  
[color_sberHealth_kotlin--canary.461.4604191287.kt](https://github.com/salute-developers/plasma/releases/download/v0.0 …

fix(plasma-hope): Handling correct offset 

---

packages/plasma-ui/src/components/Pickers/DatePicker.tsx
packages/plasma-ui/src/components/Pickers/Picker.tsx
packages/plasma-ui/src/components/Pickers/PickerItem.tsx
packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
packages/plasma-ui/src/components/Pickers/TimePicker.tsx
website/plasma-ui-docs/docs/components/Pickers.mdx

В Safari iOS 14.5 и ниже наблюдаются следующее
- ложные срабатывания onChange 
- flicking/мерцания/дёргание дочерних элементов компонента
Важное замечание - проблемы **взаимосвязаны**.
------
[colors--canary.464.4626740634.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.464.4626740634.xml)  
[color_sberHealth_ios-swift--canary.464.4626740634.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.464.4626740634.swift)  
[color_sberHealth_kotlin--canary.464.4626740634.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.464.4626740634.kt) …

fix(plasma-ui): [Picker] Fix flicking and fake onChange in Safari 14.5 and bellow

---

packages/plasma-core/src/components/Button/Button.component-test.tsx

При изменении реализации наших компонентов хотелось бы понимать и контролировать ту часть API, что может сломаться. 
Например свойство `as` **некорректно** работает на компонентах, которые обернуты в **styled**.
Например:
```jsx
const StyledButton = styled(Button)`
color: 'red';
`;
<StyledButton as="a">Hello Plasma</StyledButton>
```
в этом случае мы не получим ожидаемого результата.
Добавленный тест укажет на это.

feat(plasma-core): [Button] Add test for prop 'as'

---

packages/plasma-tokens/data/ds.ts
packages/plasma-tokens/data/themes/sbermarket_winelab.json
packages/plasma-tokens/generate.ts
packages/plasma-tokens/lib/generator/formatters/colorIosSwift.ts
packages/plasma-tokens/lib/generator/formatters/colorKotlin.ts
packages/plasma-tokens/lib/generator/formatters/colorReactNative.ts
packages/plasma-tokens/lib/generator/types.ts
packages/plasma-tokens/lib/themeBuilder/generateTokens.ts
packages/plasma-tokens/lib/themeBuilder/mapDeprecatedTokens.ts
packages/plasma-tokens/lib/themeBuilder/utils.ts
utils/plasma-tokens-utils/src/generators/generateColorThemes.ts
utils/plasma-tokens-utils/src/generators/generateFile.ts
utils/plasma-tokens-utils/src/utils/getDeprecatedVars.ts
utils/plasma-tokens-utils/src/utils/index.ts
utils/plasma-tokens-utils/src/utils/upperFirstLetter.ts

Согласно новой конвенции именования тем, принимается следующий формат:
`<название_темы>_<вид_темы>__<модификаторы_темы>` или `<название_темы>__<модификаторы_темы>`.
Так сейчас выглядит список тем с поддержкой обратной совместимости:
В случае использовании старых названий тем они будут помечены как `deprecated`, с комментарием, какое название вместо этого лучше использовать:
Так же для улучшения консистентности, для тем, которые используются в canvas приложениях, был добавлен префикс `salutejs`.
[colors--canary.475.4680213255.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.475.4680213255.xml)  
[color_sberHealth_ios-swift--canary.475.4680213255.swift](https://github.com/salute-developers/plasma/releases/dow …

feat(plasma-tokens,plama-tokens-utils): Update theme name convention

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Grid/Container.tsx
packages/plasma-b2c/src/components/Grid/Grid.stories.tsx
packages/plasma-hope/api/plasma-hope.api.md
packages/plasma-hope/src/components/Grid/types.ts
packages/plasma-hope/src/components/Grid/views/applyMaxWidth.tsx
packages/plasma-hope/src/components/Grid/views/b2c/ContainerB2C.tsx
packages/plasma-hope/src/components/Grid/views/web/ContainerWeb.tsx
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Grid/Container.tsx
packages/plasma-web/src/components/Grid/Grid.stories.tsx

Добавлена возможность настроить максимальную ширину компонента `Container`, входящего  в `Grid`, с помощью свойства `maxWidth`:
``` js
<Container maxWidth="60rem">
/* необходимые Row, Col */
</Container>
```
[color_sberHealth_ios-swift--canary.495.4829781543.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.495.4829781543.swift)  
[color_sberHealth_kotlin--canary.495.4829781543.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.495.4829781543.kt)  
[color_sberHealth_react-native--canary.495.4829781543.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.495.48297 …

feat(plasma-hope): maxWidth for Grid

---

packages/plasma-ui/src/components/Button/ActionButton.tsx

[color_sberHealth_ios-swift--canary.506.4989786425.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.506.4989786425.swift)  
[color_sberHealth_kotlin--canary.506.4989786425.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.506.4989786425.kt)  
[color_sberHealth_react-native--canary.506.4989786425.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.506.4989786425.ts)  
[color_sbermarket_business_ios-swift--canary.506.4989786425.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.506.49897 …

fix(plasma-ui): [ActionButtonProps] Omit 'onResize', 'onResizeCapture', 'nonce'

---

.github/workflows/clean-pr-documentation.yml
.github/workflows/cleanup-cache-pr.yml
.github/workflows/cypress-ct-17.yml
.github/workflows/cypress-ct.yml
.github/workflows/documentation-main.yml
.github/workflows/documentation-pr.yml
.github/workflows/examples-pr.yml
.github/workflows/examples.yml
.github/workflows/performance-test.yml
.github/workflows/release.yml
.github/workflows/tests-17.yml
.github/workflows/tests.yml
.github/workflows/theme-builder-pr.yml
.github/workflows/theme-builder.yml
.github/workflows/typescript-coverage.yml
.github/workflows/versionate-docs.yml

Необходимо ускорить наш CI. 
Один из способов это, начинать использовать **cache** для ускорения установки зависимостей.
> Access restrictions provide cache isolation and security by creating a logical boundary between different branches or tags. > Workflow runs can restore caches created in either the current branch or the default branch (usually main). 
> If a workflow run is triggered for a pull request, it can also restore caches created in the base branch, including base branches of forked repositories.
[actions/setup-node](
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#working-with-lockfiles)
[actions/cache ](https://github.com/actions/cache)
[restrictions-for-accessing-a-cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed- …

ci: Enable cache for install dependencies

---

packages/plasma-core/src/components/Popup/Popup.tsx
packages/plasma-hope/src/components/Tooltip/Tooltip.tsx

Исправлено поведение компонентов `Tooltip` и `Popup`, при использовании которых при изменении стейта возникала ошибка: Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task. 
Это связано с тем, что в новой версии библиотеки `popper`  метод `forceUpdate` содержит в себе `flushSync` и [приводит](https://github.com/floating-ui/react-popper/issues/458) к повторному рендеру компонента, который уже находится в процессе рендера. 
[color_sberHealth_ios-swift--canary.554.5210791882.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.554.5210791882.swift) …

fix(plasma-core, plasma-hope): Add promise resolve for forceUpdate method in `Popup` and `Tooltip` components

---

.github/workflows/performance-test-base.yml
.github/workflows/performance-test-pr.yml
.gitignore
package-lock.json
package.json
perftool.config.mts

**[Hotfix]: Into master**
Дубликат этого PR - #519
>1. update perftool
>2. add base branch workflow for caching
>3. update perftest workflow to use cache
>4. return typescript@4.0.8
>5. remove unnecessary prepare repository step
>6. use one thread for perftool, use 20 retries

ci: add cache for perftool tasks

---

.github/workflows/typescript-coverage.yml
utils/plasma-tokens-native/config.ts
utils/plasma-tokens-native/src/generator/formatters/colorXML.ts
utils/plasma-tokens-native/src/generator/formatters/index.ts
utils/plasma-tokens-native/src/generator/index.ts
utils/plasma-tokens-native/src/generator/transformers/gradientXML.ts
utils/plasma-tokens-native/src/generator/transformers/index.ts

Добавлена генерация наборов токенов для `Android` в формате XML, а так же поддержка сложных (многослойных) градиентов.
Добавлено исключение в воркфлоу `typescript-coverage` на шаге "Lerna bootstrap" для пакетов plasma-tokens-*, т.к. в них не выполняется этот скрипт.
[color_asdk_ios-swift--canary.565.5387372327.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.565.5387372327.swift)  
[color_asdk_kotlin--canary.565.5387372327.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.565.5387372327.kt)  
[color_asdk_react-native--canary.565.5387372327.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-n …

feat(plasma-tokens-native): Add generate complex gradient for Android

---

utils/plasma-tokens-native/src/generator/formatters/colorIosSwift.ts
utils/plasma-tokens-native/src/generator/formatters/colorXML.ts
utils/plasma-tokens-native/src/generator/transformers/gradientSwift.ts
utils/plasma-tokens-native/src/generator/transformers/gradientXML.ts
utils/plasma-tokens-native/src/types.ts
website/plasma-theme-builder/src/api/githubAPIMethods.ts
website/plasma-theme-builder/src/components/Generator/Generator.tsx
website/plasma-theme-builder/src/components/GradientTokenSwiftLayer/GradientTokenSwiftLayer.tsx
website/plasma-theme-builder/src/components/GradientTokenValue/GradientTokenValue.tsx
website/plasma-theme-builder/src/components/GradientTokenXMLLayer/GradientTokenXMLLayer.tsx
website/plasma-theme-builder/src/components/TokenForm/TokenForm.tsx
website/plasma-theme-builder/src/hooks/useRunGithubPRProcess.ts
website/plasma-theme-builder/src/utils/gradient.ts

Добавлена поддержка множественных цветов у одного слоя токеах градиента для веб-сервиса Theme Builder и генераторов для XML и Swift файлов.
Пример поддерживаемого формата:
```css
linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.015) 17.19%, rgba(255, 255, 255, 0.052) 40.24%, rgba(255, 255, 255, 0.06) 51.17%, rgba(255, 255, 255, 0.052) 62.12%, rgba(255, 255, 255, 0.015) 82.81%, rgba(255, 255, 255, 0) 100%), rgba(255, 255, 255, 0.12)
```
Обновлён шаблон генерации набора токенов цветов для Swift файлов. 
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.626.5623261451.swift'>color_a …

feat(plasma-theme-builder, plasma-tokens): Add support multiple color in gradient

---

.github/workflows/required-primary-checks.yml
packages/plasma-hope/src/components/Button/Button.tsx

Разделили первичные и важные проверки, такие как Lint и Unit tests,  в рамках одного workflow на две разные jobs
Для атомарности.  
**Unit tests** запускается с помощью `lerna run test` и поэтому мы можем использовать флаг **`--since`** и для `lerna bootstrap`, и для самой команды запуска тестов. 
А вот **Lint** запускается для всей монорепы, и так получается что флаг `--since` уже мешает и вносит проблемы, в виде неустановленных пакетов. 
Поэтому для этой проверки оставили **полный** bootstrap.   
1. plasma-core
2. plasma-web
3. plasma-tokens-utils          
Ни в одном сценарии **не было** ошибки связной с неустановленным/отсутствующим пакетом.    
https://github.com/salute-developers/plasma/actions/workflows/tests.yml?query=branch%3Aci_refactoring_tests-workflow
--------- 
<details> …

plasm-infra: Split lint and unit tests to different jobs 

---

.github/workflows/documentation-main.yml

Используем флаг - `NODE_OPTIONS=--openssl-legacy-provider` для шага сборки документации.  
Если не использовать этот флаг, то будет ошибка - [error-0308010c-digital-envelope-routines-unsupported](https://sebhastian.com/error-0308010c-digital-envelope-routines-unsupported/)
Более детально описано тут - #594

plasma-infra: Fix "Main Documentation and Storybook" workflow

---

.github/workflows/performance-test-pr.yml
scripts/perftool-send-report.js

1) Фиксит падение отправки в кликхаус (отсутствие staticTaskChange) (по мотивам https://github.com/salute-developers/plasma/actions/runs/5821423853/job/15783925109?pr=648). + не делает запрос если нечего отправлять
2) Добавляет создание кэша в ПРном прогоне базовой ветки (см https://github.com/salute-developers/plasma/pull/644#discussion_r1289868395)

Fix perftest workflow

---

.github/actions/update-package-lock/action.yml
.github/workflows/publish-canary.yml
.github/workflows/publish-common.yml
package.json

Добавлен GitHub token для корректной работы action - "Update package-lock files after publish RC or latest version"
Как оказалось secrets **не наследуются** для action(using: "composite"). 
Поэтому был добавлен соответствующий `inputs.token`

plasma-infra: Pass GitHub token to action

---

.github/workflows/performance-test-base.yml
.github/workflows/performance-test-pr.yml

С s3 начали приходить файлики с некорректными правами доступа/владельцем, причина внешняя, вероятнее всего сменился пользователь на виртуалке. Фикс заключается в удалении пермишенов при загрузке-выгрузке на s3, соответственно при записи файлов устанавливаются дефолтные флаги.

Fix perftool cache sync

---

.github/workflows/publish-canary.yml
lerna.json

Выключили флаг `--since` для workflow "Publish Canary" 
Столкнулись с тем что во время публикации версии ловим ошибку.
Если коротко то 
1. Делаем `npx lerna bootstrap --since=$(git merge-base --fork-point origin/dev)`
1.1 Собрали только то что изменили
2. Публикация пытается собрать все и падает с ошибкой     
Если правильно понял - https://github.com/intuit/auto/issues/2081 
Похоже на наш кейс.  
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.221.1-canary.673.5972477545.0
npm install @salutejs/plasma-colors@0.8.1-canary.673.5972477545.0
npm install @salutejs/plasma-core@1.126.1-canary.673.5972477545.0
npm install …
```

plasma-infra: Enable full bootstrap [Publish canary]

---

packages/plasma-icons/src/Icon.assets/SberSpasibo.tsx
packages/plasma-icons/src/Icon.tsx
packages/plasma-icons/src/Icons/IconSberSpasibo.tsx
packages/plasma-icons/src/index.ts

Добавлена иконка: 
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.223.0-canary.669.6033062361.0
npm install @salutejs/plasma-hope@1.223.0-canary.669.6033062361.0
npm install @salutejs/plasma-icons@1.157.0-canary.669.6033062361.0
npm install @salutejs/plasma-temple@1.172.0-canary.669.6033062361.0
npm install @salutejs/plasma-ui@1.204.0-canary.669.6033062361.0
npm install @salutejs/plasma-web@1.223.0-canary.669.6033062361.0
yarn add @salutejs/plasma-b2c@1.223.0-canary.669.6033062361.0
yarn add @salutejs/plasma-hope@1.223.0-canary.669.6033062361.0
yarn add @salutejs/plasma-icons@1.157.0-canary.669.6033062361.0
yarn add …
```

plasma-icons: add SberSpasibo

---

website/plasma-web-docs/docusaurus.config.js
website/plasma-web-docs/package.json

Добавлена недостающая информация в `PropsTable`. 
Из-за того что у ряда компонентов нет явного `returnType` и они импортируются через `re-export` то документация не могла корректно отобразить `PropsTable`. 
```
Not found module in @docgen/Cell. Error: Cannot find module './Cell.json'
```
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.225.2-canary.693.6117775528.0
npm install @salutejs/plasma-hope@1.225.2-canary.693.6117775528.0
npm install @salutejs/plasma-web@1.225.2-canary.693.6117775528.0
yarn add @salutejs/plasma-b2c@1.225.2-canary.693.6117775528.0
yarn add @salutejs/plasma-hope@1.225.2-canary.693.6117775528.0
yarn add …
```

web-docs: Fix parse components list [Docusaurus]

---

.github/workflows/documentation-main.yml

Для workflow: 
- `"Main Documentation and Storybook"`
делаем **явный** checkout на **master** ветку. 
Что бы правильно собирать документацию после релиза, нужно указать ref на master ветку.
Так как на проекте **default** branch - **dev**. Из-за этого документация собирается под тегем dev.     
[About workflow run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)

plasma-infra: Checkout to "master" ["Main Documentation and Storybook"]

---

packages/plasma-hope/api/plasma-hope.api.md
packages/plasma-hope/src/components/Dropdown/DropdownItem.tsx
website/plasma-web-docs/docs/components/Dropdown.mdx

Добавлена возможность использовать свойство `ref` для компонента  `DropdownItem`
-------
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.769.6310497681.ts'>borderRadius_default_react-native--canary.769.6310497681.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.769.6310497681.ts'>borderRadius_plasma_b2c_react-native--canary.769.6310497681.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.769.631049768 …

plasma-web: Pass `ref` to DropdownItem

---

.github/workflows/semgrep.yml

**Включили** настройки GitHub по security analysis. 
Включены/добавлены следующие опции:

plasma-infra: Enable GitHub security analysis options

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/ModalBase/ModalBase.stories.tsx
packages/plasma-b2c/src/components/ModalBase/index.ts
packages/plasma-b2c/src/components/PopupBase/PopupBase.stories.tsx
packages/plasma-b2c/src/components/PopupBase/index.ts
packages/plasma-b2c/src/index.ts
packages/plasma-core/api/plasma-core.api.md
packages/plasma-core/src/components/ModalBase/ModalBase.tsx
packages/plasma-core/src/components/ModalBase/ModalBaseContext.tsx
packages/plasma-core/src/components/ModalBase/index.ts
packages/plasma-core/src/components/PopupBase/PopupBase.tsx
packages/plasma-core/src/components/PopupBase/PopupBaseContext.tsx
packages/plasma-core/src/components/PopupBase/index.ts
packages/plasma-core/src/index.ts
packages/plasma-hope/api/plasma-hope.api.md
packages/plasma-hope/src/components/ModalBase/index.ts
packages/plasma-hope/src/components/PopupBase/index.ts
packages/plasma-hope/src/index.ts
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/ModalBase/ModalBase.stories.tsx
packages/plasma-web/src/components/ModalBase/index.ts
packages/plasma-web/src/components/PopupBase/PopupBase.stories.tsx
packages/plasma-web/src/components/PopupBase/index.ts
packages/plasma-web/src/index.ts

Реализован компонент `ModalBase`, сделанный на основе `PopupBase`, который сохраняет все его свойства(исключая `frame`), но также добавляет:
- `withBlur?: boolean` - Нужно ли применять blur для подложки.
- `сloseOnEsc?: boolean` - Закрывать модальное окно при нажатии на ESC(по умолчанию true).
- `сloseOnOverlayClick?: boolean` - Закрывать модальное окно при нажатии вне области модального окна(по умолчанию true).
- `onEscKeyDown?: (event: KeyboardEvent) => void` - Обработчик клика при нажатии на ESC(если не передан, то при нажатии используется onClose).
- `onOverlayClick?: (event: React.MouseEvent<HTMLDivElement>) => void` - Обработчик клика при нажатии вне области модального окна(если не передан, то при нажатии используется onClose).
- `initialFocusRef?: React.RefObject<HTMLElement>` - …

feat(plasma-core, plasma-web, plasma-b2c): ModalBase component

---

CONTRIBUTING.md
packages/plasma-core/api/plasma-core.api.md
packages/plasma-core/src/components/Button/Button.types.ts

Blur свойство теперь deprecated для компонента Button. Работает только на кнопках с прозрачностью
**Пример:**
**Было в доке**
**Стало**
-------
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.785.6381248900.ts'>borderRadius_default_react-native--canary.785.6381248900.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.785.6381248900.ts'>borderRadius_plasma_b2c_react-native--canary.785.6381248900.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/bor …

fix(plasma-web-docs): Remove button blur prop from component & docs

---

.github/workflows/semgrep.yml

используем опцию `continue-on-error` для semgrep workflow, что бы alert не считался как failed pipeline.   
Когда semgrep отправляет alert для PR то сам workflow помечался как **failed**. 
Данное поведение переопределено.

plasma-infra(semgrep): Use "continue-on-error" option

---

.github/workflows/authorize-external-pr.yml
.github/workflows/theme-builder-pr.yml

Первая часть этих изменений для проверки корректности - https://github.com/salute-developers/plasma/pull/844

plasma-infra: WIP

---

.github/workflows/change-detection.yml
.github/workflows/clean-pr-documentation.yml
.github/workflows/cleanup-cache-pr.yml
.github/workflows/documentation-pr.yml
.github/workflows/performance-test-pr.yml
.github/workflows/publish-canary.yml
.github/workflows/publish-common.yml
.github/workflows/publish-rc.yml

Добавлена возможность запуска **внешних** pull request через **fork**
Подробное описание `Handling external pull request by fork`  - #805

plasma-infra: Handle external pull request

---

packages/plasma-asdk/package-lock.json
packages/plasma-asdk/package.json
packages/plasma-b2c/package-lock.json
packages/plasma-b2c/package.json
packages/plasma-hope/package-lock.json
packages/plasma-hope/package.json
packages/plasma-new-hope/package-lock.json
packages/plasma-new-hope/package.json
packages/plasma-web/package-lock.json
packages/plasma-web/package.json

Обновлены зависимости: 
- [`vite` to 4.5.0](https://github.com/salute-developers/plasma/security/dependabot/97)
- [`default-browser-id` to 2.0.0](https://github.com/advisories/GHSA-7p7h-4mm5-852v) 
- `@microsoft/api-extractor` to 7.38.3 (several moderate) 
Исправлены **все** **critical** и **high** vulnerabilities в plasma-{b2c, web, hope, new-hope, asdk} библиотеках
---------
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.861.6939308474.ts'>borderRadius_default_react-native--canary.861.6939308474.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v …

plasma-infra: Fix vulnerabilities

---

packages/plasma-b2c/package.json

Тестовый ПР для проверки, что assets грузятся по условию. 
В этом ПР **не должно быть** assets.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.10.1-canary.889.7096374424.0
npm install @salutejs/plasma-b2c@1.250.1-canary.889.7096374424.0
npm install @salutejs/plasma-new-hope@0.17.1-canary.889.7096374424.0
npm install @salutejs/plasma-web@1.250.1-canary.889.7096374424.0
yarn add @salutejs/plasma-asdk@0.10.1-canary.889.7096374424.0
yarn add @salutejs/plasma-b2c@1.250.1-canary.889.7096374424.0
yarn add @salutejs/plasma-new-hope@0.17.1-canary.889.7096374424.0
yarn add @salutejs/plasma-web@1.250.1-canary.889.7096374424.0
```
</details>

plasma-b2c: Check upload assets

---

.nvmrc

- зафиксировали версию Node.js (18.16.1) для корректной работы CI 
https://nodejs.org/en/blog/release/v18.19.0 
TL;DR 
> After two months of baking time in Node.js 20, npm 10 is backported, so that all release lines include a supported version of npm. This release includes npm v10.2.3.
А у нас есть ограничение на версию npm 
```
"engines": {
"npm": "^8.19.0 || ^9.5.1"
}
``` 
Поэтому решили зафиксировать точную версию Node.js, а не tag

plasma-infra: Use 18.16.1 node version

---

.github/workflows/publish-rc.yml

- добавлена логика получения `pull_request.base.sha` для правильного расчета условия загрузки assets
Когда мы находимся в dev ветки команда - `npx lerna la --json --since=$(git merge-base --fork-point origin/dev)` не видит изменений. 
Поэтому для publish RC решили изменить подход отслеживания изменений с момента последнего выпуска. 
В таком подходе есть уязвимость, например
В прошлом у нас были внесены изменения в `@salutejs/plasma-tokens-native` но с префиксом `chore` и соотвественно такие изменения **не сделали** bump версии пакета и **не было** выпуска, это ключевой момент. 
И поэтому вывод команды `npx lerna changed --all --json` учтет эти изменения, они не были опубликованы.   
И расчет условия загрузки для ваших изменений будет **некорректным**, потому что вывод `npx lerna changed` …

plasma-infra: Upload assets when publish rc

---

packages/plasma-hope/src/components/Upload/UploadButton.tsx

-   исправлены стили для StyledButton в состоянии isGrabbing
Из-за лишних скобок в стилях для состояния isGrabbing слетали все стили для styled-components.
**До** наведения мыши с файлом
**После**
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.255.0-canary.926.7207896497.0
npm install @salutejs/plasma-hope@1.249.0-canary.926.7207896497.0
npm install @salutejs/plasma-web@1.255.0-canary.926.7207896497.0
yarn add @salutejs/plasma-b2c@1.255.0-canary.926.7207896497.0
yarn add @salutejs/plasma-hope@1.249.0-canary.926.7207896497.0
yarn add @salutejs/plasma-web@1.255.0-canary.926.7207896497.0
```
</details>

plasma-hope: fix broken style for Upload button

---

packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx
packages/plasma-new-hope/src/components/Tooltip/Tooltip.types.ts

- для сохранения обратной совместимости  вернули поддержку prop `children`
При использовании компонента `Tooltip` children не отображается
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.16.1-canary.937.7274120598.0
npm install @salutejs/plasma-b2c@1.257.1-canary.937.7274120598.0
npm install @salutejs/plasma-new-hope@0.23.1-canary.937.7274120598.0
npm install @salutejs/plasma-temple@1.191.1-canary.937.7274120598.0
npm install @salutejs/plasma-ui@1.223.1-canary.937.7274120598.0
npm install @salutejs/plasma-web@1.257.1-canary.937.7274120598.0
yarn add @salutejs/plasma-asdk@0.16.1-canary.937.7274120598.0
yarn add …
```

fix(plasma-new-hope): Add support children props to `Tooltip` component

---

package-lock.json
package.json

Обновление vite не помогло избавиться от `fsevents.watch is not a function`. 
Решили добавить блок, чтобы наверняка 
```
"overrides": {
"chokidar": "^3.3.1"
},
```

plasma-infra: Overrides chokidar version

---

actions/versionate-docs/action.yml
actions/versionate-docs/src/main.ts

- исправлены стили для StyledButton в состоянии isGrabbing
plasma-hope: fix broken style for Upload button (https://github.com/salute-developers/plasma/pull/926)
- вынесены токены;
- поправлено поведение props square;
- добавлены недостающие props: stretch и pin
feat(plasma-new-hope): refactor & add stretch/pin props (https://github.com/salute-developers/plasma/pull/896)
-   добавлен новый дизайн компонента
-   добавили новый api
Было:
Стало:
plasma-new-hope: Notification redesign (https://github.com/salute-developers/plasma/pull/927)
- для сохранения обратной совместимости  вернули поддержку prop children
fix(plasma-new-hope): Add support children props to Tooltip component (https://github.com/salute-developers/plasma/pull/937)
- добавлены/обновлены конфигурации в библиотеках …

Release by 22.12.2023

---

packages/plasma-new-hope/src/components/Typography/Body/Body.tsx
packages/plasma-new-hope/src/components/Typography/Dspl/Dspl.tsx
packages/plasma-new-hope/src/components/Typography/Heading/Heading.tsx
packages/plasma-new-hope/src/components/Typography/Old/Body/Body.tsx
packages/plasma-new-hope/src/components/Typography/Old/Button/Button.tsx
packages/plasma-new-hope/src/components/Typography/Old/Caption/Caption.tsx
packages/plasma-new-hope/src/components/Typography/Old/Display/Display.tsx
packages/plasma-new-hope/src/components/Typography/Old/Footnote/Footnote.tsx
packages/plasma-new-hope/src/components/Typography/Old/Headline/Headline.tsx
packages/plasma-new-hope/src/components/Typography/Old/Paragraph/Paragraph.tsx
packages/plasma-new-hope/src/components/Typography/Old/ParagraphText/ParagraphText.tsx
packages/plasma-new-hope/src/components/Typography/Old/Subtitle/Subtitle.tsx
packages/plasma-new-hope/src/components/Typography/Old/Underline/Underline.tsx
packages/plasma-new-hope/src/components/Typography/Text/Text.tsx

-   удален пустой useEffect из компонент типографики
Раньше была бага связанная с линарией (без useEffect крашилась сборка new-hope). Сейчас баг исправился -> useEffect больше не нужен.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.20.0-canary.946.7298430960.0
npm install @salutejs/plasma-b2c@1.261.0-canary.946.7298430960.0
npm install @salutejs/plasma-new-hope@0.27.0-canary.946.7298430960.0
npm install @salutejs/plasma-web@1.261.0-canary.946.7298430960.0
yarn add @salutejs/plasma-asdk@0.20.0-canary.946.7298430960.0
yarn add @salutejs/plasma-b2c@1.261.0-canary.946.7298430960.0
yarn add @salutejs/plasma-new-hope@0.27.0-canary.946.7298430960.0
yarn add …
```

feat(plasma-new-hope): remove useEffect from typography

---

packages/plasma-b2c/src/components/Carousel/Carousel.stories.tsx
packages/plasma-hope/api/plasma-hope.api.md
packages/plasma-hope/src/components/Carousel/Carousel.tsx
packages/plasma-hope/src/components/Carousel/hooks.tsx
packages/plasma-web/src/components/Carousel/Carousel.stories.tsx

Решен баг с пролистыванием (onDragScroll) в accessible mode - mobile & desktop.
Control panel в карусели работает корректно (можно выбрать scrollAlign).
Добавил проп isDragScrollDisabled, чтобы дать возможность отключать скролл через drag event. 
Фикс control panel в Carousel в plasma-web.
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.263.1-canary.957.7345838046.0
npm install @salutejs/plasma-hope@1.251.1-canary.957.7345838046.0
npm install @salutejs/plasma-web@1.263.1-canary.957.7345838046.0
yarn add @salutejs/plasma-b2c@1.263.1-canary.957.7345838046.0
yarn add @salutejs/plasma-hope@1.251.1-canary.957.7345838046.0
yarn add …
```

fix(plasma-hope/plasma-web): Turn onDragScroll off by default in accessibility mode in Carousel. Fix storybook control panel in it.

---

packages/plasma-new-hope/src/components/Calendar/CalendarDouble/CalendarDouble.tsx

-   добавлен ref в forwardRef вторым аргументом
В CalendarDouble в forwardRef не было ref как пропса, из-за чего в консоль падал ворнинг об этом.
forwardRef должен принимать два аргумента
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.23.0-canary.959.7347249945.0
npm install @salutejs/plasma-b2c@1.264.0-canary.959.7347249945.0
npm install @salutejs/plasma-new-hope@0.30.0-canary.959.7347249945.0
npm install @salutejs/plasma-web@1.264.0-canary.959.7347249945.0
yarn add @salutejs/plasma-asdk@0.23.0-canary.959.7347249945.0
yarn add @salutejs/plasma-b2c@1.264.0-canary.959.7347249945.0
yarn add @salutejs/plasma-new-hope@0.30.0-canary.959.7347249945.0
yarn add …
```

feat(plasma-new-hope): fix CalendarDouble ref

---

.github/workflows/required-primary-checks.yml
packages/plasma-new-hope/src/components/Popover/Popover.styles.ts

-   Поправлено отображение Popover arrow в Safari, Firefox
В safari не отображалась стрелка, а в Firefox не срабатывал rotate.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.25.1-canary.963.7501084786.0
npm install @salutejs/plasma-b2c@1.266.1-canary.963.7501084786.0
npm install @salutejs/plasma-new-hope@0.31.1-canary.963.7501084786.0
npm install @salutejs/plasma-web@1.266.1-canary.963.7501084786.0
yarn add @salutejs/plasma-asdk@0.25.1-canary.963.7501084786.0
yarn add @salutejs/plasma-b2c@1.266.1-canary.963.7501084786.0
yarn add @salutejs/plasma-new-hope@0.31.1-canary.963.7501084786.0
yarn add @salutejs/plasma-web@1.266.1-canary.963.7501084786.0
``` …

fix(plasma-web): fix Popover arrow in Safari, Firefox

---

.github/workflows/publish-canary.yml
.github/workflows/publish-common.yml
.github/workflows/publish-rc.yml

- добавлена возможность прокинуть опции/флаги для запуска - **auto shipit**;
- выключили генерацию changelog для pubslish: canary, RC;  
changelog нужен нам только когда делаем latest release во всех остальных случаях - нет.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.10.1-canary.890.7096675247.0
npm install @salutejs/plasma-b2c@1.250.1-canary.890.7096675247.0
npm install @salutejs/plasma-new-hope@0.17.1-canary.890.7096675247.0
npm install @salutejs/plasma-web@1.250.1-canary.890.7096675247.0
yarn add @salutejs/plasma-asdk@0.10.1-canary.890.7096675247.0
yarn add @salutejs/plasma-b2c@1.250.1-canary.890.7096675247.0
yarn add …
```

plasma-infra: Pass cli options for "@auto-it"

---

.github/workflows/required-primary-checks.yml
.github/workflows/typescript-coverage.yml

- выключили флаг `since` чтобы корректно обрабатывать/устанавливать зависимости    
- добавлен пакет `plasma-icons` для корректной работы  
Пакет `plasma-icons` идет как `peerDep` и не ставится с флагом `--since` (в этом пакете не было изменений и ставиться latest версия из npm) в которой нет нужных изменений. 
#968 - именно тут столкнулись с проблемой, которая решается этим PR  
#970 - тут проверили эти изменения

plasma-infra: Handle plasma-icons as dep 

---

packages/plasma-new-hope/src/components/Spinner/Spinner.tsx

Исправлено отображение компонента `Spinner` при размере 8px
Если указать значение size='8' у компонента `Spinner`, то он будет крутиться не во круг своей оси, а со смещением
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.25.2-canary.966.7538300022.0
npm install @salutejs/plasma-b2c@1.267.2-canary.966.7538300022.0
npm install @salutejs/plasma-new-hope@0.31.2-canary.966.7538300022.0
npm install @salutejs/plasma-web@1.267.2-canary.966.7538300022.0
yarn add @salutejs/plasma-asdk@0.25.2-canary.966.7538300022.0
yarn add @salutejs/plasma-b2c@1.267.2-canary.966.7538300022.0
yarn add @salutejs/plasma-new-hope@0.31.2-canary.966.7538300022.0
yarn add …
```

fix(plasma-new-hope): Fix size for `Spinner` component

---

packages/plasma-ui/package.json
packages/plasma-ui/src/components/Badge/BadgeBase.component-test.tsx
packages/plasma-ui/src/components/Slider/Slider.component-test.tsx

-  Поправлены тесты Badge для ui
В plasma-ui падали тесты так как они были симлинкой на plasma-core. Заменили на обычные файлы.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.30.0-canary.985.7582657911.0
npm install @salutejs/plasma-b2c@1.272.0-canary.985.7582657911.0
npm install @salutejs/plasma-core@1.145.0-canary.985.7582657911.0
npm install @salutejs/plasma-hope@1.256.0-canary.985.7582657911.0
npm install @salutejs/plasma-icons@1.178.0-canary.985.7582657911.0
npm install @salutejs/plasma-new-hope@0.36.0-canary.985.7582657911.0
npm install @salutejs/plasma-temple@1.197.0-canary.985.7582657911.0
npm install …
```

feat(plasma-ui): fix Badge tests

---

packages/plasma-icons/package.json

-   поправлена публикация пакета со всем содержимым билда
В пакете не было папки scalable, в которой находились новые иконки.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.30.1-canary.989.7584242110.0
npm install @salutejs/plasma-b2c@1.272.1-canary.989.7584242110.0
npm install @salutejs/plasma-hope@1.256.1-canary.989.7584242110.0
npm install @salutejs/plasma-icons@1.178.1-canary.989.7584242110.0
npm install @salutejs/plasma-temple@1.197.1-canary.989.7584242110.0
npm install @salutejs/plasma-ui@1.229.1-canary.989.7584242110.0
npm install @salutejs/plasma-web@1.272.1-canary.989.7584242110.0
yarn add @salutejs/plasma-asdk@0.30.1-canary.989.7584242110.0 …
```

fix(plasma-icons): fix package publish

---

lerna.json

- переопределили логику `ignoreChanges` для команды `lerna ls` чтобы изменения файлов `*.component-test.tsx` тоже учитывалось      
Чтобы правильно понять "а какие пакеты у нас изменились?" переопределили свойство `ignoreChanges` для команды `lerna ls`. 
Теперь когда у нас запускается worfklow " ./.github/workflows/change-detection.yml" он учитывает в себе и измененые `*.component-test.tsx` файлы.      
Например мы изменили компонент `Badge` и нам пришлось адаптировать под новый API и визуал тесты - `Badge.component-test.tsx`
Прямые изменения были только в пакетах `plasma-{b2c,web}`, а измененные тесты лежат в `plasma-core`. 
А так как **ранее** мы **не учитывали** в своих расчетах файлы тестов, то CI не запустил тесты для plasma-ui, которые тоже раньше ссылались на тесты в plasma-core, а …

plasma-infra: Override `lerna ls` config

---

packages/plasma-b2c/src/components/PopupBase/PopupBase.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/Popup/Popup.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Popup/Popup.stories.tsx
packages/plasma-new-hope/src/examples/sds_engineer/components/Popup/Popup.stories.tsx
packages/plasma-web/src/components/PopupBase/PopupBase.stories.tsx

-   поправлено отображение примера Popup в storybook
Невозможно было проверить работу Popup на мобилках из-за некорректной верстки примера.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.30.3-canary.997.7655379448.0
npm install @salutejs/plasma-b2c@1.272.3-canary.997.7655379448.0
npm install @salutejs/plasma-new-hope@0.36.2-canary.997.7655379448.0
npm install @salutejs/plasma-web@1.272.3-canary.997.7655379448.0
yarn add @salutejs/plasma-asdk@0.30.3-canary.997.7655379448.0
yarn add @salutejs/plasma-b2c@1.272.3-canary.997.7655379448.0
yarn add @salutejs/plasma-new-hope@0.36.2-canary.997.7655379448.0
yarn add …
```

chore: fix Popup storybook example

---

.github/workflows/publish-rc.yml

- добавлено уведомление для упавшего процесса публикации релиз кандидата 
Что бы своевременно получать сообщение об упавшем CI при публикации релиз кандидата.
Теперь получаем в канал mattermost через webhooks соответствующие сообщение

plasma-infra: Add notification when publish failed

---

.github/workflows/performance-test-pr.yml

Убирает loglevel=verbose у perftool, чтобы сильно не засоряло логи

Remove perftool max log verbosity

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Calendar/Calendar.stories.tsx
packages/plasma-new-hope/src/components/Calendar/Calendar.types.ts
packages/plasma-new-hope/src/components/Calendar/hoc/withRange.tsx
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Calendar/Calendar.stories.tsx

- добавлено новое свойство `onChangeStartOfRange` в библиотеки `plasma-{web,b2c}`
Возник такой кейс 
> есть календари, в которых есть ограничения диапазона, который пользователь может выбрать, например не больше недели, и при выборе первой даты нужно `disable` даты все, кроме дат за неделю и после первой выбранной
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.4.0-canary.1014.7840120119.0
npm install @salutejs/caldera@0.4.0-canary.1014.7840120119.0
npm install @salutejs/plasma-asdk@0.39.0-canary.1014.7840120119.0
npm install @salutejs/plasma-b2c@1.281.0-canary.1014.7840120119.0
npm install @salutejs/plasma-new-hope@0.45.0-canary.1014.7840120119.0
npm …
```

plasma-web: Add `onChangeStartOfRange` prop into Calendar

---

packages/plasma-b2c/src/components/Select/Select.stories.tsx
packages/plasma-hope/src/components/Select/withMultiSelect.tsx
packages/plasma-web/src/components/Select/Select.stories.tsx

- Обновлены зависимости у колбэка, который вызывался при выборе элемента в `multiselect` режиме для библиотеки `@salutejs/plasma-hope`
- Необходимо было добавить зависимость `value`, т.к. иначе при оборачивании обработчика `onChangeValue` в `useCallback` выбиралось только одно значение.
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.282.1-canary.1040.7883094690.0
npm install @salutejs/plasma-hope@1.261.1-canary.1040.7883094690.0
npm install @salutejs/plasma-web@1.282.1-canary.1040.7883094690.0
yarn add @salutejs/plasma-b2c@1.282.1-canary.1040.7883094690.0
yarn add @salutejs/plasma-hope@1.261.1-canary.1040.7883094690.0
yarn add …
```

fix(plasma-hope): Add value deps for `Select` component with multiselect mode

---

.github/workflows/publish-common.yml
auto-plugins/src/upload-assets-extend.ts
auto.config.js
patches/@auto-it+upload-assets+10.46.0.patch

- добавлена возможность указать пакет/релиз к которому нужно прикрепить assets  
С увеличением кол-ва assets и пакетов появилась угроза выхода за выданные API rate лимиты. 
По сути в текущей ситуации нам нужно грузить assets **только** для пакета - `@salutejs/plasma-tokens`.

plasma-infra: Upload assets for target package(-s)

---

auto-plugins/src/upload-assets-extend.ts
auto.config.js

исправил условие фильтрации пакетов. Теперь работает строгое сравнение по названию пакета. 
Сделано, чтобы исключить попадание случаев когда match по "@salutejs/plasma-tokens" в:
```js
[
{ name: "@salutejs/plasma-tokens@1.72.0", ... }
{ name: "@salutejs/plasma-tokens-native@1.23.0", ...}
]
```
В фильтр попадали оба пакета.   
Теперь строгое сравнение вернет **только** пакет - `@salutejs/plasma-tokens`

plasma-infra:  Refactoring upload assets by package

---

.github/workflows/documentation-pr.yml
.github/workflows/required-primary-checks.yml
.github/workflows/typescript-coverage.yml

- добавлен filter флаг `--no-private`
- добавлен filter флаг `--no-private`
- добавлена сборка документации для вертикали "SDDS SERV"
Чтобы не добавлять каждый новый пакет в `LERNA_IGNORE_LIST`, 
мы используем **filter** флаг `--no-private` с помощью которого и исключим из сборки не нужные для этого процесса приватные пакеты.  
Изменения сделаны по мотивам #1062 - где мы добавляем новый приватный пакет документации для вертикали sdds serv

plasma-infra: Simplify code

---

packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/package-lock.json
packages/sdds-serv/package.json

<details>
<br />
```bash
npm install @salutejs/sdds-serv@0.12.1-canary.1072.8077092341.0
yarn add @salutejs/sdds-serv@0.12.1-canary.1072.8077092341.0
```
</details>

fix(sdds-serv): package rename

---

packages/plasma-new-hope/src/examples/plasma_b2c/components/Overlay/Overlay.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Overlay/Overlay.stories.tsx
packages/plasma-new-hope/src/examples/sds_engineer/components/Overlay/Overlay.stories.tsx

Исправлены на **новый формат** stories для компонента `Overlay`
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.11.1-canary.1075.8092130882.0
npm install @salutejs/caldera@0.11.1-canary.1075.8092130882.0
npm install @salutejs/plasma-asdk@0.46.1-canary.1075.8092130882.0
npm install @salutejs/plasma-b2c@1.288.1-canary.1075.8092130882.0
npm install @salutejs/plasma-new-hope@0.52.1-canary.1075.8092130882.0
npm install @salutejs/plasma-web@1.288.1-canary.1075.8092130882.0
npm install @salutejs/sdds-serv@0.12.2-canary.1075.8092130882.0
yarn add @salutejs/caldera-online@0.11.1-canary.1075.8092130882.0
yarn add @salutejs/caldera@0.11.1-canary.1075.8092130882.0 …
```

chore(new-hope): fix overlay stories

---

packages/plasma-tokens-b2b/generate.ts
packages/plasma-tokens-b2c/generate.ts
packages/plasma-tokens-web/generate.ts

* Добавлены ре-экспорты актуальных токенов в библиотеки `@salutejs/plasma-tokens-b2b`, `@salutejs/plasma-tokens-b2c`, `@salutejs/plasma-tokens-web`
У пользователей появилась необходимость забирать токены напрямую по пути `import { textPrimary } from "@salutejs/plasma-tokens-b2b"` и т.д.
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.13.0-canary.1078.8095147029.0
npm install @salutejs/caldera@0.13.0-canary.1078.8095147029.0
npm install @salutejs/plasma-asdk@0.48.0-canary.1078.8095147029.0
npm install @salutejs/plasma-b2c@1.290.0-canary.1078.8095147029.0
npm install @salutejs/plasma-core@1.152.0-canary.1078.8095147029.0
npm install …
```

feat(plasma-tokens-*): Add re-export fallback tokens

---

.github/workflows/documentation-deploy-dev-subdir.yml

Добавлена конфигурация для deploy в `plasma.sberdevices.ru/dev/` 
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.11.1-canary.1077.8094014915.0
npm install @salutejs/caldera@0.11.1-canary.1077.8094014915.0
npm install @salutejs/plasma-asdk@0.46.1-canary.1077.8094014915.0
npm install @salutejs/plasma-b2c@1.288.1-canary.1077.8094014915.0
npm install @salutejs/plasma-new-hope@0.52.1-canary.1077.8094014915.0
npm install @salutejs/plasma-web@1.288.1-canary.1077.8094014915.0
npm install @salutejs/sdds-serv@0.12.2-canary.1077.8094014915.0
yarn add @salutejs/caldera-online@0.11.1-canary.1077.8094014915.0
yarn add …
```

plasma-infra: Deploy documentation and storybook artefact to `plasma.sberdevices.ru/dev/`

---

packages/caldera-online/api/caldera-online.api.md
packages/caldera-online/src/components/Dropdown/index.ts
packages/caldera/api/caldera.api.md
packages/caldera/src/components/Dropdown/index.ts
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/ButtonGroup/ButtonGroup.config.ts
packages/sdds-serv/src/components/ButtonGroup/ButtonGroup.stories.tsx
packages/sdds-serv/src/components/ButtonGroup/ButtonGroup.tsx
packages/sdds-serv/src/components/ButtonGroup/index.tsx
packages/sdds-serv/src/components/Dropdown/index.ts
packages/sdds-serv/src/index.ts

- добавлен `ButtonGroup`
- добавлен экспорт `DropdownItem` (а так же в caldera, caldera-online)
Стабилизация пакета sdds-serv.
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.16.0-canary.1092.8152262621.0
npm install @salutejs/caldera@0.16.0-canary.1092.8152262621.0
npm install @salutejs/sdds-serv@0.17.0-canary.1092.8152262621.0
yarn add @salutejs/caldera-online@0.16.0-canary.1092.8152262621.0
yarn add @salutejs/caldera@0.16.0-canary.1092.8152262621.0
yarn add @salutejs/sdds-serv@0.17.0-canary.1092.8152262621.0
```
</details>

fix(sdds-serv): add components to sdds-serv

---

packages/plasma-new-hope/src/components/Popover/Popover.styles.ts
packages/plasma-new-hope/src/components/Popover/Popover.tsx
packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx

-   Classname добавляется в tooltip
Теперь не ломается стрелка при добавлении стилей
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.16.1-canary.1083.8155986695.0
npm install @salutejs/caldera@0.16.1-canary.1083.8155986695.0
npm install @salutejs/plasma-asdk@0.50.1-canary.1083.8155986695.0
npm install @salutejs/plasma-b2c@1.292.1-canary.1083.8155986695.0
npm install @salutejs/plasma-new-hope@0.56.1-canary.1083.8155986695.0
npm install @salutejs/plasma-web@1.292.1-canary.1083.8155986695.0
npm install @salutejs/sdds-serv@0.17.1-canary.1083.8155986695.0
yarn add @salutejs/caldera-online@0.16.1-canary.1083.8155986695.0
yarn add …
```

fix(new-hope): remove wrapper from popover

---

packages/plasma-tokens-b2b/.gitignore
packages/plasma-tokens-b2b/generate.ts
packages/plasma-tokens-b2b/package.json
packages/plasma-tokens-b2c/.gitignore
packages/plasma-tokens-b2c/generate.ts
packages/plasma-tokens-b2c/package.json
packages/plasma-tokens-web/.gitignore
packages/plasma-tokens-web/generate.ts
packages/plasma-tokens-web/package.json

* Добавлена директория `new` для новых токенов
* При импорте новых токенов напрямую из индекса пакетов `@salutejs/plasma-tokens-b2c` / `@salutejs/plasma-tokens-b2b` / `@salutejs/plasma-tokens-web` они не будут применяться, т.к. имеют префикс `--plasma-colors`
* Новые токены, которые имели такое же название как и у старых, переопределяли значения
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.16.1-canary.1094.8156406225.0
npm install @salutejs/caldera@0.16.1-canary.1094.8156406225.0
npm install @salutejs/plasma-asdk@0.50.1-canary.1094.8156406225.0
npm install @salutejs/plasma-b2c@1.292.1-canary.1094.8156406225.0
npm install …
```

fix(plasma-tokens-*): Add `new` directory for for new tokens

---

packages/plasma-new-hope/src/components/Calendar/hooks/useDays.ts
packages/plasma-new-hope/src/components/Calendar/utils/index.ts

-   добавлено возможность выбрать 1 дня в типе range
Возможность выбор 1 дня в типе range, убрал проверку на hoverDate со startDate. И изменил название функции, которая была написана неправильно 
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.17.0-canary.1084.8168958226.0
npm install @salutejs/caldera@0.17.0-canary.1084.8168958226.0
npm install @salutejs/plasma-asdk@0.51.0-canary.1084.8168958226.0
npm install @salutejs/plasma-b2c@1.293.0-canary.1084.8168958226.0
npm install @salutejs/plasma-new-hope@0.57.0-canary.1084.8168958226.0
npm install @salutejs/plasma-web@1.293.0-canary.1084.8168958226.0
npm install …
```

feat(new-hope): edit calendar range logic and fix name

---

.github/workflows/documentation-deploy-dev-subdir.yml
website/sdds-serv-docs/docusaurus.config.js

- исправлена конфигурация для deploy в `/dev` директорию
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.17.1-canary.1102.8175322475.0
npm install @salutejs/caldera@0.17.1-canary.1102.8175322475.0
npm install @salutejs/plasma-asdk@0.51.1-canary.1102.8175322475.0
npm install @salutejs/plasma-b2c@1.293.1-canary.1102.8175322475.0
npm install @salutejs/plasma-new-hope@0.57.1-canary.1102.8175322475.0
npm install @salutejs/plasma-ui@1.237.3-canary.1102.8175322475.0
npm install @salutejs/plasma-web@1.293.1-canary.1102.8175322475.0
npm install @salutejs/sdds-serv@0.18.1-canary.1102.8175322475.0
yarn add @salutejs/caldera-online@0.17.1-canary.1102.8175322475.0 …
```

plasma-infra: Refactoring "Deploy documentation and storybook artefacts to `/dev`"

---

packages/plasma-ui/src/components/Pickers/PickerItem.tsx

-   fix бага в документации 
Убрал свойство "overflow: hidden", чтобы исправить баг. Визуализация на рабочих компонентах никак не пострадала 
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.17.1-canary.1089.8186819754.0
npm install @salutejs/caldera@0.17.1-canary.1089.8186819754.0
npm install @salutejs/plasma-asdk@0.51.1-canary.1089.8186819754.0
npm install @salutejs/plasma-b2c@1.293.1-canary.1089.8186819754.0
npm install @salutejs/plasma-new-hope@0.57.1-canary.1089.8186819754.0
npm install @salutejs/plasma-ui@1.237.3-canary.1089.8186819754.0
npm install @salutejs/plasma-web@1.293.1-canary.1089.8186819754.0
npm install …
```

fix(ui): fix pickers documentation bug with overflow

---

packages/plasma-new-hope/src/components/TextField/TextField.tsx

Исправлен баг с прозрачностью в компоненте TextField. Проблема была только в сафари, т.к. вебкит не применяет opacity к inline тегам. 
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.17.0-canary.1082.8157187677.0
npm install @salutejs/caldera@0.17.0-canary.1082.8157187677.0
npm install @salutejs/plasma-asdk@0.51.0-canary.1082.8157187677.0
npm install @salutejs/plasma-b2c@1.293.0-canary.1082.8157187677.0
npm install @salutejs/plasma-new-hope@0.57.0-canary.1082.8157187677.0
npm install @salutejs/plasma-web@1.293.0-canary.1082.8157187677.0
npm install @salutejs/sdds-serv@0.18.0-canary.1082.8157187677.0
yarn add …
```

feat(plasma-new-hope): TextField issue with opacity

---

packages/caldera-online/src/components/Button/Button.config.ts
packages/caldera/src/components/Button/Button.config.ts
packages/plasma-b2c/src/components/Button/Button.config.ts
packages/plasma-b2c/src/components/ButtonGroup/ButtonGroup.config.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Button/Button.config.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/ButtonGroup/ButtonGroup.config.ts
packages/plasma-new-hope/src/examples/plasma_web/components/Button/Button.config.ts
packages/plasma-new-hope/src/examples/plasma_web/components/ButtonGroup/ButtonGroup.config.ts
packages/plasma-new-hope/src/examples/sds_engineer/components/Button/Button.config.ts
packages/plasma-new-hope/src/examples/sds_engineer/components/ButtonGroup/ButtonGroup.config.ts
packages/plasma-web/src/components/Button/Button.config.ts
packages/plasma-web/src/components/ButtonGroup/ButtonGroup.config.ts
packages/sdds-serv/src/components/Button/Button.config.ts
packages/sdds-serv/src/components/ButtonGroup/ButtonGroup.config.ts

- удалены токены scale из кнопки и группы кнопок в пакетах b2c, web, sdds-serv, caldera/-online
- удалены токены scale из example для plasma-new-hope
Scale ошибочно применялся к кнопке при ховере и нажатии, поэтому были удалены токены, которые задавали значение scale.
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.19.0-canary.1110.8254420470.0
npm install @salutejs/caldera@0.19.0-canary.1110.8254420470.0
npm install @salutejs/plasma-asdk@0.55.0-canary.1110.8254420470.0
npm install @salutejs/plasma-b2c@1.297.0-canary.1110.8254420470.0
npm install @salutejs/plasma-new-hope@0.59.0-canary.1110.8254420470.0
npm install …
```

feat: remove scale tokens from Button & ButtonGroup

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/ButtonBase/index.ts
packages/plasma-b2c/src/index.ts
packages/plasma-new-hope/src/components/ButtonBase/index.ts
packages/plasma-new-hope/src/index.ts
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/ButtonBase/index.ts
packages/plasma-web/src/index.ts

-   добавлен styled-элемент ButtonBase в new-hope и b2c
-   он служит базой для создания кастомных кнопок
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.20.1-canary.1080.8261082592.0
npm install @salutejs/caldera@0.20.1-canary.1080.8261082592.0
npm install @salutejs/plasma-asdk@0.56.1-canary.1080.8261082592.0
npm install @salutejs/plasma-b2c@1.298.1-canary.1080.8261082592.0
npm install @salutejs/plasma-new-hope@0.60.1-canary.1080.8261082592.0
npm install @salutejs/plasma-web@1.298.1-canary.1080.8261082592.0
npm install @salutejs/sdds-serv@0.23.1-canary.1080.8261082592.0
yarn add @salutejs/caldera-online@0.20.1-canary.1080.8261082592.0
yarn add …
```

feat(plasma-new-hope, b2c): ButtonBase

---

packages/plasma-icons/package-lock.json
packages/plasma-icons/package.json
packages/plasma-icons/src/old/IconRoot.tsx
packages/plasma-icons/src/scalable/IconRoot.tsx

- убрали зависимость `plasma-core` и заменили на plain value: `var(--plasma-colors-primary)` 
- поставили версию `5.1.0` для `@types/styled-components` (в клиентских пакетах именно такая)
`npx lerna bootstrap --scope="@salutejs/{plasma-new-hope,plasma-web-docs,plasma-web,plasma-docs-ui}"`
при сборке документации для `plasma-web-docs` упадет с ошибкой:
```console
Error:  Client bundle compiled with errors therefore further build is impossible.
Module not found: Error: Can't resolve '@salutejs/plasma-core' in '/home/runner/work/DEV_STAGE/DEV_STAGE/website/plasma-web-docs/node_modules/@salutejs/plasma-icons/es'
```  
```console
Module not found: Error: Can't resolve '@salutejs/plasma-core' in '/home/runner/work/DEV_STAGE/DEV_STAGE/website/plasma-web-docs/node_modules/@salutejs/plasma-icons/es …
```

plasma-infra: Plasma-icons delete dep plasma-core

---

.github/workflows/required-primary-checks.yml

В приватном пакете `@salutejs/perftest-helpers` тоже есть/будут `unit test` и поэтому флаг `--no-private` мешает.  
Нужен что бы разблокировать - https://github.com/salute-developers/plasma/pull/1114

plasma-infra: Delete flag `--no-private` [Unit test]

---

packages/plasma-b2c/src/components/Drawer/Drawer.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/Drawer/Drawer.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Drawer/Drawer.stories.tsx
packages/plasma-new-hope/src/examples/sds_engineer/components/Drawer/Drawer.stories.tsx
packages/plasma-web/src/components/Drawer/Drawer.stories.tsx
packages/sdds-serv/src/components/Drawer/Drawer.stories.tsx

- изменили величину измерения высоты на dvh в storybook
Так как в браузерах телефона появляется плашка, которая накладывается поверх контента - из-за высоты дровера не было видно скруглений.
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.21.1-canary.1116.8323779850.0
npm install @salutejs/caldera@0.21.1-canary.1116.8323779850.0
npm install @salutejs/plasma-asdk@0.58.2-canary.1116.8323779850.0
npm install @salutejs/plasma-b2c@1.300.3-canary.1116.8323779850.0
npm install @salutejs/plasma-new-hope@0.61.1-canary.1116.8323779850.0
npm install @salutejs/plasma-web@1.300.3-canary.1116.8323779850.0
npm install …
```

fix: change height for Drawer stories

---

packages/caldera-online/package-lock.json
packages/caldera/package-lock.json
packages/plasma-asdk/package-lock.json
packages/plasma-b2c/package-lock.json
packages/plasma-b2c/src/components/Image/Image.stories.tsx
packages/plasma-new-hope/package-lock.json
packages/plasma-new-hope/src/components/Image/Image.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/Image/Image.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Image/Image.stories.tsx
packages/plasma-new-hope/src/examples/sds_engineer/components/Image/Image.stories.tsx
packages/plasma-web/package-lock.json
packages/plasma-web/src/components/Image/Image.stories.tsx
packages/sdds-serv/package-lock.json
packages/sdds-serv/src/components/Image/Image.stories.tsx

- поправлена передача пропсов в Image сторях
Поправлена передача пропсов в Image сторях.
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.21.2-canary.1119.8324919346.0
npm install @salutejs/caldera@0.21.2-canary.1119.8324919346.0
npm install @salutejs/plasma-asdk@0.58.3-canary.1119.8324919346.0
npm install @salutejs/plasma-b2c@1.300.4-canary.1119.8324919346.0
npm install @salutejs/plasma-new-hope@0.61.2-canary.1119.8324919346.0
npm install @salutejs/plasma-web@1.300.4-canary.1119.8324919346.0
npm install @salutejs/sdds-serv@0.25.3-canary.1119.8324919346.0
yarn add @salutejs/caldera-online@0.21.2-canary.1119.8324919346.0
yarn add …
```

fix: fix args for Image stories

---

.github/config-ci.json
.github/create-links.js
.github/processing-scope.js
.github/workflows/change-detection.yml
.github/workflows/cypress.yml
.github/workflows/documentation-deploy-pr.yml
.github/workflows/documentation-main.yml
.github/workflows/documentation-pr.yml
.github/workflows/performance-test-base.yml
.github/workflows/performance-test-pr.yml
.github/workflows/publish-canary.yml
.github/workflows/required-primary-checks.yml
.github/workflows/theme-builder-pr.yml
.github/workflows/theme-builder.yml
.github/workflows/typescript-coverage.yml

- распараллели процесс создания и загрузки артефактов документации
- добавили `marocchino/sticky-pull-request-comment` для приклеивания сообщения к одному комментарию в pr
- добавлена конфигурация: `config-ci.json` 
- удалены неиспользуемые переменные
При увеличении кол-ва клиентских пакетов будет расти время загрузки артефактов документации. 
Уже сейчас время на загрузку для всех пакетов составляет: от `20 min` до `30 min`.
Поэтом решили делать параллельные job сборки документации (нечто подобное делаем для запуска тестов Cypress)       
- возможность перезапустить упавшую job для конкретного пакета (раньше весь процесс целиком)  
- ставится только то что нужно пакету который запустил pipeline
- возможность доп оптимизаций, что дадут ускорения выполнения (например включение cache)
- …

plasma-infra: Refactoring deploy documentations artefacts [PR context] 

---

.github/workflows/publish-rc.yml

В workflow для публикации релиз кандидата забыл 
- поправить формат получаемых данных для `process-scope.js` 
- в job "catch" неправильное имя failed job и поэтому не могу ничего найти
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.21.3-canary.1143.8386648522.0
npm install @salutejs/caldera@0.21.3-canary.1143.8386648522.0
npm install @salutejs/plasma-asdk@0.58.4-canary.1143.8386648522.0
npm install @salutejs/plasma-b2c@1.300.5-canary.1143.8386648522.0
npm install @salutejs/plasma-core@1.154.1-canary.1143.8386648522.0
npm install @salutejs/plasma-hope@1.271.2-canary.1143.8386648522.0
npm install @salutejs/plasma-new-hope@0.61.3-canary.1143.8386648522.0 …
```

plasma-infra: Fix publish rc

---

packages/plasma-asdk/.storybook/decoratorThemes.tsx
packages/plasma-asdk/.storybook/preview-head.html
packages/plasma-b2c/.storybook/decoratorThemes.tsx
packages/plasma-b2c/.storybook/preview-head.html
packages/plasma-web/.storybook/decoratorThemes.tsx
packages/plasma-web/.storybook/preview-head.html

* Исправлена ошибка примера путём обновления токенов бэграундов в сторибуке для библиотек `plasma-web`, `plasma-b2c`, `plasma-asdk`.
До:
После:
Сейчас заливка некоторых новых компонент сливаются с фоном сторибука
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.58.4-canary.1139.8374382404.0
npm install @salutejs/plasma-b2c@1.300.5-canary.1139.8374382404.0
npm install @salutejs/plasma-web@1.300.5-canary.1139.8374382404.0
yarn add @salutejs/plasma-asdk@0.58.4-canary.1139.8374382404.0
yarn add @salutejs/plasma-b2c@1.300.5-canary.1139.8374382404.0
yarn add @salutejs/plasma-web@1.300.5-canary.1139.8374382404.0
```
</details>

fix(plasma-web,plasma-b2c,plasma-asdk): Replace tokens for background in storybook to new

---

packages/plasma-asdk/.storybook/decoratorThemes.tsx
packages/plasma-b2c/.storybook/decoratorThemes.tsx
packages/plasma-web/.storybook/decoratorThemes.tsx

Во время сборки сторибука через vite в слинкованных пакетах происходит ошибка при попытке зарезволить вложенные пути
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.59.2-canary.1144.8391665037.0
npm install @salutejs/plasma-b2c@1.301.2-canary.1144.8391665037.0
npm install @salutejs/plasma-web@1.301.2-canary.1144.8391665037.0
yarn add @salutejs/plasma-asdk@0.59.2-canary.1144.8391665037.0
yarn add @salutejs/plasma-b2c@1.301.2-canary.1144.8391665037.0
yarn add @salutejs/plasma-web@1.301.2-canary.1144.8391665037.0
```
</details>

fix(plasma-web,plasma-b2c,plasma-asdk): Remove js token from import with nested directory

---

actions/perftest-helpers/src/modules/sendReport.test.ts
actions/perftest-helpers/src/modules/sendReport.ts
actions/perftest-helpers/src/modules/types.ts
actions/perftest-helpers/src/modules/writeComment.ts
package-lock.json
package.json

Добавлена функциональность анализа мод. 
PR в perftool: https://github.com/salute-developers/perftool/pull/420. 
Анализ мод позволяет определять ошибки третьего рода, соответственно job должна реже краснеть в случае шумного прогона. Плюс для компонентов со стабильно мультимодальными результатами должна вырасти точность измерений.
Также исправлено баги:
- ошибка 413 при отправке результатов, 
- падение при отсуствии изменений. 
- добавлено добавление записи в кликач, даже если нечего отправлять, для лучшего подсчета прогонов.
-------
Test 1: https://github.com/salute-developers/plasma/pull/1122
Test 2: https://github.com/salute-developers/plasma/pull/1115 — падение ок

Perftool mode analysis

---

.github/actions/update-package-lock/action.yml

добавлена логика для `on_retry_command`. 
Теперь перед тем как повторить команду `sync package-lock files` сперва сделаем `git reset` для предсказуемости результата.      
НО теперь проверяем что получилось: [29 package.json](https://github.com/salute-developers/plasma/commit/f39b23b14abbd830278302eace0ac3f602e9aa10)
И только [9 lock файлов обновлено](https://github.com/salute-developers/plasma/commit/92ccc499d71f0d1c5ca5046e751609c51f30fddc)
поэтому нам нужно перед retry сбросить результат полученный в момент ошибки и заново все прогнать.

plasma-infra: Refactoring retry for sync package-lock files

---

.github/workflows/dispatch-custom-event.yml

- добавлен dispatch события для запуска `build icons` в `plasma-android`
Вызывается или в ручном режиме с указанием версии пакета plasma-icons или после публикации релиза. 
Нужно чтобы процесс сборки иконок было в полу-автоматическом режиме.   
Черновик - https://github.com/salute-developers/plasma/issues/1129

plasma-infra: Dispatch build-icons event

---

packages/plasma-b2c/src/components/Tooltip/Tooltip.config.ts
packages/plasma-b2c/src/components/Tooltip/Tooltip.stories.tsx
packages/plasma-new-hope/src/components/Popover/Popover.tsx
packages/plasma-new-hope/src/components/Tooltip/Tooltip.tokens.ts
packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx
packages/plasma-new-hope/src/components/Tooltip/Tooltip.types.ts
packages/plasma-web/src/components/Tooltip/Tooltip.config.ts
packages/plasma-web/src/components/Tooltip/Tooltip.stories.tsx
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/Tooltip/Tooltip.config.ts
packages/sdds-serv/src/components/Tooltip/Tooltip.stories.tsx
packages/sdds-serv/src/components/Tooltip/Tooltip.tsx
packages/sdds-serv/src/components/Tooltip/index.ts
packages/sdds-serv/src/index.ts

-  добавлены фолбэки на следующие свойства: isVisible, arrow, animated
При рефакторинге тултипа потерялись некоторые пропсы из-за чего пропала обратная совместимость.
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.23.0-canary.1140.8433944914.0
npm install @salutejs/caldera@0.23.0-canary.1140.8433944914.0
npm install @salutejs/plasma-asdk@0.60.0-canary.1140.8433944914.0
npm install @salutejs/plasma-b2c@1.302.0-canary.1140.8433944914.0
npm install @salutejs/plasma-new-hope@0.63.0-canary.1140.8433944914.0
npm install @salutejs/plasma-web@1.302.0-canary.1140.8433944914.0
npm install @salutejs/sdds-serv@0.27.0-canary.1140.8433944914.0
yarn add …
```

feat(plasma-new-hope): tooltip old api fallback

---

packages/plasma-icons/package.json

- добавлена директория `old` для обратной совместимости  
поломались пути до части иконок, например 
```console
Module not found: Can't resolve './old/Icons/IconClockFilled'
```
или
```console
unhandledRejection Error: Cannot find module './old/Icons/IconApps'
```
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.26.1-canary.1149.8446846250.0
npm install @salutejs/caldera@0.26.1-canary.1149.8446846250.0
npm install @salutejs/plasma-asdk@0.63.1-canary.1149.8446846250.0
npm install @salutejs/plasma-b2c@1.305.1-canary.1149.8446846250.0
npm install @salutejs/plasma-hope@1.272.1-canary.1149.8446846250.0
npm install …
```

plasma-icons: Add `old` dir for publish

---

utils/plasma-tokens-utils/src/functions.ts
website/plasma-theme-builder/src/builder/createTheme.ts
website/plasma-theme-builder/src/components/Token/Token.tsx
website/plasma-theme-builder/src/components/TokenForm/TokenForm.tsx
website/plasma-theme-builder/src/types/formulas.ts
website/plasma-theme-builder/src/types/index.ts
website/plasma-theme-builder/src/utils/color.tsx
website/plasma-theme-builder/src/utils/formulas.tsx
website/plasma-theme-builder/src/utils/index.ts
website/plasma-theme-builder/src/utils/other.tsx
website/plasma-theme-builder/src/utils/themes.tsx
website/plasma-theme-builder/src/utils/tokens.tsx

* Добавлена генерация hover / active состояний для групп токенов.
Необходимо было добавить генерацию токенов.
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_caldera_online_react-native--canary.1134.8504864222.ts'>borderRadius_caldera_online_react-native--canary.1134.8504864222.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_caldera_react-native--canary.1134.8504864222.ts'>borderRadius_caldera_react-native--canary.1134.8504864222.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_reac …

feat(plasma-theme-builder): Add generate hover / active state for tokens

---

website/plasma-web-docs/docs/_changelog.md

ссылка `_changelog` указывала на файл из `plasma-ui`  
<details>
<br />
```bash
npm install @salutejs/plasma-web@1.311.1-canary.1173.8611058354.0
yarn add @salutejs/plasma-web@1.311.1-canary.1173.8611058354.0
```
</details>

plasma-docs(web-docs): Fix symlink for `_changelog.md`

---

.github/get-lerna-scope.js
.github/meta.js
.github/workflows/documentation-deploy-pr.yml

Декларативно описали JSON структуру - это возможный состояние того, что нужно установить для корректной работы пакета и сборки документации. 
Главная задача уйти от большого кол-ва `if` для каждого пакета и сделать процесс максимально прозрачным.  
`Lerna` может предоставить список того что зависит от пакета и его транзитивные зависимости. 
```console
npx lerna la --json --include-dependencies --scope="package"
```    
В нашем случае в этот список будут попадать транзитивные зависимости зависимостей =(
и в итоге все равно придется писать фильтр лист только уже на базе ignore логики.
Как только наши пакеты и их зависимости будет приведены в порядок. Можно будет посмотреть в сторону комбинации `lerna la` и минимального конфига.

plasma-infra: Refactoring deploy documentations artefacts

---

packages/plasma-new-hope/src/components/Cell/Cell.tsx
website/plasma-website/components/roster/Grid.tsx
website/plasma-website/components/roster/IconsList.tsx

Фикс ввода названий иконок
Сделал так, что обрезал все кроме букв и цифр. А еще добавил отступы у блоков иконок 
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.31.2-canary.1169.8614020591.0
npm install @salutejs/plasma-asdk@0.69.1-canary.1169.8614020591.0
npm install @salutejs/plasma-b2c@1.311.1-canary.1169.8614020591.0
npm install @salutejs/plasma-new-hope@0.71.2-canary.1169.8614020591.0
npm install @salutejs/plasma-web@1.311.1-canary.1169.8614020591.0
npm install @salutejs/sdds-serv@0.36.1-canary.1169.8614020591.0
yarn add @salutejs/caldera-online@0.31.2-canary.1169.8614020591.0
yarn add @salutejs/plasma-asdk@0.69.1-canary.1169.8614020591.0
yarn add …
```

fix(plasma-website): Fix Icons

---

packages/plasma-b2c/src/components/Dropdown/Dropdown.stories.tsx
packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
packages/plasma-b2c/src/components/Tooltip/Tooltip.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/Divider/Divider.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/TextField/TextField.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/Tooltip/Tooltip.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/TextField/TextField.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Tooltip/Tooltip.stories.tsx
packages/plasma-new-hope/src/examples/sds_engineer/components/TextField/TextField.stories.tsx
packages/plasma-new-hope/src/examples/sds_engineer/components/Tooltip/Tooltip.stories.tsx
packages/plasma-web/src/components/Dropdown/Dropdown.stories.tsx
packages/plasma-web/src/components/TextField/TextField.stories.tsx
packages/plasma-web/src/components/Tooltip/Tooltip.stories.tsx
packages/sdds-serv/src/components/TextField/TextField.stories.tsx
packages/sdds-serv/src/components/Tooltip/Tooltip.stories.tsx

- Исправлено некорректное поведение пропса placement
- Также исправлен проп enableContentLeft и enableContentRight в TextField
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.35.1-canary.1182.8691036704.0
npm install @salutejs/plasma-asdk@0.73.1-canary.1182.8691036704.0
npm install @salutejs/plasma-b2c@1.315.1-canary.1182.8691036704.0
npm install @salutejs/plasma-new-hope@0.75.1-canary.1182.8691036704.0
npm install @salutejs/plasma-web@1.315.1-canary.1182.8691036704.0
npm install @salutejs/sdds-serv@0.41.1-canary.1182.8691036704.0
yarn add @salutejs/caldera-online@0.35.1-canary.1182.8691036704.0
yarn add …
```

feat(plasma-new-hope, b2c, web, sdds): Fix storybook argTypes

---

packages/plasma-web/src/components/TextField/TextField.tsx

- добавлен дефолтный size в прослойку textfield в plasma-web
В прослойке textfield в plasma-web значение size переопределялось, из-за чего не применялись дефолтные значения конфига.
<details>
<br />
```bash
npm install @salutejs/plasma-web@1.317.0-canary.1187.8736914506.0
yarn add @salutejs/plasma-web@1.317.0-canary.1187.8736914506.0
```
</details>

fix(plasma-web): add default size to Textfield interlayer

---

packages/plasma-new-hope/src/examples/plasma_b2c/components/Button/Button.stories.tsx

- добавлен story для проверки доступности 
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.36.6-canary.1183.8752730341.0
npm install @salutejs/plasma-asdk@0.74.6-canary.1183.8752730341.0
npm install @salutejs/plasma-b2c@1.316.6-canary.1183.8752730341.0
npm install @salutejs/plasma-new-hope@0.76.6-canary.1183.8752730341.0
npm install @salutejs/plasma-web@1.317.2-canary.1183.8752730341.0
npm install @salutejs/sdds-serv@0.42.6-canary.1183.8752730341.0
yarn add @salutejs/caldera-online@0.36.6-canary.1183.8752730341.0
yarn add @salutejs/plasma-asdk@0.74.6-canary.1183.8752730341.0
yarn add @salutejs/plasma-b2c@1.316.6-canary.1183.8752730341.0
yarn add …
```

plasma-new-hope(Button): Add complex accessibility story

---

packages/plasma-new-hope/src/examples/plasma_b2c/components/Radiobox/Radiobox.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Radiobox/Radiobox.stories.tsx

- расширен пример в `stories` с учетом `a11y` возможностей  
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.36.7-canary.1188.8782897168.0
npm install @salutejs/plasma-asdk@0.74.7-canary.1188.8782897168.0
npm install @salutejs/plasma-b2c@1.316.7-canary.1188.8782897168.0
npm install @salutejs/plasma-new-hope@0.76.7-canary.1188.8782897168.0
npm install @salutejs/plasma-web@1.317.3-canary.1188.8782897168.0
npm install @salutejs/sdds-serv@0.42.7-canary.1188.8782897168.0
yarn add @salutejs/caldera-online@0.36.7-canary.1188.8782897168.0
yarn add @salutejs/plasma-asdk@0.74.7-canary.1188.8782897168.0
yarn add …
```

plasma-new-hope(radiobox): Improved a11y

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-new-hope/src/components/TextField/TextField.tsx
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/TextField/TextField.tsx
packages/sdds-serv/api/sdds-serv.api.md

- исправлен target для `ref` (теперь указывает на input tag)

plasma-*: Fix textfield ref 

---

packages/plasma-b2c/src/components/Calendar/Calendar.stories.tsx
packages/plasma-new-hope/src/components/Calendar/Calendar.types.ts
packages/plasma-new-hope/src/components/Calendar/CalendarBase/CalendarBase.tsx
packages/plasma-new-hope/src/components/Calendar/CalendarDouble/CalendarDouble.tsx
packages/plasma-new-hope/src/components/Calendar/hooks/useDays.ts
packages/plasma-new-hope/src/components/Calendar/ui/CalendarDays/CalendarDays.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarDays/CalendarDays.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Calendar/Calendar.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Calendar/Calendar.stories.tsx
packages/plasma-new-hope/src/examples/sds_engineer/components/Calendar/Calendar.stories.tsx
packages/plasma-web/src/components/Calendar/Calendar.stories.tsx

- добавлен пропс для включения/исключения минимума и максимума диапазона дат
Появился запрос на выбор крайних дат диапазона. Изначально было нестрогое сравнение на выход за границы периода из-за чего крайние значения были недоступны. Пример: min=7 max=15, при этом числа доступные для выбора 7 < x < 15
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.42.0-canary.1203.9113315762.0
npm install @salutejs/plasma-asdk@0.80.0-canary.1203.9113315762.0
npm install @salutejs/plasma-b2c@1.322.0-canary.1203.9113315762.0
npm install @salutejs/plasma-new-hope@0.82.0-canary.1203.9113315762.0
npm install @salutejs/plasma-web@1.323.0-canary.1203.9113315762.0
npm install …
```

feat: add calendar edge dates control

---

actions/perftest-helpers/src/modules/writeComment.test.ts
actions/perftest-helpers/src/modules/writeComment.ts

Добавляет сообщение об ошибке в случае сломанных перф тестов
ТЕСТ https://github.com/salute-developers/plasma/pull/1212

Add message for broken perftests

---

packages/plasma-new-hope/src/components/Segment/Segment.template-doc.mdx
packages/plasma-new-hope/src/components/Tabs/Tabs.template-doc.mdx
packages/plasma-new-hope/src/components/Tabs/ui/TabItem/TabItem.tsx
packages/plasma-new-hope/src/components/Tabs/ui/Tabs/Tabs.styles.ts
packages/plasma-new-hope/src/components/Tabs/ui/Tabs/Tabs.tsx
website/plasma-web-docs/docs/components/Segment.mdx
website/plasma-web-docs/docs/components/Tabs.mdx
website/sdds-serv-docs/docs/components/Segment.mdx
website/sdds-serv-docs/docs/components/Tabs.mdx

- добавлен корректный проброс className в Tab и TabItem
- поправлена документация для Tab и Segment
ДО:
ПОСЛЕ:
В Tab и TabItem некорректно пробрасывался className, поэтому нельзя было оборачивать компонент в styled. Помимо этого в документации некорректно визуально отображались табы и сегменты
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.46.0-canary.1220.9266427683.0
npm install @salutejs/plasma-asdk@0.84.0-canary.1220.9266427683.0
npm install @salutejs/plasma-b2c@1.326.0-canary.1220.9266427683.0
npm install @salutejs/plasma-new-hope@0.86.0-canary.1220.9266427683.0
npm install @salutejs/plasma-web@1.327.0-canary.1220.9266427683.0
npm install …
```

feat(plasma-new-hope): fix tabs styles

---

packages/caldera-online/api/caldera-online.api.md
packages/caldera-online/src/components/Checkbox/Checkbox.tsx
packages/caldera-online/src/components/Radiobox/Radiobox.ts
packages/plasma-asdk/api/plasma-asdk.api.md
packages/plasma-asdk/src/components/Checkbox/Checkbox.stories.tsx
packages/plasma-asdk/src/components/Checkbox/Checkbox.tsx
packages/plasma-asdk/src/components/Radiobox/Radiobox.stories.tsx
packages/plasma-asdk/src/components/Radiobox/Radiobox.ts
packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Checkbox/Checkbox.tsx
packages/plasma-b2c/src/components/Radiobox/Radiobox.ts
packages/plasma-new-hope/src/components/Checkbox/Checkbox.types.ts
packages/plasma-new-hope/src/components/Radiobox/Radiobox.tsx
packages/plasma-new-hope/src/mixins/applyDisabled.ts
packages/plasma-new-hope/src/mixins/index.ts
packages/plasma-new-hope/src/types/InputHTMLAttributes.ts
packages/plasma-new-hope/src/types/index.ts
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Checkbox/Checkbox.tsx
packages/plasma-web/src/components/Radiobox/Radiobox.ts
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/Checkbox/Checkbox.tsx
packages/sdds-serv/src/components/Radiobox/Radiobox.ts

Поправил типы в checkbox для библиотек plasma-asdk, sdds-serv и caldera-online  
Убрал принудительно поставленный тип в этих библиотеках. Теперь код аналогичен web и b2c
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.46.1-canary.1217.9271710675.0
npm install @salutejs/plasma-asdk@0.84.1-canary.1217.9271710675.0
npm install @salutejs/plasma-b2c@1.326.1-canary.1217.9271710675.0
npm install @salutejs/plasma-new-hope@0.86.1-canary.1217.9271710675.0
npm install @salutejs/plasma-web@1.327.1-canary.1217.9271710675.0
npm install @salutejs/sdds-serv@0.54.1-canary.1217.9271710675.0
yarn add @salutejs/caldera-online@0.46.1-canary.1217.9271710675.0
yarn add …
```

Fix checkbox types

---

packages/plasma-icons/scripts/utils.ts

- заменили значение свойства `stroke` на `currentColor`
Цвет для свойства `stroke` не наследовался, потому что значение были константой (захардкожены внутри самого svg). Теперь используем `currentColor` чтобы была возможность управлять цветом из вне.  
https://codesandbox.io/p/sandbox/plasma-web-example-forked-6w8vvp?file=%2Fpackage.json%3A3%2C64
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.85.1-canary.1226.9349089565.0
npm install @salutejs/plasma-b2c@1.327.1-canary.1226.9349089565.0
npm install @salutejs/plasma-hope@1.280.1-canary.1226.9349089565.0
npm install @salutejs/plasma-icons@1.193.1-canary.1226.9349089565.0
npm install …
```

plasma-icons: Replace stroke value to "currentColor"

---

.github/workflows/cypress-release-branch.yml
.github/workflows/cypress.yml

- запуск `workflow` **только** в релизной ветки и без условий ( для всех библиотек ) 
Один из шагов автоматизации регресса.

plasma-infra: Cypress checks on release branch

---

packages/caldera-online/api/caldera-online.api.md
packages/caldera-online/src/components/Switch/Switch.tsx
packages/plasma-asdk/api/plasma-asdk.api.md
packages/plasma-asdk/src/components/Switch/Switch.tsx
packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Switch/Switch.tsx
packages/plasma-new-hope/src/components/Switch/Switch.tsx
packages/plasma-new-hope/src/components/Switch/Switch.types.ts
packages/plasma-new-hope/src/components/Switch/index.ts
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Switch/Switch.tsx
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/Switch/Switch.tsx
scaffold/template-docs/docusaurus.config.js
utils/plasma-docs-ui/README.md
utils/plasma-docs-ui/src/components/PropsTable.tsx
utils/plasma-docs-ui/src/types/DocgenInfo.ts
website/plasma-ui-docs/docusaurus.config.js
website/plasma-ui-docs/src/components/PropsTable.tsx
website/plasma-web-docs/docs/components/Checkbox.mdx
website/plasma-web-docs/docs/components/Radiobox.mdx
website/plasma-web-docs/docs/components/Switch.mdx
website/plasma-web-docs/docusaurus.config.js
website/plasma-web-docs/src/components/PropsTable.tsx
website/sdds-serv-docs/docs/components/Checkbox.mdx
website/sdds-serv-docs/docs/components/Radiobox.mdx
website/sdds-serv-docs/docs/components/Switch.mdx
website/sdds-serv-docs/docusaurus.config.js
website/sdds-serv-docs/src/components/PropsTable.tsx

- исправлена документация для компонента `Switch`, `Checkbox` и `Radiobox`
- изменена работа документации, теперь при генерации файла документации туда добавляются все типы, в том числе и из `react`
- в компонент `PropsTable` добавлен параметр `include`, который добавляет свойство в документацию, если он является типом из `react`
Поменял типы в Switch во всех библиотеках, теперь принцип работы аналогичен Checkbox и Radiobox, а также добавил обратную совместимость с core
Изменил импорт типов в Switch во всех библиотеках 
Изменил принцип работы генерации доки. Теперь в json сохраняется все типы и обрезка типов из react происходит в самом компоненте 
Добавил скриншоты:
Как было:
Как стало:
<details>
<br /> …

plasma-*: Edit docs core and change docs Switch, Checkbox and Radiobox

---

website/plasma-web-docs/docs/components/Carousel.mdx

- исправлено свойства `stylingCallback` на `scopeCallback`
- исправлено свойства `stylingResetCallback` на `scopeResetCallback`
Убрал несуществующие свойства stylingCallback и stylingResetCallback, заменил их на существующие scopeCallback и scopeResetCallback

Edit carousel docs

---

packages/plasma-icons/scripts/generateAndroidArchive.ts

- добавлены `.xml` иконки для всех имеющихся размеров: 16, 24, 36
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.93.0-canary.1259.9613931890.0
npm install @salutejs/plasma-b2c@1.335.0-canary.1259.9613931890.0
npm install @salutejs/plasma-hope@1.285.0-canary.1259.9613931890.0
npm install @salutejs/plasma-icons@1.198.0-canary.1259.9613931890.0
npm install @salutejs/plasma-ui@1.255.0-canary.1259.9613931890.0
npm install @salutejs/plasma-web@1.336.0-canary.1259.9613931890.0
npm install @salutejs/sdds-serv@0.63.0-canary.1259.9613931890.0
yarn add @salutejs/plasma-asdk@0.93.0-canary.1259.9613931890.0
yarn add …
```

plasma-icons: handle all icons size [Android]

---

website/plasma-website/components/roster/Footer.tsx
website/plasma-website/components/roster/Header.tsx
website/plasma-website/components/roster/IconClipboard.tsx
website/plasma-website/components/roster/IconExtendedInfo.tsx
website/plasma-website/components/roster/IconHoverDetails.tsx
website/plasma-website/components/roster/IconOptionsColors.tsx
website/plasma-website/components/roster/IconOptionsSize.tsx
website/plasma-website/components/roster/IconsList.tsx
website/plasma-website/package-lock.json
website/plasma-website/pages/icons.tsx
website/plasma-website/store/actions.ts
website/plasma-website/store/index.tsx
website/plasma-website/store/reducer.ts
website/plasma-website/store/types.ts
website/plasma-website/types/Data.ts
website/plasma-website/utils/iconsList.ts

- добавлен вывод комбинации (старых + новых) иконок
- добавлено динамическое изменение размера иконок в grid
- косметические правки по дизайну

plasma-website: Redesign "Icons" page [Part 2]

---

scaffold/template-docs/docs/intro.mdx
website/caldera-online-docs/docs/intro.mdx
website/sdds-serv-docs/docs/intro.mdx

Исправлен шаблон для `intro.mdx`.
В документации указывался пакет `@salutejs/plasma-tokens`, а нужно было целевой. 
Например для `caldera-online` необходимо установить и использовать `@salutejs/caldera-online-themes`.

plasma-docs: Fix intro.mdx

---

website/plasma-website/components/roster/AbstractIcon.tsx
website/plasma-website/components/roster/IconFilterMenu.tsx
website/plasma-website/components/roster/IconOptionsColors.tsx
website/plasma-website/components/roster/IconOptionsSize.tsx
website/plasma-website/components/roster/IconsList.tsx
website/plasma-website/components/roster/index.ts
website/plasma-website/package-lock.json
website/plasma-website/package.json
website/plasma-website/pages/icons.tsx
website/plasma-website/store/actions.ts
website/plasma-website/store/index.tsx
website/plasma-website/store/reducer.ts
website/plasma-website/store/types.ts
website/plasma-website/types/Data.ts
website/plasma-website/utils/iconsList.ts
website/plasma-website/utils/listSizes.ts

- добавлено меню фильтра по размеру 
- внесены дизайн правки   
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.51.1-canary.1265.9664294667.0
npm install @salutejs/plasma-asdk@0.94.1-canary.1265.9664294667.0
npm install @salutejs/plasma-b2c@1.336.1-canary.1265.9664294667.0
npm install @salutejs/plasma-new-hope@0.91.1-canary.1265.9664294667.0
npm install @salutejs/plasma-web@1.337.1-canary.1265.9664294667.0
npm install @salutejs/sdds-serv@0.64.1-canary.1265.9664294667.0
yarn add @salutejs/caldera-online@0.51.1-canary.1265.9664294667.0
yarn add @salutejs/plasma-asdk@0.94.1-canary.1265.9664294667.0
yarn add …
```

plasma-website: Add icons filter menu

---

packages/caldera-online/src/components/Sheet/Sheet.stories.tsx
packages/plasma-b2c/src/components/Sheet/Sheet.stories.tsx
packages/plasma-new-hope/src/components/Sheet/Sheet.tsx
packages/plasma-new-hope/src/components/Sheet/Sheet.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Sheet/Sheet.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Sheet/Sheet.stories.tsx
packages/plasma-web/src/components/Sheet/Sheet.stories.tsx
packages/sdds-serv/src/components/Sheet/Sheet.stories.tsx
website/caldera-online-docs/docs/components/Sheet.mdx

- убран из примеров в `stories` лишний горизонтальный скролл 
- добавлена недостающая документация в `caldera-online` 
**Before**:
**After**:
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.55.1-canary.1273.9743629696.0
npm install @salutejs/plasma-asdk@0.98.1-canary.1273.9743629696.0
npm install @salutejs/plasma-b2c@1.340.1-canary.1273.9743629696.0
npm install @salutejs/plasma-new-hope@0.95.1-canary.1273.9743629696.0
npm install @salutejs/plasma-web@1.341.1-canary.1273.9743629696.0
npm install @salutejs/sdds-serv@0.68.1-canary.1273.9743629696.0
yarn add @salutejs/caldera-online@0.55.1-canary.1273.9743629696.0
yarn add …
```

plasma-*: Fix `Sheet` scroll

---

package.json
scaffold/Readme.md
scaffold/scaffold-components.js

- скрипт для генерации компонентов вынесен в отдельную команду
Теперь есть возможность запустить команду 
```console
npm run scaffold:update-components-docs --vertical="caldera-online-themes" --package="caldera-online" --exclude="sheet"
```
и тем самым обновить все компоненты документации(в том числе появятся новые, и sync старых).

plasma-infra(scaffold): Extend script for update/sync component list 

---

packages/plasma-new-hope/src/components/Dropdown/Dropdown.tsx
packages/plasma-new-hope/src/components/Dropdown/Dropdown.types.ts
packages/plasma-new-hope/src/components/Popover/Popover.tsx
website/plasma-web-docs/docs/components/Dropdown.mdx
website/sdds-serv-docs/docs/components/Dropdown.mdx

- добавлено новое свойство `portal`
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.57.0-canary.1260.9777960646.0
npm install @salutejs/plasma-asdk@0.100.0-canary.1260.9777960646.0
npm install @salutejs/plasma-b2c@1.342.0-canary.1260.9777960646.0
npm install @salutejs/plasma-new-hope@0.97.0-canary.1260.9777960646.0
npm install @salutejs/plasma-web@1.343.0-canary.1260.9777960646.0
npm install @salutejs/sdds-serv@0.70.0-canary.1260.9777960646.0
yarn add @salutejs/caldera-online@0.57.0-canary.1260.9777960646.0
yarn add @salutejs/plasma-asdk@0.100.0-canary.1260.9777960646.0
yarn add @salutejs/plasma-b2c@1.342.0-canary.1260.9777960646.0
yarn add …
```

feat(plasma-new-hope): Added prop 'portal' into Dropdown component

---

website/plasma-ui-docs/src/components/Storybook.tsx
website/plasma-web-docs/src/components/Storybook.tsx

- убрана ссылка/кнопка на storybook из документации для `plasma-{web,ui}`
**Before:**
**After:**
Сокращенные ссылки не работали как ожидается. Поэтому приняли решение временно скрыть/убрать их.

plasma-docs: hide short links for storybook

---

packages/plasma-icons/scripts/generateIconsIos.mjs

- исправлена генерация иконок под iOS
**Before:**
**After:**
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.102.1-canary.1283.9806525690.0
npm install @salutejs/plasma-b2c@1.344.1-canary.1283.9806525690.0
npm install @salutejs/plasma-hope@1.286.1-canary.1283.9806525690.0
npm install @salutejs/plasma-icons@1.198.1-canary.1283.9806525690.0
npm install @salutejs/plasma-ui@1.256.1-canary.1283.9806525690.0
npm install @salutejs/plasma-web@1.345.1-canary.1283.9806525690.0
npm install @salutejs/sdds-serv@0.72.1-canary.1283.9806525690.0
yarn add @salutejs/plasma-asdk@0.102.1-canary.1283.9806525690.0
yarn add @salutejs/plasma-b2c@1.344.1-canary.1283.9806525690.0 …
```

plasma-icons: Rewrite generate icons for iOS

---

packages/plasma-new-hope/src/components/Popup/Popup.template-doc.mdx
packages/plasma-new-hope/src/components/Slider/ui/Handler/Handler.tsx
website/caldera-online-docs/docs/components/Popup.mdx

- удален лишний `console.log(computedBounds);`
- исправлен шаблон для `Popup` (был неправильный import)
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.61.1-canary.1290.9868019360.0
npm install @salutejs/plasma-asdk@0.104.1-canary.1290.9868019360.0
npm install @salutejs/plasma-b2c@1.346.1-canary.1290.9868019360.0
npm install @salutejs/plasma-new-hope@0.101.1-canary.1290.9868019360.0
npm install @salutejs/plasma-web@1.347.1-canary.1290.9868019360.0
npm install @salutejs/sdds-serv@0.74.1-canary.1290.9868019360.0
yarn add @salutejs/caldera-online@0.61.1-canary.1290.9868019360.0
yarn add @salutejs/plasma-asdk@0.104.1-canary.1290.9868019360.0
yarn add …
```

plasma-*: Fix tech debt

---

packages/plasma-icons/scripts/utils.ts

Изменен порядок исполнения функций для 
```js
const svgContent = compose(
removeLineBreak,
getSvgContent,
setFillCurrentColor,
setStrokeCurrentColor,
removeFillOpacity,
**removeOpacity**,
convertInlineStyleToObject,
camelizeAttributes,
)(source);
``` 
чтобы корректно обрабатывать свойства в `svg` 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.105.1-canary.1294.9868888674.0
npm install @salutejs/plasma-b2c@1.347.1-canary.1294.9868888674.0
npm install @salutejs/plasma-hope@1.287.1-canary.1294.9868888674.0
npm install @salutejs/plasma-icons@1.198.3-canary.1294.9868888674.0
npm install @salutejs/plasma-ui@1.257.1-canary.1294.9868888674.0
npm install …
```

plasma-icons: Changes execute order methods in compose

---

packages/plasma-b2c/src/components/AudioPlayer/AudioPlayer.stories.tsx
packages/plasma-web/src/components/AudioPlayer/AudioPlayer.stories.tsx
website/plasma-web-docs/docs/components/AudioPlayer.mdx

- изменен `cdn` в примерах`https://vc-static.sberdevices.ru/smartmarket-video-news/` на `https://cdn1.newsback.sberdevices.ru/p-newsback/`
По просьбе команды новостей, ради закапывания `vc-static`
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.350.1-canary.1298.9905613224.0
npm install @salutejs/plasma-web@1.351.1-canary.1298.9905613224.0
yarn add @salutejs/plasma-b2c@1.350.1-canary.1298.9905613224.0
yarn add @salutejs/plasma-web@1.351.1-canary.1298.9905613224.0
```
</details>

plasma-{b2c,web}: Fix vc cdn url

---

packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx

- исправлен проброс стилей в Tooltip
В Tooltip не было возможности переопределить токены.
Теперь className и style прокидываются в Root
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.66.1-canary.1311.9990050021.0
npm install @salutejs/plasma-asdk@0.109.1-canary.1311.9990050021.0
npm install @salutejs/plasma-b2c@1.351.1-canary.1311.9990050021.0
npm install @salutejs/plasma-new-hope@0.106.1-canary.1311.9990050021.0
npm install @salutejs/plasma-web@1.352.1-canary.1311.9990050021.0
npm install @salutejs/sdds-dfa@0.79.1-canary.1311.9990050021.0
npm install @salutejs/sdds-serv@0.80.1-canary.1311.9990050021.0
yarn add …
```

plasma-new-hope:  forward styles and className to Tooltip root

---

packages/plasma-new-hope/src/components/TextArea/TextArea.tsx

- исправлена логика при использовании свойства `autoResize` (теперь ширина автоматически растягивается)
Результат с включенным `autoResize` после изменения ширины
**До:**
**После:**
В функции, которая изменяет ширину, при изменении родительского элемента работала не правильно. До этого - если изменяется высота, то он пересчитывает и ширину в том числе. Теперь она работает только при изменении ширины родительского элемента
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.68.1-canary.1297.10035953739.0
npm install @salutejs/plasma-asdk@0.111.1-canary.1297.10035953739.0
npm install @salutejs/plasma-b2c@1.353.1-canary.1297.10035953739.0
npm install …
```

plasma-*: Fix width autoresize prop in textarea

---

packages/plasma-ui/src/components/Pickers/Pickers.perftest.tsx

-   добавили новый api
-   изменили свойство size
Более подробное описание решаемой проблемы.
<details>
<br />
```bash
npm install @salutejs/plasma-ui@1.263.1-canary.1337.10217683874.0
yarn add @salutejs/plasma-ui@1.263.1-canary.1337.10217683874.0
```
</details>

plasma-ui: fix TimePicker perftest

---

scaffold/template-docs/docs/intro.mdx
website/sdds-dfa-docs/docs/intro.mdx
website/sdds-serv-docs/docs/intro.mdx

* Поправлено описание подключения темы для `sdds` вертикали
Сейчас в документации во вкладке "Введение" упоминается лишнее подключение типографики через зависимость plasma-typo. Это делать не нужно, т.к. токены шрифтов и всех настроек уже лежат в соответствующих темах.
Поэтому необходимо удалить из существующих документаций эту информацию, а также из шаблонов в scaffold.
<details>
<br />
```bash
npm install @salutejs/plasma-ui@1.263.1-canary.1338.10218214240.0
yarn add @salutejs/plasma-ui@1.263.1-canary.1338.10218214240.0
```
</details>

fix(sdds-serv-docs,sdd-dfa-docs): Fix introducing page

---

packages/plasma-new-hope/src/components/Notification/NotificationsPortal.tsx

Добавил `overflow: hidden` на контейнер используемого Popup
Иначе, при анимации скрытия нотификаций появляются общий скрол
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.117.1-canary.1339.10246269224.0
npm install @salutejs/plasma-b2c@1.359.1-canary.1339.10246269224.0
npm install @salutejs/plasma-new-hope@0.114.1-canary.1339.10246269224.0
npm install @salutejs/plasma-web@1.360.1-canary.1339.10246269224.0
npm install @salutejs/sdds-cs@0.89.1-canary.1339.10246269224.0
npm install @salutejs/sdds-dfa@0.87.1-canary.1339.10246269224.0
npm install @salutejs/sdds-serv@0.88.1-canary.1339.10246269224.0
yarn add …
```

fix: fix Notification animation overflow

---

packages/plasma-b2c/package-lock.json
packages/plasma-b2c/package.json
packages/plasma-tokens/package.json
packages/plasma-web/package-lock.json
packages/plasma-web/package.json
packages/themes/core-themes/src/generate.ts
packages/themes/core-themes/src/utils/fallbackTokens.ts
packages/themes/core-themes/src/utils/index.ts
packages/themes/core-themes/src/utils/other.ts
packages/themes/plasma-themes/src/css/plasma_b2c.module.css
packages/themes/plasma-themes/src/css/plasma_b2c__dark.css
packages/themes/plasma-themes/src/css/plasma_b2c__light.css
packages/themes/plasma-themes/src/css/plasma_web.module.css
packages/themes/plasma-themes/src/css/plasma_web__dark.css
packages/themes/plasma-themes/src/css/plasma_web__light.css
packages/themes/plasma-themes/src/themes/plasma_b2c__dark.ts
packages/themes/plasma-themes/src/themes/plasma_b2c__light.ts
packages/themes/plasma-themes/src/themes/plasma_web__dark.ts
packages/themes/plasma-themes/src/themes/plasma_web__light.ts
packages/themes/plasma-themes/src/tokens/plasma_b2c/index.ts
packages/themes/plasma-themes/src/tokens/plasma_web/index.ts

* Добавлены методы генерации старых токенов в библиотеку `core-themes`
* Добавлены токены со старым неймингом (префиксом `plasma-colors`) в вертикаль `plasma-themes` для тем `plasma-web`  и `plasma-b2c`
Сейчас, если использовать способ подключения тем через библиотеку `@salutejs/plasma-themes` часть компонент будет не корректно отображаться, т.к. в них используются старые токены.
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_caldera_online_react-native--canary.1355.10409432870.ts'>borderRadius_caldera_online_react-native--canary.1355.10409432870.ts</a><br>
<a …

feat(plasma-themes): Add fallback tokens for `plasma-themes`

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Tabs/TabsController.tsx
packages/plasma-new-hope/src/components/Tabs/Tabs.template-doc.mdx
packages/plasma-new-hope/src/components/Tabs/ui/TabItem/TabItem.tsx
packages/plasma-new-hope/src/components/Tabs/ui/TabItem/TabItem.types.ts
packages/plasma-new-hope/src/components/Tabs/ui/Tabs/Tabs.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Tabs/TabItem.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Tabs/Tabs.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Tabs/TabsController.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Tabs/TabItem.ts
packages/plasma-new-hope/src/examples/plasma_web/components/Tabs/Tabs.ts
packages/plasma-new-hope/src/examples/plasma_web/components/Tabs/TabsController.tsx
packages/plasma-new-hope/src/types/AsProps.ts
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Tabs/TabsController.tsx
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/Tabs/Tabs.tsx
packages/sdds-cs/src/components/Tabs/TabsController.tsx
packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-dfa/src/components/Tabs/Tabs.tsx
packages/sdds-dfa/src/components/Tabs/TabsController.tsx
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/Tabs/Tabs.tsx
packages/sdds-serv/src/components/Tabs/TabsController.tsx
website/plasma-web-docs/docs/components/Tabs.mdx
website/sdds-cs-docs/docs/components/Tabs.mdx
website/sdds-dfa-docs/docs/components/Tabs.mdx
website/sdds-serv-docs/docs/components/Tabs.mdx

- исправлены типы и описание компонента для корректной генерации документации
- добавлены недостающие примеры в документацию `sdds-cs`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.125.1-canary.1362.10423909326.0
npm install @salutejs/plasma-b2c@1.367.1-canary.1362.10423909326.0
npm install @salutejs/plasma-new-hope@0.122.1-canary.1362.10423909326.0
npm install @salutejs/plasma-web@1.368.1-canary.1362.10423909326.0
npm install @salutejs/sdds-cs@0.97.1-canary.1362.10423909326.0
npm install @salutejs/sdds-dfa@0.95.1-canary.1362.10423909326.0
npm install @salutejs/sdds-serv@0.96.1-canary.1362.10423909326.0
yarn add …
```

fix(plasma-*): Tabs types and documentation

---

packages/plasma-new-hope/src/components/TextField/variations/_label-placement/base.ts

- исправлено "дергание" `label` в `inner` режиме
`height` срабатывает не сразу, а после изменения шрифта, поэтому появляется дергание. `flex` срабатывает сразу
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.129.1-canary.1359.10459694920.0
npm install @salutejs/plasma-b2c@1.371.1-canary.1359.10459694920.0
npm install @salutejs/plasma-new-hope@0.126.1-canary.1359.10459694920.0
npm install @salutejs/plasma-web@1.372.1-canary.1359.10459694920.0
npm install @salutejs/sdds-cs@0.101.1-canary.1359.10459694920.0
npm install @salutejs/sdds-dfa@0.99.1-canary.1359.10459694920.0
npm install @salutejs/sdds-serv@0.100.1-canary.1359.10459694920.0
yarn add …
```

fix(new-hope): Textfield label bug

---

packages/plasma-b2c/src/components/Radiobox/Radiobox.stories.tsx
packages/plasma-new-hope/src/components/TextField/variations/_label-placement/base.ts

- добавлены параметры `view` для примеров в storybook в `plasma-b2c` 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.129.1-canary.1358.10460366650.0
npm install @salutejs/plasma-b2c@1.371.1-canary.1358.10460366650.0
npm install @salutejs/plasma-new-hope@0.126.1-canary.1358.10460366650.0
npm install @salutejs/plasma-web@1.372.1-canary.1358.10460366650.0
npm install @salutejs/sdds-cs@0.101.1-canary.1358.10460366650.0
npm install @salutejs/sdds-dfa@0.99.1-canary.1358.10460366650.0
npm install @salutejs/sdds-serv@0.100.1-canary.1358.10460366650.0
yarn add @salutejs/plasma-asdk@0.129.1-canary.1358.10460366650.0
yarn add …
```

plasma-b2c: Add view props into radiobox stories

---

website/plasma-website/components/roster/SearchForm.tsx

- Исправлено смещение текста при наборе в поиск
- Иногда тексту не хватало места при наборе. Это было исправлено путём увеличения ширины `input` на 1rem и удаления отступа слева в 1rem у иконки-крестика, чтобы визуально всё осталось как было.
При наборе текста видно небольшое смещение. Есть возможность делать мини-прокрутку при наведении на `input`.
https://github.com/user-attachments/assets/e97640f2-ce55-4b6f-873c-bfaadd8b9bbb
Баг не проявляется.
https://github.com/user-attachments/assets/6d779fd2-65b0-4359-ad60-ece903b67feb

plasma-website: fix searchForm input text shifting

---

packages/plasma-new-hope/src/components/Modal/Modal.tsx
packages/plasma-new-hope/src/components/Popup/PopupContext.tsx

- исправлена логика регистрации `popup's`
Сделали ошибку когда правили другой баг  
фикс для PR https://github.com/salute-developers/plasma/pull/1325
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.133.1-canary.1380.10485553077.0
npm install @salutejs/plasma-b2c@1.375.1-canary.1380.10485553077.0
npm install @salutejs/plasma-new-hope@0.128.2-canary.1380.10485553077.0
npm install @salutejs/plasma-web@1.376.1-canary.1380.10485553077.0
npm install @salutejs/sdds-cs@0.105.1-canary.1380.10485553077.0
npm install @salutejs/sdds-dfa@0.103.1-canary.1380.10485553077.0
npm install @salutejs/sdds-serv@0.104.1-canary.1380.10485553077.0
yarn add …
```

plasma-*: Fix Modal Overlay & Popup registration logic

---

.github/workflows/performance-test-base.yml
.github/workflows/performance-test-pr.yml
CODEOWNERS

решили выключить, вернем чуть позже.

plasma-infra: Disabled perf test

---

packages/plasma-new-hope/src/components/Slider/Slider.template-doc.mdx
packages/plasma-new-hope/src/components/Slider/components/SliderBase/SliderBase.tsx
website/plasma-web-docs/docs/components/Slider.mdx
website/sdds-dfa-docs/docs/components/Slider.mdx

- удалена лишняя зависимость `ref.current` в hooks 
- исправлена документация в `plasma-web`
- для `plasma-new-hope` и `sdds-dfa` добавлены недостающие файлы документации
- `ref.current` не нужен в зависимости хука, т.к. его изменение не влечет за собой rerender. Убрали их, чтобы в консоль не попадал warning. 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.136.1-canary.1386.10523593917.0
npm install @salutejs/plasma-b2c@1.378.1-canary.1386.10523593917.0
npm install @salutejs/plasma-new-hope@0.130.1-canary.1386.10523593917.0
npm install @salutejs/plasma-web@1.379.1-canary.1386.10523593917.0
npm install @salutejs/sdds-cs@0.108.1-canary.1386.10523593917.0 …
```

plasma-{new-hope, web}, sdds-dfa: removed redundant dependencies from `Slider` hooks; docs fixed

---

packages/plasma-new-hope/src/components/Tabs/Tabs.template-doc.mdx
website/sdds-serv-docs/docs/components/Tooltip.mdx

добавили в документацию раздел для `Tooltip` 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.136.2-canary.1391.10525070095.0
npm install @salutejs/plasma-b2c@1.378.2-canary.1391.10525070095.0
npm install @salutejs/plasma-new-hope@0.130.2-canary.1391.10525070095.0
npm install @salutejs/plasma-web@1.379.2-canary.1391.10525070095.0
npm install @salutejs/sdds-cs@0.108.2-canary.1391.10525070095.0
npm install @salutejs/sdds-dfa@0.106.2-canary.1391.10525070095.0
npm install @salutejs/sdds-serv@0.107.2-canary.1391.10525070095.0
yarn add @salutejs/plasma-asdk@0.136.2-canary.1391.10525070095.0
yarn add @salutejs/plasma-b2c@1.378.2-canary.1391.10525070095.0
yarn …
```

plasma-docs: Update sdds-serv docs

---

packages/plasma-web/src/components/TextField/TextField.tsx

- добавлен размер `xs` в `plasma-web` 
<details>
<br />
```bash
npm install @salutejs/plasma-web@1.381.0-canary.1395.10561418913.0
yarn add @salutejs/plasma-web@1.381.0-canary.1395.10561418913.0
```
</details>

plasma-web: size `xs` added to `TextField`

---

packages/plasma-b2c/src/components/Checkbox/Checkbox.stories.tsx
packages/plasma-b2c/src/components/Radiobox/Radiobox.stories.tsx
packages/plasma-web/src/components/Checkbox/Checkbox.stories.tsx
packages/plasma-web/src/components/Radiobox/Radiobox.stories.tsx
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/Checkbox/Checkbox.stories.tsx
packages/sdds-dfa/src/components/Checkbox/Checkbox.stories.tsx
packages/sdds-serv/src/components/Checkbox/Checkbox.stories.tsx

- добавлен пропс view в сторибук для Radiobox и Checkbox
- удалены 3 view из sdds-cs для Radiobox и Checkbox, так как их нет в макетах
Не отображалось поле выбора view в сторибук для Radiobox и Checkbox.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.140.0-canary.1385.10628883741.0
npm install @salutejs/plasma-b2c@1.382.0-canary.1385.10628883741.0
npm install @salutejs/plasma-new-hope@0.134.0-canary.1385.10628883741.0
npm install @salutejs/plasma-web@1.384.0-canary.1385.10628883741.0
npm install @salutejs/sdds-cs@0.112.0-canary.1385.10628883741.0
npm install @salutejs/sdds-dfa@0.110.0-canary.1385.10628883741.0
npm install …
```

feat(plasma-*): forward view to radiobox and checkbox stories

---

packages/plasma-new-hope/src/components/Popup/PopupContext.tsx

- удалено обращение к `document` на сервере
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.139.1-canary.1410.10630690850.0
npm install @salutejs/plasma-b2c@1.381.1-canary.1410.10630690850.0
npm install @salutejs/plasma-new-hope@0.133.1-canary.1410.10630690850.0
npm install @salutejs/plasma-web@1.383.1-canary.1410.10630690850.0
npm install @salutejs/sdds-cs@0.111.1-canary.1410.10630690850.0
npm install @salutejs/sdds-dfa@0.109.1-canary.1410.10630690850.0
npm install @salutejs/sdds-serv@0.110.1-canary.1410.10630690850.0
yarn add @salutejs/plasma-asdk@0.139.1-canary.1410.10630690850.0
yarn add @salutejs/plasma-b2c@1.381.1-canary.1410.10630690850.0
yarn add …
```

plasma-*: PopupProvider server rendering [HOTFIX]

---

packages/plasma-b2c/src/components/DatePicker/DatePicker.stories.tsx
packages/plasma-new-hope/src/components/DatePicker/DatePicker.template-doc.mdx
packages/plasma-new-hope/src/components/DatePicker/DatePickerBase.types.ts
packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
packages/plasma-new-hope/src/components/DatePicker/hooks/useDatePicker.ts
packages/plasma-new-hope/src/components/DatePicker/utils/dateHelper.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/DatePicker/DatePicker.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/DatePicker/DatePicker.stories.tsx
packages/plasma-new-hope/src/utils/datejs.ts
packages/plasma-web/src/components/DatePicker/DatePicker.stories.tsx
packages/sdds-cs/src/components/DatePicker/DatePicker.stories.tsx
packages/sdds-dfa/src/components/DatePicker/DatePicker.stories.tsx
packages/sdds-serv/src/components/DatePicker/DatePicker.stories.tsx
website/plasma-b2c-docs/docs/components/DatePicker.mdx
website/plasma-web-docs/docs/components/DatePicker.mdx
website/sdds-cs-docs/docs/components/DatePicker.mdx
website/sdds-dfa-docs/docs/components/DatePicker.mdx
website/sdds-serv-docs/docs/components/DatePicker.mdx

- добавлена поддержка русского и английского языка
- добавлено форматирование даты 
- добавлен параметр `lang` с параметрами `ru` и `en`
- обновлен Storybook и документация
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.142.0-canary.1404.10657398641.0
npm install @salutejs/plasma-b2c@1.384.0-canary.1404.10657398641.0
npm install @salutejs/plasma-new-hope@0.136.0-canary.1404.10657398641.0
npm install @salutejs/plasma-web@1.386.0-canary.1404.10657398641.0
npm install @salutejs/sdds-cs@0.114.0-canary.1404.10657398641.0
npm install @salutejs/sdds-dfa@0.112.0-canary.1404.10657398641.0
npm install @salutejs/sdds-serv@0.113.0-canary.1404.10657398641.0
yarn add …
```

plasma-(*): Add format and lang in Datepicker

---

packages/plasma-new-hope/src/components/Popup/PopupContext.tsx

- удалено обращение к `document` на сервере
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.144.1-canary.1411.10666649424.0
npm install @salutejs/plasma-b2c@1.386.1-canary.1411.10666649424.0
npm install @salutejs/plasma-new-hope@0.137.1-canary.1411.10666649424.0
npm install @salutejs/plasma-web@1.388.1-canary.1411.10666649424.0
npm install @salutejs/sdds-cs@0.116.1-canary.1411.10666649424.0
npm install @salutejs/sdds-dfa@0.114.1-canary.1411.10666649424.0
npm install @salutejs/sdds-serv@0.115.1-canary.1411.10666649424.0
yarn add @salutejs/plasma-asdk@0.144.1-canary.1411.10666649424.0
yarn add @salutejs/plasma-b2c@1.386.1-canary.1411.10666649424.0
yarn add …
```

plasma-*: PopupProvider server rendering

---

packages/plasma-new-hope/src/components/Grid/Grid.tsx
packages/sdds-cs/src/components/Grid/Grid.config.tsx
packages/sdds-dfa/src/components/Grid/Grid.config.tsx
packages/sdds-finportal/src/components/Grid/Grid.config.tsx
packages/sdds-serv/src/components/Grid/Grid.config.tsx

- исправили `view` по-умолчанию для `sdds` вертикалей 
**Before:**
**After:**
Ранее использовалось значение `legacy` которое не предусмотрено для `sdds` вертикалей 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.150.1-canary.1431.10831152564.0
npm install @salutejs/plasma-b2c@1.392.1-canary.1431.10831152564.0
npm install @salutejs/plasma-new-hope@0.143.1-canary.1431.10831152564.0
npm install @salutejs/plasma-web@1.394.1-canary.1431.10831152564.0
npm install @salutejs/sdds-cs@0.122.1-canary.1431.10831152564.0
npm install @salutejs/sdds-dfa@0.120.1-canary.1431.10831152564.0
npm install @salutejs/sdds-finportal@0.114.1-canary.1431.10831152564.0
npm install …
```

fix(sdds-*): Use correct default view for Grid

---

packages/plasma-new-hope/src/components/TextField/TextField.tsx

- ref добавлена в зависимости для определения отображения placeholder
Ref добавлена в зависимости для определения отображения placeholder. Была проблема с отображением placeholder, при установке его значения через ref.current.value
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.152.0-canary.1433.10848014265.0
npm install @salutejs/plasma-b2c@1.394.0-canary.1433.10848014265.0
npm install @salutejs/plasma-new-hope@0.145.0-canary.1433.10848014265.0
npm install @salutejs/plasma-web@1.396.0-canary.1433.10848014265.0
npm install @salutejs/sdds-cs@0.124.0-canary.1433.10848014265.0
npm install @salutejs/sdds-dfa@0.122.0-canary.1433.10848014265.0
npm install …
```

feat(plasma-new-hope): Add TextField ref to deps for placeholder

---

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx

- исправлен баг, когда прокидывалось изначальное значение значение в single combobox, но не отображалось;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.154.0-canary.1436.10882554984.0
npm install @salutejs/plasma-b2c@1.396.0-canary.1436.10882554984.0
npm install @salutejs/plasma-new-hope@0.146.0-canary.1436.10882554984.0
npm install @salutejs/plasma-web@1.398.0-canary.1436.10882554984.0
npm install @salutejs/sdds-cs@0.126.0-canary.1436.10882554984.0
npm install @salutejs/sdds-dfa@0.124.0-canary.1436.10882554984.0
npm install @salutejs/sdds-finportal@0.118.0-canary.1436.10882554984.0
npm install @salutejs/sdds-serv@0.125.0-canary.1436.10882554984.0
yarn …
```

plasma-*: Fixed issue with predefined value in single Combobox

---

packages/plasma-b2c/src/components/Dropdown/Dropdown.stories.tsx
packages/plasma-web/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-cs/src/components/Combobox/Combobox.stories.tsx
packages/sdds-dfa/src/components/Combobox/Combobox.stories.tsx
packages/sdds-finportal/src/components/Combobox/Combobox.stories.tsx
packages/sdds-serv/src/components/Combobox/Combobox.stories.tsx

- исправлен баг с некорректной работой св-ва `placement` в storybook в новой вкладке;
- убрана приписка `new` в названиях сторей для `combobox` в sdds-*;
Исправлен баг с некорректной работой св-ва `placement` в storybook при открытии новой вкладки.
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.402.1-canary.1455.11029890540.0
npm install @salutejs/plasma-web@1.404.1-canary.1455.11029890540.0
npm install @salutejs/sdds-cs@0.132.1-canary.1455.11029890540.0
npm install @salutejs/sdds-dfa@0.130.1-canary.1455.11029890540.0
npm install @salutejs/sdds-finportal@0.124.1-canary.1455.11029890540.0
npm install @salutejs/sdds-serv@0.131.1-canary.1455.11029890540.0 …
```

feat(plasma-web, b2c): Added mappings for placement prop in Dropdown

---

.github/workflows/notification-code-review-completed.yml
.github/workflows/publish-common.yml
lerna.json

- убрали из workflow публикации пакеты связанные с документацией  (ускорили на `~1 мин 30 сек`)
- выключили пакеты: `perftest-helpers`, `versionate-docs` (временно не нужны)
**Before:**
**After:**
- для workflow " Code review completed" расширил фильтр, чтобы считался APPROVED **только** от команды разработки

plasma-infra: Small improvements 

---

packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.styles.ts
packages/plasma-new-hope/src/components/Breadcrumbs/ui/BreadcrumbShorter/BreadcrumbShorter.styles.ts
packages/plasma-new-hope/src/components/ButtonBase/index.ts
packages/plasma-new-hope/src/components/Cell/Cell.styles.ts
packages/plasma-new-hope/src/components/Cell/ui/CellTextbox/CellTextbox.styles.ts
packages/plasma-new-hope/src/components/Cell/ui/CellTextboxLabel/CellTextboxLabel.styles.ts
packages/plasma-new-hope/src/components/Cell/ui/CellTextboxSubtitle/CellTextboxSubtitle.styles.ts
packages/plasma-new-hope/src/components/Cell/ui/CellTextboxTitle/CellTextboxTitle.styles.ts
packages/plasma-new-hope/src/components/Drawer/Drawer.styles.ts

Заменены импорты со `styled-components` на `linaria` в рамках пакета `plasma-new-hope`.
Заменены импорты со `styled-components` на `linaria` в рамках пакета `plasma-new-hope`.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.170.0-canary.1468.11177090450.0
npm install @salutejs/plasma-b2c@1.412.0-canary.1468.11177090450.0
npm install @salutejs/plasma-new-hope@0.161.0-canary.1468.11177090450.0
npm install @salutejs/plasma-web@1.414.0-canary.1468.11177090450.0
npm install @salutejs/sdds-cs@0.142.0-canary.1468.11177090450.0
npm install @salutejs/sdds-dfa@0.140.0-canary.1468.11177090450.0
npm install @salutejs/sdds-finportal@0.134.0-canary.1468.11177090450.0 …
```

feat(plasma-new-hope): Got rid of styled-components imports in new-hope

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-new-hope/src/components/Accordion/Accordion.types.ts
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.types.ts
packages/plasma-web/api/plasma-web.api.md
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-serv/api/sdds-serv.api.md

- свойство `view` помечено как `optional`
- свойство `view` для AccordionItem помечено как `deprecated`      
- свойство `title` для `AccordionItem` теперь `ReactNode` 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.170.1-canary.1467.11208747391.0
npm install @salutejs/plasma-b2c@1.412.1-canary.1467.11208747391.0
npm install @salutejs/plasma-new-hope@0.161.1-canary.1467.11208747391.0
npm install @salutejs/plasma-web@1.414.1-canary.1467.11208747391.0
npm install @salutejs/sdds-cs@0.142.1-canary.1467.11208747391.0
npm install @salutejs/sdds-dfa@0.140.1-canary.1467.11208747391.0
npm install @salutejs/sdds-finportal@0.134.1-canary.1467.11208747391.0
npm …
```

[PLASMA-3591]: Fix Accordion types 

---

packages/plasma-b2c/src/components/Drawer/Drawer.component-test.tsx
packages/plasma-b2c/src/components/ModalBase/ModalBase.stories.tsx
packages/plasma-b2c/src/components/Popover/Popover.component-test.tsx
packages/plasma-b2c/src/components/PopupBase/PopupBase.stories.tsx
packages/plasma-new-hope/src/components/Popup/Popup.styles.ts
packages/plasma-new-hope/src/components/Popup/Popup.tsx
packages/plasma-new-hope/src/components/Popup/Popup.types.ts
packages/plasma-new-hope/src/components/Popup/PopupContext.tsx
packages/plasma-new-hope/src/components/Popup/PopupRoot.tsx
packages/plasma-new-hope/src/components/Popup/hooks/usePopup.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Modal/Modal.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/Popup/Popup.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Modal/Modal.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Popup/Popup.stories.tsx
packages/plasma-web/src/components/Drawer/Drawer.component-test.tsx
packages/plasma-web/src/components/Modal/Modal.component-test.tsx
packages/plasma-web/src/components/ModalBase/ModalBase.component-test.tsx
packages/plasma-web/src/components/ModalBase/ModalBase.stories.tsx
packages/plasma-web/src/components/Notification/Notification.component-test.tsx
packages/plasma-web/src/components/Popover/Popover.component-test.tsx
packages/plasma-web/src/components/PopupBase/PopupBase.component-test.tsx
packages/plasma-web/src/components/PopupBase/PopupBase.stories.tsx
packages/sdds-cs/src/components/Modal/Modal.stories.tsx
packages/sdds-cs/src/components/Popup/Popup.stories.tsx
packages/sdds-dfa/src/components/Modal/Modal.stories.tsx
packages/sdds-dfa/src/components/Popup/Popup.stories.tsx
packages/sdds-finportal/src/components/Modal/Modal.stories.tsx
packages/sdds-finportal/src/components/Popup/Popup.stories.tsx
packages/sdds-serv/src/components/Modal/Modal.stories.tsx
packages/sdds-serv/src/components/Popup/Popup.stories.tsx

- добавлены storybook декораторы для `Popup` и `Notification` для правильного отображения: `Drawer, Modal, Notification, Popup`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.171.2-canary.1412.11251053962.0
npm install @salutejs/plasma-b2c@1.413.2-canary.1412.11251053962.0
npm install @salutejs/plasma-new-hope@0.162.2-canary.1412.11251053962.0
npm install @salutejs/plasma-web@1.415.2-canary.1412.11251053962.0
npm install @salutejs/sdds-cs@0.143.2-canary.1412.11251053962.0
npm install @salutejs/sdds-dfa@0.141.2-canary.1412.11251053962.0
npm install @salutejs/sdds-finportal@0.135.2-canary.1412.11251053962.0
npm install …
```

plasma-*: Fix popup mount logic

---

packages/sdds-cs/.storybook/decoratorThemes.tsx
packages/sdds-cs/src/components/Badge/Badge.config.ts
packages/sdds-cs/src/components/Button/Button.config.ts
packages/sdds-cs/src/components/Chip/Chip.config.tsx

- используется token `--text-accent` когда `view: secondary` 
- для `closeIconColor` используется token `--text-accent` когда `view: secondary` 
- изменены `padding{Right,Left}` на  `8px`
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.144.1-canary.1473.11275792009.0
yarn add @salutejs/sdds-cs@0.144.1-canary.1473.11275792009.0
```
</details>

[PLASMA-3611]: Правки конфигураций Button, Chip, Badge [SDDS-CS]

---

packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.styles.ts
packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.template-doc.mdx
packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.tsx
packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
packages/plasma-new-hope/src/components/Breadcrumbs/utils/index.tsx
website/plasma-b2c-docs/docs/components/Breadcrumbs.mdx
website/sdds-cs-docs/docs/components/Breadcrumbs.mdx
website/sdds-dfa-docs/docs/components/Breadcrumbs.mdx
website/sdds-serv-docs/docs/components/Breadcrumbs.mdx

* Добавлена поддержка обработчика `onClick` при клике на ссылку
* Поправлены union типы 
* Обновлена документация с указанием типов элементов
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.173.0-canary.1480.11325361501.0
npm install @salutejs/plasma-b2c@1.415.0-canary.1480.11325361501.0
npm install @salutejs/plasma-new-hope@0.164.0-canary.1480.11325361501.0
npm install @salutejs/plasma-web@1.417.0-canary.1480.11325361501.0
npm install @salutejs/sdds-cs@0.145.0-canary.1480.11325361501.0
npm install @salutejs/sdds-dfa@0.143.0-canary.1480.11325361501.0
npm install @salutejs/sdds-finportal@0.137.0-canary.1480.11325361501.0
npm install …
```

feat(plasma-new-hope, *-docs): Add onClick for item to `Breadcrumbs` component

---

packages/plasma-new-hope/src/components/Attach/Attach.template-doc.mdx
packages/plasma-new-hope/src/components/Attach/Attach.tsx
packages/plasma-new-hope/src/components/Attach/Attach.types.ts
website/plasma-b2c-docs/docs/components/Attach.mdx
website/plasma-web-docs/docs/components/Attach.mdx
website/sdds-cs-docs/docs/components/Attach.mdx
website/sdds-dfa-docs/docs/components/Attach.mdx
website/sdds-serv-docs/docs/components/Attach.mdx

- исправлен `onChange`, `id` и `name`
- добавлено свойство `onClear`
- в документацию добавлен пример с использованием компонента внутри формы
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.174.1-canary.1481.11343722626.0
npm install @salutejs/plasma-b2c@1.416.1-canary.1481.11343722626.0
npm install @salutejs/plasma-new-hope@0.165.1-canary.1481.11343722626.0
npm install @salutejs/plasma-web@1.418.1-canary.1481.11343722626.0
npm install @salutejs/sdds-cs@0.146.1-canary.1481.11343722626.0
npm install @salutejs/sdds-dfa@0.144.1-canary.1481.11343722626.0
npm install @salutejs/sdds-finportal@0.138.1-canary.1481.11343722626.0
npm install …
```

`plasma-new-hope`: fix Attach

---

packages/plasma-new-hope/src/components/TextArea/TextArea.tsx

- добавлена фокусировка по клику на дочерние элементы
По клику на helpers / icons будет появляться курсор на TextArea
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.175.1-canary.1444.11348071542.0
npm install @salutejs/plasma-b2c@1.417.1-canary.1444.11348071542.0
npm install @salutejs/plasma-new-hope@0.166.1-canary.1444.11348071542.0
npm install @salutejs/plasma-web@1.419.1-canary.1444.11348071542.0
npm install @salutejs/sdds-cs@0.147.1-canary.1444.11348071542.0
npm install @salutejs/sdds-dfa@0.145.1-canary.1444.11348071542.0
npm install @salutejs/sdds-finportal@0.139.1-canary.1444.11348071542.0
npm install …
```

plasma-*: Focus TextArea by click inside

---

packages/plasma-new-hope/.storybook/main.ts

Добавил displayName в сгенеренные классы в сторибуке new-hope
@vadim-kudr это то что ты хотел? 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.177.1-canary.1346.11361458839.0
npm install @salutejs/plasma-b2c@1.419.1-canary.1346.11361458839.0
npm install @salutejs/plasma-new-hope@0.168.1-canary.1346.11361458839.0
npm install @salutejs/plasma-web@1.421.1-canary.1346.11361458839.0
npm install @salutejs/sdds-cs@0.149.1-canary.1346.11361458839.0
npm install @salutejs/sdds-dfa@0.147.1-canary.1346.11361458839.0
npm install @salutejs/sdds-finportal@0.141.1-canary.1346.11361458839.0
npm install @salutejs/sdds-serv@0.148.1-canary.1346.11361458839.0
yarn add …
```

plasma-infra: improve dsplName for storybook

---

packages/plasma-b2c/src/components/Accordion/Accordion.stories.tsx
packages/plasma-new-hope/src/components/Accordion/Accordion.template-doc.mdx
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Accordion/Accordion.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Accordion/Accordion.stories.tsx
packages/plasma-web/src/components/Accordion/Accordion.stories.tsx
packages/sdds-cs/src/components/Accordion/Accordion.config.ts
packages/sdds-cs/src/components/Accordion/Accordion.stories.tsx
packages/sdds-dfa/src/components/Accordion/Accordion.config.ts
packages/sdds-dfa/src/components/Accordion/Accordion.stories.tsx
packages/sdds-finportal/src/components/Accordion/Accordion.config.ts
packages/sdds-finportal/src/components/Accordion/Accordion.stories.tsx
packages/sdds-serv/src/components/Accordion/Accordion.config.ts
packages/sdds-serv/src/components/Accordion/Accordion.stories.tsx
website/plasma-b2c-docs/docs/components/Accordion.mdx
website/plasma-web-docs/docs/components/Accordion.mdx
website/sdds-cs-docs/docs/components/Accordion.mdx
website/sdds-dfa-docs/docs/components/Accordion.mdx
website/sdds-serv-docs/docs/components/Accordion.mdx

- Исправлен параметр `contentRight`
- Исправлен отступы во всех поставках `sdds` в `AccordionItem`
- Добавлен новый параметр `opened`, для контроля состоянием вне компонента
- Добавлена возможность прокидывать `ref` в `AccordionItem`
- Добавлена возможность прокдывать кнопки в `contentRight`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.180.0-canary.1484.11400899769.0
npm install @salutejs/plasma-b2c@1.422.0-canary.1484.11400899769.0
npm install @salutejs/plasma-new-hope@0.171.0-canary.1484.11400899769.0
npm install @salutejs/plasma-web@1.424.0-canary.1484.11400899769.0
npm install @salutejs/sdds-cs@0.152.0-canary.1484.11400899769.0
npm install …
```

feat(*): Fix Accordion Right Content and Paddings

---

packages/sdds-cs/src/components/Breadcrumbs/Breadcrumbs.config.ts
packages/sdds-cs/src/components/DatePicker/DatePicker.config.ts
website/sdds-cs-docs/docs/components/DatePicker.mdx

Исправлены неправильные значения по умолчанию для компонентов 
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.153.1-canary.1496.11455162336.0
yarn add @salutejs/sdds-cs@0.153.1-canary.1496.11455162336.0
```
</details>

sdds-cs: Fix default value for prop size

---

packages/plasma-b2c/css/package.json
packages/plasma-new-hope/emotion/package.json
packages/plasma-new-hope/package.json
packages/plasma-new-hope/styled-components/package.json
packages/plasma-web/css/package.json

Для корректной работы tree shaking в наших пакетах сделали следующее.
Добавили свойство `sideEffects` в `plasma-new-hope`: 
- в root  используем `"sideEffects": ["*.css"]`
- для styled-components\emotion используем `"sideEffects": false`
Добавили свойство `sideEffects` в `plasma-{web, b2c}\css`: 
- используем `"sideEffects": ["*.css"]`
Данные собраны на примере: 
```tsx
import React from 'react';
import { TextField, Button, TextArea } from '@salutejs/plasma-web/css';
export function App() {
return (
<div style={{display: 'flex', flexDirection: 'column', gap: '2rem'}}>
<TextField placeholder="Plasma WEB CSS" size="l" />
<Button view="accent" text="Plasma WEB CSS"/>
</div>
);
}
``` 
**BEFORE:**
------
**AFTER:**
<details>
<summary>📦 Published PR as canary version: <code>Canary …

[PLASMA-3579]: Improved tree shaking

---

packages/plasma-new-hope/src/components/Calendar/ui/CalendarDays/CalendarDays.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarMonths/CalendarMonths.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarQuarters/CalendarQuarters.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarYears/CalendarYears.tsx
packages/plasma-new-hope/src/components/TextArea/TextArea.styles.ts
packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
packages/plasma-new-hope/src/components/TextField/TextField.styles.ts
packages/plasma-new-hope/src/components/TextField/TextField.tsx

- поправлено поведение hover для дней на календарной сетке
**Before**:
https://github.com/user-attachments/assets/992d2566-10a1-40ff-8d76-d3e2d8de4d13
**After**:
https://github.com/user-attachments/assets/8e0bf060-a103-46ba-aa4a-b5bc6bef632d
Поправлено поведение hover для дней на календарной сетке.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.182.2-canary.1498.11494484213.0
npm install @salutejs/plasma-b2c@1.424.2-canary.1498.11494484213.0
npm install @salutejs/plasma-new-hope@0.173.2-canary.1498.11494484213.0
npm install @salutejs/plasma-web@1.426.2-canary.1498.11494484213.0
npm install @salutejs/sdds-cs@0.154.2-canary.1498.11494484213.0
npm install …
```

fix(plasma-new-hope): Fix Calendar hover behaviour

---

packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.types.ts

- добавлена явная типизация placeholder для Single DatePicker
**Before**:
**After**:
Добавлена явная типизация placeholder для Single DatePicker.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.182.2-canary.1501.11495261464.0
npm install @salutejs/plasma-b2c@1.424.2-canary.1501.11495261464.0
npm install @salutejs/plasma-new-hope@0.173.2-canary.1501.11495261464.0
npm install @salutejs/plasma-web@1.426.2-canary.1501.11495261464.0
npm install @salutejs/sdds-cs@0.154.2-canary.1501.11495261464.0
npm install @salutejs/sdds-dfa@0.152.2-canary.1501.11495261464.0
npm install @salutejs/sdds-finportal@0.146.2-canary.1501.11495261464.0
npm install …
```

fix(plasma-new-hope): Fix DatePicker placeholder type

---

packages/plasma-new-hope/src/components/Drawer/Drawer.tsx

- исправлен импорт useFocusTrap внутри Drawer
**Before**:
https://github.com/user-attachments/assets/515ec287-9ecf-4914-9187-c5d5cc002b29
**After**:
https://github.com/user-attachments/assets/6728cf1a-415e-4034-a3e0-6243f56a74d2
При открытии модалки из drawer и фокусе на контент, происходит переполнение стека.
Проблема заключается в том, что useFocusTrap импортируется из plasma-core и из хуков в new-hope. Из-за этого происходит конфликт.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.182.4-canary.1508.11518994013.0
npm install @salutejs/plasma-b2c@1.424.4-canary.1508.11518994013.0
npm install @salutejs/plasma-new-hope@0.173.4-canary.1508.11518994013.0 …
```

fix(plasma-new-hope): Fix useFocusTrap import

---

packages/plasma-b2c/src/components/TextArea/TextArea.stories.tsx
packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/TextArea/TextArea.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/TextField/TextField.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/TextArea/TextArea.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/TextField/TextField.stories.tsx
packages/plasma-web/src/components/TextArea/TextArea.stories.tsx
packages/plasma-web/src/components/TextField/TextField.stories.tsx
packages/sdds-cs/src/components/TextArea/TextArea.stories.tsx
packages/sdds-cs/src/components/TextField/TextField.stories.tsx
packages/sdds-dfa/src/components/TextArea/TextArea.stories.tsx
packages/sdds-dfa/src/components/TextField/TextField.stories.tsx
packages/sdds-finportal/src/components/TextArea/TextArea.stories.tsx
packages/sdds-finportal/src/components/TextField/TextField.stories.tsx
packages/sdds-serv/src/components/TextArea/TextArea.stories.tsx
packages/sdds-serv/src/components/TextField/TextField.stories.tsx

- добавлен hasHint пропс в storybook для TextField/TextArea
Добавлен hasHint пропс в storybook для TextField/TextArea, для согласованности с дизайном.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.187.0-canary.1513.11580788581.0
npm install @salutejs/plasma-b2c@1.429.0-canary.1513.11580788581.0
npm install @salutejs/plasma-new-hope@0.178.0-canary.1513.11580788581.0
npm install @salutejs/plasma-web@1.431.0-canary.1513.11580788581.0
npm install @salutejs/sdds-cs@0.159.0-canary.1513.11580788581.0
npm install @salutejs/sdds-dfa@0.157.0-canary.1513.11580788581.0
npm install @salutejs/sdds-finportal@0.151.0-canary.1513.11580788581.0
npm install …
```

feat(plasma-*,sdds-*): Refactor TextField/TextArea storybook hint args

---

packages/plasma-new-hope/src/components/Popup/Popup.tsx
packages/plasma-new-hope/src/components/Popup/PopupContext.tsx
packages/plasma-new-hope/src/components/Portal/Portal.tsx

- добавлено больше проверок canUseDom
**After**:
Билд Next начал опять падать с ошибками о неверном обращении к DOM после рефактора архитектуры Popup.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.187.1-canary.1515.11581730946.0
npm install @salutejs/plasma-b2c@1.429.1-canary.1515.11581730946.0
npm install @salutejs/plasma-new-hope@0.178.1-canary.1515.11581730946.0
npm install @salutejs/plasma-web@1.431.1-canary.1515.11581730946.0
npm install @salutejs/sdds-cs@0.159.1-canary.1515.11581730946.0
npm install @salutejs/sdds-dfa@0.157.1-canary.1515.11581730946.0
npm install @salutejs/sdds-finportal@0.151.1-canary.1515.11581730946.0
npm install …
```

fix(plasma-new-hope): Add more canUseDOM checks to Popup

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
packages/plasma-new-hope/src/components/Range/Range.tsx
packages/plasma-new-hope/src/components/Range/Range.types.ts
packages/plasma-web/api/plasma-web.api.md
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-serv/api/sdds-serv.api.md

- добавлена возможность передать autoComplete в Range/DatePickerRange
Добавлена возможность передать autoComplete в Range/DatePickerRange.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.194.0-canary.1530.11700796066.0
npm install @salutejs/plasma-b2c@1.436.0-canary.1530.11700796066.0
npm install @salutejs/plasma-new-hope@0.184.0-canary.1530.11700796066.0
npm install @salutejs/plasma-web@1.438.0-canary.1530.11700796066.0
npm install @salutejs/sdds-cs@0.166.0-canary.1530.11700796066.0
npm install @salutejs/sdds-dfa@0.164.0-canary.1530.11700796066.0
npm install @salutejs/sdds-finportal@0.158.0-canary.1530.11700796066.0
npm install …
```

feat(plasma-new-hope): Add autoComplete prop to Range

---

packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDatePopover/RangeDatePopover.tsx

- добавлен пропс type для двойного DatePickerRange
Без этого пропса нельзя задать конечную сетку календаря для выбора даты.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.194.1-canary.1535.11702289511.0
npm install @salutejs/plasma-b2c@1.436.1-canary.1535.11702289511.0
npm install @salutejs/plasma-new-hope@0.184.1-canary.1535.11702289511.0
npm install @salutejs/plasma-web@1.438.1-canary.1535.11702289511.0
npm install @salutejs/sdds-cs@0.166.1-canary.1535.11702289511.0
npm install @salutejs/sdds-dfa@0.164.1-canary.1535.11702289511.0
npm install @salutejs/sdds-finportal@0.158.1-canary.1535.11702289511.0
npm install …
```

fix(plasma-new-hope): Fix DatePickerRange grid type prop

---

packages/plasma-b2c/src/components/Chip/Chip.component-test.tsx
packages/plasma-new-hope/src/components/Chip/Chip.tsx
packages/plasma-new-hope/src/components/Chip/Chip.types.ts
packages/plasma-web/src/components/Chip/Chip.component-test.tsx

- добавлено событие onClickClose по клику на крестик
- onClear помечено как deprecated
- написан тест на onClickClose
Появилась потребность разделить события клика по Chip и по крестику внутри Chip
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.195.0-canary.1536.11704107927.0
npm install @salutejs/plasma-b2c@1.437.0-canary.1536.11704107927.0
npm install @salutejs/plasma-new-hope@0.185.0-canary.1536.11704107927.0
npm install @salutejs/plasma-web@1.439.0-canary.1536.11704107927.0
npm install @salutejs/sdds-cs@0.167.0-canary.1536.11704107927.0
npm install @salutejs/sdds-dfa@0.165.0-canary.1536.11704107927.0
npm install …
```

feat(plasma-new-hope): Divide chip events

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Tabs/index.ts
packages/plasma-new-hope/src/components/Tabs/index.ts
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Tabs/index.ts
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/Tabs/index.ts
packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-dfa/src/components/Tabs/index.ts
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-finportal/src/components/Tabs/index.ts
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-insol/src/components/Tabs/index.ts
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/Tabs/index.ts

- `TabItemProps`, `TabsProps` экспортируются во все пакеты
`TabItemProps`, `TabsProps` экспортируются во все пакеты для поддержания обратной совместимости у пользователей, которые ранее использовали эти импорты. 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.197.1-canary.1545.11773810119.0
npm install @salutejs/plasma-b2c@1.439.1-canary.1545.11773810119.0
npm install @salutejs/plasma-new-hope@0.187.1-canary.1545.11773810119.0
npm install @salutejs/plasma-web@1.441.1-canary.1545.11773810119.0
npm install @salutejs/sdds-cs@0.170.1-canary.1545.11773810119.0
npm install @salutejs/sdds-dfa@0.167.1-canary.1545.11773810119.0
npm install …
```

`plasma-*, sdds-*`: `TabItemProps`, `TabsProps` exported

---

website/sdds-cs-docs/docs/components/Cell.mdx
website/sdds-cs-docs/docs/components/Chip.mdx
website/sdds-cs-docs/docs/components/Mask.mdx
website/sdds-cs-docs/docs/components/Toast.mdx

Изменена документация ( значения `size` ) для корректного отображения в документации в вертикали `sdds-cs`
- Изменена документация к компонентам `Mask`, `Toast`, `Cell`, `Chip`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.201.2-canary.1557.11803291365.0
npm install @salutejs/plasma-b2c@1.443.2-canary.1557.11803291365.0
npm install @salutejs/plasma-new-hope@0.191.2-canary.1557.11803291365.0
npm install @salutejs/plasma-web@1.445.2-canary.1557.11803291365.0
npm install @salutejs/sdds-cs@0.174.2-canary.1557.11803291365.0
npm install @salutejs/sdds-dfa@0.171.2-canary.1557.11803291365.0
npm install @salutejs/sdds-finportal@0.165.2-canary.1557.11803291365.0 …
```

fix(sdds-cs-docs): Edit docs components for correctly view

---

packages/sdds-finportal/.gitignore
packages/sdds-finportal/.storybook/main.ts
packages/sdds-finportal/package.json
packages/sdds-finportal/src/helpers/createComponentByConfig.ts
packages/sdds-finportal/src/helpers/hasComponentDraftConfig.ts

Нужно вносить изменения в конфигурации компонентов, но нельзя чтобы они 
- протекали в текущие реализации
- были доступны **только** в storybook для проверки
Создаем дубликат конфигурации компонент, например для компонента - `Badge.config.draft.ts`. 
ИМХО c таким подходом 
- все изменения изолированы 
- находятся рядом с родными компонентами
- малый шанс сделать ошибку и не внести изменения в draft когда меняется основной конфиг            
На уровне сборки storybook в файле `main.ts` объявляем флаг `IS_DRAFT`:
```ts
define: {
'import.meta.env.IS_DRAFT': process.env.IS_DRAFT || false,
},
```
и когда мы хотим собрать/посмотреть в storybook компонент с draft конфигурацией то вызываем `storybook:draft`
Под капотом команды лежит
```console
"IS_DRAFT=true storybook dev -p ${PORT:-7007} -c …
```

[PLASMA-3849]: Работа с draft конфигурациями компонентов в `finportal-draft` 

---

.github/workflows/documentation-deploy-pr.yml

Продолжение истории из #1524
Проверка этой логики - https://github.com/Yakutoc/plasma-dev-stage/actions/runs/11908665607
<details>
<br />
```bash
npm install @salutejs/sdds-finportal@0.168.2-canary.1575.11927224206.0
yarn add @salutejs/sdds-finportal@0.168.2-canary.1575.11927224206.0
```
</details>

plasma-infra: Handle build storybook draft component

---

packages/sdds-cs/src/components/TextArea/TextArea.config.tsx

- Изменен `view negative` для `textarea` в соответствии с макетом для вертикали `sdds-cs`
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.178.2-canary.1567.11960453951.0
yarn add @salutejs/sdds-cs@0.178.2-canary.1567.11960453951.0
```
</details>

fix(sdds-cs): edit view negative in textarea sdds-cs

---

packages/sdds-insol/scripts/copy-linaria-components.sh
packages/sdds-serv/scripts/copy-linaria-components.sh

- Добавлен `switch` в поставку `sdds-serv` для сборки `linaria`
Вариант до: https://codesandbox.io/p/sandbox/lwkjwy?file=%2Fsrc%2Findex.js
Вариант после: https://codesandbox.io/p/sandbox/plasma-sdds-serv-example-forked-s9drhh?file=%2Fpackage.json%3A13%2C1
<details>
<br />
```bash
npm install @salutejs/sdds-insol@0.170.0-canary.1583.11968748564.0
npm install @salutejs/sdds-serv@0.178.0-canary.1583.11968748564.0
yarn add @salutejs/sdds-insol@0.170.0-canary.1583.11968748564.0
yarn add @salutejs/sdds-serv@0.178.0-canary.1583.11968748564.0
```
</details>

feat(sdds-serv): Add switch to linaria build

---

packages/plasma-new-hope/src/components/Calendar/CalendarBase/CalendarBase.tsx
packages/plasma-new-hope/src/components/Calendar/CalendarDouble/CalendarDouble.tsx
packages/plasma-new-hope/src/components/Calendar/store/reducer.ts

- при отсутствии значения календарная сетка отображается с минимальной даты
**Before**:
**After**:
При отсутствии значения календарная сетка отображается с минимальной даты
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.208.0-canary.1572.11972038908.0
npm install @salutejs/plasma-b2c@1.450.0-canary.1572.11972038908.0
npm install @salutejs/plasma-new-hope@0.197.0-canary.1572.11972038908.0
npm install @salutejs/plasma-web@1.452.0-canary.1572.11972038908.0
npm install @salutejs/sdds-cs@0.181.0-canary.1572.11972038908.0
npm install @salutejs/sdds-dfa@0.178.0-canary.1572.11972038908.0
npm install @salutejs/sdds-finportal@0.172.0-canary.1572.11972038908.0
npm …
```

feat(plasma-new-hope): Add displaying date from min value in Calendar

---

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.styles.ts
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
packages/plasma-new-hope/src/components/Dropdown/Dropdown.styles.ts
packages/plasma-new-hope/src/components/Dropdown/Dropdown.types.ts
packages/plasma-new-hope/src/components/Select/Select.styles.ts
packages/plasma-new-hope/src/components/Select/Select.types.ts

- исправлен баг, возникающий когда проп `listHeight` был больше, чем актуальная высота списка, что приводило к пустым пробелам в этом же выпадающем списке.
Поправили `listHeight` в Select, Combobox, Dropdown, теперь высота списка обрезается по высоте этого списка, либо по listHeight в случаях, когда оно меньше чем высота списка.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.210.0-canary.1585.12012734025.0
npm install @salutejs/plasma-b2c@1.452.0-canary.1585.12012734025.0
npm install @salutejs/plasma-new-hope@0.199.0-canary.1585.12012734025.0
npm install @salutejs/plasma-web@1.454.0-canary.1585.12012734025.0
npm install …
```

feat(plasma-new-hope): listHeight prop stands for a css maxHeight now

---

packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.tsx
packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.types.ts
scaffold/template-docs/docs/form/Components.mdx
scaffold/template-docs/docs/form/NativeForm.mdx
scaffold/template-docs/docs/form/ReactHookForm.mdx
website/plasma-b2c-docs/docs/form/Components.mdx
website/plasma-b2c-docs/docs/form/NativeForm.mdx
website/plasma-b2c-docs/docs/form/ReactHookForm.mdx
website/plasma-web-docs/docs/form/Components.mdx
website/plasma-web-docs/docs/form/NativeForm.mdx
website/plasma-web-docs/docs/form/ReactHookForm.mdx
website/sdds-cs-docs/docs/form/Components.mdx
website/sdds-cs-docs/docs/form/NativeForm.mdx
website/sdds-cs-docs/docs/form/ReactHookForm.mdx
website/sdds-dfa-docs/docs/form/Components.mdx
website/sdds-dfa-docs/docs/form/NativeForm.mdx
website/sdds-dfa-docs/docs/form/ReactHookForm.mdx
website/sdds-insol-docs/docs/form/Components.mdx
website/sdds-insol-docs/docs/form/NativeForm.mdx
website/sdds-insol-docs/docs/form/ReactHookForm.mdx
website/sdds-serv-docs/docs/form/Components.mdx
website/sdds-serv-docs/docs/form/NativeForm.mdx
website/sdds-serv-docs/docs/form/ReactHookForm.mdx

- Добавлена поддержка `react-hook-form` для `autocomplite`
- Добавлена документация по использованию `autocomplite` с нативной формой и `react-hook-form`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.211.0-canary.1574.12018059654.0
npm install @salutejs/plasma-b2c@1.453.0-canary.1574.12018059654.0
npm install @salutejs/plasma-new-hope@0.200.0-canary.1574.12018059654.0
npm install @salutejs/plasma-web@1.455.0-canary.1574.12018059654.0
npm install @salutejs/sdds-cs@0.184.0-canary.1574.12018059654.0
npm install @salutejs/sdds-dfa@0.181.0-canary.1574.12018059654.0
npm install @salutejs/sdds-finportal@0.175.0-canary.1574.12018059654.0
npm install …
```

feat(new-hope): add react hook form support in autocomplite

---

packages/plasma-new-hope/src/components/TextArea/TextArea.tsx

- убран автоподскролл по фокусу
Убран автоподскролл по фокусу.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.208.2-canary.1590.12000699920.0
npm install @salutejs/plasma-b2c@1.450.2-canary.1590.12000699920.0
npm install @salutejs/plasma-new-hope@0.197.2-canary.1590.12000699920.0
npm install @salutejs/plasma-web@1.452.2-canary.1590.12000699920.0
npm install @salutejs/sdds-cs@0.181.2-canary.1590.12000699920.0
npm install @salutejs/sdds-dfa@0.178.2-canary.1590.12000699920.0
npm install @salutejs/sdds-finportal@0.172.2-canary.1590.12000699920.0
npm install @salutejs/sdds-insol@0.172.2-canary.1590.12000699920.0
npm install …
```

fix: TextArea auto scroll on focus

---

website/sdds-cs-docs/src/theme/Playground/index.tsx

Переопределено значение токена для `--background-primary` чтобы не было такого как на screenshots

docs(sdds-cs): Overwrite background-primary-token

---

packages/plasma-new-hope/src/components/Popup/ClientOnlyPortal.tsx
packages/plasma-new-hope/src/components/Popup/PopupContext.tsx

- добавлено небезопасное свойство `UNSAFE_SSR_ENABLED` в компонент `PopupProvider` для корректной гидрации компонента;
Пока решили рефакторинг попапов отложить, ограничились вводом нового временного свойства `UNSAFE_SSR_ENABLED` для тех, кто использует попапы в нексте. Также создано ишью: [1599](https://github.com/salute-developers/plasma/issues/1599)
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.218.1-canary.1596.12137404478.0
npm install @salutejs/plasma-b2c@1.460.1-canary.1596.12137404478.0
npm install @salutejs/plasma-new-hope@0.207.1-canary.1596.12137404478.0
npm install @salutejs/plasma-web@1.462.1-canary.1596.12137404478.0
npm install …
```

PLASMA-4067: Popup hydration issues [FIX]

---

packages/plasma-new-hope/src/components/Calendar/Calendar.tokens.ts
packages/plasma-new-hope/src/components/Calendar/store/reducer.ts
packages/plasma-new-hope/src/components/Calendar/ui/CalendarHeader/CalendarHeader.styles.ts
packages/plasma-new-hope/src/components/Calendar/ui/CalendarHeader/CalendarHeader.tsx
packages/plasma-new-hope/src/components/Calendar/utils/calendarGridHelper.ts

- добавлено ограничение на отрицательные года
В календаре нельзя листать до отрицательных значений годов.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.220.0-canary.1605.12158492445.0
npm install @salutejs/plasma-b2c@1.462.0-canary.1605.12158492445.0
npm install @salutejs/plasma-new-hope@0.209.0-canary.1605.12158492445.0
npm install @salutejs/plasma-web@1.464.0-canary.1605.12158492445.0
npm install @salutejs/sdds-cs@0.193.0-canary.1605.12158492445.0
npm install @salutejs/sdds-dfa@0.190.0-canary.1605.12158492445.0
npm install @salutejs/sdds-finportal@0.184.0-canary.1605.12158492445.0
npm install @salutejs/sdds-insol@0.185.0-canary.1605.12158492445.0
npm …
```

PLASMA-4010: проверка на отрицательные года в календаре

---

packages/plasma-b2c/src/components/Combobox/Combobox.component-test.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/hooks/useKeyboardNavigation.ts
packages/plasma-web/src/components/Combobox/Combobox.component-test.tsx

- исправлен баг, когда нажатие на `Tab` очищало набранный текст в `single` варианте;
- исправлен баг, когда нажатие на `Tab` очищало набранный текст в `single` варианте;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.220.2-canary.1614.12168455041.0
npm install @salutejs/plasma-b2c@1.462.2-canary.1614.12168455041.0
npm install @salutejs/plasma-new-hope@0.209.2-canary.1614.12168455041.0
npm install @salutejs/plasma-web@1.464.2-canary.1614.12168455041.0
npm install @salutejs/sdds-cs@0.193.2-canary.1614.12168455041.0
npm install @salutejs/sdds-dfa@0.190.2-canary.1614.12168455041.0
npm install @salutejs/sdds-finportal@0.184.2-canary.1614.12168455041.0
npm …
```

PLASMA-3996: fix keyboard interaction bug in Combobox

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.types.ts
packages/plasma-web/api/plasma-web.api.md
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-serv/api/sdds-serv.api.md

- исправлен import для типа `RequiredProps`
Возвращены RequiredProps типы для Autocomplete
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.218.1-canary.1608.12114378461.0
npm install @salutejs/plasma-b2c@1.460.1-canary.1608.12114378461.0
npm install @salutejs/plasma-new-hope@0.207.1-canary.1608.12114378461.0
npm install @salutejs/plasma-web@1.462.1-canary.1608.12114378461.0
npm install @salutejs/sdds-cs@0.191.1-canary.1608.12114378461.0
npm install @salutejs/sdds-dfa@0.188.1-canary.1608.12114378461.0
npm install @salutejs/sdds-finportal@0.182.1-canary.1608.12114378461.0
npm install @salutejs/sdds-insol@0.183.1-canary.1608.12114378461.0
npm install …
```

PLASMA-4081: Autocomplete RequiredProps types

---

packages/plasma-new-hope/src/components/Drawer/Drawer.styles.ts
packages/plasma-new-hope/src/components/Drawer/Drawer.tokens.ts
packages/plasma-new-hope/src/components/Drawer/Drawer.tsx
packages/plasma-new-hope/src/components/Panel/Panel.tokens.ts
packages/plasma-new-hope/src/components/Panel/ui/PanelHeader/PanelHeader.styles.ts
packages/plasma-new-hope/src/components/Panel/ui/PanelHeader/PanelHeader.tsx
packages/sdds-cs/src/components/DatePicker/DatePicker.stories.tsx
packages/sdds-cs/src/components/Drawer/Drawer.config.ts
packages/sdds-cs/src/components/Drawer/Drawer.stories.tsx

- добавлена возможность изменить цвет закрывающей иконки
- актуализированы примеры в storybook 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.222.1-canary.1598.12180956760.0
npm install @salutejs/plasma-b2c@1.464.1-canary.1598.12180956760.0
npm install @salutejs/plasma-new-hope@0.211.1-canary.1598.12180956760.0
npm install @salutejs/plasma-web@1.466.1-canary.1598.12180956760.0
npm install @salutejs/sdds-cs@0.195.1-canary.1598.12180956760.0
npm install @salutejs/sdds-dfa@0.192.1-canary.1598.12180956760.0
npm install @salutejs/sdds-finportal@0.186.1-canary.1598.12180956760.0
npm install @salutejs/sdds-insol@0.187.1-canary.1598.12180956760.0
npm install …
```

PLASMA-4000: Set tokens in drawer and datepicker

---

packages/plasma-b2c/src/components/Combobox/Combobox.component-test.tsx
packages/plasma-b2c/src/components/Dropdown/Dropdown.component-test.tsx
packages/plasma-b2c/src/components/Select/Select.component-test.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/Inner/ui/Item/Item.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/Inner/ui/Item/Item.types.ts
packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.tsx
packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.type.ts
packages/plasma-new-hope/src/components/Select/ui/Inner/ui/Item/Item.tsx
packages/plasma-new-hope/src/components/Select/ui/Inner/ui/Item/Item.types.ts
packages/plasma-web/src/components/Combobox/Combobox.component-test.tsx
packages/plasma-web/src/components/Dropdown/Dropdown.component-test.tsx
packages/plasma-web/src/components/Select/Select.component-test.tsx

- расширен тип у `item` для использования дата-атрибутов и классов в DOM.
У пользователей возникла необходимость пробрасывать дата-атрибуты и, возможно класснеймы, непосредственно в сам `item`. 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.223.1-canary.1620.12231156605.0
npm install @salutejs/plasma-b2c@1.465.1-canary.1620.12231156605.0
npm install @salutejs/plasma-new-hope@0.212.1-canary.1620.12231156605.0
npm install @salutejs/plasma-web@1.467.1-canary.1620.12231156605.0
npm install @salutejs/sdds-cs@0.196.1-canary.1620.12231156605.0
npm install @salutejs/sdds-dfa@0.193.1-canary.1620.12231156605.0
npm install …
```

PLASMA-4105: passing data-attrs into Item

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Combobox/Combobox.component-test.tsx
packages/plasma-b2c/src/components/Dropdown/Dropdown.component-test.tsx
packages/plasma-b2c/src/components/Select/Select.component-test.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/FloatingPopover.tsx
packages/plasma-new-hope/src/components/Dropdown/Dropdown.tsx
packages/plasma-new-hope/src/components/Dropdown/Dropdown.types.ts
packages/plasma-new-hope/src/components/Dropdown/FloatingPopover.tsx
packages/plasma-new-hope/src/components/Select/FloatingPopover.tsx
packages/plasma-new-hope/src/components/Select/Select.tsx
packages/plasma-new-hope/src/components/Select/Select.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Combobox/Combobox.stories.tsx
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Combobox/Combobox.component-test.tsx
packages/plasma-web/src/components/Dropdown/Dropdown.component-test.tsx
packages/plasma-web/src/components/Select/Select.component-test.tsx
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-serv/api/sdds-serv.api.md

- добавлено свойство `zIndex`;
По просьбам нуждающихся и облегчения работы со слоями мы вынесли управление слоями выпадающих меню наружу. 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.223.2-canary.1631.12232898742.0
npm install @salutejs/plasma-b2c@1.465.2-canary.1631.12232898742.0
npm install @salutejs/plasma-new-hope@0.212.2-canary.1631.12232898742.0
npm install @salutejs/plasma-web@1.467.2-canary.1631.12232898742.0
npm install @salutejs/sdds-cs@0.196.2-canary.1631.12232898742.0
npm install @salutejs/sdds-dfa@0.193.2-canary.1631.12232898742.0
npm install @salutejs/sdds-finportal@0.187.2-canary.1631.12232898742.0
npm install …
```

PLASMA-4108: add zIndex prop in Dropdown, Select, Combobox

---

packages/plasma-new-hope/src/components/Popover/Popover.styles.ts
packages/plasma-new-hope/src/components/Tooltip/Tooltip.template-doc.mdx
packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx
packages/plasma-new-hope/src/components/Tooltip/Tooltip.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Tooltip/Tooltip.stories.tsx
packages/plasma-web/src/components/Tooltip/Tooltip.component-test.tsx
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-serv/api/sdds-serv.api.md
website/plasma-b2c-docs/docs/components/Tooltip.mdx
website/plasma-web-docs/docs/components/Tooltip.mdx
website/sdds-cs-docs/docs/components/Tooltip.mdx
website/sdds-dfa-docs/docs/components/Tooltip.mdx
website/sdds-insol-docs/docs/components/Tooltip.mdx
website/sdds-serv-docs/docs/components/Tooltip.mdx

- добавлена возможность открывать по `hover`
Добавлено внутреннее состояния для тултипа: isOpen
Прокинуты свойства в Popover: trigger, closeOnEsc, closeOnOverlayClick. Так же, невидимый блок между target и контентом
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.227.0-canary.1625.12267028714.0
npm install @salutejs/plasma-b2c@1.469.0-canary.1625.12267028714.0
npm install @salutejs/plasma-new-hope@0.216.0-canary.1625.12267028714.0
npm install @salutejs/plasma-web@1.471.0-canary.1625.12267028714.0
npm install @salutejs/sdds-cs@0.200.0-canary.1625.12267028714.0
npm install @salutejs/sdds-dfa@0.197.0-canary.1625.12267028714.0
npm install …
```

PLASMA-3619: add 'hover' trigger to Tooltip

---

packages/plasma-b2c/src/components/Drawer/Drawer.component-test.tsx
packages/plasma-new-hope/src/components/Popup/Popup.tsx
packages/plasma-web/src/components/Drawer/Drawer.component-test.tsx
packages/plasma-web/src/components/PopupBase/PopupBase.component-test.tsx

- rest аргументы прокидываются на уровень `.popup-base-root` элемента 
Нужно пробрасывать data-аттрибуты на уровень ниже в Popup
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.228.0-canary.1636.12271985293.0
npm install @salutejs/plasma-b2c@1.470.0-canary.1636.12271985293.0
npm install @salutejs/plasma-new-hope@0.217.0-canary.1636.12271985293.0
npm install @salutejs/plasma-web@1.472.0-canary.1636.12271985293.0
npm install @salutejs/sdds-cs@0.201.0-canary.1636.12271985293.0
npm install @salutejs/sdds-dfa@0.198.0-canary.1636.12271985293.0
npm install @salutejs/sdds-finportal@0.192.0-canary.1636.12271985293.0
npm install …
```

PLASMA-4116: изменен уровень передачи rest в Popup

---

packages/plasma-new-hope/src/components/Counter/Counter.tsx

- изменили минимальное значение для Counter с 1 на 0
Изменили минимальное значение для Counter с 1 на 0
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.232.0-canary.1640.12314741362.0
npm install @salutejs/plasma-b2c@1.474.0-canary.1640.12314741362.0
npm install @salutejs/plasma-new-hope@0.221.0-canary.1640.12314741362.0
npm install @salutejs/plasma-web@1.476.0-canary.1640.12314741362.0
npm install @salutejs/sdds-cs@0.205.0-canary.1640.12314741362.0
npm install @salutejs/sdds-dfa@0.202.0-canary.1640.12314741362.0
npm install @salutejs/sdds-finportal@0.196.0-canary.1640.12314741362.0
npm install @salutejs/sdds-insol@0.197.0-canary.1640.12314741362.0
npm …
```

PLASMA-4119: change MIN_COUNT value for Counter

---

packages/themes/sdds-themes/src/css/sdds_cs.module.css
packages/themes/sdds-themes/src/css/sdds_cs__dark.css
packages/themes/sdds-themes/src/css/sdds_cs__light.css
packages/themes/sdds-themes/src/themes/sdds_cs__dark.ts
packages/themes/sdds-themes/src/themes/sdds_cs__light.ts

- обновлен токен line-height для text-s с 1.375rem на 1.25rem
Обновлен токен line-height для text-s с 1.375rem на 1.25rem
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.232.0-canary.1644.12316139970.0
npm install @salutejs/plasma-b2c@1.474.0-canary.1644.12316139970.0
npm install @salutejs/plasma-new-hope@0.221.0-canary.1644.12316139970.0
npm install @salutejs/plasma-web@1.476.0-canary.1644.12316139970.0
npm install @salutejs/sdds-cs@0.205.0-canary.1644.12316139970.0
npm install @salutejs/sdds-dfa@0.202.0-canary.1644.12316139970.0
npm install @salutejs/sdds-finportal@0.196.0-canary.1644.12316139970.0
npm install …
```

PLASMA-4123: update sdds-cs themes

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-new-hope/src/components/TextArea/TextArea.types.tsx
packages/plasma-web/api/plasma-web.api.md
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-serv/api/sdds-serv.api.md

- изменен тип rightHelper с string на ReactNode
Изменен тип rightHelper с string на ReactNode для TextArea
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.233.0-canary.1642.12348263740.0
npm install @salutejs/plasma-b2c@1.475.0-canary.1642.12348263740.0
npm install @salutejs/plasma-new-hope@0.222.0-canary.1642.12348263740.0
npm install @salutejs/plasma-web@1.477.0-canary.1642.12348263740.0
npm install @salutejs/sdds-cs@0.206.0-canary.1642.12348263740.0
npm install @salutejs/sdds-dfa@0.203.0-canary.1642.12348263740.0
npm install @salutejs/sdds-finportal@0.197.0-canary.1642.12348263740.0
npm install @salutejs/sdds-insol@0.198.0-canary.1642.12348263740.0
npm …
```

Plasma-4158: change rightHelper type for TextArea

---

packages/sdds-cs/src/components/Attach/Attach.config.ts
packages/sdds-cs/src/components/Autocomplete/Autocomplete.config.ts
packages/sdds-cs/src/components/Button/Button.config.ts
packages/sdds-cs/src/components/Combobox/Combobox.config.ts
packages/sdds-cs/src/components/DatePicker/DatePicker.config.ts
packages/sdds-cs/src/components/IconButton/IconButton.config.ts
packages/sdds-cs/src/components/Link/Link.config.tsx
packages/sdds-cs/src/components/Notification/Notification.config.ts
packages/sdds-cs/src/components/NumberInput/NumberInput.config.ts
packages/sdds-cs/src/components/Segment/SegmentItem.config.ts
packages/sdds-cs/src/components/Select/Select.config.ts
packages/sdds-cs/src/components/Tabs/horizontal/HorizontalTabItem.config.ts
packages/sdds-cs/src/components/Tabs/horizontal/HorizontalTabs.config.ts
packages/sdds-cs/src/components/Tabs/vertical/VerticalTabItem.config.ts
packages/sdds-cs/src/components/Tabs/vertical/VerticalTabs.config.ts
packages/sdds-cs/src/components/TextField/TextField.config.ts
packages/sdds-cs/src/components/Toast/Toast.config.ts

- изменено значение на `#1A9E32`
Изменен токен --text-accent-hover на hex #1A9E32
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.207.0-canary.1643.12352980035.0
yarn add @salutejs/sdds-cs@0.207.0-canary.1643.12352980035.0
```
</details>

PLASMA-4139: change accent hover from token to hex

---

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/SelectNative/SelectNative.tsx
packages/plasma-new-hope/src/components/Select/Select.tsx
packages/plasma-new-hope/src/components/Select/Select.types.ts
packages/plasma-new-hope/src/components/Select/ui/SelectNative/SelectNative.styles.ts
packages/plasma-new-hope/src/components/Select/ui/SelectNative/SelectNative.tsx
scaffold/template-docs/docs/form/Components.mdx
scaffold/template-docs/docs/form/NativeForm.mdx
scaffold/template-docs/docs/form/ReactHookForm.mdx
website/plasma-b2c-docs/docs/form/Components.mdx
website/plasma-b2c-docs/docs/form/NativeForm.mdx
website/plasma-b2c-docs/docs/form/ReactHookForm.mdx
website/plasma-web-docs/docs/form/Components.mdx
website/plasma-web-docs/docs/form/NativeForm.mdx
website/plasma-web-docs/docs/form/ReactHookForm.mdx
website/sdds-cs-docs/docs/form/Components.mdx
website/sdds-cs-docs/docs/form/NativeForm.mdx
website/sdds-cs-docs/docs/form/ReactHookForm.mdx
website/sdds-dfa-docs/docs/form/Components.mdx
website/sdds-dfa-docs/docs/form/NativeForm.mdx
website/sdds-dfa-docs/docs/form/ReactHookForm.mdx
website/sdds-insol-docs/docs/form/NativeForm.mdx
website/sdds-insol-docs/docs/form/ReactHookForm.mdx
website/sdds-serv-docs/docs/form/NativeForm.mdx
website/sdds-serv-docs/docs/form/ReactHookForm.mdx

- Добавлена поддержка `react-hook-form` для компонента `select`
- Обновлена документация 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.234.0-canary.1639.12362024619.0
npm install @salutejs/plasma-b2c@1.476.0-canary.1639.12362024619.0
npm install @salutejs/plasma-new-hope@0.223.0-canary.1639.12362024619.0
npm install @salutejs/plasma-web@1.478.0-canary.1639.12362024619.0
npm install @salutejs/sdds-cs@0.208.0-canary.1639.12362024619.0
npm install @salutejs/sdds-dfa@0.204.0-canary.1639.12362024619.0
npm install @salutejs/sdds-finportal@0.198.0-canary.1639.12362024619.0
npm install @salutejs/sdds-insol@0.199.0-canary.1639.12362024619.0
npm install …
```

Plasma 3734: Support React-hook-form select

---

packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/Notification/Notification.tsx
packages/sdds-dfa/src/components/Notification/Notification.tsx
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-finportal/src/components/Notification/Notification.tsx
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-insol/src/components/Notification/Notification.tsx
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/Notification/Notification.tsx

- Исправлен тип выходного компонента `notification`
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.214.1-canary.1664.12429823449.0
npm install @salutejs/sdds-dfa@0.208.1-canary.1664.12429823449.0
npm install @salutejs/sdds-finportal@0.202.1-canary.1664.12429823449.0
npm install @salutejs/sdds-insol@0.203.1-canary.1664.12429823449.0
npm install @salutejs/sdds-serv@0.210.1-canary.1664.12429823449.0
yarn add @salutejs/sdds-cs@0.214.1-canary.1664.12429823449.0
yarn add @salutejs/sdds-dfa@0.208.1-canary.1664.12429823449.0
yarn add @salutejs/sdds-finportal@0.202.1-canary.1664.12429823449.0
yarn add @salutejs/sdds-insol@0.203.1-canary.1664.12429823449.0
yarn add …
```

PLASMA-4169: cast types for notification

---

packages/plasma-b2c/src/components/TextArea/TextArea.stories.tsx
packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/TextArea/TextArea.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/TextArea/TextArea.stories.tsx
packages/plasma-web/src/components/TextArea/TextArea.stories.tsx
packages/plasma-web/src/components/TextField/TextField.stories.tsx
packages/sdds-cs/src/components/TextArea/TextArea.stories.tsx
packages/sdds-dfa/src/components/TextArea/TextArea.stories.tsx
packages/sdds-finportal/src/components/TextArea/TextArea.stories.tsx
packages/sdds-insol/src/components/TextArea/TextArea.stories.tsx
packages/sdds-serv/src/components/TextArea/TextArea.stories.tsx

- актуализированы примеры в storybook в соответствии с дизайном 
- исправлена работа `placeholder` при работе `react-hook-form` с defaultValues
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.240.0-canary.1649.12458108927.0
npm install @salutejs/plasma-b2c@1.482.0-canary.1649.12458108927.0
npm install @salutejs/plasma-giga@0.209.0-canary.1649.12458108927.0
npm install @salutejs/plasma-new-hope@0.229.0-canary.1649.12458108927.0
npm install @salutejs/plasma-web@1.484.0-canary.1649.12458108927.0
npm install @salutejs/sdds-cs@0.217.0-canary.1649.12458108927.0
npm install @salutejs/sdds-dfa@0.211.0-canary.1649.12458108927.0
npm install …
```

PLASMA-4145: edit storybook textarea

---

packages/plasma-new-hope/package.json
packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.tsx
packages/plasma-new-hope/src/components/Breadcrumbs/utils/getShortItems.tsx
packages/plasma-new-hope/src/components/Breadcrumbs/utils/index.ts
packages/plasma-new-hope/src/components/Calendar/utils/getDateWithModification.ts
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.context.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/Inner/ui/Item/Item.tsx
packages/plasma-new-hope/src/components/Dropdown/Dropdown.context.tsx
packages/plasma-new-hope/src/components/Dropdown/Dropdown.tsx
packages/plasma-new-hope/src/components/Dropdown/ui/DropdownInner/DropdownInner.tsx
packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.tsx
packages/plasma-new-hope/src/components/Select/Select.context.tsx
packages/plasma-new-hope/src/components/Select/Select.tsx
packages/plasma-new-hope/src/components/Select/ui/Inner/Inner.tsx
packages/plasma-new-hope/src/components/Select/ui/Inner/ui/Item/Item.tsx
packages/plasma-new-hope/src/components/Slider/components/DoubleUncontrolled/DoubleUncontrolled.tsx
packages/plasma-new-hope/src/engines/common.tsx
packages/plasma-new-hope/src/engines/emotion.tsx
packages/plasma-new-hope/src/engines/linaria.tsx
packages/plasma-new-hope/src/engines/styled-components.tsx
packages/plasma-new-hope/src/engines/utils.ts
packages/sdds-cs/emotion/package.json
packages/sdds-cs/package.json
packages/sdds-serv/emotion/package.json
packages/sdds-serv/package.json
packages/sdds-serv/scripts/copy-linaria-components.sh
packages/sdds-serv/styled-components/package.json
packages/sdds-serv/tsconfig.json

- исправлены циклические зависимости
- добавлен объект `exports` в `package.json` для исправления ошибки vitest ([vitest issue](https://github.com/vitest-dev/vitest/discussions/4233))
- fix error in path of  d.ts file generation in `copy-linaria.sh` script;
- add `exports` object in package json for vitest ([vitest issue](https://github.com/vitest-dev/vitest/discussions/4233))
By default components are exported built with linaria. So they use plain css. In order to fix build, there is need to use two more rollup plugins:
- for css import (example: [rollup-plugin-import-css](https://www.npmjs.com/package/rollup-plugin-import-css))
- for json files resolve (example: [@rollup/plugin-json](https://www.npmjs.com/package/@rollup/plugin-json))
<details>
<summary>📦 Published PR as canary version: …

infra(sdds-serv): fix typings path

---

packages/plasma-b2c/src/components/Popover/Popover.component-test.tsx
packages/plasma-new-hope/src/components/Popover/Popover.styles.ts
packages/plasma-new-hope/src/components/Popover/Popover.template-doc.mdx
packages/plasma-new-hope/src/components/Popover/Popover.tokens.ts
packages/plasma-new-hope/src/components/Popover/Popover.tsx
packages/plasma-new-hope/src/components/Popover/Popover.types.ts
packages/plasma-new-hope/src/components/Portal/Portal.tsx
packages/plasma-new-hope/src/components/Portal/Portal.types.ts
packages/plasma-web/src/components/Popover/Popover.component-test.tsx
website/plasma-b2c-docs/docs/components/Popover.mdx
website/plasma-web-docs/docs/components/Popover.mdx
website/sdds-cs-docs/docs/components/Popover.mdx
website/sdds-dfa-docs/docs/components/Popover.mdx
website/sdds-insol-docs/docs/components/Popover.mdx
website/sdds-serv-docs/docs/components/Popover.mdx

- в target можно передать ref на элемент, рядом с которым произойдет открытие
Появилась необходимость задавать ref в target, для динамического изменения элемента, рядом с которым произойдет открытие
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.242.0-canary.1647.12467637991.0
npm install @salutejs/plasma-b2c@1.484.0-canary.1647.12467637991.0
npm install @salutejs/plasma-giga@0.211.0-canary.1647.12467637991.0
npm install @salutejs/plasma-new-hope@0.231.0-canary.1647.12467637991.0
npm install @salutejs/plasma-web@1.486.0-canary.1647.12467637991.0
npm install @salutejs/sdds-cs@0.219.0-canary.1647.12467637991.0
npm install …
```

PLASMA-4102: expand target prop to ref in Popover

---

packages/plasma-b2c/src/components/Dropdown/Dropdown.stories.tsx
packages/plasma-giga/src/components/Dropdown/Dropdown.stories.tsx
packages/plasma-new-hope/src/components/Dropdown/Dropdown.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropdown/Dropdown.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Dropdown/Dropdown.stories.tsx
packages/plasma-web/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-cs/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-dfa/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-finportal/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-insol/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-serv/src/components/Dropdown/Dropdown.stories.tsx

- Свойство `hasArrow` стало `depricated`
- Изменен `storybook` для корректного отображения всех свойств
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.242.1-canary.1669.12470399037.0
npm install @salutejs/plasma-b2c@1.484.1-canary.1669.12470399037.0
npm install @salutejs/plasma-giga@0.211.1-canary.1669.12470399037.0
npm install @salutejs/plasma-new-hope@0.231.1-canary.1669.12470399037.0
npm install @salutejs/plasma-web@1.486.1-canary.1669.12470399037.0
npm install @salutejs/sdds-cs@0.219.1-canary.1669.12470399037.0
npm install @salutejs/sdds-dfa@0.213.1-canary.1669.12470399037.0
npm install @salutejs/sdds-finportal@0.207.1-canary.1669.12470399037.0
npm …
```

PLASMA-3648: Edit storybook dropwdown

---

packages/plasma-b2c/src/components/TextArea/TextArea.component-test.tsx
packages/plasma-b2c/src/components/TextField/TextField.component-test.tsx
packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
packages/plasma-new-hope/src/components/TextField/TextField.tsx
packages/plasma-web/src/components/TextArea/TextArea.component-test.tsx
packages/plasma-web/src/components/TextField/TextField.component-test.tsx

- свойства required попадает в `DOM` на соотвествующие элементы
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.241.0-canary.1670.12462995068.0
npm install @salutejs/plasma-b2c@1.483.0-canary.1670.12462995068.0
npm install @salutejs/plasma-giga@0.210.0-canary.1670.12462995068.0
npm install @salutejs/plasma-new-hope@0.230.0-canary.1670.12462995068.0
npm install @salutejs/plasma-web@1.485.0-canary.1670.12462995068.0
npm install @salutejs/sdds-cs@0.218.0-canary.1670.12462995068.0
npm install @salutejs/sdds-dfa@0.212.0-canary.1670.12462995068.0
npm install @salutejs/sdds-finportal@0.206.0-canary.1670.12462995068.0
npm install …
```

PLASMA-4191: set required prop to dom attribute in TextArea & TextField

---

packages/plasma-b2c/src/components/Select/Select.component-test.tsx
packages/plasma-new-hope/src/components/Select/Select.tsx
packages/plasma-new-hope/src/components/Select/ui/Target/Target.tsx
packages/plasma-new-hope/src/components/Select/ui/Target/Target.types.ts
packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.tsx
packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.types.ts
packages/plasma-web/src/components/Select/Select.component-test.tsx

- закрытие выпадающего списка теперь возможно по повторному нажатию на таргет;
Привели поведение открытия/закрытия к надлежащему виду.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.246.0-canary.1676.12492303809.0
npm install @salutejs/plasma-b2c@1.488.0-canary.1676.12492303809.0
npm install @salutejs/plasma-giga@0.215.0-canary.1676.12492303809.0
npm install @salutejs/plasma-new-hope@0.235.0-canary.1676.12492303809.0
npm install @salutejs/plasma-web@1.490.0-canary.1676.12492303809.0
npm install @salutejs/sdds-cs@0.223.0-canary.1676.12492303809.0
npm install @salutejs/sdds-dfa@0.217.0-canary.1676.12492303809.0
npm install …
```

PLASMA-4175: Select behaviour improvement

---

packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-dfa/src/index.ts

- добавлен экспорт компонента из пакета
Skeleten не был в корне index.ts в экспорте компонентов
<details>
<br />
```bash
npm install @salutejs/sdds-dfa@0.219.0-canary.1684.12503636856.0
yarn add @salutejs/sdds-dfa@0.219.0-canary.1684.12503636856.0
```
</details>

PLASMA-4213: add Skeleton export

---

packages/plasma-new-hope/package.json
packages/sdds-cs/package.json
packages/sdds-serv/package.json

Отказались от указания путей через свойство exports    
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.249.1-canary.1689.12525929253.0
npm install @salutejs/plasma-b2c@1.491.1-canary.1689.12525929253.0
npm install @salutejs/plasma-giga@0.218.1-canary.1689.12525929253.0
npm install @salutejs/plasma-hope@1.328.1-canary.1689.12525929253.0
npm install @salutejs/plasma-new-hope@0.237.1-canary.1689.12525929253.0
npm install @salutejs/plasma-web@1.493.1-canary.1689.12525929253.0
npm install @salutejs/sdds-cs@0.226.1-canary.1689.12525929253.0
npm install @salutejs/sdds-dfa@0.221.1-canary.1689.12525929253.0
npm install …
```

hotfix: reverting exports prop from package.json due to ts overcomplexity

---

packages/plasma-new-hope/package.json
packages/sdds-cs/package.json
packages/sdds-serv/package.json

Дубликат #1689 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.252.1-canary.1704.12786192228.0
npm install @salutejs/plasma-b2c@1.494.1-canary.1704.12786192228.0
npm install @salutejs/plasma-giga@0.221.1-canary.1704.12786192228.0
npm install @salutejs/plasma-new-hope@0.240.1-canary.1704.12786192228.0
npm install @salutejs/plasma-web@1.496.1-canary.1704.12786192228.0
npm install @salutejs/sdds-cs@0.229.1-canary.1704.12786192228.0
npm install @salutejs/sdds-dfa@0.224.1-canary.1704.12786192228.0
npm install @salutejs/sdds-finportal@0.217.1-canary.1704.12786192228.0
npm install @salutejs/sdds-insol@0.218.1-canary.1704.12786192228.0
npm install …
```

hotfix: reverting exports prop from package.json due to ts overcomplexity [DEV]

---

packages/plasma-new-hope/src/components/Dropdown/Dropdown.tokens.ts
packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.styles.ts
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/Dropdown/Dropdown.config.ts
packages/sdds-cs/src/components/Dropdown/Dropdown.stories.tsx

- добавлен токен `itemMargin`
- добавлен токен `disclosureIconColor`
- в конфигурационных файлах и `storybook` оставлен только размер `s`
- значения токенов приведены к макету
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.255.1-canary.1705.12885562854.0
npm install @salutejs/plasma-b2c@1.497.1-canary.1705.12885562854.0
npm install @salutejs/plasma-giga@0.224.1-canary.1705.12885562854.0
npm install @salutejs/plasma-new-hope@0.243.1-canary.1705.12885562854.0
npm install @salutejs/plasma-web@1.499.1-canary.1705.12885562854.0
npm install @salutejs/sdds-cs@0.232.1-canary.1705.12885562854.0
npm install @salutejs/sdds-dfa@0.227.1-canary.1705.12885562854.0
npm …
```

PLASMA-4257: fix `Dropdown` tokens and sizes in `sdds-cs`

---

website/plasma-b2c-docs/docs/components/Notification.mdx
website/plasma-giga-docs/docs/components/Segment.mdx
website/plasma-giga-docs/docs/components/Slider.mdx

Заглушки от scafolld заменены на названия пакетов.

fix: Replace template placeholder to package name 

---

packages/plasma-new-hope/src/components/Tree/Tree.styles.ts
packages/plasma-new-hope/src/components/Tree/Tree.tsx

- перенесен внешний css из rc-tree в локальную сборку
исправлена сборка css
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.253.1-canary.1710.12871726145.0
npm install @salutejs/plasma-b2c@1.495.1-canary.1710.12871726145.0
npm install @salutejs/plasma-giga@0.222.1-canary.1710.12871726145.0
npm install @salutejs/plasma-new-hope@0.241.1-canary.1710.12871726145.0
npm install @salutejs/plasma-web@1.497.1-canary.1710.12871726145.0
npm install @salutejs/sdds-cs@0.230.1-canary.1710.12871726145.0
npm install @salutejs/sdds-dfa@0.225.1-canary.1710.12871726145.0
npm install @salutejs/sdds-finportal@0.218.1-canary.1710.12871726145.0
npm install …
```

PLASMA-4255: Move "rc-tree/assets/index.css" to Tree.styles.js

---

packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/Chip/Chip.config.tsx
packages/sdds-cs/src/components/Chip/Chip.stories.tsx
website/sdds-cs-docs/docs/components/Chip.mdx

- добавлен размер `xs`
Добавлен размер xs для Chip
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.236.0-canary.1713.12904792306.0
yarn add @salutejs/sdds-cs@0.236.0-canary.1713.12904792306.0
```
</details>

PLASMA-4288: add xs size for Chip

---

packages/plasma-new-hope/src/components/Dropdown/Dropdown.template-doc.mdx
packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.type.ts
website/plasma-b2c-docs/docs/components/Dropdown.mdx
website/plasma-giga-docs/docs/components/Dropdown.mdx
website/plasma-web-docs/docs/components/Dropdown.mdx
website/sdds-cs-docs/docs/components/Dropdown.mdx
website/sdds-dfa-docs/docs/components/Dropdown.mdx
website/sdds-insol-docs/docs/components/Dropdown.mdx
website/sdds-serv-docs/docs/components/Dropdown.mdx

- сделали свойство `placement` для вложенных меню опциональным
Свойство `placement` для вложенных дропдаунов сделано опциональным.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.260.0-canary.1722.12945590646.0
npm install @salutejs/plasma-b2c@1.502.0-canary.1722.12945590646.0
npm install @salutejs/plasma-giga@0.229.0-canary.1722.12945590646.0
npm install @salutejs/plasma-new-hope@0.248.0-canary.1722.12945590646.0
npm install @salutejs/plasma-web@1.504.0-canary.1722.12945590646.0
npm install @salutejs/sdds-cs@0.237.0-canary.1722.12945590646.0
npm install @salutejs/sdds-dfa@0.232.0-canary.1722.12945590646.0
npm install …
```

PLASMA-4356: make placement optional for DropdownItem [master]

---

packages/plasma-new-hope/src/components/Dropdown/Dropdown.template-doc.mdx
packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.type.ts
website/plasma-b2c-docs/docs/components/Dropdown.mdx
website/plasma-giga-docs/docs/components/Dropdown.mdx
website/plasma-web-docs/docs/components/Dropdown.mdx
website/sdds-cs-docs/docs/components/Dropdown.mdx
website/sdds-dfa-docs/docs/components/Dropdown.mdx
website/sdds-insol-docs/docs/components/Dropdown.mdx
website/sdds-serv-docs/docs/components/Dropdown.mdx

- свойство `placement` для вложенных дропдаунов сделано опциональным
Свойство `placement` для вложенных дропдаунов сделано опциональным.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.260.0-canary.1723.12945644036.0
npm install @salutejs/plasma-b2c@1.502.0-canary.1723.12945644036.0
npm install @salutejs/plasma-giga@0.229.0-canary.1723.12945644036.0
npm install @salutejs/plasma-new-hope@0.248.0-canary.1723.12945644036.0
npm install @salutejs/plasma-web@1.504.0-canary.1723.12945644036.0
npm install @salutejs/sdds-cs@0.237.0-canary.1723.12945644036.0
npm install @salutejs/sdds-dfa@0.232.0-canary.1723.12945644036.0
npm install …
```

PLASMA-4356: make placement optional for DropdownItem

---

packages/sdds-insol/src/components/Tabs/horizontal/HorizontalTabItem.config.ts
packages/sdds-insol/src/components/Tabs/vertical/VerticalTabItem.config.ts

- исправлен цвет `divider` у `TabItem`
<details>
<br />
```bash
npm install @salutejs/sdds-insol@0.226.2-canary.1721.12949402068.0
yarn add @salutejs/sdds-insol@0.226.2-canary.1721.12949402068.0
```
</details>

PLASMA-4294: Fix TabItem divider color in `sdds-insol`

---

packages/sdds-finportal/src/components/Divider/Divider.config.draft.ts
packages/sdds-finportal/src/components/Divider/Divider.stories.tsx

- добавлен черновик для `Divider` с новыми токенами для `view`
Токены заменены на `--outline-solid-primary`. Изменения добавлены в draft config для draft storybook.
<details>
<br />
```bash
npm install @salutejs/sdds-finportal@0.225.2-canary.1725.12985545035.0
yarn add @salutejs/sdds-finportal@0.225.2-canary.1725.12985545035.0
```
</details>

PLASMA-3841: fix Divider `view` tokens in `sdds-finportal`

---

packages/plasma-new-hope/src/components/Segment/tokens.ts
packages/plasma-new-hope/src/components/Segment/ui/SegmentItem/variations/_size/base.ts
packages/plasma-new-hope/src/components/Segment/ui/SegmentItem/variations/_view/base.ts
packages/sdds-insol/src/components/Segment/Segment.stories.tsx
packages/sdds-insol/src/components/Segment/SegmentGroup.config.ts
packages/sdds-insol/src/components/Segment/SegmentItem.config.ts

- актуализированы размеры шрифта в компоненте
- исправлен цвет иконки при наведении на выбранный сегмент
Актуализация компонента, согласно макетам
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.261.0-canary.1726.13029058317.0
npm install @salutejs/plasma-b2c@1.503.0-canary.1726.13029058317.0
npm install @salutejs/plasma-giga@0.230.0-canary.1726.13029058317.0
npm install @salutejs/plasma-new-hope@0.249.0-canary.1726.13029058317.0
npm install @salutejs/plasma-web@1.505.0-canary.1726.13029058317.0
npm install @salutejs/sdds-cs@0.238.0-canary.1726.13029058317.0
npm install @salutejs/sdds-dfa@0.233.0-canary.1726.13029058317.0
npm install …
```

PLASMA-4295: update Segment config

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Notification/Notification.tsx
packages/plasma-giga/api/plasma-giga.api.md
packages/plasma-giga/src/components/Notification/Notification.tsx
packages/plasma-new-hope/src/components/Notification/Notification.types.ts
packages/plasma-new-hope/src/components/Notification/NotificationsPortal.tsx
packages/plasma-new-hope/src/components/Notification/NotificationsProvider.tsx
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Notification/Notification.tsx
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/Notification/Notification.tsx
packages/sdds-dfa/src/components/Notification/Notification.tsx
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-finportal/src/components/Notification/Notification.tsx
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-insol/src/components/Notification/Notification.tsx
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/Notification/Notification.tsx

- добавлен UNSAFE_SSR_ENABLED по аналогии с PopupProvider
Добавлен UNSAFE_SSR_ENABLED по аналогии с PopupProvider, для решения проблемы с гидрацией.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.263.0-canary.1718.13051742234.0
npm install @salutejs/plasma-b2c@1.505.0-canary.1718.13051742234.0
npm install @salutejs/plasma-giga@0.232.0-canary.1718.13051742234.0
npm install @salutejs/plasma-new-hope@0.251.0-canary.1718.13051742234.0
npm install @salutejs/plasma-web@1.507.0-canary.1718.13051742234.0
npm install @salutejs/sdds-cs@0.240.0-canary.1718.13051742234.0
npm install @salutejs/sdds-dfa@0.235.0-canary.1718.13051742234.0
npm install …
```

PLASMA-4350: add UNSAFE_SSR_ENABLED to Notification

---

packages/plasma-new-hope/src/components/Toast/ToastController.tsx
packages/plasma-new-hope/src/components/Toast/ToastProvider/ToastProvider.tsx

Убрана очистка таймаута в ToastContorller 
Не работал таймайут при монтировании приложения через React.createRoot
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.263.1-canary.1712.13062616456.0
npm install @salutejs/plasma-b2c@1.505.1-canary.1712.13062616456.0
npm install @salutejs/plasma-giga@0.232.1-canary.1712.13062616456.0
npm install @salutejs/plasma-new-hope@0.251.1-canary.1712.13062616456.0
npm install @salutejs/plasma-web@1.507.1-canary.1712.13062616456.0
npm install @salutejs/sdds-cs@0.240.1-canary.1712.13062616456.0
npm install @salutejs/sdds-dfa@0.235.1-canary.1712.13062616456.0
npm install …
```

fix(*): Fix ToastController timeout clearing

---

packages/sdds-finportal/src/components/Badge/Badge.config.draft.ts

- исправлен `margin` у `contentLeft` и `contentRight`
<details>
<br />
```bash
npm install @salutejs/sdds-finportal@0.230.1-canary.1728.13071691884.0
yarn add @salutejs/sdds-finportal@0.230.1-canary.1728.13071691884.0
```
</details>

PLASMA-3964: fix Badge margin in `sdds-finportal`

---

packages/plasma-b2c/src/components/Autocomplete/Autocomplete.stories.tsx
packages/plasma-giga/src/components/Autocomplete/Autocomplete.stories.tsx
packages/plasma-new-hope/src/components/Portal/Portal.tsx
packages/plasma-new-hope/src/components/TextField/TextField.styles.ts
packages/plasma-web/src/components/Autocomplete/Autocomplete.stories.tsx
packages/sdds-dfa/src/components/Autocomplete/Autocomplete.stories.tsx
packages/sdds-finportal/src/components/Autocomplete/Autocomplete.stories.tsx

- исправлена ошибка гидрации в Next
- исправлена ширина компонента в storybook
Из-за проверки canUseDOM на сервере возвращался null, а в клиенте была разметка. Из-за этого возникала ошибка гидрации
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.266.0-canary.1730.13072913854.0
npm install @salutejs/plasma-b2c@1.508.0-canary.1730.13072913854.0
npm install @salutejs/plasma-giga@0.235.0-canary.1730.13072913854.0
npm install @salutejs/plasma-new-hope@0.254.0-canary.1730.13072913854.0
npm install @salutejs/plasma-web@1.510.0-canary.1730.13072913854.0
npm install @salutejs/sdds-cs@0.243.0-canary.1730.13072913854.0
npm install …
```

PLASMA-4392: fix Portal hydration error

---

packages/plasma-new-hope/src/components/NumberInput/NumberInput.tsx

- удалён лишний `console.log`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.267.1-canary.1742.13109369002.0
npm install @salutejs/plasma-b2c@1.509.1-canary.1742.13109369002.0
npm install @salutejs/plasma-giga@0.236.1-canary.1742.13109369002.0
npm install @salutejs/plasma-new-hope@0.255.1-canary.1742.13109369002.0
npm install @salutejs/plasma-web@1.511.1-canary.1742.13109369002.0
npm install @salutejs/sdds-cs@0.244.1-canary.1742.13109369002.0
npm install @salutejs/sdds-dfa@0.239.1-canary.1742.13109369002.0
npm install @salutejs/sdds-finportal@0.232.1-canary.1742.13109369002.0
npm install @salutejs/sdds-insol@0.233.1-canary.1742.13109369002.0
npm install …
```

fix(plasma-new-hope): redundant log removed from `NumberInput`

---

packages/plasma-new-hope/src/components/Accordion/Accordion.tokens.ts
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.styles.ts
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
packages/sdds-finportal/src/components/Accordion/Accordion.config.draft.ts
packages/sdds-finportal/src/components/Accordion/Accordion.stories.tsx

- добавлен `draft config`
- токены приведены в соответствие с макетом
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.267.2-canary.1733.13113759730.0
npm install @salutejs/plasma-b2c@1.509.2-canary.1733.13113759730.0
npm install @salutejs/plasma-giga@0.236.2-canary.1733.13113759730.0
npm install @salutejs/plasma-new-hope@0.255.2-canary.1733.13113759730.0
npm install @salutejs/plasma-web@1.511.2-canary.1733.13113759730.0
npm install @salutejs/sdds-cs@0.244.2-canary.1733.13113759730.0
npm install @salutejs/sdds-dfa@0.239.2-canary.1733.13113759730.0
npm install @salutejs/sdds-finportal@0.232.2-canary.1733.13113759730.0
npm install …
```

PLASMA-3710: fix `Accordion` tokens in `sdds-finportal`

---

packages/plasma-new-hope/src/components/Accordion/Accordion.tokens.ts
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.styles.ts
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
packages/sdds-insol/src/components/Accordion/Accordion.config.ts
packages/sdds-insol/src/components/Accordion/Accordion.stories.tsx

- исправлены отступы для Header размеров
- заголовок окрашивается в акцентный цвет у открытых элементов
Приведение конфига Accordion в соответствие с макетом
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.270.0-canary.1736.13152101875.0
npm install @salutejs/plasma-b2c@1.512.0-canary.1736.13152101875.0
npm install @salutejs/plasma-giga@0.239.0-canary.1736.13152101875.0
npm install @salutejs/plasma-new-hope@0.258.0-canary.1736.13152101875.0
npm install @salutejs/plasma-web@1.514.0-canary.1736.13152101875.0
npm install @salutejs/sdds-cs@0.247.0-canary.1736.13152101875.0
npm install @salutejs/sdds-dfa@0.242.0-canary.1736.13152101875.0
npm install …
```

PLASMA-4305: update Accordion config

---

packages/plasma-b2c/src/components/TextField/TextField.component-test.tsx
packages/plasma-new-hope/src/components/TextField/TextField.tsx
packages/plasma-web/src/components/TextField/TextField.component-test.tsx

- исправлен баг, связанный с пропсом required в режиме с чипами;
Оригинально проблема пришла из комопнента комбобокс, но т.к. комбобокс наследуется от текстфилда - то фикс сделан именно в нем. Суть в следующем: если включен режим с чипами (мультипл мод), и также если прокидывается пропс `required`, то форма не отправляется, т.к. инпут остается пустым (что понятно, чип выбран и инпут очищается). Мой фикс прост и лаконичен: мы просто убираем required из html-инпута, если выбран 1 и более чип. Для сингл режима все осталось по-прежнему.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.271.0-canary.1738.13153391749.0
npm install …
```

PLASMA-4355: Remove required prop in chip mode in Textfield

---

website/plasma-b2c-docs/docs/next.mdx
website/plasma-giga-docs/docs/next.mdx
website/plasma-web-docs/docs/next.mdx
website/sdds-cs-docs/docs/next.mdx
website/sdds-dfa-docs/docs/next.mdx
website/sdds-insol-docs/docs/next.mdx
website/sdds-serv-docs/docs/next.mdx

- добавлен раздела в документацию по работе с NextJs
Добавили раздел в доке по работе с некстом.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.271.0-canary.1740.13154795789.0
npm install @salutejs/plasma-b2c@1.513.0-canary.1740.13154795789.0
npm install @salutejs/plasma-giga@0.240.0-canary.1740.13154795789.0
npm install @salutejs/plasma-new-hope@0.259.0-canary.1740.13154795789.0
npm install @salutejs/plasma-web@1.515.0-canary.1740.13154795789.0
npm install @salutejs/sdds-cs@0.248.0-canary.1740.13154795789.0
npm install @salutejs/sdds-dfa@0.243.0-canary.1740.13154795789.0
npm install @salutejs/sdds-finportal@0.236.0-canary.1740.13154795789.0
npm install …
```

PLASMA-4293: add page guide for next.js

---

packages/plasma-new-hope/src/components/Calendar/hooks/useCalendarDateChange.ts
packages/plasma-new-hope/src/components/Calendar/store/reducer.ts
packages/plasma-new-hope/src/components/Calendar/store/types.ts

- исправлен выбор месяца на двойном календаре
Поправлено поведение календарной сетки месяца. Когда происходит выбор месяца из второй половины двойного календаря, брался год из первой части календаря.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.273.0-canary.1756.13182478014.0
npm install @salutejs/plasma-b2c@1.515.0-canary.1756.13182478014.0
npm install @salutejs/plasma-giga@0.242.0-canary.1756.13182478014.0
npm install @salutejs/plasma-new-hope@0.261.0-canary.1756.13182478014.0
npm install @salutejs/plasma-web@1.517.0-canary.1756.13182478014.0
npm install @salutejs/sdds-cs@0.250.0-canary.1756.13182478014.0
npm install …
```

PLASMA-4415: add year forward to Month update

---

packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.styles.ts
packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx

- Изменен тег в AccrodionItem с `button` на `div`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.273.1-canary.1758.13229702930.0
npm install @salutejs/plasma-b2c@1.515.1-canary.1758.13229702930.0
npm install @salutejs/plasma-giga@0.242.1-canary.1758.13229702930.0
npm install @salutejs/plasma-new-hope@0.261.1-canary.1758.13229702930.0
npm install @salutejs/plasma-web@1.517.1-canary.1758.13229702930.0
npm install @salutejs/sdds-cs@0.250.1-canary.1758.13229702930.0
npm install @salutejs/sdds-dfa@0.245.1-canary.1758.13229702930.0
npm install @salutejs/sdds-finportal@0.238.1-canary.1758.13229702930.0
npm install …
```

PLASMA-4098: Accordion Header Tag

---

website/plasma-b2c-docs/docs/components/Portal.mdx
website/plasma-giga-docs/docs/components/Portal.mdx
website/plasma-web-docs/docs/components/Portal.mdx
website/sdds-insol-docs/docs/components/Portal.mdx
website/sdds-serv-docs/docs/components/Portal.mdx

Для компонента `Portal` убрали лишний `Badge` о том что только `styled-components`

PLASMA-4383: Delete unnecessary Badge info [DOCS]

---

packages/plasma-new-hope/package-lock.json
packages/plasma-new-hope/package.json
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/VirtualList/VirtualList.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/index.ts
website/plasma-b2c-docs/docs/components/Combobox.mdx
website/plasma-giga-docs/docs/components/Combobox.mdx
website/plasma-web-docs/docs/components/Combobox.mdx
website/sdds-cs-docs/docs/components/Combobox.mdx
website/sdds-dfa-docs/docs/components/Combobox.mdx
website/sdds-insol-docs/docs/components/Combobox.mdx
website/sdds-serv-docs/docs/components/Combobox.mdx

- добавлена опциональная виртуализация в выпадащий список;
Пропс `virtual` для виртуализации выпадающего списка.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.274.0-canary.1761.13279424878.0
npm install @salutejs/plasma-b2c@1.516.0-canary.1761.13279424878.0
npm install @salutejs/plasma-giga@0.243.0-canary.1761.13279424878.0
npm install @salutejs/plasma-new-hope@0.262.0-canary.1761.13279424878.0
npm install @salutejs/plasma-web@1.518.0-canary.1761.13279424878.0
npm install @salutejs/sdds-cs@0.251.0-canary.1761.13279424878.0
npm install @salutejs/sdds-dfa@0.246.0-canary.1761.13279424878.0
npm install …
```

PLASMA-4172: virtual prop in Combobox

---

packages/sdds-insol/src/components/Combobox/Combobox.config.ts
packages/sdds-insol/src/components/Select/Select.config.ts
packages/sdds-insol/src/components/TextField/TextField.config.ts

- исправлен размер иконки закрытия в чипах
Исправлен размер иконки закрытия в чипах
<details>
<br />
```bash
npm install @salutejs/sdds-insol@0.247.0-canary.1765.13373688080.0
yarn add @salutejs/sdds-insol@0.247.0-canary.1765.13373688080.0
```
</details>

PLAMSA-4394: update close-icon in embedded chips

---

packages/plasma-b2c/src/components/Combobox/Combobox.component-test.tsx
packages/plasma-b2c/src/components/Select/Select.component-test.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/Inner/ui/Item/Item.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/utils/updateDescendants.ts
packages/plasma-new-hope/src/components/Select/Select.tsx
packages/plasma-new-hope/src/components/Select/ui/Inner/ui/Item/Item.tsx
packages/plasma-new-hope/src/components/Select/utils/updateDescendants.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Combobox/Combobox.stories.tsx
packages/plasma-web/src/components/Combobox/Combobox.component-test.tsx
packages/plasma-web/src/components/Select/Select.component-test.tsx

- исправлен баг, связанный с возможностью выбирать `disabled` item через его родителя;
- исправлен баг, связанный с возможностью выбирать `disabled` item через его родителя;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.281.0-canary.1766.13384359206.0
npm install @salutejs/plasma-b2c@1.523.0-canary.1766.13384359206.0
npm install @salutejs/plasma-giga@0.250.0-canary.1766.13384359206.0
npm install @salutejs/plasma-new-hope@0.269.0-canary.1766.13384359206.0
npm install @salutejs/plasma-web@1.525.0-canary.1766.13384359206.0
npm install @salutejs/sdds-cs@0.258.0-canary.1766.13384359206.0
npm install @salutejs/sdds-dfa@0.253.0-canary.1766.13384359206.0
npm …
```

PLASMA-4312: исправить выбор disabled эл-ов при multiselect

---

packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-insol/src/components/Segment/Segment.stories.tsx
packages/sdds-insol/src/components/Segment/SegmentItem.config.ts

-  добавлен `view='accent'`
Добавлен `view='accent'`
<details>
<br />
```bash
npm install @salutejs/sdds-insol@0.242.0-canary.1774.13286891394.0
yarn add @salutejs/sdds-insol@0.242.0-canary.1774.13286891394.0
```
</details>

PLASMA-4484: add accent view for Segment

---

packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-insol/src/components/Segment/Segment.stories.tsx
packages/sdds-insol/src/components/Segment/SegmentGroup.config.ts
packages/sdds-insol/src/components/Segment/SegmentItem.config.ts

-  добавлен размер `XL`
Добавлен размер xl
<details>
<br />
```bash
npm install @salutejs/sdds-insol@0.251.0-canary.1773.13388619410.0
yarn add @salutejs/sdds-insol@0.251.0-canary.1773.13388619410.0
```
</details>

PLASMA-4482: add xl size for Segment

---

packages/plasma-new-hope/src/components/Calendar/CalendarBase/CalendarBase.tsx
packages/plasma-new-hope/src/components/Calendar/CalendarDouble/CalendarDouble.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarMonths/CalendarMonths.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarQuarters/CalendarQuarters.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarYears/CalendarYears.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/Calendar/Calendar.stories.tsx
packages/plasma-new-hope/src/examples/plasma_b2c/components/DatePicker/DatePicker.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Calendar/Calendar.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/DatePicker/DatePicker.stories.tsx

- исправлена логика отрисовки календарных сеток "месяц", "квартал", "год" для минимальной и максимальной дат
**Before**:
https://github.com/user-attachments/assets/18943dab-5a6d-4e0f-945b-2aef7c815b23
**After**:
https://github.com/user-attachments/assets/1725f4c3-3db7-469a-b0d6-c1f5e275623f
При отрисовке сеток использовалась точная минимальная и максимальная дата. Месяц имеет значения 01/{номер месяца}/{год}. Минимальная дата у которой день указан больше 01 приводила к тому, что на сетке месяцев, нужный месяц был в состоянии disabled. Аналогично и для сеток квартал/год.
Теперь в минимальной дате учитывается часть, соответствующая структуре даты. Например для минимальной даты 13.04.2024 в сетке месяцев будет учтен месяц и год. День будет установлен как 01, чтобы 04 месяц (апрель) можно …

PLASMA-4291: fix min/max Calendar logic for month, quarter, year

---

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts

- добавлено св-во `onChangeValue` для отслеживания изменений значения в строке поиска.
По просьбам консумеров добавлено `onChangeValue`.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.283.0-canary.1782.13387584790.0
npm install @salutejs/plasma-b2c@1.525.0-canary.1782.13387584790.0
npm install @salutejs/plasma-giga@0.252.0-canary.1782.13387584790.0
npm install @salutejs/plasma-new-hope@0.271.0-canary.1782.13387584790.0
npm install @salutejs/plasma-web@1.527.0-canary.1782.13387584790.0
npm install @salutejs/sdds-cs@0.260.0-canary.1782.13387584790.0
npm install @salutejs/sdds-dfa@0.255.0-canary.1782.13387584790.0
npm install …
```

PLASMA-4445: add onChangeValue prop in combobox

---

packages/plasma-new-hope/src/components/Popover/hooks/usePopoverOffset.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/DatePicker/DatePicker.stories.tsx

- исправлена зависимость useEffect в  usePopoverOffset
**Before**:
**After**:
Исправлена зависимость useEffect в  usePopoverOffset
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.288.0-canary.1788.13492486250.0
npm install @salutejs/plasma-b2c@1.530.0-canary.1788.13492486250.0
npm install @salutejs/plasma-giga@0.257.0-canary.1788.13492486250.0
npm install @salutejs/plasma-new-hope@0.276.0-canary.1788.13492486250.0
npm install @salutejs/plasma-web@1.532.0-canary.1788.13492486250.0
npm install @salutejs/sdds-cs@0.265.0-canary.1788.13492486250.0
npm install @salutejs/sdds-dfa@0.260.0-canary.1788.13492486250.0
npm install …
```

PLASMA: fix usePopoverOffset hook deps

---

packages/plasma-b2c/src/components/Autocomplete/Autocomplete.component-test.tsx
packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.styles.ts
packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.tsx
packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.types.ts
packages/plasma-new-hope/src/components/Autocomplete/FloatingPopover.tsx
packages/plasma-web/src/components/Autocomplete/Autocomplete.component-test.tsx

- переведен на **новую** архитектуру с использованием `@floating-ui`
Автокомплит переведен на новую архитектуру, по примеру комбобокса, селекта и дропдауна.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.292.0-canary.1794.13544543346.0
npm install @salutejs/plasma-b2c@1.534.0-canary.1794.13544543346.0
npm install @salutejs/plasma-giga@0.261.0-canary.1794.13544543346.0
npm install @salutejs/plasma-new-hope@0.279.0-canary.1794.13544543346.0
npm install @salutejs/plasma-web@1.536.0-canary.1794.13544543346.0
npm install @salutejs/sdds-cs@0.269.0-canary.1794.13544543346.0
npm install @salutejs/sdds-dfa@0.264.0-canary.1794.13544543346.0
npm install …
```

PLASMA-4517: new architecture in Autocomplete

---

packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/ViewContainer/ViewContainer.config.ts
website/sdds-cs-docs/docs/components/Tooltip.mdx

-  Добавлена view `onDark`
- Добавлена документация для компонента, описывающая возможность использования `ViewContainer`
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.272.0-canary.1804.13584347001.0
yarn add @salutejs/sdds-cs@0.272.0-canary.1804.13584347001.0
```
</details>

 PLASMA-4584:Add `onDark` view for `ViewContainer` component [sdds-cs]

---

packages/sdds-cs/src/components/Counter/Counter.config.ts

- изменен размер шрифта с `xxs` на `s`
Исправления согласно макетам
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.276.1-canary.1808.13645203147.0
yarn add @salutejs/sdds-cs@0.276.1-canary.1808.13645203147.0
```
</details>

PLASMA-4590: Counter change font 'xxs' to 's' [sdds-cs]

---

packages/plasma-ui/src/utils/deviceDetection.ts

- добавлена поддержка `StarOS` устройств
Нужно было поддержать линейку устройств со следующим `userAgent` 
```
Mozilla/5.0 (Linux; Android 14; SK63S Build/UP1A.231005.007.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.82 Mobile Safari/537.36 ASDK/24.10.2.2281 (Android) StarOS/1.98.20250121043554-b12386 (tv_cvte_aml_963_968_d4; TV) uiFamily=TV
Mozilla/5.0 (Linux; Android 14; SK63S Build/UP1A.231005.007.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.82 Mobile Safari/537.36 ASDK/24.10.2.2281 (Android) StarOS/1.98.20250121043554-b12446 (tv_cvte_aml_963_968_d4; TV) uiFamily=TV
```
<details>
<br />
```bash
npm …
```

PLASMA-4364: add case for StarOS TV for detectDevice method

---

packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.styles.ts
packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.tsx
packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.types.ts
packages/plasma-new-hope/src/components/Autocomplete/ui/VirtualList/VirtualList.tsx
packages/plasma-new-hope/src/components/Autocomplete/ui/index.ts
website/plasma-b2c-docs/docs/components/Autocomplete.mdx
website/plasma-giga-docs/docs/components/Autocomplete.mdx
website/plasma-web-docs/docs/components/Autocomplete.mdx
website/sdds-cs-docs/docs/components/Autocomplete.mdx
website/sdds-dfa-docs/docs/components/Autocomplete.mdx
website/sdds-insol-docs/docs/components/Autocomplete.mdx
website/sdds-serv-docs/docs/components/Autocomplete.mdx

- добавлена опциональная виртуализация в выпадающий список;
Пропс `virtual` для виртуализации выпадающего списка.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.301.0-canary.1817.13658365689.0
npm install @salutejs/plasma-b2c@1.543.0-canary.1817.13658365689.0
npm install @salutejs/plasma-giga@0.270.0-canary.1817.13658365689.0
npm install @salutejs/plasma-new-hope@0.287.0-canary.1817.13658365689.0
npm install @salutejs/plasma-web@1.545.0-canary.1817.13658365689.0
npm install @salutejs/sdds-cs@0.279.0-canary.1817.13658365689.0
npm install @salutejs/sdds-dfa@0.273.0-canary.1817.13658365689.0
npm install …
```

PLASMA-4518: virtual prop in Autocomplete

---

packages/plasma-new-hope/src/components/Calendar/CalendarBase/CalendarBase.tsx
packages/plasma-new-hope/src/components/Calendar/CalendarDouble/CalendarDouble.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarDays/CalendarDays.tsx
packages/plasma-new-hope/src/components/Calendar/ui/CalendarHeader/CalendarHeader.tsx
packages/plasma-new-hope/src/components/Calendar/utils/calendarGridHelper.ts
packages/plasma-new-hope/src/components/Calendar/utils/constants.ts

- добавлены переводы на `eng` для aria-label 
Раньше был зашит только русский, теперь при переключении locale текст будет на eng  
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.305.2-canary.1829.13784636905.0
npm install @salutejs/plasma-b2c@1.547.2-canary.1829.13784636905.0
npm install @salutejs/plasma-giga@0.274.2-canary.1829.13784636905.0
npm install @salutejs/plasma-new-hope@0.291.2-canary.1829.13784636905.0
npm install @salutejs/plasma-web@1.549.2-canary.1829.13784636905.0
npm install @salutejs/sdds-cs@0.283.2-canary.1829.13784636905.0
npm install @salutejs/sdds-dfa@0.277.2-canary.1829.13784636905.0
npm install …
```

PLASMA-4517: Add i18n for Calendar

---

packages/plasma-b2c/api/plasma-b2c.api.md
packages/plasma-b2c/src/components/Dropdown/Dropdown.stories.tsx
packages/plasma-giga/api/plasma-giga.api.md
packages/plasma-giga/src/components/Dropdown/Dropdown.stories.tsx
packages/plasma-new-hope/src/components/Dropdown/Dropdown.tsx
packages/plasma-new-hope/src/components/Dropdown/Dropdown.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropdown/Dropdown.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Dropdown/Dropdown.stories.tsx
packages/plasma-web/api/plasma-web.api.md
packages/plasma-web/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-cs/api/sdds-cs.api.md
packages/sdds-cs/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-dfa/api/sdds-dfa.api.md
packages/sdds-dfa/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-finportal/api/sdds-finportal.api.md
packages/sdds-finportal/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-insol/api/sdds-insol.api.md
packages/sdds-insol/src/components/Dropdown/Dropdown.stories.tsx
packages/sdds-serv/api/sdds-serv.api.md
packages/sdds-serv/src/components/Dropdown/Dropdown.stories.tsx

- добавлено свойство openByRightClick для открытия по правому клику
расширен функционал
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.288.0-canary.1791.13484791679.0
npm install @salutejs/plasma-b2c@1.530.0-canary.1791.13484791679.0
npm install @salutejs/plasma-giga@0.257.0-canary.1791.13484791679.0
npm install @salutejs/plasma-new-hope@0.276.0-canary.1791.13484791679.0
npm install @salutejs/plasma-web@1.532.0-canary.1791.13484791679.0
npm install @salutejs/sdds-cs@0.265.0-canary.1791.13484791679.0
npm install @salutejs/sdds-dfa@0.260.0-canary.1791.13484791679.0
npm install @salutejs/sdds-finportal@0.253.0-canary.1791.13484791679.0
npm install …
```

PLASMA-4491: open Dropdown by right click

---

packages/plasma-b2c/src/components/Switch/Switch.config.ts
packages/plasma-giga/src/components/Switch/Switch.config.ts
packages/plasma-new-hope/src/components/Switch/Switch.styles.ts
packages/plasma-new-hope/src/components/Switch/Switch.tokens.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Switch/Switch.config.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Switch/Switch.outline.config.ts
packages/plasma-new-hope/src/examples/plasma_web/components/Switch/Switch.config.ts
packages/plasma-new-hope/src/examples/plasma_web/components/Switch/Switch.outline.config.ts
packages/plasma-web/src/components/Switch/Switch.config.ts
packages/sdds-cs/src/components/Switch/Switch.config.ts
packages/sdds-dfa/src/components/Switch/Switch.config.ts
packages/sdds-finportal/src/components/Switch/Switch.config.ts
packages/sdds-insol/src/components/Switch/Switch.config.ts
packages/sdds-serv/src/components/Switch/Switch.config.ts

- Добавлен новый токен, для изменения кол-ва строк в `description`
- Изменены токены цвета при `off` состоянии
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.308.0-canary.1819.13844598368.0
npm install @salutejs/plasma-b2c@1.550.0-canary.1819.13844598368.0
npm install @salutejs/plasma-giga@0.277.0-canary.1819.13844598368.0
npm install @salutejs/plasma-new-hope@0.294.0-canary.1819.13844598368.0
npm install @salutejs/plasma-web@1.552.0-canary.1819.13844598368.0
npm install @salutejs/sdds-cs@0.286.0-canary.1819.13844598368.0
npm install @salutejs/sdds-dfa@0.280.0-canary.1819.13844598368.0
npm install …
```

PLASMA-4432: set switch off toggle color

---

packages/plasma-b2c/src/components/Notification/Notification.stories.tsx
packages/plasma-giga/src/components/Notification/Notification.stories.tsx
packages/plasma-new-hope/src/components/Notification/Notification.styles.ts
packages/plasma-new-hope/src/components/Notification/Notification.template-doc.mdx
packages/plasma-new-hope/src/components/Notification/Notification.tokens.ts
packages/plasma-new-hope/src/components/Notification/Notification.types.ts
packages/plasma-new-hope/src/components/Notification/NotificationsPortal.tsx
packages/plasma-new-hope/src/examples/fixtures/Notification.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Notification/Notification.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Notification/Notification.stories.tsx
packages/plasma-web/src/components/Notification/Notification.stories.tsx
packages/sdds-cs/src/components/Notification/Notification.stories.tsx
packages/sdds-dfa/src/components/Notification/Notification.stories.tsx
packages/sdds-finportal/src/components/Notification/Notification.stories.tsx
packages/sdds-insol/src/components/Notification/Notification.stories.tsx
packages/sdds-serv/src/components/Notification/Notification.stories.tsx
website/plasma-b2c-docs/docs/components/Notification.mdx
website/plasma-giga-docs/docs/components/Notification.mdx
website/plasma-web-docs/docs/components/Notification.mdx
website/sdds-cs-docs/docs/components/Notification.mdx
website/sdds-dfa-docs/docs/components/Notification.mdx
website/sdds-insol-docs/docs/components/Notification.mdx
website/sdds-serv-docs/docs/components/Notification.mdx

- добавлены новые значения для `NotificationPlacement`. `top`, `center`, `left`, `bottom`, `right` и производные комбинации.   
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.309.0-canary.1832.13849926955.0
npm install @salutejs/plasma-b2c@1.551.0-canary.1832.13849926955.0
npm install @salutejs/plasma-giga@0.278.0-canary.1832.13849926955.0
npm install @salutejs/plasma-new-hope@0.295.0-canary.1832.13849926955.0
npm install @salutejs/plasma-web@1.553.0-canary.1832.13849926955.0
npm install @salutejs/sdds-cs@0.287.0-canary.1832.13849926955.0
npm install @salutejs/sdds-dfa@0.281.0-canary.1832.13849926955.0
npm install …
```

PLASMA-4478: Extend NotificationPlacement prop

---

packages/plasma-new-hope/src/components/TextField/variations/_read-only/base.ts

- исправлен баг в режиме `readOnly`;
У псевдо-элемента before для режима readOnly стоит z-index: -1, и это приводило к багу, когда фон и тень (бордер) уходили ниже всех других компонентов на странице. Чтобы этого не происходило я поставил родительскому тегу z-index: 0, 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.315.0-canary.1838.13899379517.0
npm install @salutejs/plasma-b2c@1.557.0-canary.1838.13899379517.0
npm install @salutejs/plasma-giga@0.284.0-canary.1838.13899379517.0
npm install @salutejs/plasma-new-hope@0.301.0-canary.1838.13899379517.0
npm install @salutejs/plasma-web@1.559.0-canary.1838.13899379517.0
npm install …
```

PLASMA-4676: fix read-only mode in Textfield

---

packages/plasma-b2c/src/components/Combobox/Combobox.stories.tsx
packages/plasma-giga/src/components/Combobox/Combobox.stories.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Combobox/Combobox.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Combobox/Combobox.stories.tsx
packages/plasma-web/src/components/Combobox/Combobox.stories.tsx
packages/sdds-cs/src/components/Combobox/Combobox.stories.tsx
packages/sdds-dfa/src/components/Combobox/Combobox.stories.tsx
packages/sdds-finportal/src/components/Combobox/Combobox.stories.tsx
packages/sdds-insol/src/components/Combobox/Combobox.stories.tsx
packages/sdds-serv/src/components/Combobox/Combobox.stories.tsx

- добавлено **новое** свойство `emptyStateDescription `   
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.316.0-canary.1844.13914817759.0
npm install @salutejs/plasma-b2c@1.558.0-canary.1844.13914817759.0
npm install @salutejs/plasma-giga@0.285.0-canary.1844.13914817759.0
npm install @salutejs/plasma-new-hope@0.302.0-canary.1844.13914817759.0
npm install @salutejs/plasma-web@1.560.0-canary.1844.13914817759.0
npm install @salutejs/sdds-cs@0.294.0-canary.1844.13914817759.0
npm install @salutejs/sdds-dfa@0.288.0-canary.1844.13914817759.0
npm install @salutejs/sdds-finportal@0.281.0-canary.1844.13914817759.0
npm install …
```

PLASMA-4241: Add emptyStateDescription prop to Combobox

---

packages/plasma-new-hope/src/components/Autocomplete/FloatingPopover.tsx
packages/plasma-new-hope/src/components/Combobox/ComboboxNew/FloatingPopover.tsx
packages/plasma-new-hope/src/components/Dropdown/FloatingPopover.tsx
packages/plasma-new-hope/src/components/Select/FloatingPopover.tsx

- исправлен баг с позиционированием выпадающего списка при динамическом изменении его высоты;
Все сделано в рамках настройки floating-ui.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.320.0-canary.1858.13945612029.0
npm install @salutejs/plasma-b2c@1.562.0-canary.1858.13945612029.0
npm install @salutejs/plasma-giga@0.289.0-canary.1858.13945612029.0
npm install @salutejs/plasma-new-hope@0.306.0-canary.1858.13945612029.0
npm install @salutejs/plasma-web@1.564.0-canary.1858.13945612029.0
npm install @salutejs/sdds-cs@0.298.0-canary.1858.13945612029.0
npm install @salutejs/sdds-dfa@0.292.0-canary.1858.13945612029.0
npm install …
```

PLASMA-4163: add autoUpdate in FloatingPopover

---

packages/plasma-b2c/src/components/Select/Select.config.ts
packages/plasma-b2c/src/components/Select/Select.stories.tsx
packages/plasma-giga/src/components/Select/Select.config.ts
packages/plasma-giga/src/components/Select/Select.stories.tsx
packages/plasma-new-hope/src/components/Select/Select.tokens.ts
packages/plasma-new-hope/src/components/Select/Select.tsx
packages/plasma-new-hope/src/components/Select/Select.types.ts
packages/plasma-new-hope/src/components/Select/ui/Target/Target.tsx
packages/plasma-new-hope/src/components/Select/ui/Target/Target.types.ts
packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.styles.tsx
packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.tsx
packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.types.ts
packages/plasma-new-hope/src/components/TextField/variations/_read-only/base.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Select/Select.config.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Select/Select.stories.tsx
packages/plasma-new-hope/src/examples/plasma_web/components/Select/Select.config.ts
packages/plasma-new-hope/src/examples/plasma_web/components/Select/Select.stories.tsx
packages/plasma-web/src/components/Select/Select.config.ts
packages/plasma-web/src/components/Select/Select.stories.tsx
packages/sdds-cs/src/components/Select/Select.config.ts
packages/sdds-cs/src/components/Select/Select.stories.tsx
packages/sdds-dfa/src/components/Select/Select.config.ts
packages/sdds-dfa/src/components/Select/Select.stories.tsx
packages/sdds-finportal/src/components/Select/Select.config.ts
packages/sdds-finportal/src/components/Select/Select.stories.tsx
packages/sdds-insol/src/components/Select/Select.config.ts
packages/sdds-insol/src/components/Select/Select.stories.tsx
packages/sdds-serv/src/components/Select/Select.config.ts
packages/sdds-serv/src/components/Select/Select.stories.tsx

-   Добавлено состояние read only, поправлено disabled
Обновлен дизайн
Копия #1748
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.320.0-canary.1859.13945881812.0
npm install @salutejs/plasma-b2c@1.562.0-canary.1859.13945881812.0
npm install @salutejs/plasma-giga@0.289.0-canary.1859.13945881812.0
npm install @salutejs/plasma-new-hope@0.306.0-canary.1859.13945881812.0
npm install @salutejs/plasma-web@1.564.0-canary.1859.13945881812.0
npm install @salutejs/sdds-cs@0.298.0-canary.1859.13945881812.0
npm install @salutejs/sdds-dfa@0.292.0-canary.1859.13945881812.0
npm install @salutejs/sdds-finportal@0.285.0-canary.1859.13945881812.0
npm install …
```

PLASMA-3632: Add `readOnly` to Select

---

packages/plasma-b2c/src/components/Range/Range.config.ts
packages/plasma-giga/src/components/Range/Range.config.ts
packages/plasma-new-hope/src/examples/plasma_b2c/components/Range/Range.config.ts
packages/plasma-new-hope/src/examples/plasma_web/components/Range/Range.config.ts
packages/plasma-web/src/components/Range/Range.config.ts
packages/sdds-cs/src/components/Range/Range.config.ts
packages/sdds-dfa/src/components/Range/Range.config.ts
packages/sdds-finportal/src/components/Range/Range.config.ts
packages/sdds-serv/src/components/Range/Range.config.ts

- добавлен `hover` для `input` control в компоненте  
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.325.0-canary.1839.13975685676.0
npm install @salutejs/plasma-b2c@1.567.0-canary.1839.13975685676.0
npm install @salutejs/plasma-giga@0.294.0-canary.1839.13975685676.0
npm install @salutejs/plasma-new-hope@0.311.0-canary.1839.13975685676.0
npm install @salutejs/plasma-web@1.569.0-canary.1839.13975685676.0
npm install @salutejs/sdds-cs@0.303.0-canary.1839.13975685676.0
npm install @salutejs/sdds-dfa@0.297.0-canary.1839.13975685676.0
npm install @salutejs/sdds-finportal@0.290.0-canary.1839.13975685676.0
npm install …
```

PLASMA-4509: Add hover in range

---

packages/sdds-clfd-auto/.storybook/decoratorThemes.tsx

- справил `decoratorThemes` убрав `plasma-typo` 
<details>
<br />
```bash
npm install @salutejs/sdds-clfd-auto@0.300.1-canary.1869.14057484730.0
yarn add @salutejs/sdds-clfd-auto@0.300.1-canary.1869.14057484730.0
```
</details>

PLASMA-4597-fix: Remove plasma-typo from storybook

---

packages/plasma-new-hope/src/components/Button/Button.tsx

- добавлен `margin` при наличии `children` у `contentLeft`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.329.0-canary.1878.14202614030.0
npm install @salutejs/plasma-b2c@1.571.0-canary.1878.14202614030.0
npm install @salutejs/plasma-giga@0.298.0-canary.1878.14202614030.0
npm install @salutejs/plasma-new-hope@0.315.0-canary.1878.14202614030.0
npm install @salutejs/plasma-web@1.573.0-canary.1878.14202614030.0
npm install @salutejs/sdds-clfd-auto@0.302.0-canary.1878.14202614030.0
npm install @salutejs/sdds-cs@0.307.0-canary.1878.14202614030.0
npm install @salutejs/sdds-dfa@0.301.0-canary.1878.14202614030.0
npm install …
```

PLASMA-4576: Button fix margin with child

---

packages/plasma-new-hope/src/components/TextArea/TextArea.styles.ts
packages/plasma-new-hope/src/components/TextArea/TextArea.tsx

-   исправлен баг при вводе `col` и некорректном отображении `outerLabelWrapper`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.328.1-canary.1854.14203909655.0
npm install @salutejs/plasma-b2c@1.570.1-canary.1854.14203909655.0
npm install @salutejs/plasma-giga@0.297.1-canary.1854.14203909655.0
npm install @salutejs/plasma-new-hope@0.314.1-canary.1854.14203909655.0
npm install @salutejs/plasma-web@1.572.1-canary.1854.14203909655.0
npm install @salutejs/sdds-clfd-auto@0.301.1-canary.1854.14203909655.0
npm install @salutejs/sdds-cs@0.306.1-canary.1854.14203909655.0
npm install @salutejs/sdds-dfa@0.300.1-canary.1854.14203909655.0
npm install …
```

PLASMA-3621: Fix outer label wrapper width textatea

---

packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.stories.tsx
packages/plasma-web/src/components/PreviewGallery/PreviewGallery.stories.tsx

Исправлен пример stories для компонента PreviewGallery
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.576.1-canary.1890.14258039816.0
npm install @salutejs/plasma-web@1.578.1-canary.1890.14258039816.0
yarn add @salutejs/plasma-b2c@1.576.1-canary.1890.14258039816.0
yarn add @salutejs/plasma-web@1.578.1-canary.1890.14258039816.0
```
</details>

PLASMA-4781: Fix `PreviewGallery` stories example

---

.github/workflows/cypress-by-cron-every-day.yml
.github/workflows/cypress-common.yml
.github/workflows/cypress.yml
cypress/config/b2b-config.json
cypress/config/b2c-config.json
cypress/config/web-config.json
packages/plasma-b2c/package.json

- добавлен retry для шагов
- lerna bootstrap
- запуск самих тестов
- запуск тестов в связке с react 17 теперь по cron каждый день в полночь  
Мотивация выноса тестов React 17 на расписание, уменьшить кол-во проверок в пр.  
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.576.1-canary.1884.14259946946.0
yarn add @salutejs/plasma-b2c@1.576.1-canary.1884.14259946946.0
```
</details>

plasma-infra: Add retry logic for cypress tests 

---

packages/plasma-new-hope/src/components/NumberFormat/NumberFormat.tsx
packages/plasma-new-hope/src/components/TextField/TextField.styles.ts
packages/plasma-new-hope/src/components/TextField/TextField.tokens.ts
packages/plasma-new-hope/src/components/TextField/TextField.tsx

- Если текст не помещается, то ставятся 3 точки
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.1-canary.1937.14729137192.0
npm install @salutejs/plasma-b2c@1.577.1-canary.1937.14729137192.0
npm install @salutejs/plasma-giga@0.304.1-canary.1937.14729137192.0
npm install @salutejs/plasma-hope@1.339.1-canary.1937.14729137192.0
npm install @salutejs/plasma-new-hope@0.321.1-canary.1937.14729137192.0
npm install @salutejs/plasma-ui@1.315.1-canary.1937.14729137192.0
npm install @salutejs/plasma-web@1.579.1-canary.1937.14729137192.0
npm install @salutejs/sdds-clfd-auto@0.308.1-canary.1937.14729137192.0
npm install …
```

PLASMA-3890: Textfield text overflow ellipsis

---

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/hooks/useKeyboardNavigation.ts
packages/plasma-new-hope/src/components/Dropdown/hooks/useKeyboardNavigation.ts
packages/plasma-new-hope/src/components/Dropdown/ui/DropdownItem/DropdownItem.tsx
packages/plasma-new-hope/src/components/Select/hooks/useKeyboardNavigation.ts

- исправлен баг, связанный с возможностью открывать вложенный список с флагом `disabled`;
- исправлен баг, связанный с возможностью открывать вложенный список с флагом `disabled`;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.336.1-canary.1952.14735805278.0
npm install @salutejs/plasma-b2c@1.578.1-canary.1952.14735805278.0
npm install @salutejs/plasma-giga@0.305.1-canary.1952.14735805278.0
npm install @salutejs/plasma-new-hope@0.322.1-canary.1952.14735805278.0
npm install @salutejs/plasma-web@1.580.1-canary.1952.14735805278.0
npm install @salutejs/sdds-clfd-auto@0.309.1-canary.1952.14735805278.0
npm install …
```

PLASMA-4987: fix disabled group issue in Dropdown

---

packages/plasma-new-hope/src/components/NumberFormat/NumberFormat.tsx
packages/plasma-new-hope/src/components/TextField/TextField.tsx

- Исправлено название переменной
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.336.1-canary.1953.15016453238.0
npm install @salutejs/plasma-b2c@1.578.1-canary.1953.15016453238.0
npm install @salutejs/plasma-giga@0.305.1-canary.1953.15016453238.0
npm install @salutejs/plasma-new-hope@0.322.1-canary.1953.15016453238.0
npm install @salutejs/plasma-web@1.580.1-canary.1953.15016453238.0
npm install @salutejs/sdds-clfd-auto@0.309.1-canary.1953.15016453238.0
npm install @salutejs/sdds-cs@0.314.1-canary.1953.15016453238.0
npm install @salutejs/sdds-dfa@0.308.1-canary.1953.15016453238.0
npm install @salutejs/sdds-finportal@0.301.1-canary.1953.15016453238.0
npm …
```

PLASMA-3890: Fix var name in textfield

---

packages/sdds-cs/src/components/NumberFormat/NumberFormat.stories.tsx
website/sdds-cs-docs/docs/components/NumberFormat.mdx

- исправлены значения свойства `size` в примерах документации и storybook
Исправлен размер в документации и в сторибуке
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.316.0-canary.1961.15024816740.0
yarn add @salutejs/sdds-cs@0.316.0-canary.1961.15024816740.0
```
</details>

PLASMA-4904: update story and docs for NumberFormat

---

packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
packages/plasma-new-hope/src/components/TextField/TextField.tokens.ts
packages/plasma-new-hope/src/components/TextField/TextField.tsx
packages/plasma-new-hope/src/components/TextField/variations/_label-placement/base.ts
packages/plasma-web/src/components/TextField/TextField.stories.tsx

- исправлено некорректное поведение фокуса в режиме `readOnly`;
Оригинально баг был в текстфилде, соответственно из селекта баг тоже изчез.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.337.1-canary.1971.15205193916.0
npm install @salutejs/plasma-b2c@1.579.1-canary.1971.15205193916.0
npm install @salutejs/plasma-core@1.196.1-canary.1971.15205193916.0
npm install @salutejs/plasma-giga@0.306.1-canary.1971.15205193916.0
npm install @salutejs/plasma-hope@1.340.1-canary.1971.15205193916.0
npm install @salutejs/plasma-new-hope@0.323.1-canary.1971.15205193916.0
npm install @salutejs/plasma-tokens-b2b@1.48.1-canary.1971.15205193916.0
npm install …
```

PLASMA-5079: fix incorrect behaviour in readOnly mode in TextField

---

packages/plasma-new-hope/src/components/Popover/Popover.tsx

- добавлена обработка случая, когда frame передан как ID
При создании ref на портал не учитывался случай, когда во frame передавался ID портала. Из-за чего рендер Popover происходил не в ожидаемом месте
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.338.1-canary.2001.15297455776.0
npm install @salutejs/plasma-b2c@1.580.1-canary.2001.15297455776.0
npm install @salutejs/plasma-giga@0.307.1-canary.2001.15297455776.0
npm install @salutejs/plasma-hope@1.341.1-canary.2001.15297455776.0
npm install @salutejs/plasma-icons@1.217.1-canary.2001.15297455776.0
npm install @salutejs/plasma-new-hope@0.324.1-canary.2001.15297455776.0
npm install …
```

PLASMA-5150: add frame as id to Popover

---

packages/plasma-giga/src/components/Modal/Modal.stories.tsx
packages/plasma-new-hope/src/components/Drawer/Drawer.tsx
packages/plasma-new-hope/src/components/Drawer/hooks/useDrawer.ts
packages/plasma-new-hope/src/components/Modal/Modal.tsx
packages/plasma-new-hope/src/components/Modal/hooks/useModal.ts
packages/plasma-new-hope/src/components/Popup/Popup.tsx
packages/plasma-new-hope/src/components/Popup/Popup.types.ts
packages/plasma-new-hope/src/components/Popup/PopupContext.tsx
packages/sdds-crm/src/components/Modal/Modal.stories.tsx
packages/sdds-cs/src/components/Modal/Modal.stories.tsx
packages/sdds-dfa/src/components/Modal/Modal.stories.tsx
packages/sdds-finportal/src/components/Modal/Modal.stories.tsx
packages/sdds-insol/src/components/Modal/Modal.stories.tsx
packages/sdds-netology/src/components/Modal/Modal.stories.tsx
packages/sdds-scan/src/components/Modal/Modal.stories.tsx
packages/sdds-serv/src/components/Modal/Modal.stories.tsx

- массив элементов контекста Popup заменен на Map
- исправлен импорт safeUseId
При использовании useQuery из RTK происходило дублирование ID в массиве items PopupProvider. Чтобы исправить это поведение, массив был заменен на Map и были исправлены импорты
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.341.0-canary.2022.15758717316.0
npm install @salutejs/plasma-b2c@1.583.0-canary.2022.15758717316.0
npm install @salutejs/plasma-giga@0.310.0-canary.2022.15758717316.0
npm install @salutejs/plasma-new-hope@0.327.0-canary.2022.15758717316.0
npm install @salutejs/plasma-ui@1.320.0-canary.2022.15758717316.0
npm install …
```

PLASMA-5169: change popup items to map

---

packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx

- добавлена проверка при обновлении value/defaultValue
**Before**:
https://github.com/user-attachments/assets/fea399b1-8225-4b39-889b-b332664a4bcc
**After**:
https://github.com/user-attachments/assets/2e733867-15fb-4818-97f1-f0c024dc37cb
Когда DatePicker используется внутри Drawer происходит анмаунт и маунт при закрытии и повторном открытии Drawer. Возникал конфликт при апдейте value/defaultValue.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.343.0-canary.2058.15994236534.0
npm install @salutejs/plasma-b2c@1.585.0-canary.2058.15994236534.0
npm install @salutejs/plasma-giga@0.312.0-canary.2058.15994236534.0
npm install …
```

PLASMA-5310: add check for value update in DatePicker

---

packages/sdds-bizcom/.storybook/decoratorThemes.tsx
packages/sdds-bizcom/.storybook/preview.tsx
packages/sdds-bizcom/README.md
packages/sdds-bizcom/src/components/Tokens/Colors/Colors.stories.tsx
packages/sdds-bizcom/src/components/Tokens/NumberTokens/CornerRadius.stories.tsx
packages/sdds-bizcom/src/components/Tokens/NumberTokens/Spacing.stories.tsx
packages/sdds-bizcom/src/components/Tokens/Typography/Typography.stories.tsx

-   добавлена поддержка темы `sdds-procom`
-   добавлена поддержка темы `sdds-bcp`
<details>
<br />
```bash
npm install @salutejs/sdds-bizcom@0.317.0-canary.2060.16049755319.0
yarn add @salutejs/sdds-bizcom@0.317.0-canary.2060.16049755319.0
```
</details>

PLASMA-5353: support themes: bcp,procom [sdds-bizcom]

---

packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
packages/plasma-new-hope/src/components/TextArea/TextArea.types.tsx
packages/plasma-new-hope/src/components/Typography/Heading/Heading.tsx
packages/plasma-new-hope/src/components/Typography/Typography.tsx

- добавлена поддержка a11y для aria role heading  
- добавлено новое свойство `labelAriaHidden` для управления `aria-hidden`  
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.344.0-canary.2097.16444622079.0
npm install @salutejs/plasma-b2c@1.586.0-canary.2097.16444622079.0
npm install @salutejs/plasma-giga@0.313.0-canary.2097.16444622079.0
npm install @salutejs/plasma-hope@1.347.0-canary.2097.16444622079.0
npm install @salutejs/plasma-icons@1.221.0-canary.2097.16444622079.0
npm install @salutejs/plasma-new-hope@0.330.0-canary.2097.16444622079.0
npm install @salutejs/plasma-ui@1.323.0-canary.2097.16444622079.0
npm install …
```

PLASMA-5486: Add ARIA for `Heading` components 

---

packages/plasma-new-hope/src/examples/components/Combobox/Combobox.ts
packages/plasma-new-hope/src/examples/components/Popover/Popover.ts
packages/plasma-new-hope/src/examples/components/Select/Select.config.ts
packages/plasma-new-hope/src/examples/components/Select/Select.ts
packages/plasma-new-hope/src/examples/components/Table/Table.ts

- исправлены пути для импортов в `examples` в storybook для `plasma-new-hope`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.345.1-canary.2102.16522537635.0
npm install @salutejs/plasma-b2c@1.587.1-canary.2102.16522537635.0
npm install @salutejs/plasma-giga@0.314.1-canary.2102.16522537635.0
npm install @salutejs/plasma-new-hope@0.331.1-canary.2102.16522537635.0
npm install @salutejs/plasma-web@1.589.1-canary.2102.16522537635.0
npm install @salutejs/sdds-bizcom@0.319.1-canary.2102.16522537635.0
npm install @salutejs/sdds-crm@0.318.1-canary.2102.16522537635.0
npm install @salutejs/sdds-cs@0.323.1-canary.2102.16522537635.0
npm install …
```

PLASMA-5551: fix paths for storybook

---

packages/plasma-new-hope/src/components/Skeleton/Skeleton.template-doc.mdx
packages/plasma-new-hope/src/components/Skeleton/hoc/withSkeleton.tsx
packages/plasma-ui/src/components/Skeleton/Skeleton.stories.tsx
packages/plasma-ui/src/hocs/hocs.md
website/plasma-b2c-docs/docs/components/Skeleton.mdx
website/plasma-b2c-docs/docs/functions/hocs.mdx
website/plasma-giga-docs/docs/components/Skeleton.mdx
website/plasma-ui-docs/docs/functions/hocs.mdx
website/plasma-web-docs/docs/components/Skeleton.mdx
website/plasma-web-docs/docs/functions/hocs.mdx
website/sdds-crm-docs/docs/components/Skeleton.mdx
website/sdds-cs-docs/docs/components/Skeleton.mdx
website/sdds-dfa-docs/docs/components/Skeleton.mdx
website/sdds-finportal-docs/docs/components/Skeleton.mdx
website/sdds-insol-docs/docs/components/Skeleton.mdx
website/sdds-netology-docs/docs/components/Skeleton.mdx
website/sdds-scan-docs/docs/components/Skeleton.mdx
website/sdds-serv-docs/docs/components/Skeleton.mdx

- исправлена типизация пропсов внутри `withSkeleton`
Исправлена типизация пропсов внутри `withSkeleton`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.346.0-canary.2116.16646069672.0
npm install @salutejs/plasma-b2c@1.588.0-canary.2116.16646069672.0
npm install @salutejs/plasma-core@1.204.0-canary.2116.16646069672.0
npm install @salutejs/plasma-giga@0.315.0-canary.2116.16646069672.0
npm install @salutejs/plasma-hope@1.349.0-canary.2116.16646069672.0
npm install @salutejs/plasma-new-hope@0.332.0-canary.2116.16646069672.0
npm install @salutejs/plasma-tokens@1.119.0-canary.2116.16646069672.0
npm install @salutejs/plasma-ui@1.325.0-canary.2116.16646069672.0 …
```

PLASMA-5568: fix withSkeleton type

---

packages/plasma-new-hope/src/components/Attach/Attach.tsx
packages/plasma-new-hope/src/components/Attach/Attach.types.ts
packages/plasma-new-hope/src/components/Attach/utils/getFileicon.tsx

- Добавлен новый параметр `customIcon`
- Расширены типы файлов с вшитыми иконками `docx` , `xlsx`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.346.0-canary.2123.16716340557.0
npm install @salutejs/plasma-b2c@1.588.0-canary.2123.16716340557.0
npm install @salutejs/plasma-core@1.204.0-canary.2123.16716340557.0
npm install @salutejs/plasma-giga@0.315.0-canary.2123.16716340557.0
npm install @salutejs/plasma-hope@1.349.0-canary.2123.16716340557.0
npm install @salutejs/plasma-new-hope@0.332.0-canary.2123.16716340557.0
npm install @salutejs/plasma-tokens@1.119.0-canary.2123.16716340557.0
npm install @salutejs/plasma-ui@1.325.0-canary.2123.16716340557.0
npm …
```

PLASMA-5352: Add attach customIcon

---

packages/sdds-finai/src/components/Tooltip/Tooltip.config.ts

- токены инвертированы, и теперь по-умолчанию используется onDark значения
По требованию команды внесли такие изменения   
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.347.1-canary.2154.16989970539.0
npm install @salutejs/plasma-b2c@1.589.1-canary.2154.16989970539.0
npm install @salutejs/plasma-giga@0.316.1-canary.2154.16989970539.0
npm install @salutejs/plasma-new-hope@0.333.1-canary.2154.16989970539.0
npm install @salutejs/plasma-web@1.591.1-canary.2154.16989970539.0
npm install @salutejs/sdds-bizcom@0.321.1-canary.2154.16989970539.0
npm install @salutejs/sdds-crm@0.320.1-canary.2154.16989970539.0
npm install …
```

PLASMA-5582: use `onDark` as default view into tooltip [FinAi]

---

website/plasma-b2c-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/plasma-b2c-docs/docs/components/Autocomplete.mdx
website/plasma-giga-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/plasma-giga-docs/docs/components/Autocomplete.mdx
website/plasma-web-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/plasma-web-docs/docs/components/Autocomplete.mdx
website/sdds-crm-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/sdds-crm-docs/docs/components/Autocomplete.mdx
website/sdds-cs-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/sdds-cs-docs/docs/components/Autocomplete.mdx
website/sdds-dfa-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/sdds-dfa-docs/docs/components/Autocomplete.mdx
website/sdds-finai-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/sdds-finai-docs/docs/components/Autocomplete.mdx
website/sdds-insol-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/sdds-insol-docs/docs/components/Autocomplete.mdx
website/sdds-netology-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/sdds-netology-docs/docs/components/Autocomplete.mdx
website/sdds-scan-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/sdds-scan-docs/docs/components/Autocomplete.mdx
website/sdds-serv-docs/docs/_examples/_autocomplete/_autocomplete-clear-example.mdx
website/sdds-serv-docs/docs/components/Autocomplete.mdx
website/sdds-serv-docs/docs/next.mdx

- Добавлен пример очистки поля ввода
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.590.1-canary.2165.17228756249.0
npm install @salutejs/plasma-web@1.592.1-canary.2165.17228756249.0
yarn add @salutejs/plasma-b2c@1.590.1-canary.2165.17228756249.0
yarn add @salutejs/plasma-web@1.592.1-canary.2165.17228756249.0
```
</details>

PLASMA-5199: Добавлен пример очистки поля ввода для Autocomplete 

---

packages/plasma-new-hope/src/components/Note/Note.tsx
packages/plasma-new-hope/src/components/Note/Note.types.ts
packages/plasma-new-hope/src/components/Note/variations/_size/base.ts

- исправлена ошибка с некорректным переносом по буквам - правильно по словам
- расширен `type` до ReactNode для свойств `title, text`     
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.351.0-canary.2247.17854524722.0
npm install @salutejs/plasma-b2c@1.593.0-canary.2247.17854524722.0
npm install @salutejs/plasma-giga@0.320.0-canary.2247.17854524722.0
npm install @salutejs/plasma-new-hope@0.337.0-canary.2247.17854524722.0
npm install @salutejs/plasma-web@1.595.0-canary.2247.17854524722.0
npm install @salutejs/sdds-bizcom@0.325.0-canary.2247.17854524722.0
npm install @salutejs/sdds-crm@0.324.0-canary.2247.17854524722.0
npm install …
```

PLASMA-5851: Fix Note issues 

---

.github/workflows/cypress-by-cron-every-day.yml
.github/workflows/cypress-common.yml

Сохраняем только скриншоты упавших тестов, сама структура стало проще    
```md
Package/Component/
└── diff.png
``` 
ранее сохраняли всю директорию cypress, что было избыточно      
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.350.1-canary.2007.18030906219.0
npm install @salutejs/plasma-b2c@1.592.1-canary.2007.18030906219.0
npm install @salutejs/plasma-giga@0.319.1-canary.2007.18030906219.0
npm install @salutejs/plasma-new-hope@0.336.1-canary.2007.18030906219.0
npm install @salutejs/plasma-web@1.594.1-canary.2007.18030906219.0
npm install @salutejs/sdds-bizcom@0.324.1-canary.2007.18030906219.0
npm install …
```

PLASMA-5177: Simplify test diff artefacts structure
