salute-developers/plasma

packages/plasma-temple/src/components/Page/Page.tsx, packages/plasma-temple/src/components/PlasmaApp/PlasmaApp.tsx, packages/plasma-temple/src/hooks/useInitializeAssistant.ts
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.62.1-canary.6.2274683481.0
yarn add @salutejs/plasma-temple@1.62.1-canary.6.2274683481.0
```
</details>
=> feat(plasma-temple): Откат не используемого кода

.github/workflows/release.yml, packages/plasma-b2c/package-lock.json, packages/plasma-core/package-lock.json, packages/plasma-icons/package-lock.json, packages/plasma-temple/package-lock.json, packages/plasma-tokens-b2b/package-lock.json, packages/plasma-tokens-b2c/package-lock.json, packages/plasma-tokens-web/package-lock.json, packages/plasma-tokens/package-lock.json, packages/plasma-typo/package-lock.json, packages/plasma-typo/package.json, packages/plasma-ui/package-lock.json, packages/plasma-web/package-lock.json, utils/plasma-cy-utils/package-lock.json, utils/plasma-sb-utils/package-lock.json, utils/plasma-tokens-android/package-lock.json, utils/plasma-tokens-ios-swift/package-lock.json
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.63.2-canary.18.2278589958.0
npm install @salutejs/plasma-core@1.57.2-canary.18.2278589958.0
npm install @salutejs/plasma-temple@1.65.2-canary.18.2278589958.0
npm install @salutejs/plasma-typo@0.4.2-canary.18.2278589958.0
npm install @salutejs/plasma-ui@1.101.2-canary.18.2278589958.0
npm install @salutejs/plasma-web@1.98.2-canary.18.2278589958.0
npm install @salutejs/plasma-cy-utils@0.10.2-canary.18.2278589958.0
yarn add @salutejs/plasma-b2c@1.63.2-canary.18.2278589958.0
yarn add @salutejs/plasma-core@1.57.2-canary.18.2278589958.0
yarn add @salutejs/plasma-temple@1.65.2-canary.18.2278589958.0
yarn add …
```
=> chore: update locks

packages/plasma-web/.storybook/manager-head.html, packages/plasma-web/.storybook/preview-head.html
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.69.1-canary.37.2389892221.0
npm install @salutejs/plasma-web@1.104.1-canary.37.2389892221.0
yarn add @salutejs/plasma-b2c@1.69.1-canary.37.2389892221.0
yarn add @salutejs/plasma-web@1.104.1-canary.37.2389892221.0
```
</details>
=> chore(plasma-web): Add SansDisplay typo for storybook

packages/plasma-temple/src/components/AssistantProvider/hooks/useAssistantInsets.ts, packages/plasma-temple/src/hooks/useSpatNav.ts
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.72.2-canary.59.2460804781.0
yarn add @salutejs/plasma-temple@1.72.2-canary.59.2460804781.0
```
</details>
=> fix(plasma-temple): useSpatNavBetweenTargets - fix ssr render

.babelrc.js, packages/plasma-b2c/package-lock.json, packages/plasma-b2c/package.json, packages/plasma-core/package-lock.json, packages/plasma-core/package.json, packages/plasma-icons/package-lock.json, packages/plasma-icons/package.json, packages/plasma-ui/package-lock.json, packages/plasma-ui/package.json, packages/plasma-web/package-lock.json, packages/plasma-web/package.json
Добавил плагин.
Проверил на сборках, что он действительно выносить неизменные элементы.
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.70.2-canary.46.2448438593.0
npm install @salutejs/plasma-core@1.60.2-canary.46.2448438593.0
npm install @salutejs/plasma-icons@1.84.2-canary.46.2448438593.0
npm install @salutejs/plasma-temple@1.70.2-canary.46.2448438593.0
npm install @salutejs/plasma-typo@0.7.2-canary.46.2448438593.0
npm install @salutejs/plasma-ui@1.106.2-canary.46.2448438593.0
npm install @salutejs/plasma-web@1.105.2-canary.46.2448438593.0
npm install @salutejs/plasma-cy-utils@0.13.2-canary.46.2448438593.0
npm install …
```
=> build(plasma-ui): added  @babel/plugin-transform-react-constant-elements

packages/plasma-temple/src/components/Grid/Grid.stories.tsx, packages/plasma-temple/src/components/Grid/GridSkeleton/GridSkeleton.tsx, packages/plasma-temple/src/components/Grid/index.ts, packages/plasma-temple/src/components/index@mobile.ts, packages/plasma-temple/src/components/index@sberbox.ts, packages/plasma-temple/src/components/index@sberportal.ts, website/plasma-temple-docs/docs/components/Grid.mdx
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.79.0-canary.86.2581627776.0
yarn add @salutejs/plasma-temple@1.79.0-canary.86.2581627776.0
```
</details>
=> feat(plasma-temple): grid skeleton

packages/plasma-ui/.storybook/preview.js, packages/plasma-ui/package-lock.json, packages/plasma-ui/package.json, packages/plasma-ui/src/components/Card/Card.stories.tsx, packages/plasma-ui/src/components/Card/performance-results/content-card--basic-default.json, packages/plasma-ui/src/components/Card/performance-results/content-card--basic-value.json, packages/plasma-ui/src/components/Card/performance-results/content-card--fast-answer.json, packages/plasma-ui/src/components/Card/performance-results/content-card--list-and-header.json, packages/plasma-ui/src/components/Card/performance-results/content-card--list-card.json
Performance addon for Card.
Зафиксировал результаты прогона аддона на сбилженном сторебуке.
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.81.0-canary.85.2588073116.0
npm install @salutejs/plasma-ui@1.116.0-canary.85.2588073116.0
yarn add @salutejs/plasma-temple@1.81.0-canary.85.2588073116.0
yarn add @salutejs/plasma-ui@1.116.0-canary.85.2588073116.0
```
</details>
=> feat(plasma-ui): Performance addon for Card

packages/plasma-temple/src/components/StateLayout/types.ts
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.81.0-canary.88.2594924509.0
npm install @salutejs/plasma-temple@1.81.0-canary.88.2594924509.0
npm install @salutejs/plasma-ui@1.116.0-canary.88.2594924509.0
npm install @salutejs/plasma-web@1.116.0-canary.88.2594924509.0
yarn add @salutejs/plasma-b2c@1.81.0-canary.88.2594924509.0
yarn add @salutejs/plasma-temple@1.81.0-canary.88.2594924509.0
yarn add @salutejs/plasma-ui@1.116.0-canary.88.2594924509.0
yarn add @salutejs/plasma-web@1.116.0-canary.88.2594924509.0
```
</details>
=> feat(plasma-temple): enhance state layout props

packages/plasma-ui/package-lock.json, packages/plasma-ui/src/components/ProductCard/ProductCard.stories.tsx, packages/plasma-ui/src/components/ProductCard/performance-results/content-productcard--product-card-performance.json
Добавил https://storybook.js.org/addons/storybook-addon-performance
Написал Interactions для переключения кол-ва товаров в ProductCart
Зафиксировал результаты прогона аддона на сбилженном сторебуке.
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.81.0-canary.83.2590002760.0
npm install @salutejs/plasma-temple@1.81.0-canary.83.2590002760.0
npm install @salutejs/plasma-ui@1.116.0-canary.83.2590002760.0
npm install @salutejs/plasma-web@1.116.0-canary.83.2590002760.0
yarn add @salutejs/plasma-b2c@1.81.0-canary.83.2590002760.0
yarn add @salutejs/plasma-temple@1.81.0-canary.83.2590002760.0
yarn add @salutejs/plasma-ui@1.116.0-canary.83.2590002760.0
yarn add …
```
=> feat(plasma-ui): Performance addon for ProductCart

packages/plasma-web/src/components/Calendar/Calendar.tsx, packages/plasma-web/src/components/Calendar/CalendarBase.tsx, packages/plasma-web/src/components/Calendar/hooks.ts, packages/plasma-web/src/components/Calendar/mixins.ts, packages/plasma-web/src/components/Calendar/types.ts, packages/plasma-web/src/components/Calendar/utils.ts, packages/plasma-web/src/components/Calendar/withRange.tsx, website/plasma-web-docs/docs/components/Calendar.mdx
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.81.1-canary.90.2612325182.0
npm install @salutejs/plasma-temple@1.81.1-canary.90.2612325182.0
npm install @salutejs/plasma-ui@1.116.1-canary.90.2612325182.0
npm install @salutejs/plasma-web@1.116.1-canary.90.2612325182.0
yarn add @salutejs/plasma-b2c@1.81.1-canary.90.2612325182.0
yarn add @salutejs/plasma-temple@1.81.1-canary.90.2612325182.0
yarn add @salutejs/plasma-ui@1.116.1-canary.90.2612325182.0
yarn add @salutejs/plasma-web@1.116.1-canary.90.2612325182.0
```
</details>
=> docs(plasma-web,plasma-web-docs): Add comments and documentation for `Calendar`

website/plasma-ui-docs/docs/components/Carousel.mdx
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.81.1-canary.75.2615065602.0
npm install @salutejs/plasma-temple@1.81.1-canary.75.2615065602.0
npm install @salutejs/plasma-ui@1.116.1-canary.75.2615065602.0
npm install @salutejs/plasma-web@1.116.1-canary.75.2615065602.0
yarn add @salutejs/plasma-b2c@1.81.1-canary.75.2615065602.0
yarn add @salutejs/plasma-temple@1.81.1-canary.75.2615065602.0
yarn add @salutejs/plasma-ui@1.116.1-canary.75.2615065602.0
yarn add @salutejs/plasma-web@1.116.1-canary.75.2615065602.0
```
</details>
=> fix(plasma-ui-docs): up Components creation

packages/plasma-ui/src/components/Checkbox/Checkbox.tsx
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.84.2-canary.105.2710248320.0
npm install @salutejs/plasma-ui@1.118.2-canary.105.2710248320.0
yarn add @salutejs/plasma-temple@1.84.2-canary.105.2710248320.0
yarn add @salutejs/plasma-ui@1.118.2-canary.105.2710248320.0
```
</details>
=> fix(plasma-ui): Fix visible border in Input for `Checkbox` and `RadioBox`

packages/plasma-ui/src/components/Carousel/Carousel.stories.tsx, packages/plasma-web/src/components/Carousel/Carousel.stories.tsx
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.85.0-canary.104.2710238054.0
npm install @salutejs/plasma-temple@1.85.0-canary.104.2710238054.0
npm install @salutejs/plasma-ui@1.119.0-canary.104.2710238054.0
npm install @salutejs/plasma-web@1.119.0-canary.104.2710238054.0
yarn add @salutejs/plasma-b2c@1.85.0-canary.104.2710238054.0
yarn add @salutejs/plasma-temple@1.85.0-canary.104.2710238054.0
yarn add @salutejs/plasma-ui@1.119.0-canary.104.2710238054.0
yarn add @salutejs/plasma-web@1.119.0-canary.104.2710238054.0
```
</details>
=> feat(plasma-ui): Add accessability story for `Carousel` component

packages/plasma-tokens/generate.ts, packages/plasma-tokens/lib/themeBuilder/constants.ts, packages/plasma-tokens/lib/themeBuilder/createTheme.ts, packages/plasma-tokens/lib/themeBuilder/generateTokens.ts, packages/plasma-tokens/lib/themeBuilder/mapDeprecatedTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/backgrounds/getBackgroundPrimaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/backgrounds/getBackgroundSecondaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/backgrounds/getBackgroundTertiaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceClearTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceSolidDefaultTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentCardTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentDefaultTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentPrimaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentSecondaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentTertiaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/overlay/getOverlayHardTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/overlay/getOverlaySoftTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/textIconsTokenGetters/getTextParagraphTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/textIconsTokenGetters/getTextSecondaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/textIconsTokenGetters/getTextTertiaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/types.ts, packages/plasma-tokens/lib/themeBuilder/utils.ts
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.87.0-canary.119.2803560557.0
npm install @salutejs/plasma-core@1.65.0-canary.119.2803560557.0
npm install @salutejs/plasma-icons@1.91.0-canary.119.2803560557.0
npm install @salutejs/plasma-temple@1.86.0-canary.119.2803560557.0
npm install @salutejs/plasma-tokens-b2b@1.4.0-canary.119.2803560557.0
npm install @salutejs/plasma-tokens-b2c@0.13.0-canary.119.2803560557.0
npm install @salutejs/plasma-tokens-web@1.19.0-canary.119.2803560557.0
npm install @salutejs/plasma-tokens@1.19.0-canary.119.2803560557.0
npm install @salutejs/plasma-typo@0.12.0-canary.119.2803560557.0
npm install …
```
=> feat(plasma-tokens): generate custom theme tokens

packages/plasma-b2c/src/components/Modal/Modal.stories.tsx, packages/plasma-web/src/components/Modal/Modal.stories.tsx, packages/plasma-web/src/components/Modal/Modal.tsx
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.87.1-canary.130.2859734479.0
npm install @salutejs/plasma-core@1.65.1-canary.130.2859734479.0
npm install @salutejs/plasma-icons@1.91.1-canary.130.2859734479.0
npm install @salutejs/plasma-temple@1.86.1-canary.130.2859734479.0
npm install @salutejs/plasma-typo@0.12.1-canary.130.2859734479.0
npm install @salutejs/plasma-ui@1.120.1-canary.130.2859734479.0
npm install @salutejs/plasma-web@1.120.1-canary.130.2859734479.0
npm install @salutejs/plasma-cy-utils@0.18.1-canary.130.2859734479.0
npm install @salutejs/plasma-sb-utils@0.64.1-canary.130.2859734479.0
yarn add …
```
=> fix(plasma-web):  Scroll for `Modal` component if it is open

website/plasma-web-docs/docs/components/Toast.mdx
=> docs(plasma-web-docs): Toast: wrong pkg imports

packages/plasma-tokens/generate.ts, packages/plasma-tokens/lib/themeBuilder/generateTokens.ts, packages/plasma-tokens/lib/themeBuilder/mapDeprecatedTokens.ts
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.88.0-canary.121.2831667832.0
npm install @salutejs/plasma-core@1.66.0-canary.121.2831667832.0
npm install @salutejs/plasma-icons@1.92.0-canary.121.2831667832.0
npm install @salutejs/plasma-temple@1.87.0-canary.121.2831667832.0
npm install @salutejs/plasma-tokens@1.20.0-canary.121.2831667832.0
npm install @salutejs/plasma-typo@0.13.0-canary.121.2831667832.0
npm install @salutejs/plasma-ui@1.121.0-canary.121.2831667832.0
npm install @salutejs/plasma-web@1.121.0-canary.121.2831667832.0
npm install @salutejs/plasma-cy-utils@0.19.0-canary.121.2831667832.0
npm install …
```
=> feat(plasma-tokens): generate ios android tokens

packages/plasma-web/src/components/Tooltip/Tooltip.tsx
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.89.0-canary.144.2925735104.0
npm install @salutejs/plasma-web@1.122.0-canary.144.2925735104.0
yarn add @salutejs/plasma-b2c@1.89.0-canary.144.2925735104.0
yarn add @salutejs/plasma-web@1.122.0-canary.144.2925735104.0
```
</details>
=> feat(plasma-web): Add ref for `Tooltip` component

packages/plasma-ui/src/mixins/applyInteraction.ts
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.87.1-canary.147.2926205107.0
npm install @salutejs/plasma-ui@1.121.1-canary.147.2926205107.0
yarn add @salutejs/plasma-temple@1.87.1-canary.147.2926205107.0
yarn add @salutejs/plasma-ui@1.121.1-canary.147.2926205107.0
```
</details>
=> fix(plasma-ui): Remove hover effect for touch devices

packages/plasma-ui/src/components/Header/Header.stories.tsx, website/plasma-ui-docs/docs/components/Header.mdx
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.87.1-canary.142.2925479332.0
npm install @salutejs/plasma-ui@1.121.1-canary.142.2925479332.0
yarn add @salutejs/plasma-temple@1.87.1-canary.142.2925479332.0
yarn add @salutejs/plasma-ui@1.121.1-canary.142.2925479332.0
```
</details>
=> docs(plasma-ui-docs): Update docs and stories for `HeaderMinimize` and `HeaderBack` components

packages/plasma-b2c/src/components/Modal/Modal.stories.tsx, packages/plasma-web/src/components/Modal/Modal.tsx
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.91.1-canary.154.2989126092.0
npm install @salutejs/plasma-web@1.124.1-canary.154.2989126092.0
yarn add @salutejs/plasma-b2c@1.91.1-canary.154.2989126092.0
yarn add @salutejs/plasma-web@1.124.1-canary.154.2989126092.0
```
</details>
=> fix(plasma-web): Fix rendering `Modal` component for next.js 

.github/workflows/release.yml, package-lock.json, package.json, packages/plasma-tokens/.gitignore
<details>
<br />
```bash
npm install @salutejs/plasma-b2c@1.91.0-canary.136.2970912092.0
npm install @salutejs/plasma-core@1.68.0-canary.136.2970912092.0
npm install @salutejs/plasma-icons@1.94.0-canary.136.2970912092.0
npm install @salutejs/plasma-temple@1.91.0-canary.136.2970912092.0
npm install @salutejs/plasma-tokens@1.21.0-canary.136.2970912092.0
npm install @salutejs/plasma-typo@0.15.0-canary.136.2970912092.0
npm install @salutejs/plasma-ui@1.125.0-canary.136.2970912092.0
npm install @salutejs/plasma-web@1.124.0-canary.136.2970912092.0
npm install @salutejs/plasma-cy-utils@0.21.0-canary.136.2970912092.0
npm install …
```
=> feat(plasma-tokens): save theme artifacts

packages/plasma-ui/src/components/Sheet/Sheet.tsx
[colors--canary.159.3035678947.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.159.3035678947.xml)  
[PlasmaTokensColor--canary.159.3035678947.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.159.3035678947.swift)
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.92.1-canary.159.3035678947.0
npm install @salutejs/plasma-ui@1.126.1-canary.159.3035678947.0
yarn add @salutejs/plasma-temple@1.92.1-canary.159.3035678947.0
yarn add @salutejs/plasma-ui@1.126.1-canary.159.3035678947.0
```
</details>
=> fix(plasma-ui): Fix component Sheet

packages/plasma-temple/src/components/GalleryNew/hooks/useMultiGallery.ts, packages/plasma-temple/src/hooks/useFocusedState.tsx
[colors--canary.163.3048451902.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.163.3048451902.xml)  
[PlasmaTokensColor--canary.163.3048451902.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/PlasmaTokensColor--canary.163.3048451902.swift)
<details>
<br />
```bash
npm install @salutejs/plasma-temple@1.93.1-canary.163.3048451902.0
yarn add @salutejs/plasma-temple@1.93.1-canary.163.3048451902.0
```
</details>
=> fix(plasma-temple): focusin(-out) => focus / blur

packages/plasma-tokens/config.ts, packages/plasma-tokens/data/themes/sbermarket.json, packages/plasma-tokens/lib/generator/formatters/iosSwift.ts, packages/plasma-tokens/lib/generator/formatters/kotlin.ts, packages/plasma-tokens/lib/generator/formatters/reactNative.ts, packages/plasma-tokens/lib/generator/index.ts, packages/plasma-tokens/lib/generator/transformers/gradientKotlin.ts, packages/plasma-tokens/lib/generator/transformers/gradientReactNative.ts, packages/plasma-tokens/lib/generator/transformers/gradientSwift.ts, packages/plasma-tokens/lib/generator/transformers/index.ts, packages/plasma-tokens/lib/generator/types.ts
[sbermarket_ios-swift--canary.170.3150944806.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.170.3150944806.swift)  
[sbermarket_kotlin--canary.170.3150944806.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.170.3150944806.kt)  
[sbermarket_react-native--canary.170.3150944806.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.170.3150944806.ts)  
[colors--canary.170.3150944806.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.170.3150944806.xml)  
[PlasmaTokensColor--canary.170.3150944806.swift](https://github.com/salute-develope …
=> feat(plasma-tokens): Add gradient generators

packages/plasma-b2c/src/components/Upload/UploadButton.tsx
[sbermarket_ios-swift--canary.176.3181378209.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.176.3181378209.swift)  
[sbermarket_kotlin--canary.176.3181378209.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.176.3181378209.kt)  
[sbermarket_react-native--canary.176.3181378209.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.176.3181378209.ts)  
[colors--canary.176.3181378209.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.176.3181378209.xml)  
[PlasmaTokensColor--canary.176.3181378209.swift](https://github.com/salute-develope …
=> feat(plasma-b2c): add event as second optional arguments for onChange/onUpload methods

packages/plasma-ui/src/components/Sheet/Sheet.stories.tsx, packages/plasma-ui/src/components/Sheet/Sheet.tsx, packages/plasma-ui/src/hooks/index.ts, packages/plasma-ui/src/hooks/useThemeContext.ts
Добавлен свойство `hasTransition` контролирующее  анимацию открытия окна-шторки поверх основного экрана.
[sbermarket_ios-swift--canary.178.3195768743.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.178.3195768743.swift)  
[sbermarket_kotlin--canary.178.3195768743.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.178.3195768743.kt)  
[sbermarket_react-native--canary.178.3195768743.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.178.3195768743.ts)  
[colors--canary.178.3195768743.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary. …
=> feat(plasma-ui): handle "Sheet" component transition

packages/plasma-ui/src/components/ProductCard/ProductCard.stories.tsx, packages/plasma-ui/src/components/ProductCard/ProductCard.tsx
[sbermarket_ios-swift--canary.175.3195093367.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.175.3195093367.swift)  
[sbermarket_kotlin--canary.175.3195093367.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.175.3195093367.kt)  
[sbermarket_react-native--canary.175.3195093367.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.175.3195093367.ts)  
[colors--canary.175.3195093367.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.175.3195093367.xml)  
[PlasmaTokensColor--canary.175.3195093367.swift](https://github.com/salute-develope …
=> feat(plasma-ui): processing multiple badge

packages/plasma-temple/package.json
[sbermarket_ios-swift--canary.181.3217815979.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.181.3217815979.swift)  
[sbermarket_kotlin--canary.181.3217815979.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.181.3217815979.kt)  
[sbermarket_react-native--canary.181.3217815979.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.181.3217815979.ts)  
[colors--canary.181.3217815979.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.181.3217815979.xml)  
[PlasmaTokensColor--canary.181.3217815979.swift](https://github.com/salute-develope …
=> feat(plasma-temple): update desc

packages/plasma-core/src/components/Button/Button.tsx
[sbermarket_ios-swift--canary.183.3218368551.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.183.3218368551.swift)  
[sbermarket_kotlin--canary.183.3218368551.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.183.3218368551.kt)  
[sbermarket_react-native--canary.183.3218368551.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.183.3218368551.ts)  
[colors--canary.183.3218368551.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.183.3218368551.xml)  
[PlasmaTokensColor--canary.183.3218368551.swift](https://github.com/salute-develope …
=> fix(plasma-core): Fix wrapper props for `Button` component

packages/plasma-core/src/components/Carousel/utils.ts
[sbermarket_ios-swift--canary.184.3218763047.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.184.3218763047.swift)  
[sbermarket_kotlin--canary.184.3218763047.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.184.3218763047.kt)  
[sbermarket_react-native--canary.184.3218763047.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.184.3218763047.ts)  
[colors--canary.184.3218763047.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.184.3218763047.xml)  
[PlasmaTokensColor--canary.184.3218763047.swift](https://github.com/salute-develope …
=> fix(plasma-ui): fixes CarouselLite short track scroll bug

packages/plasma-web/src/components/Notification/NotificationsPortal.tsx
[sbermarket_ios-swift--canary.189.3262805284.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.189.3262805284.swift)  
[sbermarket_kotlin--canary.189.3262805284.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.189.3262805284.kt)  
[sbermarket_react-native--canary.189.3262805284.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.189.3262805284.ts)  
[colors--canary.189.3262805284.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.189.3262805284.xml)  
[PlasmaTokensColor--canary.189.3262805284.swift](https://github.com/salute-develope …
=> fix(plasma-web): delete notification scrollbar

packages/plasma-b2c/src/components/Upload/UploadButton.tsx
[sbermarket_ios-swift--canary.190.3273195049.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.190.3273195049.swift)  
[sbermarket_kotlin--canary.190.3273195049.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.190.3273195049.kt)  
[sbermarket_react-native--canary.190.3273195049.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.190.3273195049.ts)  
[colors--canary.190.3273195049.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.190.3273195049.xml)  
[PlasmaTokensColor--canary.190.3273195049.swift](https://github.com/salute-develope …
=> fix(plasma-b2c): Button type=button

packages/plasma-tokens/data/themes/sberprime.json, packages/plasma-tokens/lib/themeBuilder/createTheme.ts, packages/plasma-tokens/lib/themeBuilder/generateThemeHTML.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/backgrounds/getBackgroundPrimaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/backgrounds/getBackgroundSecondaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/themeTokenGetters/backgrounds/getBackgroundTertiaryTokens.ts, packages/plasma-tokens/lib/themeBuilder/types.ts
[sbermarket_ios-swift--canary.182.3279227055.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.182.3279227055.swift)  
[sbermarket_kotlin--canary.182.3279227055.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.182.3279227055.kt)  
[sbermarket_react-native--canary.182.3279227055.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.182.3279227055.ts)  
[sberprime_ios-swift--canary.182.3279227055.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.182.3279227055.swift) …
=>  feat(plasma-tokens): Add `sberprime` theme

packages/plasma-typo/src/archetypes/index.ts, packages/plasma-typo/src/archetypes/mage.ts, packages/plasma-typo/src/archetypes/plasma.ts, packages/plasma-typo/src/archetypes/ruler.ts, packages/plasma-typo/src/archetypes/sage.ts, packages/plasma-typo/src/archetypes/sbermarket.ts, packages/plasma-typo/src/archetypes/soulmate.ts, packages/plasma-typo/src/helpers.ts, packages/plasma-typo/src/index.ts
[sbermarket_ios-swift--canary.199.3321669717.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.199.3321669717.swift)  
[sbermarket_kotlin--canary.199.3321669717.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.199.3321669717.kt)  
[sbermarket_react-native--canary.199.3321669717.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.199.3321669717.ts)  
[sberprime_ios-swift--canary.199.3321669717.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.199.3321669717.swift) …
=> feat(plasma-typo): Add tokens for new typo and `Sbermarket` archetype

packages/plasma-icons/package-lock.json, packages/plasma-icons/package.json, utils/plasma-sb-utils/package-lock.json, utils/plasma-sb-utils/package.json
[sbermarket_ios-swift--canary.200.3330209896.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.200.3330209896.swift)  
[sbermarket_kotlin--canary.200.3330209896.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.200.3330209896.kt)  
[sbermarket_react-native--canary.200.3330209896.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.200.3330209896.ts)  
[sberprime_ios-swift--canary.200.3330209896.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.200.3330209896.swift) …
=> chore(plasma-icons,plasma-sb-utils): Bump plasma-core version

packages/plasma-core/src/components/Button/createButton.tsx, packages/plasma-core/src/components/Spinner/Spinner.tsx, packages/plasma-core/src/types/ThemeProps.ts, packages/plasma-core/src/types/ThemeProviderContextBase.ts, packages/plasma-core/src/types/index.ts, packages/plasma-ui/src/components/Button/ActionButton.tsx, packages/plasma-ui/src/components/Button/Button.tsx, packages/plasma-ui/src/components/Spinner/Spinner.tsx, packages/plasma-ui/src/types/index.ts
[sbermarket_ios-swift--canary.193.3335493988.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.193.3335493988.swift)  
[sbermarket_kotlin--canary.193.3335493988.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.193.3335493988.kt)  
[sbermarket_react-native--canary.193.3335493988.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.193.3335493988.ts)  
[sberprime_ios-swift--canary.193.3335493988.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.193.3335493988.swift) …
=> fix(plasma-core): handle "Spinner" size

packages/plasma-temple/src/components/HeroSlider/HeroSlider@common.tsx, packages/plasma-temple/src/components/HeroSlider/types.ts, packages/plasma-temple/src/hooks/useTouchHander.ts
[sbermarket_ios-swift--canary.196.3336411635.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.196.3336411635.swift)  
[sbermarket_kotlin--canary.196.3336411635.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.196.3336411635.kt)  
[sbermarket_react-native--canary.196.3336411635.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.196.3336411635.ts)  
[sberprime_ios-swift--canary.196.3336411635.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.196.3336411635.swift) …
=> fix(plasma-temple): fix warnings and rerender of HeroSlider

packages/plasma-ui/src/components/ProductCard/ProductCardText.tsx
При увеличение системного шрифта в android app появлялся визуальный дефект - обрезка текста по нижней границе.
Решение, убрать ограничение по максимальной высоте. 
Проверено для мобильного приложения и в браузерах: Chrome, FF, Safari, регресса нет.                
[sbermarket_ios-swift--canary.201.3336655785.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.201.3336655785.swift)  
[sbermarket_kotlin--canary.201.3336655785.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.201.3336655785.kt)  
[sbermarket_react-native--canary.201.3336655785.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-nat …
=> fix(plasma-ui): delete unnecessary max-height property

packages/plasma-temple/src/components/HeroSlide/HeroSlide@sberbox.tsx, packages/plasma-temple/src/components/HeroSlide/HeroSlide@sberportal.tsx, packages/plasma-temple/src/components/HeroSlider/HeroSlider@common.tsx
[sbermarket_ios-swift--canary.202.3337683697.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.202.3337683697.swift)  
[sbermarket_kotlin--canary.202.3337683697.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.202.3337683697.kt)  
[sbermarket_react-native--canary.202.3337683697.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.202.3337683697.ts)  
[sberprime_ios-swift--canary.202.3337683697.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.202.3337683697.swift) …
=> fix(plasma-temple): update `HeroSliderDots` component

packages/plasma-tokens/data/themes/sbermarket.json, packages/plasma-tokens/lib/generator/formatters/kotlin.ts, utils/plasma-tokens-utils/src/generation.ts, utils/plasma-tokens-utils/src/utils/objectToCSSVariables.ts
[sbermarket_ios-swift--canary.203.3345796997.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_ios-swift--canary.203.3345796997.swift)  
[sbermarket_kotlin--canary.203.3345796997.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_kotlin--canary.203.3345796997.kt)  
[sbermarket_react-native--canary.203.3345796997.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sbermarket_react-native--canary.203.3345796997.ts)  
[sberprime_ios-swift--canary.203.3345796997.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/sberprime_ios-swift--canary.203.3345796997.swift) …
=> fix(plasma-tokens): Fix `sbermarket` theme

packages/plasma-tokens/config.ts, packages/plasma-tokens/generate.ts, packages/plasma-tokens/lib/generator/formatters/colorIosSwift.ts, packages/plasma-tokens/lib/generator/formatters/colorKotlin.ts, packages/plasma-tokens/lib/generator/formatters/colorReactNative.ts, packages/plasma-tokens/lib/generator/formatters/index.ts, packages/plasma-tokens/lib/generator/formatters/typoKotlin.ts, packages/plasma-tokens/lib/generator/formatters/typoReactNative.ts, packages/plasma-tokens/lib/generator/index.ts, packages/plasma-tokens/lib/themeBuilder/generateTokens.ts, packages/plasma-tokens/lib/themeBuilder/utils.ts, packages/plasma-tokens/package-lock.json, packages/plasma-tokens/package.json
[colors--canary.198.3362763601.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.198.3362763601.xml)  
[color_sbermarket_ios-swift--canary.198.3362763601.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.198.3362763601.swift)  
[color_sbermarket_kotlin--canary.198.3362763601.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.198.3362763601.kt)  
[color_sbermarket_react-native--canary.198.3362763601.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.198.3362763601.ts) …
=> feat(plasma-tokens): Add typography generator

packages/plasma-ui/src/components/Tabs/TabItem.tsx, packages/plasma-ui/src/components/Tabs/TabsAnimationContext.tsx
[colors--canary.209.3381016224.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.209.3381016224.xml)  
[color_sbermarket_ios-swift--canary.209.3381016224.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.209.3381016224.swift)  
[color_sbermarket_kotlin--canary.209.3381016224.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.209.3381016224.kt)  
[color_sbermarket_react-native--canary.209.3381016224.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.209.3381016224.ts) …
=> feat(plasma-ui): Add ref for `TabItem` component

packages/plasma-ui/src/components/Sheet/Sheet.tsx
[colors--canary.208.3384185184.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.208.3384185184.xml)  
[color_sbermarket_ios-swift--canary.208.3384185184.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.208.3384185184.swift)  
[color_sbermarket_kotlin--canary.208.3384185184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.208.3384185184.kt)  
[color_sbermarket_react-native--canary.208.3384185184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.208.3384185184.ts) …
=> fix(plasma-ui): Increase area for touch in `Sheet` component

packages/plasma-ui/src/components/Pickers/Picker.tsx, packages/plasma-ui/src/utils/index.ts, packages/plasma-ui/src/utils/react.ts
[colors--canary.207.3384012578.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.207.3384012578.xml)  
[color_sbermarket_ios-swift--canary.207.3384012578.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.207.3384012578.swift)  
[color_sbermarket_kotlin--canary.207.3384012578.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.207.3384012578.kt)  
[color_sbermarket_react-native--canary.207.3384012578.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.207.3384012578.ts) …
=> fix(plasma-ui): fix Pickers for React 18

packages/plasma-tokens/lib/generator/formatters/colorIosSwift.ts, packages/plasma-tokens/lib/generator/transformers/gradientSwift.ts, packages/plasma-tokens/lib/generator/types.ts, packages/plasma-tokens/package-lock.json, packages/plasma-tokens/package.json
[colors--canary.211.3425447069.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.211.3425447069.xml)  
[color_sbermarket_ios-swift--canary.211.3425447069.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.211.3425447069.swift)  
[color_sbermarket_kotlin--canary.211.3425447069.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.211.3425447069.kt)  
[color_sbermarket_react-native--canary.211.3425447069.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.211.3425447069.ts) …
=> fix(plasma-tokens): Fix gradient generator for iOS platform

packages/plasma-temple/src/components/AssistantProvider/assistant.ts
[colors--canary.221.3470426341.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.221.3470426341.xml)  
[color_sbermarket_ios-swift--canary.221.3470426341.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.221.3470426341.swift)  
[color_sbermarket_kotlin--canary.221.3470426341.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.221.3470426341.kt)  
[color_sbermarket_react-native--canary.221.3470426341.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.221.3470426341.ts) …
=> fix(plasma-temple): `getAssistantRef` returns correct value

.github/workflows/clean-pr-documentation.yml, .github/workflows/versionate-docs.yml, actions/versionate-docs/src/main.ts
[colors--canary.223.3486285077.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.223.3486285077.xml)  
[color_sbermarket_ios-swift--canary.223.3486285077.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.223.3486285077.swift)  
[color_sbermarket_kotlin--canary.223.3486285077.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.223.3486285077.kt)  
[color_sbermarket_react-native--canary.223.3486285077.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.223.3486285077.ts) …
=> ci: fix actions versionate and clean

website/plasma-ui-docs/docs/intro.mdx, website/plasma-web-docs/docs/intro.mdx
[colors--canary.225.3496486268.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.225.3496486268.xml)  
[color_sbermarket_ios-swift--canary.225.3496486268.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.225.3496486268.swift)  
[color_sbermarket_kotlin--canary.225.3496486268.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.225.3496486268.kt)  
[color_sbermarket_react-native--canary.225.3496486268.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.225.3496486268.ts) …
=> docs(plasma-ui, plasma-web): fix docs typos

.github/workflows/versionate-docs.yml
[colors--canary.227.3497361353.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.227.3497361353.xml)  
[color_sbermarket_ios-swift--canary.227.3497361353.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.227.3497361353.swift)  
[color_sbermarket_kotlin--canary.227.3497361353.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.227.3497361353.kt)  
[color_sbermarket_react-native--canary.227.3497361353.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.227.3497361353.ts) …
=> ci: fix typo s3 versions

packages/plasma-icons/src/IconRoot.tsx, packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx, packages/plasma-web/src/components/Calendar/CalendarBase.tsx, packages/plasma-web/src/components/Calendar/CalendarDayItem.tsx, packages/plasma-web/src/components/Calendar/CalendarDays.tsx, packages/plasma-web/src/components/Calendar/CalendarDouble.tsx, packages/plasma-web/src/components/Calendar/CalendarHeader.tsx, packages/plasma-web/src/components/Calendar/CalendarMonths.tsx, packages/plasma-web/src/components/Calendar/CalendarYears.tsx, packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts, packages/plasma-web/src/components/Calendar/hooks/useMonths.ts, packages/plasma-web/src/components/Calendar/types.ts, packages/plasma-web/src/components/Calendar/utils.ts
Добавить поддержку доступности согласно [примеру(Date Picker Dialog Example)](https://www.w3.org/WAI/ARIA/apg/example-index/dialog-modal/datepicker-dialog.html)
Проверить на доступность в:
macOS
[VoiceOver](https://www.apple.com/ru/accessibility/vision/) - (нативные возможности системы);
Windows
[JAWS](https://www.freedomscientific.com/products/software/jaws/) (платный[ограничения в 40 мин пользования]);
[NVDA](https://www.nvaccess.org/about-nvda/) (бесплатный);
[colors--canary.222.3522295576.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.222.3522295576.xml)  
[color_sbermarket_ios-swift--canary.222.3522295576.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermar …
=> feat(plasma-web): add a11y for date picker (Calendar)

packages/plasma-core/src/components/Skeleton/TextSkeleton.tsx
[colors--canary.241.3531118930.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.241.3531118930.xml)  
[color_sbermarket_ios-swift--canary.241.3531118930.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.241.3531118930.swift)  
[color_sbermarket_kotlin--canary.241.3531118930.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.241.3531118930.kt)  
[color_sbermarket_react-native--canary.241.3531118930.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.241.3531118930.ts) …
=> docs(plasma-core): Skeleton: fix typo

packages/plasma-b2c/package-lock.json, packages/plasma-b2c/package.json, packages/plasma-b2c/src/components/Editable/Editable.tsx, packages/plasma-b2c/src/components/ElasticGrid/ElasticGrid.tsx, packages/plasma-b2c/src/components/PreviewGallery/PreviewGalleryItemWithTooltip.tsx, packages/plasma-b2c/src/components/PreviewGallery/PreviewGalleryItems.tsx, packages/plasma-b2c/src/components/Slider/Double.tsx, packages/plasma-b2c/src/components/Slider/Handle.tsx, packages/plasma-b2c/src/components/Slider/Single.tsx, packages/plasma-b2c/src/components/Slider/SliderBase.tsx, packages/plasma-b2c/src/components/Tabs/TabItem.tsx, packages/plasma-b2c/src/components/TextField/TextField.tsx, packages/plasma-b2c/src/components/Upload/UploadButton.tsx, packages/plasma-b2c/src/utils/selectText.ts
[colors--canary.237.3534558431.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.237.3534558431.xml)  
[color_sbermarket_ios-swift--canary.237.3534558431.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.237.3534558431.swift)  
[color_sbermarket_kotlin--canary.237.3534558431.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.237.3534558431.kt)  
[color_sbermarket_react-native--canary.237.3534558431.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.237.3534558431.ts) …
=> fix(plasma-b2c): improve type-coverage

packages/plasma-web/package-lock.json, packages/plasma-web/package.json, packages/plasma-web/src/components/Calendar/CalendarBase.tsx, packages/plasma-web/src/components/Calendar/hooks/useYears.ts, packages/plasma-web/src/components/Dropdown/Dropdown.tsx, packages/plasma-web/src/components/Dropdown/DropdownItem.tsx, packages/plasma-web/src/components/Dropdown/DropdownUncontrolled.tsx, packages/plasma-web/src/components/Dropdown/keyboardNavigation/useKeyboardNavigation.ts, packages/plasma-web/src/components/Dropdown/keyboardNavigation/utils.ts, packages/plasma-web/src/components/Dropdown/withAssistiveDropdown.tsx, packages/plasma-web/src/components/Input/Input.tsx, packages/plasma-web/src/components/Modal/ModalsContext.tsx, packages/plasma-web/src/components/Notification/NotificationsProvider.tsx, packages/plasma-web/src/components/Select/withMultiSelect.tsx, packages/plasma-web/src/components/Select/withSingleSelect.tsx, packages/plasma-web/src/tokens/typography.ts
[colors--canary.235.3534736095.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.235.3534736095.xml)  
[color_sbermarket_ios-swift--canary.235.3534736095.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.235.3534736095.swift)  
[color_sbermarket_kotlin--canary.235.3534736095.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.235.3534736095.kt)  
[color_sbermarket_react-native--canary.235.3534736095.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.235.3534736095.ts) …
=> fix(plasma-web): improve type-coverage

website/plasma-ui-docs/docs/components/Card.mdx
[colors--canary.243.3539426182.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.243.3539426182.xml)  
[color_sbermarket_ios-swift--canary.243.3539426182.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.243.3539426182.swift)  
[color_sbermarket_kotlin--canary.243.3539426182.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.243.3539426182.kt)  
[color_sbermarket_react-native--canary.243.3539426182.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.243.3539426182.ts) …
=> docs(plasma-ui-docs): Card: fix images

packages/plasma-core/package-lock.json, packages/plasma-core/package.json, packages/plasma-core/src/components/Basebox/Basebox.tsx, packages/plasma-core/src/components/Carousel/utils.ts, packages/plasma-core/src/components/PaginationDots/usePaginationDots.ts, packages/plasma-core/src/components/Popup/Popup.tsx, packages/plasma-core/src/components/SSRProvider/SSRProvider.tsx, packages/plasma-core/src/components/Skeleton/TextSkeleton.tsx, packages/plasma-core/src/components/Tabs/createTabsController.tsx, packages/plasma-core/src/components/Toast/ToastProvider.tsx, packages/plasma-core/src/types/ThemeProviderContextBase.ts, packages/plasma-core/src/utils/extractTextFrom.ts, packages/plasma-core/src/utils/transformStyles.ts
[colors--canary.231.3539470148.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.231.3539470148.xml)  
[color_sbermarket_ios-swift--canary.231.3539470148.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.231.3539470148.swift)  
[color_sbermarket_kotlin--canary.231.3539470148.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.231.3539470148.kt)  
[color_sbermarket_react-native--canary.231.3539470148.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.231.3539470148.ts) …
=> fix(plasma-core): improve type-coverage

packages/plasma-ui/package-lock.json, packages/plasma-ui/package.json, packages/plasma-ui/src/components/Carousel/Carousel.examples.tsx, packages/plasma-ui/src/components/Cell/Cell.tsx, packages/plasma-ui/src/components/Checkbox/Checkbox.tsx, packages/plasma-ui/src/components/Confirm/Confirm.tsx, packages/plasma-ui/src/components/Field/Field.tsx, packages/plasma-ui/src/components/Grid/Col.tsx, packages/plasma-ui/src/components/Grid/Container.tsx, packages/plasma-ui/src/components/Header/HeaderArrow.tsx, packages/plasma-ui/src/components/Header/HeaderRoot.tsx, packages/plasma-ui/src/components/Header/HeaderSubtitle.tsx, packages/plasma-ui/src/components/Header/HeaderTitle.tsx, packages/plasma-ui/src/components/Pickers/DatePicker.tsx, packages/plasma-ui/src/components/Pickers/PickerItem.tsx, packages/plasma-ui/src/components/Pickers/TimePicker.tsx, packages/plasma-ui/src/components/ProductCard/ProductCard.tsx, packages/plasma-ui/src/components/ProductCard/ProductCardText.tsx, packages/plasma-ui/src/components/Radiobox/Radiobox.tsx, packages/plasma-ui/src/components/Slider/Double.tsx, packages/plasma-ui/src/components/Slider/Handle.tsx, packages/plasma-ui/src/components/Slider/Single.tsx, packages/plasma-ui/src/components/Stepper/Stepper.hooks.ts, packages/plasma-ui/src/components/Stepper/Stepper.tsx, packages/plasma-ui/src/components/Tabs/TabItem.tsx, packages/plasma-ui/src/components/Tabs/TabsSlider.tsx, packages/plasma-ui/src/components/TextField/TextField.tsx, packages/plasma-ui/src/helpers/GridLines.tsx, packages/plasma-ui/src/helpers/StoryDecorators.tsx, packages/plasma-ui/src/utils/react.ts
[colors--canary.234.3542704878.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.234.3542704878.xml)  
[color_sbermarket_ios-swift--canary.234.3542704878.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.234.3542704878.swift)  
[color_sbermarket_kotlin--canary.234.3542704878.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.234.3542704878.kt)  
[color_sbermarket_react-native--canary.234.3542704878.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.234.3542704878.ts) …
=> fix(plasma-ui): improve type-coverage

packages/plasma-tokens/data/themes/metro.json, packages/plasma-tokens/data/themes/selgros.json, packages/plasma-tokens/data/themes/smbusiness.json, packages/plasma-tokens/lib/themeBuilder/mapDeprecatedTokens.ts, utils/plasma-tokens-utils/src/generators/generateColorThemeValues.ts, utils/plasma-tokens-utils/src/generators/generateColorThemes.ts, utils/plasma-tokens-utils/src/utils/objectToCSSVariables.ts, utils/plasma-tokens-utils/src/utils/other.ts
Создание дополнительных трёх тем для сбермаркета и удаление префиксов `plasma-colors` у css переменных для тем, который были созданы с помощью генератора и лежат в директории `plasma-tokens/data/themes`
[colors--canary.217.3647001361.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.217.3647001361.xml)  
[color_metro_ios-swift--canary.217.3647001361.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.217.3647001361.swift)  
[color_metro_kotlin--canary.217.3647001361.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.217.3647001361.kt) …
=> feat(plasma-tokens): Add sbermarket tenants

packages/plasma-b2c/src/components/Editable/Editable.stories.tsx, packages/plasma-b2c/src/components/Editable/Editable.tsx
[colors--canary.252.3617935358.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.252.3617935358.xml)  
[color_sbermarket_ios-swift--canary.252.3617935358.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_ios-swift--canary.252.3617935358.swift)  
[color_sbermarket_kotlin--canary.252.3617935358.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_kotlin--canary.252.3617935358.kt)  
[color_sbermarket_react-native--canary.252.3617935358.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_react-native--canary.252.3617935358.ts) …
=> feat(plasma-b2c): add a11y for Editable component

packages/plasma-b2c/src/components/AudioPlayer/AudioPlayer.tsx, packages/plasma-b2c/src/components/PreviewGallery/PreviewGalleryItemBase.tsx, packages/plasma-core/src/components/Button/createButton.tsx, packages/plasma-web/src/components/Calendar/CalendarHeader.tsx, packages/plasma-web/src/components/Select/SelectButton.tsx
Для компонента **Button** необходимо установить значение по-умолчанию `"button"` для атрибута `type`.   
[colors--canary.272.3748065397.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.272.3748065397.xml)  
[color_metro_ios-swift--canary.272.3748065397.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.272.3748065397.swift)  
[color_metro_kotlin--canary.272.3748065397.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.272.3748065397.kt)  
[color_metro_react-native--canary.272.3748065397.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native-- …
=> feat(plasma-core): handling button type

packages/plasma-tokens/config.ts, packages/plasma-tokens/data/themes/sbermarket.json, packages/plasma-tokens/lib/generator/formatters/colorIosSwift.ts, packages/plasma-tokens/lib/generator/formatters/colorKotlin.ts, packages/plasma-tokens/lib/generator/formatters/colorReactNative.ts, packages/plasma-tokens/lib/generator/formatters/index.ts, packages/plasma-tokens/lib/generator/formatters/typoIosSwift.ts, packages/plasma-tokens/lib/generator/formatters/typoKotlin.ts, packages/plasma-tokens/lib/generator/formatters/typoReactNative.ts, packages/plasma-tokens/lib/generator/index.ts, packages/plasma-tokens/lib/generator/transformers/gradientKotlin.ts, packages/plasma-tokens/lib/generator/transformers/gradientReactNative.ts, packages/plasma-typo/src/archetypes/sbermarket.ts, packages/plasma-typo/src/helpers.ts
[colors--canary.226.3764765981.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.226.3764765981.xml)  
[color_metro_ios-swift--canary.226.3764765981.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.226.3764765981.swift)  
[color_metro_kotlin--canary.226.3764765981.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.226.3764765981.kt)  
[color_metro_react-native--canary.226.3764765981.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.226.3764765981.ts)  
[color_sbermarket_ios-swift--canary.226.3764765981.swift](https://github.com/ …
=> feat(plasma-tokens): Add tokens generate fot ios-swift platform and update generator

packages/plasma-web/src/components/Dropdown/Dropdown.types.ts, packages/plasma-web/src/components/Dropdown/DropdownItem.tsx, packages/plasma-web/src/components/Dropdown/keyboardNavigation/utils.ts, packages/plasma-web/src/components/Dropdown/withAssistiveDropdown.tsx, packages/plasma-web/src/components/Select/Select.component-test.tsx
В компоненте Select -> Drop Down необходимо уметь навигировать по выключенным элементам.        
[colors--canary.269.3780484831.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.269.3780484831.xml)  
[color_metro_ios-swift--canary.269.3780484831.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.269.3780484831.swift)  
[color_metro_kotlin--canary.269.3780484831.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.269.3780484831.kt)  
[color_metro_react-native--canary.269.3780484831.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.2 …
=> feat(plasma-web): Navigate by disabled option

.github/workflows/performance-test-main.yml, .github/workflows/performance-test-pr.yml, packages/plasma-ui/package.json, packages/plasma-ui/perftool.config.ts, utils/perftool/src/config/common.ts
[colors--canary.274.3806650475.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.274.3806650475.xml)  
[color_metro_ios-swift--canary.274.3806650475.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.274.3806650475.swift)  
[color_metro_kotlin--canary.274.3806650475.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.274.3806650475.kt)  
[color_metro_react-native--canary.274.3806650475.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.274.3806650475.ts)  
[color_sbermarket_ios-swift--canary.274.3806650475.swift](https://github.com/ …
=> ci: performance tests

website/plasma-temple-docs/docusaurus.config.js, website/plasma-ui-docs/docusaurus.config.js, website/plasma-web-docs/docusaurus.config.js
[colors--canary.280.3934298192.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.280.3934298192.xml)  
[color_metro_ios-swift--canary.280.3934298192.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.280.3934298192.swift)  
[color_metro_kotlin--canary.280.3934298192.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.280.3934298192.kt)  
[color_metro_react-native--canary.280.3934298192.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.280.3934298192.ts)  
[color_sbermarket_ios-swift--canary.280.3934298192.swift](https://github.com/ …
=> docs(plasma-ui, plasma-web, plasma-temple): add trailing slash

.github/workflows/typescript-coverage.yml
[colors--canary.283.3948618005.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.283.3948618005.xml)  
[color_metro_ios-swift--canary.283.3948618005.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.283.3948618005.swift)  
[color_metro_kotlin--canary.283.3948618005.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.283.3948618005.kt)  
[color_metro_react-native--canary.283.3948618005.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.283.3948618005.ts)  
[color_sbermarket_ios-swift--canary.283.3948618005.swift](https://github.com/ …
=> ci: fix size of ts report

packages/plasma-temple/src/hooks/useRemoteHandlers.ts
[colors--canary.284.3958023147.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.284.3958023147.xml)  
[color_metro_ios-swift--canary.284.3958023147.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.284.3958023147.swift)  
[color_metro_kotlin--canary.284.3958023147.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.284.3958023147.kt)  
[color_metro_react-native--canary.284.3958023147.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.284.3958023147.ts)  
[color_sbermarket_ios-swift--canary.284.3958023147.swift](https://github.com/ …
=> fix(plasma-temple): remove duplicate interface

website/plasma-theme-builder/package-lock.json, website/plasma-theme-builder/package.json, website/plasma-theme-builder/src/api/githubFilesFetcher.ts, website/plasma-theme-builder/src/components/App.tsx, website/plasma-theme-builder/src/components/Error/Error.tsx, website/plasma-theme-builder/src/components/Generator/Generator.tsx, website/plasma-theme-builder/src/components/Main/Main.tsx, website/plasma-theme-builder/src/components/Token/Token.tsx, website/plasma-theme-builder/src/components/hooks.tsx, website/plasma-theme-builder/src/components/types.ts, website/plasma-theme-builder/src/components/utils.ts
Сделал возможность считывания и парскинг темы из нашего репозитория. Для доступ к уже существующей необходимо перейти по ссылке вида: https://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-270/?theme=<theme_name>
[colors--canary.270.3956267287.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.270.3956267287.xml)  
[color_metro_ios-swift--canary.270.3956267287.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.270.3956267287.swift)  
[color_metro_kotlin--canary.270.3956267287.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.270.3956267287.kt) …
=> feat: Add read themes from github repo

packages/plasma-ui/perftool.config.ts, utils/perftool/src/build/index.ts, utils/perftool/src/client/index.ts, utils/perftool/src/client/measurement/tasks/render.tsx, utils/perftool/src/client/measurement/tasks/rerender.tsx, utils/perftool/src/client/measurement/types.ts, utils/perftool/src/clientEntry.ts, utils/perftool/src/compare/process.ts, utils/perftool/src/config/common.ts, utils/perftool/src/controller/controller.ts, utils/perftool/src/controller/executor.ts, utils/perftool/src/controller/index.ts, utils/perftool/src/controller/planner.ts, utils/perftool/src/reporter/index.ts, utils/perftool/src/stabilizers/staticTask.tsx, utils/perftool/src/statistics/index.ts, utils/perftool/src/utils/combineGenerators.ts, utils/perftool/src/utils/stabilizers.ts, utils/perftool/src/utils/statsMap.ts
[colors--canary.286.3991984948.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.286.3991984948.xml)  
[color_metro_ios-swift--canary.286.3991984948.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.286.3991984948.swift)  
[color_metro_kotlin--canary.286.3991984948.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.286.3991984948.kt)  
[color_metro_react-native--canary.286.3991984948.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.286.3991984948.ts)  
[color_sbermarket_ios-swift--canary.286.3991984948.swift](https://github.com/ …
=> feat(perftool): static task stabilizer

utils/perftool/src/clientEntry.ts
[colors--canary.290.4006009594.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.290.4006009594.xml)  
[color_metro_ios-swift--canary.290.4006009594.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.290.4006009594.swift)  
[color_metro_kotlin--canary.290.4006009594.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.290.4006009594.kt)  
[color_metro_react-native--canary.290.4006009594.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.290.4006009594.ts)  
[color_sbermarket_ios-swift--canary.290.4006009594.swift](https://github.com/ …
=> fix(perftool): fix auto prettier

website/plasma-theme-builder/src/builder/types.ts, website/plasma-theme-builder/src/components/AddTokenSection/AddTokenSection.tsx, website/plasma-theme-builder/src/components/Generator/Generator.tsx, website/plasma-theme-builder/src/components/Theme/Theme.tsx, website/plasma-theme-builder/src/components/ThemeInfo/ThemeInfo.tsx, website/plasma-theme-builder/src/components/ThemeModeToggle/ThemeModeToggle.tsx, website/plasma-theme-builder/src/components/Token/Token.tsx, website/plasma-theme-builder/src/components/TokenForm/TokenForm.tsx, website/plasma-theme-builder/src/components/TokensSection/TokensSection.tsx, website/plasma-theme-builder/src/components/TokensSubsection/TokensSubsection.tsx, website/plasma-theme-builder/src/components/hooks.tsx, website/plasma-theme-builder/src/components/mixins.ts, website/plasma-theme-builder/src/components/types.ts, website/plasma-theme-builder/src/components/utils.ts
[colors--canary.276.4013191131.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.276.4013191131.xml)  
[color_metro_ios-swift--canary.276.4013191131.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.276.4013191131.swift)  
[color_metro_kotlin--canary.276.4013191131.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.276.4013191131.kt)  
[color_metro_react-native--canary.276.4013191131.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.276.4013191131.ts)  
[color_sbermarket_ios-swift--canary.276.4013191131.swift](https://github.com/ …
=> feat: Add edit and download themes from github repo

.github/workflows/theme-builder-pr.yml, .github/workflows/theme-builder.yml, website/plasma-theme-builder/package-lock.json, website/plasma-theme-builder/package.json, website/plasma-theme-builder/src/api/getAuthToken.ts, website/plasma-theme-builder/src/api/getEnv.ts, website/plasma-theme-builder/src/api/getFilesSource.ts, website/plasma-theme-builder/src/api/index.ts, website/plasma-theme-builder/src/components/AuthRequestModal/AuthRequestModal.tsx, website/plasma-theme-builder/src/components/Footer/Footer.tsx, website/plasma-theme-builder/src/components/Main/Main.tsx, website/plasma-theme-builder/src/components/hooks/index.ts, website/plasma-theme-builder/src/components/hooks/useFetchTheme.tsx, website/plasma-theme-builder/src/components/hooks/useGithubAuth.tsx, website/plasma-theme-builder/src/components/hooks/useNormalizeThemeSections.tsx, website/plasma-theme-builder/src/components/utils.ts
[colors--canary.281.4023354940.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.281.4023354940.xml)  
[color_metro_ios-swift--canary.281.4023354940.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.281.4023354940.swift)  
[color_metro_kotlin--canary.281.4023354940.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.281.4023354940.kt)  
[color_metro_react-native--canary.281.4023354940.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.281.4023354940.ts)  
[color_sbermarket_ios-swift--canary.281.4023354940.swift](https://github.com/ …
=> feat: Add authorization for theme builder by GitHub

packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx, packages/plasma-web/src/components/Calendar/Calendar.stories.tsx, packages/plasma-web/src/components/Calendar/CalendarBase.tsx, packages/plasma-web/src/components/Calendar/CalendarDays.tsx, packages/plasma-web/src/components/Calendar/CalendarDouble.tsx, packages/plasma-web/src/components/Calendar/hooks/useDays.ts, packages/plasma-web/src/components/Calendar/store/reducer.ts, packages/plasma-web/src/components/Calendar/types.ts, packages/plasma-web/src/components/Calendar/utils.ts, packages/plasma-web/src/components/Calendar/withRange.tsx
Необходимо добавить возможность не указывать **init value** для календаря, то есть значение может быть **undefined**.
Было: 
Ошибка компонента 
Стало: 
Если не указывать начальное значение, то в календаре не будет выделен день. 
Но для **месяца**, **года** будет использоваться значения из `new Date()`      
[colors--canary.291.4022842967.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.291.4022842967.xml)  
[color_metro_ios-swift--canary.291.4022842967.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.291.4022842967.swift)  
[color_metro_kotlin--canary.291.4022842967.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary …
=> feat(plasma-web): Handling undefined value(s) in Calendar  

packages/plasma-tokens/config.ts, packages/plasma-tokens/data/shadows/base.ts, packages/plasma-tokens/data/shadows/index.ts, packages/plasma-tokens/generate.ts, packages/plasma-tokens/lib/generator/formatters/index.ts, packages/plasma-tokens/lib/generator/formatters/shadowReactNative.ts, packages/plasma-tokens/lib/generator/index.ts, packages/plasma-tokens/lib/themeBuilder/generateTokens.ts
[colors--canary.288.4053698929.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.288.4053698929.xml)  
[color_metro_ios-swift--canary.288.4053698929.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.288.4053698929.swift)  
[color_metro_kotlin--canary.288.4053698929.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.288.4053698929.kt)  
[color_metro_react-native--canary.288.4053698929.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.288.4053698929.ts)  
[color_sbermarket_ios-swift--canary.288.4053698929.swift](https://github.com/ …
=> feat(plasma-tokens): Add generate shadow tokens for React-Native

packages/plasma-ui/src/components/Button/ActionButton.tsx, packages/plasma-ui/src/components/Button/Button.tsx, packages/plasma-ui/src/hooks/useThemeContext.ts
Было: 
Если по какой-то причине не был передан контекст то -
`TypeError: Cannot read properties of undefined (reading 'deviceScale')`
Стало: 
**useThemeContext** теперь вернет или контекст или пустой объект. 
______________
[colors--canary.304.4052521228.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.304.4052521228.xml)  
[color_metro_ios-swift--canary.304.4052521228.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.304.4052521228.swift)  
[color_metro_kotlin--canary.304.4052521228.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.304.4052521228.kt) …
=> fix(plasma-ui): Avoid undefined in useThemeContext

.babelrc.js, package.json
[colors--canary.307.4064290734.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.307.4064290734.xml)  
[color_metro_ios-swift--canary.307.4064290734.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.307.4064290734.swift)  
[color_metro_kotlin--canary.307.4064290734.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.307.4064290734.kt)  
[color_metro_react-native--canary.307.4064290734.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.307.4064290734.ts)  
[color_sbermarket_ios-swift--canary.307.4064290734.swift](https://github.com/ …
=> feat: Remove component-test from tar files

packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx, packages/plasma-web/src/components/Calendar/Calendar.stories.tsx, packages/plasma-web/src/components/Calendar/CalendarBase.tsx, packages/plasma-web/src/components/Calendar/CalendarDayItem.tsx, packages/plasma-web/src/components/Calendar/CalendarDays.tsx, packages/plasma-web/src/components/Calendar/hooks/useDays.ts, packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts, packages/plasma-web/src/components/Calendar/types.ts
Для навигации только по доступным дням необходимо использовать комбинацию клавиш Shift + Arrow  Left\Right\Up\Down
Было: 
- Клавиатурная навигация игнорировала **disabled date**, а так же ограничения по мин/макс значениям. 
Стало: 
- Навигация с помощью комбинации клавиш Shift + Arrow  Left\Right\Up\Down идет **только** по доступным дням
- Клавиатурная навигация не может выйти за пределы ограничения по мин/макс значениям. 
--------------------------
[colors--canary.273.4055599429.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.273.4055599429.xml)  
[color_metro_ios-swift--canary.273.4055599429.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.2 …
=> feat(plasma-web): navigate by Shift + Arrow Left\Right\Up\Down

packages/plasma-tokens/lib/generator/formatters/typoKotlin.ts, packages/plasma-tokens/lib/generator/formatters/typoReactNative.ts, packages/plasma-typo/src/archetypes/sbermarket.ts
[colors--canary.305.4053370533.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.305.4053370533.xml)  
[color_metro_ios-swift--canary.305.4053370533.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.305.4053370533.swift)  
[color_metro_kotlin--canary.305.4053370533.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.305.4053370533.kt)  
[color_metro_react-native--canary.305.4053370533.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.305.4053370533.ts)  
[color_sbermarket_ios-swift--canary.305.4053370533.swift](https://github.com/ …
=> fix(plasma-tokens): Update token template for Kotlin and React-Native platforms

packages/plasma-b2c/.storybook/preview.js, packages/plasma-ui/.storybook/preview.js, packages/plasma-web/.storybook/preview.js
Необходимо включить возможно показывать код того как использовать компонент. 
Было: 
Стало: 
[colors--canary.308.4071033401.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.308.4071033401.xml)  
[color_metro_ios-swift--canary.308.4071033401.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.308.4071033401.swift)  
[color_metro_kotlin--canary.308.4071033401.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.308.4071033401.kt)  
[color_metro_react-native--canary.308.4071033401.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.308.4 …
=> chore(plasma-web/ui/b2c): Enable preview source code

packages/plasma-b2c/package.json, packages/plasma-core/package.json, packages/plasma-icons/package.json, packages/plasma-temple/package.json, packages/plasma-ui/package.json, packages/plasma-web/package.json
[colors--canary.309.4073026661.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.309.4073026661.xml)  
[color_metro_ios-swift--canary.309.4073026661.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.309.4073026661.swift)  
[color_metro_kotlin--canary.309.4073026661.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.309.4073026661.kt)  
[color_metro_react-native--canary.309.4073026661.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.309.4073026661.ts)  
[color_sbermarket_ios-swift--canary.309.4073026661.swift](https://github.com/ …
=> feat(plasma-*): Remove source maps from bundles

website/plasma-theme-builder/src/api/getEnv.ts, website/plasma-theme-builder/src/api/getFilesSource.ts, website/plasma-theme-builder/src/api/githubAPIMethods.ts, website/plasma-theme-builder/src/api/index.ts, website/plasma-theme-builder/src/components/App.tsx, website/plasma-theme-builder/src/components/Main/Main.tsx, website/plasma-theme-builder/src/components/PullRequest/PullRequest.tsx, website/plasma-theme-builder/src/components/Theme/Theme.tsx, website/plasma-theme-builder/src/components/hooks/useRunGithubPRProcess.ts, website/plasma-theme-builder/src/components/types.ts, website/plasma-theme-builder/src/components/utils.ts
В данном PR реализовал возможность создания пул-реквеста с помощью GitHub API из веб-интрефейса theme-builder'а
[colors--canary.303.4082766000.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.303.4082766000.xml)  
[color_metro_ios-swift--canary.303.4082766000.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.303.4082766000.swift)  
[color_metro_kotlin--canary.303.4082766000.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.303.4082766000.kt)  
[color_metro_react-native--canary.303.4082766000.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-n …
=> feat: Add create possibility pull request for theme builder by GitHub

packages/plasma-b2c/src/components/Button/Button.stories.tsx, packages/plasma-web/src/components/Button/Button.stories.tsx
Изменить значение по-умолчанию для свойства `outlined` в примерах песочницы, было **false** стало **true**. 
Нужно что бы в примерах сразу было видно взаимодействие с кнопкой через клавишу `Tab`.        
[colors--canary.313.4112887659.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.313.4112887659.xml)  
[color_metro_ios-swift--canary.313.4112887659.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.313.4112887659.swift)  
[color_metro_kotlin--canary.313.4112887659.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.313.4112887659.kt) …
=> fix(plasma-web/b2c): [Button] Change default  outlined prop in storybook

.github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/examples.yml, .github/workflows/performance-test-main.yml, .github/workflows/theme-builder-pr.yml, .github/workflows/theme-builder.yml, .github/workflows/versionate-docs.yml
[colors--canary.320.4123273032.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.320.4123273032.xml)  
[color_metro_ios-swift--canary.320.4123273032.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.320.4123273032.swift)  
[color_metro_kotlin--canary.320.4123273032.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.320.4123273032.kt)  
[color_metro_react-native--canary.320.4123273032.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.320.4123273032.ts)  
[color_sbermarket_ios-swift--canary.320.4123273032.swift](https://github.com/ …
=> ci: remove sync action

.babelrc.js, package.json, packages/plasma-b2c/.npmignore, packages/plasma-b2c/package.json, packages/plasma-core/.npmignore, packages/plasma-core/package.json, packages/plasma-temple/.npmignore, packages/plasma-temple/package.json, packages/plasma-ui/.npmignore, packages/plasma-ui/package.json, packages/plasma-web/.npmignore, packages/plasma-web/package.json
Разница в размере между тарниками из актуальных версий пакетов и канареек. Различие в несколько байт скорее всего обусловлено изменением исходного кода package.json
[colors--canary.322.4125774581.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.322.4125774581.xml)  
[color_metro_ios-swift--canary.322.4125774581.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.322.4125774581.swift)  
[color_metro_kotlin--canary.322.4125774581.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.322.4125774581.kt)  
[color_metro_react-native--canary.322.4125774581.ts](https://github.com/salute-developers/plasm …
=> feat(plasma-*): Add .npmignore and remove file field for test files

.github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/examples.yml, .github/workflows/performance-test-main.yml, .github/workflows/theme-builder-pr.yml, .github/workflows/theme-builder.yml, .github/workflows/versionate-docs.yml, website/plasma-ui-docs/docs/components/Cell.mdx, website/plasma-ui-docs/docs/components/Header.mdx, website/plasma-ui-docs/docs/components/Image.mdx, website/plasma-web-docs/docs/components/Image.mdx
[colors--canary.327.4144282009.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.327.4144282009.xml)  
[color_metro_ios-swift--canary.327.4144282009.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.327.4144282009.swift)  
[color_metro_kotlin--canary.327.4144282009.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.327.4144282009.kt)  
[color_metro_react-native--canary.327.4144282009.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.327.4144282009.ts)  
[color_sbermarket_ios-swift--canary.327.4144282009.swift](https://github.com/ …
=> docs(plasma-ui, plasma-web): fix images in docs

.github/workflows/clean-pr-documentation.yml, .github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/examples.yml, .github/workflows/theme-builder-pr.yml, .github/workflows/theme-builder.yml, .github/workflows/versionate-docs.yml
Убирается взаимодействие со старым сервером в джобах.
[colors--canary.331.4160327745.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.331.4160327745.xml)  
[color_metro_ios-swift--canary.331.4160327745.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.331.4160327745.swift)  
[color_metro_kotlin--canary.331.4160327745.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.331.4160327745.kt)  
[color_metro_react-native--canary.331.4160327745.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.331.4160327745.ts) …
=> ci: remove old server usage

.github/workflows/performance-test-pr.yml, package-lock.json, package.json, scripts/perftool-send-report.js
[colors--canary.323.4145566448.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.323.4145566448.xml)  
[color_metro_ios-swift--canary.323.4145566448.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.323.4145566448.swift)  
[color_metro_kotlin--canary.323.4145566448.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.323.4145566448.kt)  
[color_metro_react-native--canary.323.4145566448.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.323.4145566448.ts)  
[color_sbermarket_ios-swift--canary.323.4145566448.swift](https://github.com/ …
=> feat(plasma): send perftool report

actions/platform-test/tsconfig.json, actions/versionate-docs/tsconfig.json, packages/plasma-b2c/tsconfig.json, packages/plasma-basic-template/template/tsconfig.json, packages/plasma-core/tsconfig.json, packages/plasma-icons/tsconfig.json, packages/plasma-temple/tsconfig.json, packages/plasma-tokens-b2b/tsconfig.json, packages/plasma-tokens-b2c/tsconfig.json, packages/plasma-tokens-web/tsconfig.json, packages/plasma-tokens/tsconfig.json, packages/plasma-typo/tsconfig.json, packages/plasma-ui/tsconfig.json, packages/plasma-web/tsconfig.json, utils/plasma-docs-ui/tsconfig.json, utils/plasma-sb-utils/tsconfig.json, utils/plasma-tokens-utils/tsconfig.json, utils/showcase/tsconfig.json
[colors--canary.326.4171358468.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.326.4171358468.xml)  
[color_metro_ios-swift--canary.326.4171358468.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.326.4171358468.swift)  
[color_metro_kotlin--canary.326.4171358468.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.326.4171358468.kt)  
[color_metro_react-native--canary.326.4171358468.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.326.4171358468.ts)  
[color_sbermarket_ios-swift--canary.326.4171358468.swift](https://github.com/ …
=> feat(plasma-*): Remove declarationMap from tsconfig.json

packages/plasma-tokens/.gitignore, packages/plasma-tokens/generate.ts, packages/plasma-tokens/package.json, utils/plasma-tokens-utils/src/generation.ts, website/plasma-ui-docs/docs/design/tokens.mdx
[colors--canary.343.4182782211.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.343.4182782211.xml)  
[color_metro_ios-swift--canary.343.4182782211.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.343.4182782211.swift)  
[color_metro_kotlin--canary.343.4182782211.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.343.4182782211.kt)  
[color_metro_react-native--canary.343.4182782211.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.343.4182782211.ts)  
[color_sbermarket_ios-swift--canary.343.4182782211.swift](https://github.com/ …
=> feat(plasma-tokens,plasma-tokens-utils): Add generating brand for each themes

packages/plasma-hope/package.json
[colors--canary.346.4185045509.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.346.4185045509.xml)  
[color_metro_ios-swift--canary.346.4185045509.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.346.4185045509.swift)  
[color_metro_kotlin--canary.346.4185045509.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.346.4185045509.kt)  
[color_metro_react-native--canary.346.4185045509.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.346.4185045509.ts)  
[color_sbermarket_ios-swift--canary.346.4185045509.swift](https://github.com/ …
=> fix(plasma-hope): publish pkg

package-lock.json
[colors--canary.351.4193555506.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.351.4193555506.xml)  
[color_metro_ios-swift--canary.351.4193555506.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.351.4193555506.swift)  
[color_metro_kotlin--canary.351.4193555506.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.351.4193555506.kt)  
[color_metro_react-native--canary.351.4193555506.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.351.4193555506.ts)  
[color_sbermarket_ios-swift--canary.351.4193555506.swift](https://github.com/ …
=> build: remove obscure versions

website/plasma-theme-builder/src/components/hooks/useGithubAuth.tsx
[colors--canary.345.4185367320.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.345.4185367320.xml)  
[color_metro_ios-swift--canary.345.4185367320.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.345.4185367320.swift)  
[color_metro_kotlin--canary.345.4185367320.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.345.4185367320.kt)  
[color_metro_react-native--canary.345.4185367320.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.345.4185367320.ts)  
[color_sbermarket_ios-swift--canary.345.4185367320.swift](https://github.com/ …
=> fix(plasma-theme-builder): Update redirectURI for auth request

packages/plasma-tokens/data/themes/sberHealth.json
[colors--canary.359.4221776342.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.359.4221776342.xml)  
[color_metro_ios-swift--canary.359.4221776342.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.359.4221776342.swift)  
[color_metro_kotlin--canary.359.4221776342.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.359.4221776342.kt)  
[color_metro_react-native--canary.359.4221776342.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.359.4221776342.ts)  
[color_sberHealth_ios-swift--canary.359.4221776342.swift](https://github.com/ …
=> fix(plasma-tokens): Fix sberHealth scheme in json

packages/plasma-tokens/lib/themeBuilder/types.ts
[colors--canary.361.4223376512.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.361.4223376512.xml)  
[color_metro_ios-swift--canary.361.4223376512.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.361.4223376512.swift)  
[color_metro_kotlin--canary.361.4223376512.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.361.4223376512.kt)  
[color_metro_react-native--canary.361.4223376512.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.361.4223376512.ts)  
[color_sberHealth_ios-swift--canary.361.4223376512.swift](https://github.com/ …
=> feat(plasma-tokens): Add new name for TokenGroup

packages/plasma-b2c/src/components/Tabs/TabItem.tsx
В TabItem для `{ theme: { lowPerformance } }` нужно добавить типизацию иначе в #360 из-за изменения coverage **падает** pipeline typescript-coverage    
[colors--canary.366.4240164624.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.366.4240164624.xml)  
[color_metro_ios-swift--canary.366.4240164624.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.366.4240164624.swift)  
[color_metro_kotlin--canary.366.4240164624.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.366.4240164624.kt)  
[color_metro_react-native--canary.366.4240164624.ts](https://github.com/salute-developers/plasma/releases/d …
=> feat(plasma-b2c): [TabItem] add partial typing for theme

examples/demo-canvas-app/next-env.d.ts, examples/demo-canvas-app/package-lock.json, examples/demo-canvas-app/package.json, examples/demo-canvas-app/pages/_app.tsx, website/plasma-website/components/roster/Header.tsx, website/plasma-website/components/roster/Panel.tsx, website/plasma-website/next-env.d.ts, website/plasma-website/package-lock.json, website/plasma-website/package.json, website/plasma-website/pages/_document.tsx, website/plasma-website/pages/icons.tsx, website/plasma-website/store/index.tsx
[colors--canary.371.4290853494.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.371.4290853494.xml)  
[color_metro_ios-swift--canary.371.4290853494.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.371.4290853494.swift)  
[color_metro_kotlin--canary.371.4290853494.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.371.4290853494.kt)  
[color_metro_react-native--canary.371.4290853494.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.371.4290853494.ts)  
[color_sberHealth_ios-swift--canary.371.4290853494.swift](https://github.com/ …
=> bump next.js to 12.x

packages/plasma-hope/jest.config.js, packages/plasma-hope/package-lock.json, packages/plasma-hope/package.json
Добавлен **Jest** и все что с ним связанно, для запуска **unit-test**.    
Мотивация: 
**unit-test** из **plasma-b2c** переехали в  **plasma-hope**. 
[colors--canary.373.4301295867.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.373.4301295867.xml)  
[color_metro_ios-swift--canary.373.4301295867.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.373.4301295867.swift)  
[color_metro_kotlin--canary.373.4301295867.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.373.4301295867.kt)  
[color_metro_react-native--canary.373.4301295867.ts](https://github.com/salute-developers/plasma/releases/down …
=> feat(plasma-hope): processing unit tests hope

website/plasma-web-docs/docs/components/Modal.mdx
[colors--canary.377.4313267786.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.377.4313267786.xml)  
[color_metro_ios-swift--canary.377.4313267786.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.377.4313267786.swift)  
[color_metro_kotlin--canary.377.4313267786.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.377.4313267786.kt)  
[color_metro_react-native--canary.377.4313267786.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.377.4313267786.ts)  
[color_sberHealth_ios-swift--canary.377.4313267786.swift](https://github.com/ …
=> docs(plasma-web): Modal: add onClose to example

website/plasma-web-docs/docs/components/AudioPlayer.mdx, website/plasma-web-docs/docs/components/Editable.mdx, website/plasma-web-docs/docs/components/ElasticGrid.mdx, website/plasma-web-docs/docs/components/PreviewGallery.mdx, website/plasma-web-docs/docs/components/Slider.mdx, website/plasma-web-docs/docs/components/Upload.mdx
Компоненты 
- AudioPlayer
- Editable
- ElasticGrid
- PreviewGallery
- Upload
- Slider
были перенесены в **plasma-hope** и стали доступны в **plasma-web**. 
Теперь по этим компонентам так же добавленна соответствующая [документация](https://plasma.sberdevices.ru/web/).     
[colors--canary.379.4342318097.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.379.4342318097.xml)  
[color_metro_ios-swift--canary.379.4342318097.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.379.4342318097.swift)  
[color_metro_kotlin--canary.379.4342318097.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.379.434 …
=> feat(plasma-web-docs): Extend docs 

packages/plasma-tokens/generate.ts, utils/plasma-tokens-utils/src/functions.ts, utils/plasma-tokens-utils/src/generation.ts
Убрал префикс plasma-colors из css переменных у тем, которые генерируются в папку brands. Теперь есть возможность переключать глобальную тему и в зависимости от этого изменятся значения css переменных:
Например:
https://codesandbox.io/s/plasma-web-example-forked-68qegv?file=/src/App.js:161-175
[colors--canary.391.4346496474.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.391.4346496474.xml)  
[color_metro_ios-swift--canary.391.4346496474.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.391.4346496474.swift)  
[color_metro_kotlin--canary.391.4346496474.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_k …
=> fix(plasma-tokens): Remove `plasma-colors` prefix from brand themes

.github/workflows/cypress-ct-17.yml, .github/workflows/cypress-ct.yml, .github/workflows/typescript-coverage.yml
Сохраняем артефакты **только** если pipeline упал. 
[Документация](https://docs.github.com/en/actions/learn-github-actions/expressions#failure) 
Было: артефакты сохранялись **всегда**  
Стало: 
----------------
------------
___________
[colors--canary.404.4403709278.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.404.4403709278.xml)  
[color_metro_ios-swift--canary.404.4403709278.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.404.4403709278.swift)  
[color_metro_kotlin--canary.404.4403709278.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.404.4403709278.kt) …
=> ci: Save artifacts if previous step of a job fails

packages/plasma-hope/api/plasma-hope.api.md, packages/plasma-hope/src/components/Dropdown/withAssistiveDropdown.tsx
Необходимо было изменить/добавить метод `withAssistiveDropdown` что бы он могу вернуть `ForwardRef` и можно было бы прокинуть ref.
Было: 
```
Function components cannot have refs. Did you mean to use React.forwardRef()
```      
Стало: 
[colors--canary.393.4352994230.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.393.4352994230.xml)  
[color_metro_ios-swift--canary.393.4352994230.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.393.4352994230.swift)  
[color_metro_kotlin--canary.393.4352994230.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.393.4352994230.kt) …
=> fix(plasma-hope): change withAssistiveDropdown return type to ForwardRef

packages/plasma-core/api/plasma-core.api.md, packages/plasma-core/src/components/Slider/Double.tsx, packages/plasma-core/src/components/Slider/Single.tsx, packages/plasma-core/src/components/Slider/Slider.tsx, packages/plasma-core/src/components/Slider/SliderBase.tsx, packages/plasma-core/src/components/Slider/index.ts, packages/plasma-core/src/components/Slider/types.ts
Часть внутренного API для `Slider` была доступна во вне. 
Было:
Стало: 
Ни в документации, ни в песочнице, ни в `props` об этих типах нет упоминания.   
[colors--canary.398.4373549573.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.398.4373549573.xml)  
[color_metro_ios-swift--canary.398.4373549573.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.398.4373549573.swift)  
[color_metro_kotlin--canary.398.4373549573.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.398.4373549573.kt)  
[color_metro_react-native--canary.398.4373549573.ts](https://github.com/salute-developers/plasma/releases/d …
=> fix(plasma-core): Rework slider types

packages/plasma-colors/package.json
Чиним старую проблему: в plasma-colors не попадали файлы в тарник
БЫЛО:
```sh
notice 📦  @salutejs/plasma-colors@0.4.0
notice === Tarball Contents === 
notice 725B dist/index.js
notice 835B package.json 
notice === Tarball Details === 
notice name:          @salutejs/plasma-colors                 
notice version:       0.4.0                                   
notice filename:      salutejs-plasma-colors-0.4.0.tgz        
notice package size:  830 B                                   
notice unpacked size: 1.6 kB                                  
notice shasum:        dd5b1adb1a9418016ea2c6e6372c82dbc7e63c92
notice integrity:     sha512-KYApdAoe7Z5Sw[...]Zcg74saell+Nw==
notice total files:   2  
```
СТАЛО:
```
notice 📦  @salutejs/plasma-colors@0.4.1-canary.413.4428277903.0
notice === Tarball …
```
=> fix(plasma-colors): empty npm tar

packages/plasma-b2c/package-lock.json, packages/plasma-core/package-lock.json, packages/plasma-hope/package-lock.json, packages/plasma-icons/package-lock.json, packages/plasma-temple/package-lock.json, packages/plasma-tokens-b2b/package-lock.json, packages/plasma-tokens-b2c/package-lock.json, packages/plasma-tokens-web/package-lock.json, packages/plasma-tokens/package-lock.json, packages/plasma-ui/package-lock.json, packages/plasma-web/package-lock.json, utils/plasma-cy-utils/package-lock.json, utils/plasma-sb-utils/package-lock.json, utils/plasma-tokens-android/package-lock.json, utils/plasma-tokens-ios-swift/package-lock.json
Обновляем package-locks в ручном режиме пока не будут отключены git-hooks на push в мастере
=> build: update package-locks

packages/plasma-b2c/src/components/Card/Card.stories.tsx
[colors--canary.353.4194499292.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.353.4194499292.xml)  
[color_metro_ios-swift--canary.353.4194499292.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.353.4194499292.swift)  
[color_metro_kotlin--canary.353.4194499292.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.353.4194499292.kt)  
[color_metro_react-native--canary.353.4194499292.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.353.4194499292.ts)  
[color_sbermarket_ios-swift--canary.353.4194499292.swift](https://github.com/ …
=> chore(plasma-b2c): remove unused variable

packages/plasma-temple/package-lock.json, packages/plasma-temple/package.json
[colors--canary.422.4454098417.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.422.4454098417.xml)  
[color_metro_ios-swift--canary.422.4454098417.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.422.4454098417.swift)  
[color_metro_kotlin--canary.422.4454098417.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.422.4454098417.kt)  
[color_metro_react-native--canary.422.4454098417.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.422.4454098417.ts)  
[color_sberHealth_ios-swift--canary.422.4454098417.swift](https://github.com/ …
=> build(plasma-temple): remove unused dep

.github/workflows/typescript-coverage.yml
[colors--canary.423.4459820013.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.423.4459820013.xml)  
[color_metro_ios-swift--canary.423.4459820013.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.423.4459820013.swift)  
[color_metro_kotlin--canary.423.4459820013.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.423.4459820013.kt)  
[color_metro_react-native--canary.423.4459820013.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.423.4459820013.ts)  
[color_sberHealth_ios-swift--canary.423.4459820013.swift](https://github.com/ …
=> ci: remove duplicate jobs in mq

website/plasma-temple-docs/package-lock.json, website/plasma-temple-docs/package.json, website/plasma-ui-docs/package-lock.json, website/plasma-ui-docs/package.json, website/plasma-web-docs/package-lock.json, website/plasma-web-docs/package.json
[colors--canary.424.4460410092.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.424.4460410092.xml)  
[color_metro_ios-swift--canary.424.4460410092.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.424.4460410092.swift)  
[color_metro_kotlin--canary.424.4460410092.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.424.4460410092.kt)  
[color_metro_react-native--canary.424.4460410092.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.424.4460410092.ts)  
[color_sberHealth_ios-swift--canary.424.4460410092.swift](https://github.com/ …
=> chore(deps): remove dependency @types/react-helmet

packages/plasma-b2c/.gitignore, packages/plasma-temple/.gitignore, packages/plasma-temple/package-lock.json, packages/plasma-temple/package.json, packages/plasma-ui/.gitignore, packages/plasma-ui/.storybook/main.js, packages/plasma-ui/package-lock.json, packages/plasma-ui/package.json, packages/plasma-web/.gitignore, packages/plasma-web/package.json
Необходимо было удалить лишние npm-скрипты из storybook и зависимости с ними связанные, т.к. вся основная документация у нас лежит в https://plasma.sberdevices.ru/
[colors--canary.420.4466862200.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.420.4466862200.xml)  
[color_metro_ios-swift--canary.420.4466862200.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.420.4466862200.swift)  
[color_metro_kotlin--canary.420.4466862200.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.420.4466862200.kt)  
[color_metro_react-native--canary.420.4466862200.ts](https://github.com/salute-developers/plasma …
=> fix(plasma-*): Remove storybook docs

package-lock.json, package.json
Запланированный переход на **latest** версию `Lerna` - **6.5.1**
[colors--canary.432.4479919276.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.432.4479919276.xml)  
[color_metro_ios-swift--canary.432.4479919276.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.432.4479919276.swift)  
[color_metro_kotlin--canary.432.4479919276.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.432.4479919276.kt)  
[color_metro_react-native--canary.432.4479919276.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.432.4479919276.ts) …
=> build: bump lerna version to 6.x

packages/plasma-ui/src/components/Sheet/Sheet.stories.tsx
[colors--canary.433.4477357648.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.433.4477357648.xml)  
[color_metro_ios-swift--canary.433.4477357648.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.433.4477357648.swift)  
[color_metro_kotlin--canary.433.4477357648.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.433.4477357648.kt)  
[color_metro_react-native--canary.433.4477357648.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.433.4477357648.ts)  
[color_sberHealth_ios-swift--canary.433.4477357648.swift](https://github.com/ …
=> chore(plasma-ui): Sheet: fix storybook viewport

website/plasma-website/next.config.js, website/plasma-website/pages/index.tsx
Прокинул в сам basePath дополнительный путь для главной страницы документации, чтобы корректно забирались файлы в pr версиях доки
[colors--canary.439.4510440418.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.439.4510440418.xml)  
[color_metro_ios-swift--canary.439.4510440418.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.439.4510440418.swift)  
[color_metro_kotlin--canary.439.4510440418.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.439.4510440418.kt)  
[color_metro_react-native--canary.439.4510440418.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/c …
=> docs: fix pr base path

packages/plasma-icons/src/Icon.assets/Menu.tsx, packages/plasma-icons/src/Icon.tsx, packages/plasma-icons/src/Icons/IconMenu.tsx, packages/plasma-icons/src/index.ts
Необходимо добавить иконку "бургер" меню.  
[colors--canary.448.4541858589.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.448.4541858589.xml)  
[color_metro_ios-swift--canary.448.4541858589.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.448.4541858589.swift)  
[color_metro_kotlin--canary.448.4541858589.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.448.4541858589.kt)  
[color_metro_react-native--canary.448.4541858589.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.448.4541858589.ts) …
=> feat(plasma-icons): add "Menu" icon

packages/plasma-temple/src/components/HeroSlider/HeroSlider@common.tsx, packages/plasma-temple/src/components/HeroSlider/types.ts
Поправил getImageProps
[colors--canary.451.4543810628.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.451.4543810628.xml)  
[color_metro_ios-swift--canary.451.4543810628.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.451.4543810628.swift)  
[color_metro_kotlin--canary.451.4543810628.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.451.4543810628.kt)  
[color_metro_react-native--canary.451.4543810628.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.451.4543810628.ts) …
=> feat(plasma-temple): update getImageProps slider args

packages/plasma-tokens/data/themes/sbermarket_business.json, packages/plasma-tokens/data/themes/sbermarket_metro.json, packages/plasma-tokens/data/themes/sbermarket_selgros.json, packages/plasma-tokens/data/themes/sbermarket_vinlab.json, packages/plasma-tokens/lib/generator/formatters/colorIosSwift.ts
[colors--canary.459.4574698184.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.459.4574698184.xml)  
[color_sberHealth_ios-swift--canary.459.4574698184.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.459.4574698184.swift)  
[color_sberHealth_kotlin--canary.459.4574698184.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.459.4574698184.kt)  
[color_sberHealth_react-native--canary.459.4574698184.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.459.4574698184.ts) …
=> feat(plasma-tokens): Add `sbermarketVinlab` theme

packages/plasma-b2c/api/plasma-b2c.api.md, packages/plasma-b2c/src/components/Button/Button.tsx, packages/plasma-b2c/src/components/Grid/Container.tsx, packages/plasma-b2c/src/components/TextArea/TextArea.tsx, packages/plasma-b2c/src/components/TextField/TextField.tsx, packages/plasma-hope/api/plasma-hope.api.md, packages/plasma-hope/src/components/Button/Button.tsx, packages/plasma-hope/src/components/Button/types.ts, packages/plasma-hope/src/components/Grid/Container.tsx, packages/plasma-hope/src/components/Grid/types.ts, packages/plasma-hope/src/components/Grid/views/b2c/Container.tsx, packages/plasma-hope/src/components/Grid/views/b2c/ContainerB2C.tsx, packages/plasma-hope/src/components/Grid/views/web/ContainerWeb.tsx, packages/plasma-hope/src/components/Modal/ModalView.tsx, packages/plasma-hope/src/components/TextArea/TextArea.tsx, packages/plasma-hope/src/components/TextArea/types.ts, packages/plasma-hope/src/components/TextField/TextField.tsx, packages/plasma-hope/src/components/TextField/types.ts, packages/plasma-web/api/plasma-web.api.md, packages/plasma-web/src/components/Button/Button.tsx, packages/plasma-web/src/components/Grid/Container.tsx, packages/plasma-web/src/components/TextArea/TextArea.tsx, packages/plasma-web/src/components/TextField/TextField.tsx
[colors--canary.457.4563647590.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.457.4563647590.xml)  
[color_metro_ios-swift--canary.457.4563647590.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_ios-swift--canary.457.4563647590.swift)  
[color_metro_kotlin--canary.457.4563647590.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_kotlin--canary.457.4563647590.kt)  
[color_metro_react-native--canary.457.4563647590.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_metro_react-native--canary.457.4563647590.ts)  
[color_sberHealth_ios-swift--canary.457.4563647590.swift](https://github.com/ …
=> refactor(plasma-hope,plasma-web,plama-b2c): Update `TextArea`, `TextField`, `Button` and `Container` components

packages/plasma-hope/src/components/Carousel/Carousel.tsx, packages/plasma-hope/src/components/Carousel/hooks.tsx
Добавлена возможность прокрутки `Carousel` с помощью мышки
[colors--canary.476.4686853378.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.476.4686853378.xml)  
[color_sberHealth_ios-swift--canary.476.4686853378.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.476.4686853378.swift)  
[color_sberHealth_kotlin--canary.476.4686853378.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.476.4686853378.kt)  
[color_sberHealth_react-native--canary.476.4686853378.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.476.46868 …
=> feat(plasma-hope): draggable scroll in carousel

packages/plasma-ui/src/components/Sheet/Sheet.stories.tsx, packages/plasma-ui/src/components/Sheet/Sheet.tsx, packages/plasma-ui/src/components/Sheet/useSheetSwipe.ts
Добавил возможность закрытия компонента `Sheet` по свайпу на всю высоту контента:
https://user-images.githubusercontent.com/26903236/231776474-f6c87b2c-9a61-4cac-8b1d-57d2e08291a8.mov
Также, если компонент имеет скролл, то закрыть его можно будет либо в самом начале скрола, либо по горизонтальной плашке:
https://user-images.githubusercontent.com/26903236/231776550-9673da53-fa54-4923-b416-fef719c0be9b.mov
[colors--canary.482.4752482064.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/colors--canary.482.4752482064.xml)  
[color_sberHealth_ios-swift--canary.482.4752482064.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.482.4752482064.swift) …
=> feat(plasma-ui): Add swipe for whole sheet in `Sheet` component

website/plasma-web-docs/package.json
[color_sberHealth_ios-swift--canary.502.4891530405.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.502.4891530405.swift)  
[color_sberHealth_kotlin--canary.502.4891530405.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.502.4891530405.kt)  
[color_sberHealth_react-native--canary.502.4891530405.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.502.4891530405.ts)  
[color_sbermarket_business_ios-swift--canary.502.4891530405.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.502.48915 …
=> docs(plasma-web-docs): fix CodeSandbox import

packages/plasma-temple/src/components/AssistantProvider/AssistantContext.ts
[color_sberHealth_ios-swift--canary.503.4935777797.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.503.4935777797.swift)  
[color_sberHealth_kotlin--canary.503.4935777797.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.503.4935777797.kt)  
[color_sberHealth_react-native--canary.503.4935777797.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.503.4935777797.ts)  
[color_sbermarket_business_ios-swift--canary.503.4935777797.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.503.49357 …
=> fix(plasma-temple): create assistant context

.github/workflows/clean-pr-documentation.yml, .github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/examples.yml, .github/workflows/performance-test.yml, .github/workflows/release.yml, .github/workflows/tests-17.yml, .github/workflows/tests.yml, .github/workflows/theme-builder-pr.yml, .github/workflows/theme-builder.yml, .github/workflows/versionate-docs.yml, package.json
Настроил github actions на ветку `dev`
perfomance тесты пришлось дублировать
[color_sberHealth_ios-swift--canary.521.5056692110.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.521.5056692110.swift)  
[color_sberHealth_kotlin--canary.521.5056692110.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.521.5056692110.kt)  
[color_sberHealth_react-native--canary.521.5056692110.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.521.5056692110.ts)  
[color_sbermarket_business_ios-swift--canary.521.5056692110.swift](https://github.com/salute-developers/plasma/releases …
=> ci: prepare actions for dev branch

cypress/webpack.config.js, package-lock.json, package.json, packages/plasma-core/src/components/Skeleton/Skeleton.component-test.tsx, packages/plasma-core/src/components/Spinner/Spinner.component-test.tsx, packages/plasma-core/src/components/Toast/ToastBase.component-test.tsx
[color_sberHealth_ios-swift--canary.534.5133965229.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.534.5133965229.swift)  
[color_sberHealth_kotlin--canary.534.5133965229.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.534.5133965229.kt)  
[color_sberHealth_react-native--canary.534.5133965229.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.534.5133965229.ts)  
[color_sbermarket_business_ios-swift--canary.534.5133965229.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.534.51339 …
=> ci: fix lerna publish

package.json
Плановый переход на более новую версию **npm**.
Меняем настройки, что бы CI workflow работали корректно.  
--------
[color_sberHealth_ios-swift--canary.522.5067667684.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.522.5067667684.swift)  
[color_sberHealth_kotlin--canary.522.5067667684.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.522.5067667684.kt)  
[color_sberHealth_react-native--canary.522.5067667684.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.522.5067667684.ts)  
[color_sbermarket_business_ios-swift--canary.522.5067667684.swift](https://githu …
=> chore:(plasma-infra) bump engines npm package.json property 

.github/workflows/cypress-ct-17.yml, .github/workflows/tests-17.yml, packages/plasma-b2c/api/plasma-b2c.api.md, packages/plasma-b2c/tsconfig.json, packages/plasma-temple/tsconfig.json, packages/plasma-ui/tsconfig.json, packages/plasma-web/api/plasma-web.api.md, packages/plasma-web/tsconfig.json
Столкнулись с проблемой, что пользователи наших библиотек не все перешли на React 18. 
В связи с чем возникали проблемы  с типами, например #506 , #498 , #497.  
Поэтому решили добавить соответствующую проверку.  
1) Выполнить в корне проекта 
`npm i --no-audit --no-progress react@17 react-dom@17 @types/react@17.0.40 @types/react-dom --prefix="./packages/plasma-temple"`
2) Убедиться что plasma-ui используется React 18
3) В компоненте `packages/plasma-ui/src/components/Button/ActionButton.tsx` исправить следующее
```ts
export type ActionButtonProps = Omit<ActionButtonBaseProps, 'nonce' | 'onResize' | 'onResizeCapture'>;
``` 
на 
```ts
export type ActionButtonProps = ActionButtonBaseProps;
``` 
4) Выполнить `npx lerna bootstrap --scope="@salutejs/plasma-ui" …
=> ci(plasma-infra): Run react 17 tests with correct types 

utils/plasma-tokens-native/src/generator/formatters/colorIosSwift.ts, utils/plasma-tokens-native/src/generator/transformers/gradientSwift.ts, utils/plasma-tokens-native/src/types.ts, utils/plasma-tokens-utils/package-lock.json, utils/plasma-tokens-utils/package.json, utils/plasma-tokens-utils/src/functions.ts, utils/plasma-tokens-utils/src/generators/generateTokenSet.ts, utils/plasma-tokens-utils/src/types.ts, utils/plasma-tokens-utils/src/utils/objectToCSSVariables.ts
[color_sberHealth_ios-swift--canary.548.5185739481.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_ios-swift--canary.548.5185739481.swift)  
[color_sberHealth_kotlin--canary.548.5185739481.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_kotlin--canary.548.5185739481.kt)  
[color_sberHealth_react-native--canary.548.5185739481.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sberHealth_react-native--canary.548.5185739481.ts)  
[color_sbermarket_business_ios-swift--canary.548.5185739481.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_sbermarket_business_ios-swift--canary.548.51857 …
=> feat(plasma-tokens-native): Add generate complex gradient for iOS

renovate.json
выключил auto rebase веток по мере новых изменений в base бранчах
на данном этапе это должно уменьшить очередь раннеров
=> ci: disable rebase for renovate

.github/processing-scope.js, .github/workflows/change-detection.yml, .github/workflows/cypress.yml
Запускаем тесты **только** тогда когда **есть необходимость.**  
Например, были изменения связанные только с документацией или с тем же CI, и тогда не нужно запускать проверки `cypress` или `performance testing`.    
тесты нужно запустить только для web, b2c 
тесты нужно запустить для **всех** scope: web, temple, ui, b2c
тесты нужно запустить для **всех** scope: web, temple, ui, b2c
тесты нужно запустить для  temple, ui.
Если есть изменения в таких пакетах как `typo, tokens, etc` то нужно запускать тесты для **всех** scope!     
[color_asdk_ios-swift--canary.558.5319593363.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.558.5319593363.swift) …
=> plasma-infra: run workflow by condition [Cypress] [Part 1]

.github/workflows/change-detection.yml, .github/workflows/performance-test-base.yml, .github/workflows/performance-test-pr.yml
Добавляем похожую логику как тут #558 только для  "Performance Testing". 
Логика будет немного другой, этот workflow будет запускаться **только когда есть изменения в компонентах** `plasma-web/b2c/ui/temple`.
--------
То есть, если изменения будут в пакете `plasma-icons`, то данный workflow **не запуститься** в отличие от workflow для cypress , где 
> Если есть изменения в таких пакетах как typo, tokens, icons, etc то нужно запускать тесты для всех scope! 
[color_asdk_ios-swift--canary.566.5354264334.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.566.5354264334.swift)  
[color_asdk_kotlin--canary.566.5354264334.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary …
=> plasma-infra: run workflow by condition [Performance Testing] [Part 2]

.github/workflows/performance-test-base.yml, .github/workflows/performance-test-pr.yml, .github/workflows/typescript-coverage.yml, package.json
Продолжаем ускорять работу workflow.
Используем конкретный список **scope** для **bootstrap**:  `salutejs/plasma-{core,hope,web,b2c,ui,icons}`
ИМХО, так же это позволит стабилизировать время выполнения самой команды **bootstrap** 
Используем флаг `--since` что понять в каких пакетах нужно сделать **bootstrap** 
Время работы workflow теперь варьируется от 1 минуты до 7-8, если во всех пакетах нужно сделать **bootstrap**     
[color_asdk_ios-swift--canary.574.5375317409.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.574.5375317409.swift)  
[color_asdk_kotlin--canary.574.5375317409.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.574.53 …
=> plasma-infra: Improve lerna bootstrap time execution [Part 1]

.github/workflows/cypress-common.yml, .github/workflows/tests.yml, .github/workflows/theme-builder-pr.yml, .github/workflows/theme-builder.yml, package.json
Продолжение #574 
Пропускаем workflow если нет изменений в пакетах - `@salutejs/plasma-{ui,web,b2c,temple}`
Запускаем `px lerna bootstrap` с флагом `--since`
Запускаем с флагом `--since`. Здесь логика работы такая же как и с "Typescript Coverage"  в #574 
Убран лишний шаг связанный с подготовкой репозитория, минус 1-1.30 мин от времени выполнения.
Запускаем **bootstrap** с определенным набором `scope = {b2c, web, core, hope, icons, typo, tokens, cy-utils, ui}` 
Время исполнения  **bootstrap** варьируется в среднем в пределах 5 мин. Конечно бывают выбросы и до 7 мин.         
[color_asdk_ios-swift--canary.575.5376012008.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.575.5376012008.swift) …
=> plasma-infra: Improve lerna bootstrap time execution [Part 2]

.github/workflows/theme-builder-pr.yml, website/plasma-theme-builder/src/api/githubAPIMethods.ts, website/plasma-theme-builder/src/api/index.ts, website/plasma-theme-builder/src/components/App.tsx, website/plasma-theme-builder/src/components/Generator/Generator.tsx, website/plasma-theme-builder/src/components/PullRequest/PullRequest.tsx, website/plasma-theme-builder/src/components/Theme/Theme.tsx, website/plasma-theme-builder/src/components/utils.tsx, website/plasma-theme-builder/src/hooks/useFetchTheme.tsx, website/plasma-theme-builder/src/hooks/useRunGithubPRProcess.ts
Добавлена возможность редактирования темы (в уже существующем pull-request'е) через ThemeBuilder . Для этого необходимо сформировать ссылку вида: 
```
https://plasma.sberdevices.ru/plasma-theme-builder/?theme=<theme_name>&branch=<branch_name>
```
И после подтверждения редактирования, создастся новый коммит.
[color_asdk_ios-swift--canary.571.5378725049.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.571.5378725049.swift)  
[color_asdk_kotlin--canary.571.5378725049.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.571.5378725049.kt)  
[color_asdk_react-native--canary.571.5378725049.ts](https://github.com/salute-developers/plasma/releases …
=> feat(plasma-theme-builder): Add edit existed pr in theme builder

.github/workflows/typescript-coverage.yml, packages/plasma-tokens/data/themes/asdk.json, packages/plasma-tokens/src/brands/asdk/index.ts, packages/plasma-tokens/src/themes/asdk__dark.ts, packages/plasma-tokens/src/themes/asdk__light.ts
В существующую схему `asdk` добавлены значения градиентов для android в формате XML.
[color_asdk_ios-swift--canary.567.5398343479.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.567.5398343479.swift)  
[color_asdk_kotlin--canary.567.5398343479.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.567.5398343479.kt)  
[color_asdk_react-native--canary.567.5398343479.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.567.5398343479.ts)  
[color_asdk_xml--canary.567.5398343479.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_xml--canary.567. …
=> feat(plasma-tokens): Update `asdk` theme with xml

package-lock.json, package.json
Для того что у нас было так  
[Released Plugin](https://github.com/intuit/auto/tree/main/plugins/released)
----------
[color_asdk_ios-swift--canary.580.5409097893.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.580.5409097893.swift)  
[color_asdk_kotlin--canary.580.5409097893.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.580.5409097893.kt)  
[color_asdk_react-native--canary.580.5409097893.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.580.5409097893.ts)  
[color_asdk_xml--canary.580.5409097893.xml](https://github.com/salute-developers/plasma/releases/download/v0.0.0-c …
=> chore: add "@auto-it/released"

.github/processing-scope.js, .github/workflows/change-detection.yml, .github/workflows/documentation-pr.yml, .github/workflows/performance-test-base.yml
Продолжаем ускорять. 
Теперь для этого workflow **высчитываем** набор scope. 
Так же пропускаем шаги с **build** сайта документации и **storybook** для пакета, если нет соответствующего scope.   
Так же теперь для получения списка пакетов где были произведены изменения используем `npx lerna la --json` что бы сразу работать с JSON форматом.     
[color_asdk_ios-swift--canary.577.5452199845.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.577.5452199845.swift)  
[color_asdk_kotlin--canary.577.5452199845.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.577.5452199845.kt)  
[color_asdk_react-native--canary.577.5452199845.ts](https://github …
=> plasma-infra: Improve lerna bootstrap time execution [Part 3]

.github/workflows/cypress-by-cron.yml, .github/workflows/cypress-common.yml, .github/workflows/cypress.yml
Продолжаем ускорять. 
- **Исключили** scope "temple" из общего сценария для  "Cypress" workflow. 
- Вынесли в отдельный набор jobs который запускается **только** когда внесли изменения в пакет "plasma-temple". 
```yml
on:
schedule:
- cron: 0 0 * * SUN
```
- **Добавили** запуск **нового** workflow по расписанию. Теперь каждое воскресение в полночь будет запускаться cypress для всех возможных scope.     
----------
[color_asdk_ios-swift--canary.592.5471391911.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.592.5471391911.swift)  
[color_asdk_kotlin--canary.592.5471391911.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.592.5471391911.kt …
=> plasma-infra: Improve "Cypress" workflow

.github/workflows/cypress-by-cron.yml, .github/workflows/cypress-common.yml, CODEOWNERS
Добавлен флаг `with-artifacts` для "Сypress" workflow. 
Этот флаг позволяет делать override для шага "Save artifacts":
```yml
- name: Save artifacts
if: ${{ failure() || inputs.with-artifacts }}
uses: actions/upload-artifact@v2
with:
name: Test Artifacts
path: /home/runner/work/plasma/plasma/cypress
```
Это понадобилось для "Сypress" проверки по расписанию. 
В этой проверки мы хотим всегда сохранять результат прогона.     
---------
[color_asdk_ios-swift--canary.604.5473901997.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.604.5473901997.swift)  
[color_asdk_kotlin--canary.604.5473901997.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--cana …
=> plasma-infra: Save artifacts always for "Cypress" workflow by cron

website/plasma-theme-builder/public/index.html, website/plasma-theme-builder/src/GlobalStyle.tsx, website/plasma-theme-builder/src/components/Main/Main.tsx
Поправил название платформ, для которых генерируем темы.
Добавил фавиконку для сервиса ThemeBuilder.
Временно убрал функционал автоматического переключения темы сервиса в зависимости от настроек системы.
[color_asdk_ios-swift--canary.608.5493666629.swift](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.608.5493666629.swift)  
[color_asdk_kotlin--canary.608.5493666629.kt](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.608.5493666629.kt)  
[color_asdk_react-native--canary.608.5493666629.ts](https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.608.5493666629.ts) …
=> fix(plasma-theme-builder): Fix platform name and minor refactor

auto-plugins/README.md, auto-plugins/src/index.ts, auto-plugins/src/upload-assets-extend.ts, package-lock.json, package.json
Реализовано расширение плагина `upload-assets`, в которое были добавлены следующие опции:
`headerMessage` - Кастомное сообщение для заголовка в сообщении Pull Request'a.
`filter` - Фильтр для списка ассетов. Выполняет проверку с помощью метода `test` объекта RegEx.
`includeBotPrs` - Добавлять ли сообщение в Pull Requests. По умолчанию `true`.
`group`- Группировать список асссетов. Выполняет метод `exec` объекта RegEx и берет второй результат.
`compact` - Компактный вид сообщений Pull Request'ов . По умолчанию `false`.
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.605.5507511157.swift'>color_asdk_io …
=> feat: Add new options for `upload-assets` plugin for compact and grouped view

.github/workflows/documentation-pr.yml, .github/workflows/tests.yml, .github/workflows/typescript-coverage.yml
Для ряда workflows нужно расширить логику вычисления правильного списка scope:
- Lint
- typescript coverage
- PR Documentation and Storybook  
https://github.com/salute-developers/plasma/actions/runs/5504613930/jobs/10031033007?pr=606
https://github.com/salute-developers/plasma/actions/runs/5504613929/jobs/10031386543?pr=606 
Для workflow "Lint" пришлось сделать таким образом, что ставим все за исключением tokens-*
```
npx lerna bootstrap --ignore @salutejs/plasma-tokens*
``` 
Так как команда lint запускается не через lerna, временно предлагаю оставить такой вариант. 
После того как сделаем запуск lint через lerna снова вернуться к варианту точечного scope.    
[color_asdk_ios-swift--canary.613.5527804231.swift](https://github.com/salute-developers/plas …
=> plasma-infra: Extend logic for computed scope     

.github/workflows/documentation-pr.yml, packages/plasma-ui/src/components/Sheet/Sheet.stories.tsx, packages/plasma-ui/src/components/Sheet/Sheet.tsx, packages/plasma-ui/src/components/Sheet/useSheetSwipe.ts
Исправил поведение компонента `Sheet` для случаев, когда внутри главного контейнера есть ещё дочерние контейнеры, которые имеют скролл.
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.606.5542859479.swift'>color_asdk_ios-swift--canary.606.5542859479.swift</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.606.5542859479.kt'>color_asdk_kotlin--canary.606.5542859479.kt</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.606.5542859479.ts'>color_asdk_react-native-- …
=> fix(plasma-ui): Fix scrollable behavior for `Sheet` component

.github/workflows/theme-builder.yml, website/plasma-theme-builder/package.json
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.622.5553203073.swift'>color_asdk_ios-swift--canary.622.5553203073.swift</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.622.5553203073.kt'>color_asdk_kotlin--canary.622.5553203073.kt</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.622.5553203073.ts'>color_asdk_react-native--canary.622.5553203073.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_xml--ca …
=> fix(plasma-theme-builder): Fix avoid open-ssl

packages/plasma-ui/src/components/Pickers/PickerItem.tsx
Поправлен баг, связанный с неправильной работой скролла на android устройствах. 
Баг появился после удаления проставленной высоты Item https://github.com/salute-developers/plasma/commit/026a61266a5513da129d29e34d43e9abcced25f6
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.619.5573710470.swift'>color_asdk_ios-swift--canary.619.5573710470.swift</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.619.5573710470.kt'>color_asdk_kotlin--canary.619.5573710470.kt</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download …
=> fix(plasma-ui): fix scroll TimePicker on android

.github/workflows/documentation-pr.yml
Добавил условие в workflow `documentation-pr`, которое добавляет зависимость `plasma-tokens-utils`, в случае, если она не приехала с каким-нибудь пакетом
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_ios-swift--canary.632.5680349433.swift'>color_asdk_ios-swift--canary.632.5680349433.swift</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_kotlin--canary.632.5680349433.kt'>color_asdk_kotlin--canary.632.5680349433.kt</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_asdk_react-native--canary.632.5680349433.ts'>color_a …
=> feat: Add condition for `plasma-tokens-utils` in documentation-pr workflow

packages/plasma-ui/src/components/Sheet/useSheetSwipe.ts
Исправлено поведение у компонента `Sheet`, при котором во время скролла вниз и плавного свайпа обратно окно резко закрывалось: 
Решением было добавить плавную анимацию:  
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_ios-swift--canary.635.5712593890.swift'>color_plasma_b2c_ios-swift--canary.635.5712593890.swift</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_kotlin--canary.635.5712593890.kt'>color_plasma_b2c_kotlin--canary.635.5712593890.kt</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_ …
=> fix(plasma-ui): Fix hide behavior in `Sheet` component on slow scroll

.github/workflows/required-primary-checks.yml, packages/plasma-hope/src/components/Button/Button.tsx
Убрали флаг `--since` для **Unit tests**. 
Из-за того, что у нас **не публикуются pre-release tags** команда `lerna bootstrap --since` работает некорректно и собирает предыдущую latest версию пакета.
Принято решение временно убрать флаг `--since`.        
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_ios-swift--canary.639.5737743465.swift'>color_plasma_b2c_ios-swift--canary.639.5737743465.swift</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_plasma_b2c_kotlin--canary.639.5737743465.kt'>color_plasma_b2c_kotlin--canary.639.5737743465.kt</a><br>
<a …
=> plasma-infra: Delete flag `--since` [Unit tests]

.github/workflows/performance-test-pr.yml, package-lock.json, package.json, perftool.config.mts
В этом пр апается версия перфтула, активируется фича перфтула по частичному прогону и фиксится баг с установкой зависимостей при прогоне в базовой ветке (сейчас ни актуальный кэш не достается, ни зависимости заново не устанавливаются).
Протестировано в https://github.com/salute-developers/plasma/pull/647. Сейчас проверка падает, потому что в базовой ветке старая версия
Job - https://github.com/salute-developers/plasma/actions/runs/5814842082/job/15765323689
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_ios-swift--canary.644.5811911919.swift'>color_default_ios-swift--canary.644.5811911919.swift</a><br>
<a …
=> Perftest partial run

packages/plasma-tokens/data/themes/default.json, packages/plasma-tokens/src/brands/index.ts, utils/plasma-tokens-utils/src/types.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceAccentGradientTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentAccentGradientTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentAccentTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentDeepTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentNegativeTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentPositiveTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/controlsSurfacesTokenGetters/getSurfaceTransparentWarningTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/controlsSurfacesTokenGetters/index.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/textIconsTokenGetters/getTextAccentGradientTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/textIconsTokenGetters/getTextTransparentAccentGradientTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/textIconsTokenGetters/getTextTransparentAccentTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/textIconsTokenGetters/getTextTransparentNegativeTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/textIconsTokenGetters/getTextTransparentPositiveTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/textIconsTokenGetters/getTextTransparentWarningTokens.ts, website/plasma-theme-builder/src/builder/themeTokenGetters/textIconsTokenGetters/index.ts, website/plasma-theme-builder/src/components/Generator/Generator.tsx
Актуализирован набор дефолтных токенов:
1. Убран токен: `surfaceTransparentDefault`
2. Добавлен токен `surafeTransparenetDeep`
3. Добавлены токены `surfaceAccent/AccentGradient/Positive/Negative/Wargnin-Transparent`, `textAccent/AccentGradient/Positive/Negative/Wargnin-Transparent`
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_ios-swift--canary.646.5806067353.swift'>color_default_ios-swift--canary.646.5806067353.swift</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_kotlin--canary.646.5806067353.kt'>color_default_kotlin--canary.646.5806067353.kt</a><br> …
=> feat(plasma-tokens-*, plasma-theme-builder): Actualized generate tokens set

utils/plasma-tokens-native/src/generator/formatters/colorReactNative.ts
Удалены `deprecated` цвета и импорты из генерации токенов цвета (`colors`) для платформы `ReactNative`
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_ios-swift--canary.651.5831174505.swift'>color_default_ios-swift--canary.651.5831174505.swift</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_kotlin--canary.651.5831174505.kt'>color_default_kotlin--canary.651.5831174505.kt</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/color_default_react-native--canary.651.5831174505.ts'>color_default_react-native--canary.651.5831 …
=> feat(plasma-tokens-native): Remove deprecated colors tokens from ReactNative

packages/plasma-ui/src/components/Sheet/Sheet.tsx, packages/plasma-ui/src/components/Sheet/useSheetSwipe.ts
Исправлено поведение, при котором шторка при разных свайпах вела себя не корректно:
<br>
<br>
Из-за особенностей работы событий `ontouchmove` и `onscroll` в мобильных устройствах (на android и ios) было принято решение немного изменить логику работы компонента и пользовательское взаимодействие с ним:
<br>
<br>
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.648.5864787255.ts'>borderRadius_default_react-native--canary.648.5864787255.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.648.586478 …
=> fix(plasma-ui): Update behavior scroll in `Sheet` component

packages/plasma-core/src/hooks/useResizeObserver.ts
Добавлен [обработчик requestAnimationFrame](https://github.com/ag-grid/ag-grid/issues/6562#issuecomment-1544758386) для хука `useResizeObserver`, поскольку в некоторых случаях возникала ошибка при использовании компонентов, где используется этот хук (`TextArea`):
```
Error "ResizeObserver loop limit exceeded" 
```
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.659.5888701157.ts'>borderRadius_default_react-native--canary.659.5888701157.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.659.58 …
=> fix(plasma-core): Add requestAnimationFrame for useResizeObserver hook

.github/workflows/cypress-common.yml, codecov.yml
Выключили комментарии в PR от codecove bot. 
Удаление конфигурации, не изменило поведение этой утилиты.     
Поэтому выключим на уровне конфигурации.
#650
=> plasma-infra: Disable code cove

.github/actions/update-package-lock/action.yml, .github/workflows/required-primary-checks.yml, utils/plasma-docs-ui/package-lock.json, utils/plasma-docs-ui/package.json, utils/plasma-tokens-native/package-lock.json, utils/plasma-tokens-native/package.json, website/plasma-theme-builder/package-lock.json, website/plasma-theme-builder/package.json, website/plasma-website/package-lock.json, website/plasma-website/package.json
Исправлена установка зависимостей для приватных пакетов после публикации RC версии. Версии пакета берется из `lerna ls`
=> plasma-infra: Fix manually update deps version in private packages 

.github/actions/update-package-lock/action.yml, utils/plasma-tokens-native/package-lock.json, utils/plasma-tokens-native/package.json, website/plasma-theme-builder/package-lock.json, website/plasma-theme-builder/package.json, website/plasma-website/package-lock.json, website/plasma-website/package.json
используем флаг `--save-exact` при установке зависимостей для приватных пакетов после выпуска RC версии
=> plasma-infra: Install exact version for deps

scripts/perftool-send-report.js
=> Fix perftest metrics sending

.autorc.json, package.json
Исправлена проблема подгрузки assets для pull request.  
Исправили конфигурацию для auto.
Что бы плагин `upload-assets` работал правильно, он должен быть установлен перед остальными плагинами.  
> For canaries to work this plugin must be listed before any other publishing plugin.
https://intuit.github.io/auto/docs/generated/upload-assets
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.695.6168571487.ts'>borderRadius_default_react-native--canary.695.6168571487.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_rea …
=> plasma-infra(auto): Fix upload assets work 

.github/workflows/documentation-pr.yml
Починили отправку в s3 билда главной страницы веб-сайта для пулл-реквестов, из-за которой она не отображалась. Содержимое билда должно было находиться на уровень выше
Было - стало:
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.700.6183499629.ts'>borderRadius_default_react-native--canary.700.6183499629.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.700.6183499629.ts'>borderRadius_plasma_b2c_react-native--canary.700.6183499629.ts</a><br>
<a …
=> ci: fix website main-page in pr

.github/workflows/performance-test-pr.yml, package-lock.json, package.json, scripts/perftool-send-report.js
Обновляет ручку отправки отчетов перфтула. Меняет имена полей, добавляет referrer (PR url)
Тест в https://github.com/salute-developers/plasma/pull/731
=> ci: new endpoint for perftool-send-report

packages/plasma-core/src/components/Button/createButton.tsx
Починили цвет <Spinner /> внутри <Button />
Было
Стало
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.748.6271372613.ts'>borderRadius_default_react-native--canary.748.6271372613.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.748.6271372613.ts'>borderRadius_plasma_b2c_react-native--canary.748.6271372613.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.748.6271372613.ts'>borderRadius_plasma_web_reac …
=> fix(plasma-ui,plasma-web,plasma-b2c): Button Spinner checked color

packages/plasma-b2c/api/plasma-b2c.api.md, packages/plasma-b2c/src/components/PopupBase/PopupBase.stories.tsx, packages/plasma-b2c/src/components/PopupBase/index.ts, packages/plasma-b2c/src/index.ts, packages/plasma-core/api/plasma-core.api.md, packages/plasma-core/src/components/PopupBase/PopupBase.tsx, packages/plasma-core/src/components/PopupBase/PopupBaseContext.tsx, packages/plasma-core/src/components/PopupBase/index.ts, packages/plasma-core/src/index.ts, packages/plasma-hope/api/plasma-hope.api.md, packages/plasma-hope/src/components/PopupBase/index.ts, packages/plasma-hope/src/index.ts, packages/plasma-web/api/plasma-web.api.md, packages/plasma-web/src/components/PopupBase/PopupBase.stories.tsx, packages/plasma-web/src/components/PopupBase/index.ts, packages/plasma-web/src/index.ts
Разработан `Popup`(неблокирующий) - компонент для создания всплывающих окон, которые располагаются поверх остальных элементов на экране, при этом взаимодействие с другими элементами, скроллом и т.п. не блокируется.
Свойства компонента:
- `isOpen: boolean` - Открыто ли окно.
- `frame?: 'document' | React.RefObject<HTMLElement>` - В каком контейнере позиционируется окно(по умолчанию document).
- `placement?: PopupBasePlacement` - позиция на экране.
- `center` - по умолчанию.
- `left, right, top, bottom` и их комбинации.
- `offset?: [number | string, number | string]` - Смещение относительно текущей позиции налево и вверх. 
-  `children?: React.ReactNode` - Содержимое Popup.
- `zIndex: string` -  Значение z-index для Popup.
Текущий API:
```tsx
<StyledButton text="Open" onClick={() => …
```
=> feat(plasma-web, plasma-b2c): PopupBase component

website/plasma-ui-docs/docs/intro.mdx
=> docs: update import deprecated darkSber

packages/plasma-ui/src/components/Sheet/Sheet.tsx
**What/why Changed**
Цвет sheet handler был сделан одинаковым для светлой и темной тем, так как в светлой его было плохо видно
**Было:**
**Стало:**
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.786.6380086139.ts'>borderRadius_default_react-native--canary.786.6380086139.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.786.6380086139.ts'>borderRadius_plasma_b2c_react-native--canary.786.6380086139.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary …
=> fix(plasma-ui): change sheet-handler color

.github/processing-scope.js, .github/workflows/change-detection.yml, .github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml, packages/plasma-new-hope/package.json
Включен storybook для пакета `plasma-new-hope`. 
------
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.790.6404021234.ts'>borderRadius_default_react-native--canary.790.6404021234.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.790.6404021234.ts'>borderRadius_plasma_b2c_react-native--canary.790.6404021234.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.790.6404021234.ts'>borderRadius_plasma_web_rea …
=> plasma-infra: Enable "New hope" storybook

packages/plasma-new-hope/package.json, packages/plasma-new-hope/styled-components/package.json
Hotfix: https://github.com/salute-developers/plasma/pull/796
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.797.6428059703.ts'>borderRadius_default_react-native--canary.797.6428059703.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.797.6428059703.ts'>borderRadius_plasma_b2c_react-native--canary.797.6428059703.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.797.6428059703.ts'>borderRadius_plasma_we …
=> fix(plasma-new-hope): cjs build

packages/plasma-new-hope/package.json
проверочный hotfix
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.799.6429207127.ts'>borderRadius_default_react-native--canary.799.6429207127.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.799.6429207127.ts'>borderRadius_plasma_b2c_react-native--canary.799.6429207127.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.799.6429207127.ts'>borderRadius_plasma_web_react-native--canary.799.6429207127.ts</ …
=> fix(plasma-new-hope): fix typo

packages/plasma-b2c/package-lock.json, packages/plasma-b2c/package.json, packages/plasma-web/package-lock.json, packages/plasma-web/package.json
@salutejs/plasma-tokens-b2c и @salutejs/plasma-tokens-web установлены как обычные dependencies;
@salutejs/plasma-tokens-b2b требуется в plasma-web, так же была поставлена как обычная зависимость, в plasma-b2c нигде не используется, поэтому было удалено
Если поставить библиотеку @salutejs/plasma-web или @salutejs/plasma-b2c в проект next, то при импорте любого компонента появляется ошибка об отсутствии токенов;
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.807.6506039479.ts'>borderRadius_default_react-native--canary.807.6506039479.ts</a><br>
<a …
=> fix(plasma-web/b2c): move tokens from dev deps to deps

.github/workflows/theme-builder-pr.yml, .github/workflows/theme-builder.yml
Обновлены зависимости scope, которые ставятся через lerna bootstrap
Добавление других зависимостей в scope ломают сборку: https://github.com/salute-developers/plasma/issues/255
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.818.6641704892.ts'>borderRadius_default_react-native--canary.818.6641704892.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.818.6641704892.ts'>borderRadius_plasma_b2c_react-native--canary.818.6641704892.ts</a><br>
<a …
=> fix(plasma-theme-builder): Fix authorization modal

utils/plasma-tokens-native/config.ts, utils/plasma-tokens-native/package.json, utils/plasma-tokens-native/src/generator/index.ts, utils/plasma-tokens-native/src/types.ts, utils/plasma-tokens-native/src/utils.ts
Добавлена middleware, которая встраивает в каждый файл с токенами для всех нативных платформ комментарией с версией пакета `plasma-tokens` 
Данный функционал нужен для отслеживания изменения в файлах с генерируемыми токенами
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.820.6652670506.ts'>borderRadius_default_react-native--canary.820.6652670506.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.820.6652670506.ts'>borderRadius_plasma_b2c_react-native--canary.820.6652670506.ts</a><br>
<a …
=> feat(plasma-tokens-native): Add version comment in native tokens for all platfroms

packages/plasma-new-hope/src/index.ts
Добавляет экспорт табов
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.827.6720314138.ts'>borderRadius_default_react-native--canary.827.6720314138.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.827.6720314138.ts'>borderRadius_plasma_b2c_react-native--canary.827.6720314138.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.827.6720314138.ts'>borderRadius_plasma_web_react-native--canary.827.6720314138 …
=> chore(plasma-new-hope): add Tabs export

.editorconfig, .prettierignore, packages/plasma-b2c/package.json, packages/plasma-colors/package.json, packages/plasma-core/package.json, packages/plasma-hope/package.json, packages/plasma-icons/package.json, packages/plasma-new-hope/package.json, packages/plasma-shop-template/package.json, packages/plasma-temple/package.json, packages/plasma-tokens-b2b/package.json, packages/plasma-tokens-b2c/package.json, packages/plasma-tokens-core/package.json, packages/plasma-tokens-web/package.json, packages/plasma-tokens/package.json, packages/plasma-typo/package.json, packages/plasma-ui/package.json, packages/plasma-web/package.json, utils/plasma-cy-utils/package.json, utils/plasma-docs-ui/package.json, utils/plasma-sb-utils/package.json, utils/plasma-tokens-native/package.json, utils/plasma-tokens-utils/package.json, website/plasma-temple-docs/package.json, website/plasma-theme-builder/package.json, website/plasma-ui-docs/package.json, website/plasma-web-docs/package.json, website/plasma-website/package.json
Добавлен:
- `.editorconfig`
- `package.json` в `.prettierignore`  
Что бы локальные настройки IDE форматирования не применялись для файлов проекта. 
Для консистентного форматирования добавлен`.editorconfig` и для всех `package.json` сделано **форматирование** с учетом отступа в **4 пробела**. 
Так же добавлено правило `.prettierignore` для `package.json`, что бы `lintstaged` не применял для него форматирование.   
<h3>⚡ Component performance testing</h3>
**Result:** 🟢 OK
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.837.6807866263.ts'>borderRadius_default_react-native--canary.83 …
=> plasma-infra: Add `.editorconfig` 

.github/workflows/performance-test-base.yml, .github/workflows/performance-test-pr.yml
Plasma-asdk добавлен в скоуп для perftest
=> ci(perftest): add asdk to scope

packages/plasma-asdk/package-lock.json, packages/plasma-b2c/package-lock.json, packages/plasma-hope/package-lock.json, packages/plasma-new-hope/package-lock.json, packages/plasma-web/package-lock.json
Обновлены версии пакетов в `package-lock.json` файлах
Во время публикации RC случился сбой. Пришлось ручками править версии. 
https://github.com/salute-developers/plasma/actions/runs/6878237594/job/18707477726
```
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@salutejs%2fplasma-hope: aborted
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! A complete log of this run can be found in: …
```
=> plasma-infra: Manual update package-lock.json files

.eslintignore, packages/plasma-asdk/.gitignore, packages/plasma-asdk/README.md, packages/plasma-asdk/README.stories.mdx, packages/plasma-asdk/api/plasma-asdk.api.md, packages/plasma-asdk/package-lock.json, packages/plasma-asdk/package.json, packages/plasma-asdk/src/components/List/List.tsx, packages/plasma-asdk/src/components/List/ListItem.tsx, packages/plasma-asdk/src/components/List/index.ts, packages/plasma-asdk/src/components/SSRProvider/index.ts, packages/plasma-asdk/src/themes/index.ts, packages/plasma-asdk/src/tokens/index.ts
В Plasma-ASDK было добавлен реэкспорт:
- тем stylesSalute_dark, stylesSalute_light;
- токенов;
------
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.855.6931008057.ts'>borderRadius_default_react-native--canary.855.6931008057.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.855.6931008057.ts'>borderRadius_plasma_b2c_react-native--canary.855.6931008057.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary. …
=> Plasma asdk: add theme and tokens

packages/plasma-core/package-lock.json, packages/plasma-core/package.json
Аудит и исправления уязвимостей: critical, high для библиотеки `plasma-core`. 
------
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.860.6952535043.ts'>borderRadius_default_react-native--canary.860.6952535043.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.860.6952535043.ts'>borderRadius_plasma_b2c_react-native--canary.860.6952535043.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.860.6952535043.t …
=> plasma-infra(core): Fix vulnerabilities

packages/plasma-new-hope/package-lock.json, packages/plasma-new-hope/package.json
Установили версию `@types/styled-components@5.1.0` как и во всех остальных пользовательских пакетах.
До этого использовалась версия 5.1.26 и это вызывало ошибку для метода `applySpacing` из-за разночтения api в `styled-components`
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.865.6955865239.ts'>borderRadius_default_react-native--canary.865.6955865239.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.865.6955865239.ts'>borderRadius_plasma_b2c_react-native--canary.865.6955865239.ts</a><br> …
=> plasma-infra(new-hope): Use `@types/styled-components@5.1.0`

packages/plasma-new-hope/src/components/Modal/Modal/Modal.tsx, packages/plasma-new-hope/src/index.ts, website/plasma-web-docs/docs/components/ModalBase.mdx, website/plasma-web-docs/docs/components/PopupBase.mdx
Поправлена документация для `ModalBase`, `PopupBase` для web. Также поправлены мелкие ошибки в `plasma-new-hope`.
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.862.6956851291.ts'>borderRadius_default_react-native--canary.862.6956851291.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.862.6956851291.ts'>borderRadius_plasma_b2c_react-native--canary.862.6956851291.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-nat …
=> docs: fix PopupBase, ModalBase docs

package-lock.json, package.json, packages/plasma-colors/package-lock.json, packages/plasma-colors/package.json, packages/plasma-icons/package-lock.json, packages/plasma-icons/package.json, packages/plasma-tokens-b2b/package-lock.json, packages/plasma-tokens-b2b/package.json, packages/plasma-tokens-b2c/package-lock.json, packages/plasma-tokens-b2c/package.json, packages/plasma-tokens-core/package-lock.json, packages/plasma-tokens-core/package.json, packages/plasma-tokens-web/package-lock.json, packages/plasma-tokens-web/package.json, packages/plasma-tokens/package-lock.json, packages/plasma-tokens/package.json, packages/plasma-typo/package-lock.json, packages/plasma-typo/package.json, utils/plasma-tokens-utils/package-lock.json, utils/plasma-tokens-utils/package.json
Перевели оставшиеся пользовательские библиотеки на версию typescript@4.2.4
----
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.869.6968366217.ts'>borderRadius_default_react-native--canary.869.6968366217.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.869.6968366217.ts'>borderRadius_plasma_b2c_react-native--canary.869.6968366217.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.869.6968366217.ts'>bor …
=> plasma-infra: Bump TS to 4.2.4

.github/workflows/documentation-main.yml
Поменяли расположение директорий для storybook build для корректной работы nginx конфигурации.  
Чтобы nginx отработал корректно поменяли расположение директории в которых находился результат storybook build.
Теперь всё лежит в корне, например для `plasma-web => ./web-storybook`  
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.856.7015940480.ts'>borderRadius_default_react-native--canary.856.7015940480.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.856.7015940480.ts'>borderRadius_plasma_b …
=> plasma-infra: Changed storybook location in s3   

package-lock.json
Исправлены **все** `critical` и **большая** часть `high` уязвимостей. 
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.874.7015369998.ts'>borderRadius_default_react-native--canary.874.7015369998.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.874.7015369998.ts'>borderRadius_plasma_b2c_react-native--canary.874.7015369998.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.874.7015369998.ts'>borderRadius …
=> plasma-infra: Fix vulnerabilities: high, critical in root package.json

packages/plasma-ui/package-lock.json, packages/plasma-ui/package.json
Обновлены зависимости: 
- [`vite` to 4.5.0](https://github.com/salute-developers/plasma/security/dependabot/97)
- [`default-browser-id` to 2.0.0](https://github.com/advisories/GHSA-7p7h-4mm5-852v) 
Исправлены **все** `critical` и `high` vulnerabilities
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.875.7015573607.ts'>borderRadius_default_react-native--canary.875.7015573607.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.875.7015573607.ts'>borderRadius_plasma_b2c_react-native--canary.875.7 …
=> plasma-infra(plasma-ui): Fix vulnerabilities 

packages/plasma-icons/package-lock.json, packages/plasma-tokens-b2b/design-language/package-lock.json, packages/plasma-tokens-b2b/package-lock.json, packages/plasma-tokens-b2c/design-language/package-lock.json, packages/plasma-tokens-b2c/package-lock.json, packages/plasma-tokens-web/design-language/package-lock.json, packages/plasma-tokens-web/package-lock.json, packages/plasma-tokens/package-lock.json, packages/plasma-typo/package-lock.json, utils/plasma-tokens-native/package-lock.json, utils/plasma-tokens-utils/package-lock.json
Закрыты все уязвимости в 
- plasma-typo
- plasma-icons
- plasma-tokens
-  plasma-tokens-b2c
- plasma-tokens-b2b
- plasma-tokens-web
- plasma-tokens-native
- plasma-tokens-utils
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.876.7018029350.ts'>borderRadius_default_react-native--canary.876.7018029350.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.876.7018029350.ts'>borderRadius_plasma_b2c_react-native--canary.876.7018029350.ts</a><br>
<a …
=> plasma-infra: Fix npm vulnerabilities

utils/plasma-tokens-native/package.json
В этом ПР проверяем как грузятся assets.   
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.891.7096742318.ts'>borderRadius_default_react-native--canary.891.7096742318.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.891.7096742318.ts'>borderRadius_plasma_b2c_react-native--canary.891.7096742318.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.891.7096742318.ts'>borderRadius_plasma_web_react-native--c …
=> plasma-tokens-native: Check upload assets

packages/plasma-asdk/src/mixins/index.ts, packages/plasma-new-hope/src/components/Calendar/mixins/index.ts, packages/plasma-new-hope/src/components/Calendar/ui/CalendarDayItem/CalendarDayItem.styles.ts, packages/plasma-new-hope/src/components/Calendar/ui/CalendarMonths/CalendarMonths.styles.ts, packages/plasma-new-hope/src/components/Calendar/ui/CalendarYears/CalendarYears.styles.ts, packages/plasma-new-hope/src/components/Checkbox/_focused/base.ts, packages/plasma-new-hope/src/components/Chip/variations/_focused/base.ts, packages/plasma-new-hope/src/components/Radiobox/_focused/base.ts, packages/plasma-new-hope/src/mixins/addFocus.ts, packages/plasma-new-hope/src/mixins/index.ts
Добавлен общий миксин addFocus, так как во многих компонентах были примерно одинаковые миксины и нужно было какое-то общее решение для plasma-new-hope. 
В качестве примера на него переведены компоненты: **Chip, Checkbox, Radiobox, Calendar**
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.888.7091553141.ts'>borderRadius_default_react-native--canary.888.7091553141.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.888.7091553141.ts'>borderRadius_plasma_b2c_react-native--canary.888.7091553141.t …
=> feat(plasma-new-hope/asdk): add focus mixin

utils/plasma-tokens-native/package.json
проверка загрузки assets в момент публикации RC  
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.910.7190685853.ts'>borderRadius_default_react-native--canary.910.7190685853.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_b2c_react-native--canary.910.7190685853.ts'>borderRadius_plasma_b2c_react-native--canary.910.7190685853.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_plasma_web_react-native--canary.910.7190685853.ts'>borderRadius_plasma_web_react-nat …
=> plasma-infra: Test upload assets when publish RC

packages/plasma-asdk/package-lock.json, packages/plasma-b2c/package-lock.json, packages/plasma-new-hope/package-lock.json, packages/plasma-web/package-lock.json
Обновлены версии в package-lock.json файлах
=> chore: update package-lock.json files

.github/workflows/documentation-main.yml
- добавлен storybook для "https://plasma.sberdevices.ru/asdk-storybook/"
Что бы была возможность сравнить dev и latest state
=> plasma-infra:  Add storybook for "Plasma-ASDK"

.github/changelog-builder-config.json, .github/workflows/release-pr.yml
- добавлена новая категория `Bugs`
- экранирование спец символов 
Шаг Create "changelog_artifacts.md" мог завершиться с ошибкой из-за спец символов.
Например символы `` приводили к ошибке.
=> plasma-infra: Improve changelog workflow 

packages/plasma-ui/CHANGELOG.md, packages/plasma-web/CHANGELOG.md
незакрытый тег `img` ломал сборку документации, так как был невалидный JSX
`<img />` - исправил проблему   
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.29.1-canary.987.7582226043.0
npm install @salutejs/plasma-b2c@1.271.1-canary.987.7582226043.0
npm install @salutejs/plasma-core@1.144.1-canary.987.7582226043.0
npm install @salutejs/plasma-hope@1.255.1-canary.987.7582226043.0
npm install @salutejs/plasma-icons@1.177.1-canary.987.7582226043.0
npm install @salutejs/plasma-new-hope@0.35.1-canary.987.7582226043.0
npm install @salutejs/plasma-temple@1.196.1-canary.987.7582226043.0
npm install @salutejs/plasma-tokens@1.68.1-canary.987.7582226043.0
npm …
```
=> plasma-infra: Fix broken build docs

.github/processing-scope.js, .github/workflows/change-detection.yml, .github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml
- caldera добавлена в workflows
Так как будет собрана новая библиотека Caldera нужно поднять сторибук в рамках пр.
=> ci: add caldera-package to workflows

.github/workflows/documentation-pull-request-dev.yml
- добавлен отдельный workflow для сборки документация и storybook на основе dev ветки 
Главное отличие от похоже workflow - "PR Documentation and Storybook", в том что всё собирается. 
**Нет расчета условий** для сборки конкретных пакетов. То есть мы не смотрим какие пакеты были изменены, а собираем все как есть.  
Причина - нужен стенд для проведения **регрессионного** **тестирования** релизных изменений.
=> plasma-infra(documentation): Add documentation workflow for dev branch

.github/workflows/performance-test-pr.yml, package-lock.json, package.json, perftool.config.mts
Протестировано в https://github.com/salute-developers/plasma/pull/992
Данный PR включает использование новой фичи perftool — коллаборативный прогон. Это прогон одновременно двух веток в рамках одного процесса (что упрощает некоторые операции сравнения веток и еще больше уравнивает фактор внешней нагрузки), но так, чтобы друг на друга прогоны не влияли. В нашей конфигурации запуски тестов из одной ветки и другой последовательно чередуются в одном потоке.
=> ci: use perftool collaborative mode

.github/workflows/create-release-pr.yml
- добавлен выбор ветки для создания release pull request   
В #1009 обновление Docusaurus и новая конфигурация позволили обойти данную ошибку. 
TL;DR
В сочетание MDX + JSX и запись `<img alt="some text">` приводило к ошибке  `unterminated jsx contents` когда запускали `npm run build --prefix="./website/plasma-ui-docs`.
=> plasma-infra: Refactoring release pull request workflow 

.github/processing-scope.js, .github/workflows/change-detection.yml, .github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml, .github/workflows/documentation-pull-request-dev.yml
- caldera-online добавлена в workflows
Так как будет собрана новая библиотека Caldera-online нужно поднять сторибук в рамках пр.
=> ci: add Caldera-online-package to workflows

.github/workflows/documentation-pr.yml
=> plasma-infra: Delete unnecessary `on:pull_request` into master  

.github/processing-scope.js, .github/workflows/change-detection.yml, .github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml, .github/workflows/documentation-pull-request-dev.yml
- sdds srvc добавлена в workflows
Так как будет собрана новая библиотека sdds-srvc нужно поднять сторибук в рамках пр.
=> ci: add sdds-srvc to workflows

.github/workflows/documentation-dev-stage-deploy.yml
- добавлен dev stage для возможности сделать deploy dev branch. Нужен для QA     
Данный dev stage сделан по аналогии с тем, что есть для релиза на основе master branch. 
Мотивация - потребность проводить/сравнивать состояние в pull request и stage.
=> plasma-infra: Setup s3 DEV stage – manual run

.github/workflows/cleanup-cache-pr.yml, .github/workflows/create-release-pr.yml, .github/workflows/documentation-pr.yml, .github/workflows/documentation-pull-request-dev.yml
- добавлено условие для запуска `documentation-pull-request-dev.yml` только для веток - `release`  
- исправлен двойной запуск `cleanup-cache-pr.yml`
- добавлена корректная обработка спец символов при генерации changelog
=> plasma-infra: Tech debt

.github/workflows/documentation-deploy-stage-dev.yml, .github/workflows/publish-rc.yml
Расширили список пакетов для deploy на dev stage
=> plasma-infra: Setup dev stage [Part 2]

.github/processing-scope.js, .github/workflows/change-detection.yml, .github/workflows/documentation-deploy-stage-dev.yml, .github/workflows/documentation-main.yml, .github/workflows/documentation-pr.yml, .github/workflows/documentation-pull-request-dev.yml
- sdds serv добавлена в workflows
sdds-srvc будет переименована в sdds-serv.
=> chore: add sdds-serv to workflows

packages/caldera-online/package-lock.json, packages/caldera/package-lock.json, packages/plasma-asdk/package-lock.json, packages/plasma-b2c/package-lock.json, packages/plasma-core/package-lock.json, packages/plasma-hope/package-lock.json, packages/plasma-icons/package-lock.json, packages/plasma-new-hope/package-lock.json, packages/plasma-temple/package-lock.json, packages/plasma-tokens/package-lock.json, packages/plasma-ui/package-lock.json, packages/plasma-web/package-lock.json, packages/sdds-srvc/package-lock.json, utils/plasma-cy-utils/package-lock.json, utils/plasma-sb-utils/package-lock.json
Ручной бамп версий
Произошла ошибка при публикации rc
=> chore: bump manual package-locks

utils/plasma-docs-ui/package-lock.json, utils/plasma-docs-ui/package.json
Подготовительный мероприятие перед изменениями связанными с CI для документации.
=> plasma-infra(docs-ui): Sync deps version

website/plasma-ui-docs/package-lock.json, website/plasma-ui-docs/package.json
Подготовительный мероприятие перед изменениями связанными с CI для документации.
<details>
<br />
```bash
npm install @salutejs/plasma-ui@1.240.2-canary.1120.8281830072.0
yarn add @salutejs/plasma-ui@1.240.2-canary.1120.8281830072.0
```
</details>
=> plasma-infra(ui-docs):  Clean deps

.github/actions/update-package-lock/action.yml, .github/workflows/sync-package-lock-files.yml
- добавлен retry для шага "Update package-lock files", если он упадет с ошибкой 
- добавлен workflow для ручного запуска "Update package-lock files" 
Обсуждение в issue #884
=> plasma-infra: Retry failure step

CODEOWNERS
Добавили @TitanKuzmich и @shuga2704 в code owners
=> chore: Update code owners list

packages/caldera-online/api/caldera-online.api.md, packages/caldera-online/src/components/Button/Button.config.ts, packages/caldera-online/src/components/Button/Button.stories.tsx, packages/plasma-asdk/api/plasma-asdk.api.md, packages/plasma-asdk/src/components/Button/Button.config.ts, packages/plasma-asdk/src/components/Button/Button.stories.tsx, packages/plasma-b2c/api/plasma-b2c.api.md, packages/plasma-b2c/src/components/Button/Button.config.ts, packages/plasma-b2c/src/components/Button/Button.stories.tsx, packages/plasma-new-hope/src/examples/plasma_b2c/components/Button/Button.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Button/Button.config.ts, packages/plasma-new-hope/src/examples/sds_engineer/components/Button/Button.config.ts, packages/plasma-web/api/plasma-web.api.md, packages/plasma-web/src/components/Button/Button.config.ts, packages/plasma-web/src/components/Button/Button.stories.tsx, packages/sdds-serv/api/sdds-serv.api.md, packages/sdds-serv/src/components/Button/Button.config.ts, packages/sdds-serv/src/components/Button/Button.stories.tsx
* В библиотеках `@salutejs/plasma-b2c`, `@salutejs/plasma-web`, `@salutejs/plasma-asdk`, `@salutejs/sdds-serv`, `@salutejs/caldera-online` добавлены токены состояний (active / hover) для конифгов компонента `Button`.
Сейчас токены состояний считаются некорректно с помощью color-mix.
<details>
<br />
```bash
npm install @salutejs/caldera-online@0.30.1-canary.1167.8571451172.0
npm install @salutejs/plasma-asdk@0.67.1-canary.1167.8571451172.0
npm install @salutejs/plasma-b2c@1.309.2-canary.1167.8571451172.0
npm install @salutejs/plasma-new-hope@0.70.1-canary.1167.8571451172.0
npm install @salutejs/plasma-web@1.309.2-canary.1167.8571451172.0
npm install …
```
=> fix(plasma-web,plasma-b2c,plasma-asdk,sdds-serv,calder-online): Update state tokens for `Button` component

packages/plasma-icons/.gitignore, packages/plasma-icons/package-lock.json, packages/plasma-icons/package.json, packages/plasma-icons/scripts/generateIconsIos.mjs
- добавлен конвертор SVG в PNG для iOS  
в директории `plasma-icons` нужно выполнить:
```console
npm run generate:ios
```  
Результат script будет находиться в директории `icons-ios`:
```js
'1x': {
scale: 1,
// INFO: generateIconsIos === DPI
density: 72,
},
'2x': {
scale: 2,
density: 144,
},
'3x': {
scale: 3,
density: 216,
},
```
Описывает что содержит в себе `IconName.imageset`
```json
{
"info": {
"version": 1,
"author": "xcode"
},
"images": [
{
"scale": "1x",
"idiom": "universal",
"filename": "Accessibility@1x.png"
},
{
"scale": "2x",
"idiom": "universal",
"filename": "Accessibility@2x.png"
},
{
"scale": "3x",
"idiom": "universal",
"filename": "Accessibility@3x.png"
}
]
}
```  
<details>
<br />
:sparkles: …
=> plasma-icons: Convert SVG to PNG for iOS  

.eslintignore, .github/processing-scope.js, .prettierignore
Убраны любые упоминания о пакете "Caldera"
=> plasma-infra: Delete caldera package remains

packages/plasma-tokens/package-lock.json, packages/plasma-tokens/package.json, packages/themes/caldera-online-themes/package-lock.json, packages/themes/caldera-online-themes/package.json, packages/themes/flamingo-themes/package-lock.json, packages/themes/flamingo-themes/package.json, packages/themes/plasma-themes/package-lock.json, packages/themes/plasma-themes/package.json, packages/themes/sdds-themes/package-lock.json, packages/themes/sdds-themes/package.json
Версия 5.3.1 является общей для всего проекта.   
<details>
<blockquote>
<details>
<blockquote>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_caldera_online_react-native--canary.1190.8779486510.ts'>borderRadius_caldera_online_react-native--canary.1190.8779486510.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_default_react-native--canary.1190.8779486510.ts'>borderRadius_default_react-native--canary.1190.8779486510.ts</a><br>
<a href='https://github.com/salute-developers/plasma/releases/download/v0.0.0-canary/borderRadius_flamingo_react-native--canary.1190.8779486510.ts'>borderRadius_flamingo_ …
=> plasma-infra: use styled-components@5.3.1

packages/sdds-serv/api/sdds-serv.api.md, packages/sdds-serv/src/components/IconButton/IconButton.config.ts, packages/sdds-serv/src/components/IconButton/IconButton.stories.tsx, packages/sdds-serv/src/components/IconButton/IconButton.ts, packages/sdds-serv/src/components/IconButton/index.ts, packages/sdds-serv/src/index.ts, website/sdds-serv-docs/docs/components/IconButton.mdx
- IconButton включена в поставку sdds-serv
- добавлена документация в sdds-serv-docs
При разработке IconButton не была включена в поставку sdds-serv.
<details>
<br />
```bash
npm install @salutejs/sdds-serv@0.53.0-canary.1214.9265223318.0
yarn add @salutejs/sdds-serv@0.53.0-canary.1214.9265223318.0
```
</details>
=> feat(sdds-serv): add icon button

utils/plasma-cy-utils/package-lock.json, utils/plasma-docs-ui/package-lock.json
- исправлены critical уязвимости в utils пакетах
=> plasma-infra: npm audit fix for utils packages

website/plasma-website/components/roster/AbstractIcon.tsx, website/plasma-website/components/roster/Header.tsx, website/plasma-website/components/roster/IconExtendedInfo.tsx, website/plasma-website/components/roster/IconFilterMenu.tsx, website/plasma-website/components/roster/IconsList.tsx, website/plasma-website/components/roster/SearchForm.tsx, website/plasma-website/components/roster/StyledActionIcon.tsx, website/plasma-website/getPackageInfo.js, website/plasma-website/package-lock.json, website/plasma-website/pages/icons.tsx, website/plasma-website/types/Data.ts, website/plasma-website/utils/iconsList.ts
- новый UI для блока поиск
- исправлен вывод набора иконок 
- исправлено `isDeprecate` на `isDeprecated`
=> plasma-website: New UI search block

.github/workflows/ci-lint.yml, .github/workflows/ci-unit-tests.yml, .github/workflows/typescript-coverage.yml
- реорганизовали обязательные проверки (стало меньше и быстрее) 
Сейчас список обязательных проверок неоптимальный, его можно изменить.
Будут следующие проверки:
Это ускорит наш проверки в `merge_group` с  17 мин до ~5-6 мин.
=> plasma-infra: Simplify required checks

website/plasma-website/components/palette/PaletteColorPage.tsx, website/plasma-website/components/palette/PaletteItem.tsx
- исправлено наименование блоков
- исправлена ссылку `back`
по сути hotfix для нашего website - раздел цветовой палитры
=> plasma-website: Color palette [hotfix]

packages/plasma-b2c/src/components/Accordion/Accordion.config.ts, packages/plasma-new-hope/src/components/Accordion/Accordion.tokens.ts, packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.styles.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Accordion/Accordion.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Accordion/Accordion.config.ts, packages/plasma-web/api/plasma-web.api.md, packages/plasma-web/src/components/Accordion/Accordion.config.ts, packages/sdds-cs/api/sdds-cs.api.md, packages/sdds-cs/src/components/Accordion/Accordion.config.ts, packages/sdds-cs/src/components/Accordion/Accordion.stories.tsx, packages/sdds-cs/src/components/Avatar/Avatar.config.tsx, packages/sdds-cs/src/components/Avatar/Avatar.stories.tsx, packages/sdds-cs/src/components/AvatarGroup/AvatarGroup.stories.tsx, packages/sdds-cs/src/components/Badge/Badge.config.ts, packages/sdds-cs/src/components/Badge/Badge.stories.tsx, packages/sdds-cs/src/components/Cell/Cell.config.ts, packages/sdds-cs/src/components/Cell/Cell.stories.tsx, packages/sdds-cs/src/components/Chip/Chip.config.tsx, packages/sdds-cs/src/components/Chip/Chip.stories.tsx, packages/sdds-cs/src/components/Counter/Counter.config.ts, packages/sdds-cs/src/components/Counter/Counter.stories.tsx, packages/sdds-cs/src/components/Divider/Divider.config.ts, packages/sdds-cs/src/components/Indicator/Indicator.config.tsx, packages/sdds-cs/src/components/Indicator/Indicator.stories.tsx, packages/sdds-dfa/src/components/Accordion/Accordion.config.ts, packages/sdds-serv/src/components/Accordion/Accordion.config.ts
- В пакете `sdds-cs` были изменены конфиги в компонентах: `Accordion`, `Avatar`, `Badge`, `Cell`, `Counter`, `Chip`, `Divider`, `Indicator`
- В `Accordion` добавлен токен цвета иконки
- В `plasma-web` добавлены новые view
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.122.0-canary.1344.10284816964.0
npm install @salutejs/plasma-b2c@1.364.0-canary.1344.10284816964.0
npm install @salutejs/plasma-new-hope@0.119.0-canary.1344.10284816964.0
npm install @salutejs/plasma-web@1.365.0-canary.1344.10284816964.0
npm install @salutejs/sdds-cs@0.94.0-canary.1344.10284816964.0
npm install @salutejs/sdds-dfa@0.92.0-canary.1344.10284816964.0
npm install …
```
=> fix(sdds-serv): Update configs for components in sdds-cs

website/plasma-theme-builder/package-lock.json, website/plasma-theme-builder/src/components/AddTokenSection/AddTokenSection.tsx, website/plasma-theme-builder/src/components/AuthRequestModal/AuthRequestModal.tsx, website/plasma-theme-builder/src/components/PreviewColor/PreviewColor.tsx, website/plasma-theme-builder/src/components/Theme/Theme.tsx, website/plasma-theme-builder/src/components/TokenForm/TokenForm.tsx
* Исправлена обработка пропсов `opened` для модальных окон
* Исправлено отображение полей для ввода в модальном окне редактирования токена
* Исправлена генерация токенов `active` и `hover` состояний при изменении отключении / включении токена
=> fix(plasma-theme-builder): Fix bugs in Theme Builder

packages/sdds-finportal/api/sdds-finportal.api.md, packages/sdds-finportal/src/components/TextArea/TextArea.config.tsx, packages/sdds-finportal/src/components/TextArea/TextArea.stories.tsx, packages/sdds-finportal/src/components/TextField/TextField.config.ts, packages/sdds-finportal/src/components/TextField/TextField.stories.tsx, packages/sdds-finportal/src/components/TextFieldGroup/TextFieldGroup.config.ts, packages/sdds-finportal/src/components/TextFieldGroup/TextFieldGroup.stories.tsx, packages/sdds-finportal/src/components/TextFieldGroup/TextFieldGroup.tsx, packages/sdds-finportal/src/components/TextFieldGroup/index.tsx, packages/sdds-finportal/src/index.ts
- добавлен TextFieldGroup
- добавлен свойство `required` и его логика для `TextField/Area`
<details>
<br />
```bash
npm install @salutejs/sdds-finportal@0.113.1-canary.1427.10827515212.0
yarn add @salutejs/sdds-finportal@0.113.1-canary.1427.10827515212.0
```
</details>
=> [Plasma-3453]: Update SDDS-FinPortal components

.github/actions/get-reviewers/action.yml, .github/actions/get-reviewers/index.js, .github/actions/get-reviewers/package-lock.json, .github/actions/get-reviewers/package.json, .github/teammates.json, .github/workflows/notification-pull-request-ready-for-review.yml
- добавлены уведомления когда pull request переводиться в review
- добавлен action который выбирает случайным образом участника review    
Этот workflow делает 2 вещи
1.  уведомления
2. назначение reviewers 
Для 2 пунката смотрим  - .github/actions/get-reviewers/index.js 
Алгоритм такой, когда `pull request` переводят из `Draft` to RFR нажав соответствующую кнопку 
1. Получаем список всех `pull requests` отфильтровав по `is:pr is:open review:required -draft:true -author:renovate[bot]` (работает так https://github.com/salute-developers/plasma/pulls?q=is%3Apr+is%3Aopen+review%3Arequired+-draft%3Atrue+-author%3Arenovate%5Bbot%5D+)
2. Потом считаем для каждого участника команды кол-во участий в review 
3. Фильтруем список команды: убираем автора pull request и тех у кого больше 3 review
4. Из …
=> plasma-infra: Send notification when ready for review

packages/plasma-b2c/api/plasma-b2c.api.md, packages/plasma-b2c/src/components/Badge/Badge.config.ts, packages/plasma-b2c/src/components/Badge/Badge.stories.tsx, packages/plasma-new-hope/src/components/Badge/Badge.template-doc.mdx, packages/plasma-new-hope/src/examples/plasma_b2c/components/Badge/Badge.config.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Badge/Badge.stories.tsx, packages/plasma-new-hope/src/examples/plasma_web/components/Badge/Badge.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Badge/Badge.stories.tsx, packages/plasma-web/api/plasma-web.api.md, packages/plasma-web/src/components/Badge/Badge.config.ts, packages/plasma-web/src/components/Badge/Badge.stories.tsx, packages/sdds-dfa/api/sdds-dfa.api.md, packages/sdds-dfa/src/components/Badge/Badge.config.ts, packages/sdds-dfa/src/components/Badge/Badge.stories.tsx, packages/sdds-finportal/api/sdds-finportal.api.md, packages/sdds-finportal/src/components/Badge/Badge.config.ts, packages/sdds-finportal/src/components/Badge/Badge.stories.tsx, packages/sdds-serv/api/sdds-serv.api.md, packages/sdds-serv/src/components/Badge/Badge.config.ts, packages/sdds-serv/src/components/Badge/Badge.stories.tsx, website/plasma-b2c-docs/docs/components/Badge.mdx, website/plasma-web-docs/docs/components/Badge.mdx, website/sdds-dfa-docs/docs/components/Badge.mdx, website/sdds-serv-docs/docs/components/Badge.mdx
- добавлен новый размер `XS`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.172.0-canary.1466.11269016047.0
npm install @salutejs/plasma-b2c@1.414.0-canary.1466.11269016047.0
npm install @salutejs/plasma-new-hope@0.163.0-canary.1466.11269016047.0
npm install @salutejs/plasma-web@1.416.0-canary.1466.11269016047.0
npm install @salutejs/sdds-cs@0.144.0-canary.1466.11269016047.0
npm install @salutejs/sdds-dfa@0.142.0-canary.1466.11269016047.0
npm install @salutejs/sdds-finportal@0.136.0-canary.1466.11269016047.0
npm install @salutejs/sdds-serv@0.143.0-canary.1466.11269016047.0
yarn add @salutejs/plasma-asdk@0.172.0-canary.1466.11269016047.0
yarn add …
```
=> [PLASMA-3598]: Badge: Add size XS  

packages/plasma-b2c/src/components/Tabs/Tabs.stories.tsx, packages/plasma-new-hope/src/components/Tabs/ui/horizontal/HorizontalTabs/HorizontalTabs.tsx, packages/plasma-new-hope/src/components/Tabs/ui/vertical/VerticalTabs/VerticalTabs.tsx, packages/plasma-new-hope/src/examples/plasma_b2c/components/Tabs/Tabs.stories.tsx, packages/plasma-new-hope/src/examples/plasma_web/components/Tabs/Tabs.stories.tsx, packages/plasma-web/src/components/Tabs/Tabs.stories.tsx, packages/sdds-cs/src/components/Tabs/Tabs.stories.tsx, packages/sdds-dfa/src/components/Tabs/Tabs.stories.tsx, packages/sdds-finportal/src/components/Tabs/Tabs.stories.tsx, packages/sdds-serv/src/components/Tabs/Tabs.stories.tsx
- исправлен скролл табов при малой ширине
- в `storybooks` добавлены свойства `width` и `height`, доступные при условии `clip = scroll`
https://github.com/user-attachments/assets/4db01627-1a4b-4db5-ad47-1b945d79aa91
https://github.com/user-attachments/assets/7d660f29-dbdd-4adc-baba-00e9e8882229
https://github.com/user-attachments/assets/bff65aba-d42c-40c5-bf84-e7de77ad3b20
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.173.1-canary.1476.11329630608.0
npm install @salutejs/plasma-b2c@1.415.1-canary.1476.11329630608.0
npm install @salutejs/plasma-core@1.181.1-canary.1476.11329630608.0
npm install @salutejs/plasma-hope@1.314.1-canary.1476.11329630608.0
npm …
```
=> `plasma-new-hope`: fix tabs arrow scroll

.github/workflows/clean-pr-documentation.yml, .github/workflows/create-release-pr.yml, .github/workflows/documentation-deploy-pr.yml, .github/workflows/documentation-deploy-prod.yml, .github/workflows/documentation-deploy-release-branch.yml, .github/workflows/documentation-deploy-stage-dev.yml, .github/workflows/publish-rc.yml, .github/workflows/theme-builder-deploy-demo.yml, .github/workflows/theme-builder-pr.yml, .github/workflows/theme-builder.yml, .github/workflows/versionate-docs.yml
- временный фикс версии ubuntu с latest (24.04.1) на 22.04.5
Временный фикс версии ubuntu с latest (24.04.1) на 22.04.5.
=> chore: Fix ubuntu version

.github/meta.js, .github/workflows/ci-unit-tests.yml, .github/workflows/cypress-common.yml, .github/workflows/documentation-deploy-pr.yml, .github/workflows/performance-test-base.yml, .github/workflows/performance-test-pr.yml
* Добавлены зависимости `plasma-themes` и `core-themes` на основе этого PR https://github.com/salute-developers/plasma/pull/1488
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.181.0-canary.1499.11454669033.0
npm install @salutejs/plasma-b2c@1.423.0-canary.1499.11454669033.0
npm install @salutejs/plasma-core@1.183.0-canary.1499.11454669033.0
npm install @salutejs/plasma-hope@1.316.0-canary.1499.11454669033.0
npm install @salutejs/plasma-icons@1.207.0-canary.1499.11454669033.0
npm install @salutejs/plasma-new-hope@0.172.0-canary.1499.11454669033.0
npm install @salutejs/plasma-tokens@1.102.0-canary.1499.11454669033.0
npm install …
```
=> plasma-infra: Add `plasma-themes` and `core-themes` to workflows

packages/plasma-b2c/src/components/Select/Select.config.ts, packages/plasma-new-hope/src/components/Select/Select.styles.ts, packages/plasma-new-hope/src/components/Select/Select.tokens.ts, packages/plasma-new-hope/src/components/Select/ui/Inner/ui/Item/Item.styles.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Select/Select.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Select/Select.config.ts, packages/plasma-web/src/components/Select/Select.config.ts, packages/sdds-cs/src/components/Select/Select.config.ts, packages/sdds-dfa/src/components/Select/Select.config.ts, packages/sdds-finportal/src/components/Select/Select.config.ts, packages/sdds-serv/src/components/Select/Select.config.ts
- добавлены новые токены в ядро компонента
- исправлена конфигурация компонента с учетом новых токенов для поставки `sdds-cs`
- Добавлены новые токены для `label`, `helperText`, `itemBackground` и `iconColor`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.184.0-canary.1504.11549657359.0
npm install @salutejs/plasma-b2c@1.426.0-canary.1504.11549657359.0
npm install @salutejs/plasma-new-hope@0.175.0-canary.1504.11549657359.0
npm install @salutejs/plasma-web@1.428.0-canary.1504.11549657359.0
npm install @salutejs/sdds-cs@0.156.0-canary.1504.11549657359.0
npm install @salutejs/sdds-dfa@0.154.0-canary.1504.11549657359.0
npm install …
```
=> plasma-*: Update config for `Select`

packages/plasma-new-hope/src/components/Select/Select.tokens.ts, packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.styles.tsx, packages/sdds-cs/api/sdds-cs.api.md, packages/sdds-cs/src/components/Select/Select.config.ts, packages/sdds-cs/src/components/Select/Select.stories.tsx
- добавлена `view negative` для компонента `Select`
- исправлен цветовой токен для `contentLeftColor` в компоненте `Select`
- убраны лишние опции и примеры из storybook для компонента `Select`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.189.0-canary.1519.11592655923.0
npm install @salutejs/plasma-b2c@1.431.0-canary.1519.11592655923.0
npm install @salutejs/plasma-new-hope@0.180.0-canary.1519.11592655923.0
npm install @salutejs/plasma-web@1.433.0-canary.1519.11592655923.0
npm install @salutejs/sdds-cs@0.161.0-canary.1519.11592655923.0
npm install @salutejs/sdds-dfa@0.159.0-canary.1519.11592655923.0
npm install …
```
=> [PLASMA-3718]: Fix config for `Select`

packages/themes/plasma-themes/README.md, packages/themes/sdds-themes/README.md, scaffold/template-docs/docs/intro.mdx, website/plasma-b2c-docs/docs/intro.mdx, website/plasma-web-docs/docs/intro.mdx, website/sdds-cs-docs/docs/intro.mdx, website/sdds-dfa-docs/docs/intro.mdx, website/sdds-insol-docs/docs/intro.mdx, website/sdds-serv-docs/docs/intro.mdx
Добавлены примеры смены тем
Добавлены примеры смены тем на:
- `styled-components`
- `emotion`
- `css-modules`
- `css`
=> feat: change theme docs

.github/workflows/documentation-deploy-pr.yml
=> plasma-infra: Deploy storybook build by draft

packages/plasma-asdk/api/plasma-asdk.api.md, packages/plasma-asdk/src/components/Switch/Switch.config.ts, packages/plasma-asdk/src/components/Switch/Switch.stories.tsx, packages/plasma-b2c/src/components/Switch/Switch.config.ts, packages/plasma-new-hope/src/components/Switch/Switch.tokens.ts, packages/plasma-new-hope/src/components/Switch/_toggleSize/base.ts, packages/plasma-new-hope/src/components/Switch/_view/base.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Switch/Switch.outline.config.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Switch/Switch.stories.tsx, packages/plasma-new-hope/src/examples/plasma_b2c/components/Switch/Switch.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Switch/Switch.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Switch/Switch.outline.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Switch/Switch.stories.tsx, packages/plasma-new-hope/src/examples/plasma_web/components/Switch/Switch.ts, packages/plasma-web/src/components/Switch/Switch.config.ts, packages/sdds-cs/src/components/Switch/Switch.config.ts, packages/sdds-dfa/src/components/Switch/Switch.config.ts, packages/sdds-finportal/src/components/Switch/Switch.config.ts, packages/sdds-insol/src/components/Switch/Switch.config.ts, packages/sdds-serv/src/components/Switch/Switch.config.ts
- в `plasma-new-hope` добавлен отдельный `config` файл для `Switch` в дизайне `outline`
- в связи с поддержанием `outline`-дизайна обновлены токены и стили для `Switch`, а также `config` файлы для всех пакетов в поставке
- для `plasma-asdk` обновлен и `config`, и `storybook`
`Switch` в дизайне `outline` существует не как `view`, а как отдельный самостоятельный `config` только для `plasma-new-hope`. `config` файлы для всех пакетов были обновлены, т.к. для `Switch` добавились новые токены, которые необходимы для работы `Switch outline`. 
Для `plasma-asdk` обновлен `config` и `storybook` в связи с текущими и предыдущими изменениями в Switch.
<details>
<br />
```bash
npm …
```
=> `plasma-*, sdds-*`: Switch outline design

packages/sdds-cs/api/sdds-cs.api.md, packages/sdds-cs/src/components/Segment/Segment.stories.tsx, packages/sdds-cs/src/components/Segment/SegmentGroup.config.ts, packages/sdds-cs/src/components/Segment/SegmentItem.config.ts
- Изменен конфиг `segment` в вертикали `sdds-cs` в соответсвии с макетами
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.178.3-canary.1573.11961571767.0
yarn add @salutejs/sdds-cs@0.178.3-canary.1573.11961571767.0
```
</details>
=> fix(sdds-cs): Segment config edit

packages/plasma-b2c/src/components/Calendar/CalendarBase.config.ts, packages/plasma-b2c/src/components/Calendar/CalendarDouble.config.ts, packages/plasma-new-hope/src/components/Calendar/Calendar.tokens.ts, packages/plasma-new-hope/src/components/Calendar/ui/DateStructureItem/DateStructureItem.styles.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Calendar/CalendarBase.config.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Calendar/CalendarDouble.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Calendar/CalendarBase.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Calendar/CalendarDouble.config.ts, packages/plasma-web/src/components/Calendar/CalendarBase.config.ts, packages/plasma-web/src/components/Calendar/CalendarDouble.config.ts, packages/sdds-cs/api/sdds-cs.api.md, packages/sdds-cs/src/components/Calendar/Calendar.stories.tsx, packages/sdds-cs/src/components/Calendar/CalendarBase.config.ts, packages/sdds-cs/src/components/Calendar/CalendarDouble.config.ts, packages/sdds-dfa/src/components/Calendar/CalendarBase.config.ts, packages/sdds-dfa/src/components/Calendar/CalendarDouble.config.ts, packages/sdds-finportal/src/components/Calendar/CalendarBase.config.ts, packages/sdds-finportal/src/components/Calendar/CalendarDouble.config.ts, packages/sdds-insol/src/components/Calendar/CalendarBase.config.ts, packages/sdds-insol/src/components/Calendar/CalendarDouble.config.ts, packages/sdds-serv/src/components/Calendar/CalendarBase.config.ts, packages/sdds-serv/src/components/Calendar/CalendarDouble.config.ts
- Изменены токена для компонента `Calendar` в вертикали `sdds-cs`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.207.0-canary.1566.11969356141.0
npm install @salutejs/plasma-b2c@1.449.0-canary.1566.11969356141.0
npm install @salutejs/plasma-new-hope@0.196.0-canary.1566.11969356141.0
npm install @salutejs/plasma-web@1.451.0-canary.1566.11969356141.0
npm install @salutejs/sdds-cs@0.180.0-canary.1566.11969356141.0
npm install @salutejs/sdds-dfa@0.177.0-canary.1566.11969356141.0
npm install @salutejs/sdds-finportal@0.171.0-canary.1566.11969356141.0
npm install @salutejs/sdds-insol@0.170.0-canary.1566.11969356141.0
npm install …
```
=> fix(sdds-cs): edit tokens calendar for sdds cs

packages/sdds-finportal/src/components/Badge/Badge.config.draft.ts, packages/sdds-finportal/src/components/Badge/Badge.stories.tsx
Добавлен черновик для Badge
```md
28 L - Vertical padding 4px, horizont padding 12px
24 M - Vertical padding 4px, horizont padding 8px, horizont spacing 4px 
20 S - Vertical padding 3px, Horizont padding 8px
``` 
<details>
<br />
```bash
npm install @salutejs/sdds-finportal@0.169.2-canary.1581.11947517999.0
yarn add @salutejs/sdds-finportal@0.169.2-canary.1581.11947517999.0
```
</details>
=> [PLASMA-3711]: Add draft config [Badge]

packages/sdds-insol/api/sdds-insol.api.md, packages/sdds-insol/src/components/Button/Button.config.ts, packages/sdds-insol/src/components/Button/Button.stories.tsx, packages/sdds-insol/src/components/IconButton/IconButton.config.ts, packages/sdds-insol/src/components/IconButton/IconButton.stories.tsx, website/sdds-insol-docs/docs/components/Button.mdx, website/sdds-insol-docs/docs/components/IconButton.mdx
* Добавлены размеры `XL` для компонент `Button` и `IconButton`
* Добавлен размер `XXS` для компонента `IconButton`
<details>
<br />
```bash
npm install @salutejs/sdds-insol@0.176.0-canary.1576.12028218827.0
yarn add @salutejs/sdds-insol@0.176.0-canary.1576.12028218827.0
```
</details>
=> feat(sdds-insol): Update `Button` and `IconButton` design

scaffold/template-docs/docs/form/NativeForm.mdx, scaffold/template-docs/docs/form/ReactHookForm.mdx, website/plasma-b2c-docs/docs/form/NativeForm.mdx, website/plasma-b2c-docs/docs/form/ReactHookForm.mdx, website/plasma-web-docs/docs/form/NativeForm.mdx, website/plasma-web-docs/docs/form/ReactHookForm.mdx, website/sdds-cs-docs/docs/form/NativeForm.mdx, website/sdds-cs-docs/docs/form/ReactHookForm.mdx, website/sdds-dfa-docs/docs/form/NativeForm.mdx, website/sdds-dfa-docs/docs/form/ReactHookForm.mdx, website/sdds-insol-docs/docs/form/NativeForm.mdx, website/sdds-insol-docs/docs/form/ReactHookForm.mdx, website/sdds-serv-docs/docs/form/NativeForm.mdx, website/sdds-serv-docs/docs/form/ReactHookForm.mdx
- добавлены примеры с валидацией формы в раздел "Формы"
Валидация с помощью react-hook-form + yup
https://codesandbox.io/p/sandbox/form-validation-qj7kp6
Валидация нативной формы с yup
https://codesandbox.io/p/sandbox/native-form-validation-5r2l9p
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.211.2-canary.1587.12030441373.0
npm install @salutejs/plasma-b2c@1.453.2-canary.1587.12030441373.0
npm install @salutejs/plasma-core@1.186.1-canary.1587.12030441373.0
npm install @salutejs/plasma-hope@1.321.1-canary.1587.12030441373.0
npm install @salutejs/plasma-new-hope@0.200.2-canary.1587.12030441373.0
npm install …
```
=> docs: Add validation examples docs

website/plasma-b2c-docs/docs/components/Dropdown.mdx, website/plasma-web-docs/docs/components/Dropdown.mdx, website/sdds-cs-docs/docs/components/Dropdown.mdx, website/sdds-dfa-docs/docs/components/Dropdown.mdx, website/sdds-insol-docs/docs/components/Dropdown.mdx, website/sdds-serv-docs/docs/components/Dropdown.mdx
- актуализированы примеры в документации для свойства `placement `
- актуализированы примеры в доке
=> PLASMA-4091: fixed placement property description in Dropdown

packages/plasma-new-hope/.storybook/decoratorViewContainer.tsx
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.220.1-canary.1617.12160977345.0
npm install @salutejs/plasma-b2c@1.462.1-canary.1617.12160977345.0
npm install @salutejs/plasma-new-hope@0.209.1-canary.1617.12160977345.0
npm install @salutejs/plasma-web@1.464.1-canary.1617.12160977345.0
npm install @salutejs/sdds-cs@0.193.1-canary.1617.12160977345.0
npm install @salutejs/sdds-dfa@0.190.1-canary.1617.12160977345.0
npm install @salutejs/sdds-finportal@0.184.1-canary.1617.12160977345.0
npm install @salutejs/sdds-insol@0.185.1-canary.1617.12160977345.0
npm install @salutejs/sdds-serv@0.192.1-canary.1617.12160977345.0
yarn add …
```
=> infra(new-hope): Fix storybook mapping [changelog-skip]

packages/plasma-new-hope/src/components/Popup/Popup.types.ts
- актуализированы примеры в документации
- добавлены описания типов `offset` и `placement`
Было:
Стало:
Было:
Стало:
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.221.1-canary.1615.12178456112.0
npm install @salutejs/plasma-b2c@1.463.1-canary.1615.12178456112.0
npm install @salutejs/plasma-new-hope@0.210.1-canary.1615.12178456112.0
npm install @salutejs/plasma-web@1.465.1-canary.1615.12178456112.0
npm install @salutejs/sdds-cs@0.194.1-canary.1615.12178456112.0
npm install @salutejs/sdds-dfa@0.191.1-canary.1615.12178456112.0
npm install @salutejs/sdds-finportal@0.185.1-canary.1615.12178456112.0
npm install …
```
=> PLASMA-3644: Modal examples and popup types

packages/plasma-new-hope/src/components/Notification/Notification.styles.ts, packages/plasma-new-hope/src/components/Notification/Notification.tokens.ts, packages/sdds-cs/src/components/Notification/Notification.config.ts, packages/sdds-cs/src/components/Notification/Notification.stories.tsx
- добавлен layout `horizontal`
- добавлены токены для позиционирования `actions`, `iconLeft` и `iconClose`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.222.0-canary.1604.12179786386.0
npm install @salutejs/plasma-b2c@1.464.0-canary.1604.12179786386.0
npm install @salutejs/plasma-new-hope@0.211.0-canary.1604.12179786386.0
npm install @salutejs/plasma-web@1.466.0-canary.1604.12179786386.0
npm install @salutejs/sdds-cs@0.195.0-canary.1604.12179786386.0
npm install @salutejs/sdds-dfa@0.192.0-canary.1604.12179786386.0
npm install @salutejs/sdds-finportal@0.186.0-canary.1604.12179786386.0
npm install @salutejs/sdds-insol@0.187.0-canary.1604.12179786386.0
npm …
```
=> PLASMA-4002: add horizontal notification

packages/plasma-new-hope/src/components/Tooltip/Tooltip.styles.ts, packages/plasma-new-hope/src/components/Tooltip/Tooltip.tokens.ts, packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx, packages/sdds-cs/src/components/Tooltip/Tooltip.stories.tsx
- скорректирован внутренний `align-items` 
**Было (позиция иконки)**
**Стало (позиция иконки)**
Было ( plasma-web ):
Стало ( plasma-web ):
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.222.2-canary.1602.12185035652.0
npm install @salutejs/plasma-b2c@1.464.2-canary.1602.12185035652.0
npm install @salutejs/plasma-new-hope@0.211.2-canary.1602.12185035652.0
npm install @salutejs/plasma-web@1.466.2-canary.1602.12185035652.0
npm install @salutejs/sdds-cs@0.195.2-canary.1602.12185035652.0
npm install @salutejs/sdds-dfa@0.192.2-canary.1602.12185035652.0
npm install @salutejs/sdds-finportal@0.186.2-canary.1602.12185035652.0
npm install …
```
=> PLASMA-3999: Fix icon and text position tooltip

.github/workflows/create-release-pr.yml
Когда создаем релизный pull request то в конце отправляем сообщение о создании задачи на релиз со всеми вошедшими в этот релиз задачами
=> infra: Автоматическое создание Release LF JIRA TASK 

.github/actions/write-changelog/action.yml, .github/actions/write-changelog/groupHeadingsByDeep.js, .github/actions/write-changelog/index.js, .github/actions/write-changelog/package-lock.json, .github/actions/write-changelog/package.json, .github/actions/write-changelog/processingHeadingByPackages.js, .github/actions/write-changelog/rewriteHeadingValue.js, .github/actions/write-changelog/swapSectionPlace.js, .github/actions/write-changelog/utils.js, .github/workflows/publish-latest.yml
- создание раздельного change-log (файл `.md`) для каждого пакета
- группировка по заголовку 3 уровня
После публикации latest release получаем несколько commits c `CHANGELOG.md`
Следующего формата 
```md
* обновлена конфигурация компонента
* обновлены примеры в `storybook`
[PR](pull request URL)
```
=> PLASMA-3766: Write changelog [Part 2] [changelog-skip]

packages/sdds-cs/src/components/Calendar/Calendar.stories.tsx, packages/sdds-cs/src/components/Calendar/CalendarBase.config.ts, packages/sdds-cs/src/components/DatePicker/DatePicker.config.ts
- исправлен токен фона дня, включенного в период в Range календарных сетках
Исправлен токен фона дня, включенного в период в Range календарных сетках.
<details>
<br />
```bash
npm install @salutejs/sdds-cs@0.214.0-canary.1658.12418137696.0
yarn add @salutejs/sdds-cs@0.214.0-canary.1658.12418137696.0
```
</details>
=> PLASMA-4154: update Calendar stories

packages/plasma-new-hope/src/components/Rating/utils/index.ts
- исправлена логика расчета отображаемого значения
**Before**:
**After**:
Если поставить оценку больше 5 при `iconQuantity=10` value округлялось до максимального.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.248.0-canary.1685.12513878250.0
npm install @salutejs/plasma-b2c@1.490.0-canary.1685.12513878250.0
npm install @salutejs/plasma-giga@0.217.0-canary.1685.12513878250.0
npm install @salutejs/plasma-new-hope@0.236.0-canary.1685.12513878250.0
npm install @salutejs/plasma-web@1.492.0-canary.1685.12513878250.0
npm install @salutejs/sdds-cs@0.225.0-canary.1685.12513878250.0
npm install @salutejs/sdds-dfa@0.220.0-canary.1685.12513878250.0
npm install …
```
=> PLASMA-4176: update value display logic for Rating

website/plasma-theme-builder/package-lock.json, website/plasma-theme-builder/src/components/GradientTokenValue/GradientTokenValue.tsx, website/plasma-theme-builder/src/components/SolidTokenValue/SolidTokenValue.tsx, website/plasma-theme-builder/src/components/TokenForm/TokenForm.tsx, website/plasma-theme-builder/src/utils/gradient.ts, website/plasma-theme-builder/src/utils/other.tsx
- Добавлена валидация при создании токена / редактировании токена:  
- Проверка, что токен называется в CamelCase нотации
- Название токена не должно превышвать 32 символа
- Название не должно начинаться с название подгруппы, в которой он создаётся
- В названии не должно быть зарезервированных слов "onDark", "onLight", "inverse"
- Значение обычного цвета теперь поддерживается только в HEX и HEXA форматах
- Значение градиента допускается только в полном описании: linear|radial-gradient (<угол / радиус>, <цвет> <позиция>, <цвет> <позиция>)
=> PLASMA-3987: feat(plasma-themes-builder): Add validation for TokenForm

packages/plasma-hope/src/components/Modal/Modal.tsx, packages/plasma-hope/src/components/Modal/ModalsContext.tsx
- исправлено поведение при анмаунте через условие
**Before**:
https://github.com/user-attachments/assets/2c73eb47-9875-40a2-a2b9-966511055f67
**After**:
https://github.com/user-attachments/assets/a087f1b1-f52b-4235-87c0-9db278e2d5bc
Исправлено поведение подложки при анмаунте модалки
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.267.2-canary.1746.13138491368.0
npm install @salutejs/plasma-b2c@1.509.2-canary.1746.13138491368.0
npm install @salutejs/plasma-giga@0.236.2-canary.1746.13138491368.0
npm install @salutejs/plasma-hope@1.329.1-canary.1746.13138491368.0
npm install @salutejs/plasma-new-hope@0.255.2-canary.1746.13138491368.0
npm install …
```
=> PLASMA-4215: fix Modal unmount behavior

packages/plasma-b2c/src/components/Tokens/Tokens.stories.tsx, packages/plasma-b2c/src/components/Tokens/Tokens.styles.ts, packages/plasma-giga/src/components/Tokens/Tokens.stories.tsx, packages/plasma-giga/src/components/Tokens/Tokens.styles.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Tokens/Tokens.stories.tsx, packages/plasma-new-hope/src/examples/plasma_web/components/Tokens/Tokens.stories.tsx, packages/plasma-web/src/components/Tokens/Tokens.stories.tsx, packages/plasma-web/src/components/Tokens/Tokens.styles.ts, packages/sdds-cs/src/components/Tokens/Tokens.stories.tsx, packages/sdds-cs/src/components/Tokens/Tokens.styles.ts, packages/sdds-dfa/src/components/Tokens/Tokens.stories.tsx, packages/sdds-dfa/src/components/Tokens/Tokens.styles.ts, packages/sdds-finportal/src/components/Tokens/Tokens.stories.tsx, packages/sdds-finportal/src/components/Tokens/Tokens.styles.ts, packages/sdds-insol/src/components/Tokens/Tokens.stories.tsx, packages/sdds-insol/src/components/Tokens/Tokens.styles.ts, packages/sdds-serv/src/components/Tokens/Tokens.stories.tsx, packages/sdds-serv/src/components/Tokens/Tokens.styles.ts
- в stories с выводом цветовых токенов добавлены название и тон цвета
Stories для цветовых токенов приведены в соответствие с макетами
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.282.1-canary.1783.13392666998.0
npm install @salutejs/plasma-b2c@1.524.1-canary.1783.13392666998.0
npm install @salutejs/plasma-giga@0.251.1-canary.1783.13392666998.0
npm install @salutejs/plasma-new-hope@0.270.1-canary.1783.13392666998.0
npm install @salutejs/plasma-web@1.526.1-canary.1783.13392666998.0
npm install @salutejs/sdds-cs@0.259.1-canary.1783.13392666998.0
npm install @salutejs/sdds-dfa@0.254.1-canary.1783.13392666998.0
npm install …
```
=> PLASMA-4096: update color tokens stories for packages

packages/plasma-new-hope/src/components/Steps/Steps.tokens.ts, packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.styles.ts, packages/sdds-insol/api/sdds-insol.api.md, packages/sdds-insol/src/components/Steps/Steps.config.ts, packages/sdds-insol/src/components/Steps/Steps.stories.tsx
- исправлен `background`, `cursor`
- добавлен **новый** `view accent`
- новый view, фиксы
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.284.0-canary.1776.13400228272.0
npm install @salutejs/plasma-b2c@1.526.0-canary.1776.13400228272.0
npm install @salutejs/plasma-giga@0.253.0-canary.1776.13400228272.0
npm install @salutejs/plasma-new-hope@0.272.0-canary.1776.13400228272.0
npm install @salutejs/plasma-web@1.528.0-canary.1776.13400228272.0
npm install @salutejs/sdds-cs@0.261.0-canary.1776.13400228272.0
npm install @salutejs/sdds-dfa@0.256.0-canary.1776.13400228272.0
npm install @salutejs/sdds-finportal@0.249.0-canary.1776.13400228272.0
npm install …
```
=> PLASMA-4486: add insol Step accent view

scaffold/template-docs/docs/intro.mdx, website/sdds-insol-docs/docs/intro.mdx
-   Добавлены примеры использования препроцессора `sass` в документацию на главной странице
=> PLASMA-4357: docs(sdds-inosl-docs): Add `sass` examples for intro.mdx

website/plasma-giga-docs/docs/_examples/_init_next_app.mdx, website/plasma-giga-docs/docs/_examples/_init_web_app.mdx, website/plasma-giga-docs/docs/_theme-switch/theme-switch-css-module.mdx, website/plasma-giga-docs/docs/_theme-switch/theme-switch-css.mdx, website/plasma-giga-docs/docs/_theme-switch/theme-switch-sass-module.mdx, website/plasma-giga-docs/docs/_theme-switch/theme-switch-sass.mdx, website/plasma-giga-docs/docs/_theme-switch/theme-switch-sc.mdx, website/plasma-giga-docs/docs/_theme-switch/theme-switch.mdx, website/plasma-giga-docs/docs/_theme-turn-on/theme-turn-on-css-module.mdx, website/plasma-giga-docs/docs/_theme-turn-on/theme-turn-on-css.mdx, website/plasma-giga-docs/docs/_theme-turn-on/theme-turn-on-sass-module.mdx, website/plasma-giga-docs/docs/_theme-turn-on/theme-turn-on-sass.mdx, website/plasma-giga-docs/docs/_theme-turn-on/theme-turn-on-sc.mdx, website/plasma-giga-docs/docs/_theme-turn-on/theme-turn-on.mdx, website/plasma-giga-docs/docs/_utils/_tip-css-modules.mdx, website/plasma-giga-docs/docs/_utils/_tip-processing-styles.mdx, website/plasma-giga-docs/docs/form/ReactHookForm.mdx, website/plasma-giga-docs/docs/intro.mdx, website/plasma-giga-docs/docs/next.mdx, website/plasma-giga-docs/docs/recommendations.mdx, website/plasma-giga-docs/docs/tokens.mdx, website/plasma-giga-docs/src/theme/ReactLiveScope/index.tsx
=> PLASMA-4385: update docs

website/plasma-website/components/icons/ArrowRight.tsx, website/plasma-website/components/icons/ArrowTopRight.tsx, website/plasma-website/components/index.ts, website/plasma-website/components/main/Header.tsx, website/plasma-website/components/main/Heading.tsx, website/plasma-website/components/main/LinkItem.tsx
- добавлены новые компоненты в рамках редизайна
=> PLASMA-4138: website redesign

.github/workflows/documentation-deploy-release-branch.yml
Исправления сделаны на базе того как мы сейчас реализуем deploy для pr's + master
То есть собираем без каких либо условий и проверок того, что изменилось
Тестовый стенд - https://github.com/Yakutoc/plasma-dev-stage/actions/runs/13650444984?pr=59
=> plasma-infra: Refactoring workflow for deploy release pr 

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/SelectNative/SelectNative.tsx, packages/plasma-new-hope/src/components/Select/Select.tsx, packages/plasma-new-hope/src/components/Select/ui/SelectNative/SelectNative.tsx, website/plasma-b2c-docs/docs/components/Combobox.mdx, website/plasma-b2c-docs/docs/components/Select.mdx, website/plasma-b2c-docs/src/theme/ReactLiveScope/index.tsx, website/plasma-giga-docs/docs/components/Combobox.mdx, website/plasma-giga-docs/docs/components/Select.mdx, website/plasma-giga-docs/src/theme/ReactLiveScope/index.tsx, website/plasma-web-docs/docs/components/Combobox.mdx, website/plasma-web-docs/docs/components/Select.mdx, website/plasma-web-docs/src/theme/ReactLiveScope/index.tsx, website/sdds-cs-docs/docs/components/Combobox.mdx, website/sdds-cs-docs/docs/components/Select.mdx, website/sdds-cs-docs/src/theme/ReactLiveScope/index.tsx, website/sdds-dfa-docs/docs/components/Combobox.mdx, website/sdds-dfa-docs/docs/components/Select.mdx, website/sdds-dfa-docs/src/theme/ReactLiveScope/index.tsx, website/sdds-insol-docs/docs/components/Combobox.mdx, website/sdds-insol-docs/docs/components/Select.mdx, website/sdds-insol-docs/src/theme/ReactLiveScope/index.tsx, website/sdds-serv-docs/docs/components/Combobox.mdx, website/sdds-serv-docs/docs/components/Select.mdx, website/sdds-serv-docs/src/theme/ReactLiveScope/index.tsx
- Добавлена документация по использованию `react-hook-form` с помощью `Controller`
- Добавлена документация по использованию `react-hook-form` с помощью `Controller`
- Исправлена работа документации в разделе `Формы`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.310.0-canary.1813.13851398113.0
npm install @salutejs/plasma-b2c@1.552.0-canary.1813.13851398113.0
npm install @salutejs/plasma-giga@0.279.0-canary.1813.13851398113.0
npm install @salutejs/plasma-new-hope@0.296.0-canary.1813.13851398113.0
npm install @salutejs/plasma-web@1.554.0-canary.1813.13851398113.0
npm install @salutejs/sdds-cs@0.288.0-canary.1813.13851398113.0
npm install …
```
=> PLASMA-4427: Add docs rch with controller in combobox and select

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/ui/SelectNative/SelectNative.tsx, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/utils/getRemovedElement.ts, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/utils/index.ts, packages/plasma-new-hope/src/components/Select/Select.tsx, packages/plasma-new-hope/src/components/Select/Select.types.ts, packages/plasma-new-hope/src/components/Select/ui/SelectNative/SelectNative.tsx, packages/plasma-new-hope/src/components/Select/ui/Target/Target.types.ts, packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.tsx, packages/plasma-new-hope/src/components/Select/utils/getRemovedElement.ts, packages/plasma-new-hope/src/components/Select/utils/index.ts
- расширен пропс onChange - в него добавлен item вторым параметром;
расширен пропс onChange - в него добавлен item вторым параметром;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.314.0-canary.1831.13895474823.0
npm install @salutejs/plasma-b2c@1.556.0-canary.1831.13895474823.0
npm install @salutejs/plasma-giga@0.283.0-canary.1831.13895474823.0
npm install @salutejs/plasma-new-hope@0.300.0-canary.1831.13895474823.0
npm install @salutejs/plasma-web@1.558.0-canary.1831.13895474823.0
npm install @salutejs/sdds-cs@0.292.0-canary.1831.13895474823.0
npm install @salutejs/sdds-dfa@0.286.0-canary.1831.13895474823.0
npm install …
```
=> PLASMA-4647: add item as second parameter to onChange prop

packages/plasma-giga/api/plasma-giga.api.md, packages/plasma-giga/src/components/Button/Button.config.ts, packages/plasma-giga/src/components/ButtonGroup/ButtonGroup.config.ts, packages/plasma-giga/src/components/ButtonGroup/ButtonGroup.stories.tsx, packages/plasma-giga/src/components/IconButton/IconButton.config.ts, packages/plasma-giga/src/components/IconButton/IconButton.stories.tsx
- Добавлен размер `xl`
- Добавлен размер `xl`
- Добавлен размер `xl`
<details>
<br />
```bash
npm install @salutejs/plasma-giga@0.283.1-canary.1843.13897151661.0
yarn add @salutejs/plasma-giga@0.283.1-canary.1843.13897151661.0
```
</details>
=> PLASMA-4550: add xl button to plasma-giga

packages/plasma-new-hope/src/components/Select/Select.template-doc.mdx, packages/plasma-new-hope/src/components/Select/Select.types.ts, packages/plasma-new-hope/src/components/Select/ui/Target/Target.tsx, website/plasma-b2c-docs/docs/components/Select.mdx, website/plasma-giga-docs/docs/components/Select.mdx, website/plasma-web-docs/docs/components/Select.mdx, website/sdds-cs-docs/docs/components/Select.mdx, website/sdds-dfa-docs/docs/components/Select.mdx, website/sdds-insol-docs/docs/components/Select.mdx, website/sdds-serv-docs/docs/components/Select.mdx
- добавлено свойство opened в renderTarget в Select
Добавлено свойство opened в renderTarget в Select
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.315.0-canary.1846.13897036566.0
npm install @salutejs/plasma-b2c@1.557.0-canary.1846.13897036566.0
npm install @salutejs/plasma-giga@0.284.0-canary.1846.13897036566.0
npm install @salutejs/plasma-new-hope@0.301.0-canary.1846.13897036566.0
npm install @salutejs/plasma-web@1.559.0-canary.1846.13897036566.0
npm install @salutejs/sdds-cs@0.293.0-canary.1846.13897036566.0
npm install @salutejs/sdds-dfa@0.287.0-canary.1846.13897036566.0
npm install @salutejs/sdds-finportal@0.280.0-canary.1846.13897036566.0
npm …
```
=> PLASMA-4583: add opened to Select renderTarget

packages/plasma-new-hope/src/components/Range/Range.styles.ts, packages/plasma-new-hope/src/components/Range/Range.tokens.ts, packages/plasma-new-hope/src/components/Range/Range.tsx, packages/plasma-new-hope/src/components/Range/variations/_size/base.ts, packages/plasma-new-hope/src/components/Range/variations/_view/base.ts, packages/sdds-insol/api/sdds-insol.api.md, packages/sdds-insol/src/components/Range/Range.config.ts, packages/sdds-insol/src/components/Range/Range.stories.tsx
- добавлен новый размер `xl`
- актуализированы остальные размеры согласно макетам
- актуализированы `view` согласно макетам
Добавлен новый размер `xl`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.320.0-canary.1845.13942755213.0
npm install @salutejs/plasma-b2c@1.562.0-canary.1845.13942755213.0
npm install @salutejs/plasma-giga@0.289.0-canary.1845.13942755213.0
npm install @salutejs/plasma-new-hope@0.306.0-canary.1845.13942755213.0
npm install @salutejs/plasma-web@1.564.0-canary.1845.13942755213.0
npm install @salutejs/sdds-cs@0.298.0-canary.1845.13942755213.0
npm install @salutejs/sdds-dfa@0.292.0-canary.1845.13942755213.0
npm install …
```
=> PLASMA-4603: add xl size to Range

packages/sdds-cs/src/components/Button/Button.tsx
- добавлена обработка состояния isLoading 
Продуктовый запрос от команды
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.328.0-canary.1879.14165452799.0
npm install @salutejs/plasma-b2c@1.570.0-canary.1879.14165452799.0
npm install @salutejs/plasma-core@1.195.0-canary.1879.14165452799.0
npm install @salutejs/plasma-giga@0.297.0-canary.1879.14165452799.0
npm install @salutejs/plasma-hope@1.338.0-canary.1879.14165452799.0
npm install @salutejs/plasma-icons@1.216.0-canary.1879.14165452799.0
npm install @salutejs/plasma-new-hope@0.314.0-canary.1879.14165452799.0
npm install @salutejs/plasma-tokens@1.111.0-canary.1879.14165452799.0
npm install …
```
=> PLASMA-4715: processing isLoading state

packages/themes/core-themes/package.json, packages/themes/plasma-themes/package.json, packages/themes/sdds-themes/package.json
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.328.0-canary.1883.14198911738.0
npm install @salutejs/plasma-b2c@1.570.0-canary.1883.14198911738.0
npm install @salutejs/plasma-core@1.195.0-canary.1883.14198911738.0
npm install @salutejs/plasma-giga@0.297.0-canary.1883.14198911738.0
npm install @salutejs/plasma-hope@1.338.0-canary.1883.14198911738.0
npm install @salutejs/plasma-icons@1.216.0-canary.1883.14198911738.0
npm install @salutejs/plasma-new-hope@0.314.0-canary.1883.14198911738.0
npm install @salutejs/plasma-tokens@1.111.0-canary.1883.14198911738.0
npm install @salutejs/plasma-ui@1.314.0-canary.1883.14198911738.0
npm install …
```
=> feat(*-themes): Update version

packages/plasma-new-hope/src/components/Button/Button.tsx, packages/plasma-new-hope/src/components/Chip/Chip.tsx, packages/plasma-new-hope/src/components/TextArea/TextArea.tsx, packages/plasma-new-hope/src/components/TextField/TextField.tsx
Чистка console warning  
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.329.2-canary.1881.14211036395.0
npm install @salutejs/plasma-b2c@1.571.2-canary.1881.14211036395.0
npm install @salutejs/plasma-giga@0.298.2-canary.1881.14211036395.0
npm install @salutejs/plasma-new-hope@0.315.2-canary.1881.14211036395.0
npm install @salutejs/plasma-web@1.573.2-canary.1881.14211036395.0
npm install @salutejs/sdds-clfd-auto@0.302.2-canary.1881.14211036395.0
npm install @salutejs/sdds-cs@0.307.2-canary.1881.14211036395.0
npm install @salutejs/sdds-dfa@0.301.2-canary.1881.14211036395.0
npm install @salutejs/sdds-finportal@0.294.2-canary.1881.14211036395.0
npm install …
```
=> PLASMA-4410:  Clear warning into console 

packages/plasma-b2c/src/components/Cell/Cell.stories.tsx, packages/plasma-b2c/src/components/IconButton/IconButton.stories.tsx, packages/plasma-giga/src/components/Cell/Cell.stories.tsx, packages/plasma-giga/src/components/IconButton/IconButton.stories.tsx, packages/plasma-new-hope/src/components/Cell/Cell.template-doc.mdx, packages/plasma-web/src/components/Cell/Cell.component-test.tsx, packages/plasma-web/src/components/Cell/Cell.stories.tsx, packages/plasma-web/src/components/IconButton/IconButton.stories.tsx, packages/sdds-cs/src/components/IconButton/IconButton.stories.tsx, packages/sdds-dfa/src/components/Cell/Cell.stories.tsx, packages/sdds-dfa/src/components/IconButton/IconButton.stories.tsx, packages/sdds-finportal/src/components/Cell/Cell.stories.tsx, packages/sdds-finportal/src/components/IconButton/IconButton.stories.tsx, packages/sdds-serv/src/components/Cell/Cell.stories.tsx, packages/sdds-serv/src/components/IconButton/IconButton.stories.tsx, website/plasma-b2c-docs/docs/components/Cell.mdx, website/plasma-giga-docs/docs/components/Cell.mdx, website/plasma-web-docs/docs/components/Cell.mdx, website/plasma-website/components/palette/PaletteColorPage.tsx, website/plasma-website/components/palette/TextReadble.tsx, website/sdds-cs-docs/docs/components/Cell.mdx, website/sdds-dfa-docs/docs/components/Cell.mdx, website/sdds-insol-docs/docs/components/Cell.mdx, website/sdds-serv-docs/docs/components/Cell.mdx
- исправлены опечатки в "color=inherit"
- исправлены опечатки в "color=inherit"
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.318.1-canary.1857.13940611780.0
npm install @salutejs/plasma-b2c@1.560.1-canary.1857.13940611780.0
npm install @salutejs/plasma-giga@0.287.1-canary.1857.13940611780.0
npm install @salutejs/plasma-new-hope@0.304.1-canary.1857.13940611780.0
npm install @salutejs/plasma-web@1.562.1-canary.1857.13940611780.0
npm install @salutejs/sdds-cs@0.296.1-canary.1857.13940611780.0
npm install @salutejs/sdds-dfa@0.290.1-canary.1857.13940611780.0
npm install @salutejs/sdds-finportal@0.283.1-canary.1857.13940611780.0
npm install …
```
=> fix(plasma-*): fix `color="inherit"` typo

packages/plasma-b2c/src/components/Tree/Tree.component-test.tsx, packages/plasma-new-hope/src/components/Tree/Tree.template-doc.mdx, packages/plasma-new-hope/src/components/Tree/Tree.tsx, packages/plasma-new-hope/src/components/Tree/Tree.types.ts, packages/plasma-web/src/components/Tree/Tree.component-test.tsx, website/plasma-b2c-docs/docs/components/Tree.mdx, website/plasma-giga-docs/docs/components/Tree.mdx, website/plasma-web-docs/docs/components/Tree.mdx, website/sdds-cs-docs/docs/components/Tree.mdx, website/sdds-dfa-docs/docs/components/Tree.mdx, website/sdds-insol-docs/docs/components/Tree.mdx, website/sdds-serv-docs/docs/components/Tree.mdx
- в документацию добавлен пример с виртуализацией;
- в документацию добавлен пример с виртуализацией;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.334.1-canary.1914.14404950905.0
npm install @salutejs/plasma-b2c@1.576.1-canary.1914.14404950905.0
npm install @salutejs/plasma-giga@0.303.1-canary.1914.14404950905.0
npm install @salutejs/plasma-hope@1.338.1-canary.1914.14404950905.0
npm install @salutejs/plasma-icons@1.216.1-canary.1914.14404950905.0
npm install @salutejs/plasma-new-hope@0.320.1-canary.1914.14404950905.0
npm install @salutejs/plasma-ui@1.314.1-canary.1914.14404950905.0
npm install @salutejs/plasma-web@1.578.1-canary.1914.14404950905.0
npm …
```
=> PLASMA-4408: добавлен пример с виртуализацией в Tree

packages/sdds-cs/src/components/Indicator/Indicator.config.tsx, packages/sdds-cs/src/components/Indicator/Indicator.stories.tsx, packages/sdds-cs/src/components/Rating/Rating.config.ts, packages/sdds-cs/src/components/Rating/Rating.stories.tsx, packages/sdds-cs/src/components/Rating/Rating.ts, packages/sdds-cs/src/components/Rating/index.ts
-   Изменен конфиг в соответсвии с дизайном
-   Изменен конфиг в соответсвии с дизайном
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.334.1-canary.1904.14479435497.0
npm install @salutejs/plasma-b2c@1.576.1-canary.1904.14479435497.0
npm install @salutejs/plasma-giga@0.303.1-canary.1904.14479435497.0
npm install @salutejs/plasma-hope@1.338.1-canary.1904.14479435497.0
npm install @salutejs/plasma-icons@1.216.1-canary.1904.14479435497.0
npm install @salutejs/plasma-new-hope@0.320.1-canary.1904.14479435497.0
npm install @salutejs/plasma-ui@1.314.1-canary.1904.14479435497.0
npm install @salutejs/plasma-web@1.578.1-canary.1904.14479435497.0
npm install …
```
=> PLASMA-4608: Edit config for rating and indicator

packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.styles.ts, packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.tsx, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.styles.ts, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx, packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.styles.tsx, packages/plasma-new-hope/src/components/Select/ui/Target/ui/Textfield/Textfield.tsx
- При нажатии на `helperText` фокус на `textfield` не происходит
- При нажатии на `helperText` список не раскрывается
- При нажатии на `helperText` список не раскрывается
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.334.1-canary.1913.14480249004.0
npm install @salutejs/plasma-b2c@1.576.1-canary.1913.14480249004.0
npm install @salutejs/plasma-giga@0.303.1-canary.1913.14480249004.0
npm install @salutejs/plasma-hope@1.338.1-canary.1913.14480249004.0
npm install @salutejs/plasma-icons@1.216.1-canary.1913.14480249004.0
npm install @salutejs/plasma-new-hope@0.320.1-canary.1913.14480249004.0
npm install @salutejs/plasma-ui@1.314.1-canary.1913.14480249004.0 …
```
=> PLASMA-4679: Remove popover event open to click helperText

packages/plasma-new-hope/package-lock.json, packages/plasma-new-hope/package.json, packages/plasma-new-hope/src/components/Toast/ToastNew/ToastNew.styles.ts, packages/plasma-new-hope/src/components/Toast/ToastNew/ToastNew.tokens.ts, packages/plasma-new-hope/src/components/Toast/ToastNew/ToastNew.tsx, packages/plasma-new-hope/src/components/Toast/ToastNew/ToastNew.types.ts, packages/plasma-new-hope/src/components/Toast/ToastNew/index.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Toast/Toast.stories.tsx, packages/plasma-new-hope/src/examples/plasma_b2c/components/ToastNew/Toast.config.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/ToastNew/ToastNew.stories.tsx, packages/plasma-new-hope/src/examples/plasma_b2c/components/ToastNew/ToastNew.ts, packages/plasma-new-hope/src/index.ts, packages/sdds-cs/src/components/Toast/Toast.stories.tsx, packages/sdds-cs/src/components/ToastNew/ToastNew.config.ts, packages/sdds-cs/src/components/ToastNew/ToastNew.stories.tsx, packages/sdds-cs/src/components/ToastNew/ToastNew.tsx, packages/sdds-cs/src/components/ToastNew/index.ts, packages/sdds-cs/src/index.ts, website/sdds-cs-docs/docs/components/Toast.mdx, website/sdds-cs-docs/docs/components/ToastLegacy.mdx
- обновлена архитектура компонента, улучшен контракт взаимодействия с тостами;
Переработан компонент Toast. Изменения видны только для sdds-cs.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.0-canary.1915.14487433768.0
npm install @salutejs/plasma-b2c@1.577.0-canary.1915.14487433768.0
npm install @salutejs/plasma-core@1.196.0-canary.1915.14487433768.0
npm install @salutejs/plasma-giga@0.304.0-canary.1915.14487433768.0
npm install @salutejs/plasma-hope@1.339.0-canary.1915.14487433768.0
npm install @salutejs/plasma-icons@1.217.0-canary.1915.14487433768.0
npm install @salutejs/plasma-new-hope@0.321.0-canary.1915.14487433768.0
npm install …
```
=> PLASMA-4488: переработка компонента Toast [sdds-cs]

website/plasma-website/components/Link.tsx, website/plasma-website/components/main/Menu/Menu.styles.ts, website/plasma-website/components/main/Product/Product.styles.ts, website/plasma-website/pages/index.tsx
- убрали text-decoration для ссылок в меню
- исправлены отступы в адаптиве  
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.334.1-canary.1917.14487866851.0
npm install @salutejs/plasma-b2c@1.576.1-canary.1917.14487866851.0
npm install @salutejs/plasma-core@1.195.1-canary.1917.14487866851.0
npm install @salutejs/plasma-giga@0.303.1-canary.1917.14487866851.0
npm install @salutejs/plasma-hope@1.338.1-canary.1917.14487866851.0
npm install @salutejs/plasma-icons@1.216.1-canary.1917.14487866851.0
npm install @salutejs/plasma-new-hope@0.320.1-canary.1917.14487866851.0
npm install @salutejs/plasma-ui@1.314.1-canary.1917.14487866851.0
npm install …
```
=> plasma-docs: Исправления для главной страницы 

packages/plasma-b2c/src/components/Sheet/Sheet.config.tsx, packages/plasma-b2c/src/components/Sheet/Sheet.stories.tsx, packages/plasma-giga/src/components/Sheet/Sheet.config.tsx, packages/plasma-giga/src/components/Sheet/Sheet.stories.tsx, packages/plasma-new-hope/src/components/Sheet/Sheet.styles.ts, packages/plasma-new-hope/src/components/Sheet/Sheet.tokens.ts, packages/plasma-new-hope/src/components/Sheet/Sheet.tsx, packages/plasma-new-hope/src/components/Sheet/Sheet.types.ts, packages/plasma-new-hope/src/components/Sheet/variations/_handlePlacement/base.ts, packages/plasma-new-hope/src/components/Sheet/variations/_handlePlacement/tokens.json, packages/plasma-new-hope/src/examples/plasma_b2c/components/Sheet/Sheet.config.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Sheet/Sheet.stories.tsx, packages/plasma-new-hope/src/examples/plasma_web/components/Sheet/Sheet.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Sheet/Sheet.stories.tsx, packages/plasma-web/src/components/Sheet/Sheet.config.tsx, packages/plasma-web/src/components/Sheet/Sheet.stories.tsx, packages/sdds-clfd-auto/src/components/Sheet/Sheet.config.tsx, packages/sdds-clfd-auto/src/components/Sheet/Sheet.stories.tsx, packages/sdds-cs/src/components/Sheet/Sheet.config.tsx, packages/sdds-cs/src/components/Sheet/Sheet.stories.tsx, packages/sdds-dfa/src/components/Sheet/Sheet.config.tsx, packages/sdds-dfa/src/components/Sheet/Sheet.stories.tsx, packages/sdds-finportal/src/components/Sheet/Sheet.config.tsx, packages/sdds-finportal/src/components/Sheet/Sheet.stories.tsx, packages/sdds-insol/src/components/Sheet/Sheet.config.tsx, packages/sdds-insol/src/components/Sheet/Sheet.stories.tsx, packages/sdds-serv/src/components/Sheet/Sheet.config.tsx, packages/sdds-serv/src/components/Sheet/Sheet.stories.tsx
- Добавлен props `handlePlacement`
- Добавлен пример в `storybook` с полноэкранным `sheet`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.0-canary.1892.14490584370.0
npm install @salutejs/plasma-b2c@1.577.0-canary.1892.14490584370.0
npm install @salutejs/plasma-core@1.196.0-canary.1892.14490584370.0
npm install @salutejs/plasma-giga@0.304.0-canary.1892.14490584370.0
npm install @salutejs/plasma-hope@1.339.0-canary.1892.14490584370.0
npm install @salutejs/plasma-icons@1.217.0-canary.1892.14490584370.0
npm install @salutejs/plasma-new-hope@0.321.0-canary.1892.14490584370.0
npm install @salutejs/plasma-ui@1.315.0-canary.1892.14490584370.0
npm install …
```
=> PLASMA-3596: Sheet HandlePlacement

packages/plasma-new-hope/src/components/Toast/ToastNew/ToastNew.tsx, packages/plasma-new-hope/src/components/Toast/ToastNew/ToastNew.types.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/ToastNew/ToastNew.stories.tsx, packages/sdds-cs/src/components/ToastNew/ToastNew.stories.tsx
Убрано стекирование тостов. Сейчас при появлении тоста предыдущий скрывается.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.0-canary.1920.14493102517.0
npm install @salutejs/plasma-b2c@1.577.0-canary.1920.14493102517.0
npm install @salutejs/plasma-core@1.196.0-canary.1920.14493102517.0
npm install @salutejs/plasma-giga@0.304.0-canary.1920.14493102517.0
npm install @salutejs/plasma-hope@1.339.0-canary.1920.14493102517.0
npm install @salutejs/plasma-icons@1.217.0-canary.1920.14493102517.0
npm install @salutejs/plasma-new-hope@0.321.0-canary.1920.14493102517.0
npm install @salutejs/plasma-ui@1.315.0-canary.1920.14493102517.0
npm install …
```
=> sdds-cs: Remove stacking [toast]

packages/themes/plasma-themes/src/css/plasma_giga.module.css, packages/themes/plasma-themes/src/css/plasma_giga__dark.css, packages/themes/plasma-themes/src/css/plasma_giga__light.css, packages/themes/plasma-themes/src/css/plasma_giga_app.module.css, packages/themes/plasma-themes/src/css/plasma_giga_app__dark.css, packages/themes/plasma-themes/src/css/plasma_giga_app__light.css, packages/themes/plasma-themes/src/themes/plasma_giga__dark.ts, packages/themes/plasma-themes/src/themes/plasma_giga__light.ts, packages/themes/plasma-themes/src/themes/plasma_giga_app__dark.ts, packages/themes/plasma-themes/src/themes/plasma_giga_app__light.ts, packages/themes/plasma-themes/src/tokens/plasma_giga/index.ts, packages/themes/plasma-themes/src/tokens/plasma_giga_app/index.ts, packages/themes/sdds-themes/src/css/sdds_serv.module.css, packages/themes/sdds-themes/src/css/sdds_serv__dark.css, packages/themes/sdds-themes/src/css/sdds_serv__light.css, packages/themes/sdds-themes/src/themes/sdds_serv__dark.ts, packages/themes/sdds-themes/src/themes/sdds_serv__light.ts, packages/themes/sdds-themes/src/tokens/sdds_serv/index.ts, utils/plasma-sb-utils/src/helpers/numberTokens.ts, utils/plasma-sb-utils/src/helpers/typographyTokens.ts
- Переделана размерность токенов из px в rem.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.336.0-canary.1933.14614537450.0
npm install @salutejs/plasma-b2c@1.578.0-canary.1933.14614537450.0
npm install @salutejs/plasma-giga@0.305.0-canary.1933.14614537450.0
npm install @salutejs/plasma-hope@1.340.0-canary.1933.14614537450.0
npm install @salutejs/plasma-new-hope@0.322.0-canary.1933.14614537450.0
npm install @salutejs/plasma-ui@1.316.0-canary.1933.14614537450.0
npm install @salutejs/plasma-web@1.580.0-canary.1933.14614537450.0
npm install @salutejs/sdds-clfd-auto@0.309.0-canary.1933.14614537450.0
npm install …
```
=> PLASMA-4648: Update `sdds_serv` theme

packages/plasma-b2c/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/plasma-b2c/src/components/Tabs/vertical/VerticalTabItem.config.ts, packages/plasma-giga/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/plasma-giga/src/components/Tabs/vertical/VerticalTabItem.config.ts, packages/plasma-new-hope/src/components/Tabs/tokens.ts, packages/plasma-new-hope/src/components/Tabs/ui/horizontal/HorizontalTabItem/HorizontalTabItem.styles.ts, packages/plasma-new-hope/src/components/Tabs/ui/vertical/VerticalTabItem/VerticalTabItem.styles.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Tabs/vertical/VerticalTabItem.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Tabs/vertical/VerticalTabItem.config.ts, packages/plasma-web/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/plasma-web/src/components/Tabs/vertical/VerticalTabItem.config.ts, packages/sdds-cs/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/sdds-cs/src/components/Tabs/vertical/VerticalTabItem.config.ts, packages/sdds-dfa/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/sdds-dfa/src/components/Tabs/vertical/VerticalTabItem.config.ts, packages/sdds-finportal/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/sdds-finportal/src/components/Tabs/vertical/VerticalTabItem.config.ts, packages/sdds-insol/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/sdds-insol/src/components/Tabs/vertical/VerticalTabItem.config.ts, packages/sdds-serv/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/sdds-serv/src/components/Tabs/vertical/VerticalTabItem.config.ts
- добавлен токен для регулирования свойства cursor, по-умолчанию `pointer`  
- добавлен токен для регулирования свойства cursor, по-умолчанию `default`  
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.1-canary.1943.14662029036.0
npm install @salutejs/plasma-b2c@1.577.1-canary.1943.14662029036.0
npm install @salutejs/plasma-giga@0.304.1-canary.1943.14662029036.0
npm install @salutejs/plasma-hope@1.339.1-canary.1943.14662029036.0
npm install @salutejs/plasma-new-hope@0.321.1-canary.1943.14662029036.0
npm install @salutejs/plasma-ui@1.315.1-canary.1943.14662029036.0
npm install @salutejs/plasma-web@1.579.1-canary.1943.14662029036.0
npm install …
```
=> PLASMA-4962: Add `tabsTokens.itemCursor`

packages/plasma-b2c/src/components/Combobox/Combobox.tsx, packages/plasma-b2c/src/components/Combobox/index.ts, packages/plasma-giga/src/components/Combobox/Combobox.tsx, packages/plasma-giga/src/components/Combobox/index.ts, packages/plasma-new-hope/src/components/Combobox/Combobox.template-doc.mdx, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/index.ts, packages/plasma-new-hope/src/components/Combobox/index.ts, packages/plasma-web/src/components/Combobox/Combobox.tsx, packages/plasma-web/src/components/Combobox/index.ts, packages/sdds-clfd-auto/src/components/Combobox/Combobox.tsx, packages/sdds-clfd-auto/src/components/Combobox/index.ts, packages/sdds-cs/src/components/Combobox/Combobox.tsx, packages/sdds-cs/src/components/Combobox/index.ts, packages/sdds-dfa/src/components/Combobox/Combobox.tsx, packages/sdds-dfa/src/components/Combobox/index.ts, packages/sdds-finportal/src/components/Combobox/Combobox.tsx, packages/sdds-finportal/src/components/Combobox/index.ts, packages/sdds-insol/src/components/Combobox/Combobox.tsx, packages/sdds-insol/src/components/Combobox/index.ts, packages/sdds-serv/src/components/Combobox/Combobox.tsx, packages/sdds-serv/src/components/Combobox/index.ts, website/plasma-b2c-docs/docs/components/Combobox.mdx, website/plasma-giga-docs/docs/components/Combobox.mdx, website/plasma-web-docs/docs/components/Combobox.mdx, website/sdds-cs-docs/docs/components/Combobox.mdx, website/sdds-dfa-docs/docs/components/Combobox.mdx, website/sdds-insol-docs/docs/components/Combobox.mdx, website/sdds-serv-docs/docs/components/Combobox.mdx
- актуализирована документация;
- добавлен явный экспорт типа ComboboxItemOption;
- актуализирована документация;
- добавлен явный экспорт типа ComboboxItemOption;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.336.0-canary.1925.14706826356.0
npm install @salutejs/plasma-b2c@1.578.0-canary.1925.14706826356.0
npm install @salutejs/plasma-giga@0.305.0-canary.1925.14706826356.0
npm install @salutejs/plasma-hope@1.340.0-canary.1925.14706826356.0
npm install @salutejs/plasma-new-hope@0.322.0-canary.1925.14706826356.0
npm install @salutejs/plasma-ui@1.316.0-canary.1925.14706826356.0
npm install @salutejs/plasma-web@1.580.0-canary.1925.14706826356.0
npm install …
```
=> PLASMA-4815: апдейт доки для Combobox

packages/sdds-cs/src/components/Checkbox/Checkbox.config.ts, packages/sdds-cs/src/components/Checkbox/Checkbox.stories.tsx, packages/sdds-cs/src/components/Radiobox/Radiobox.config.ts
- Исправлен баг с `border` при отжатом `checkbox`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.1-canary.1944.14717616818.0
npm install @salutejs/plasma-b2c@1.577.1-canary.1944.14717616818.0
npm install @salutejs/plasma-giga@0.304.1-canary.1944.14717616818.0
npm install @salutejs/plasma-hope@1.339.1-canary.1944.14717616818.0
npm install @salutejs/plasma-new-hope@0.321.1-canary.1944.14717616818.0
npm install @salutejs/plasma-ui@1.315.1-canary.1944.14717616818.0
npm install @salutejs/plasma-web@1.579.1-canary.1944.14717616818.0
npm install @salutejs/sdds-clfd-auto@0.308.1-canary.1944.14717616818.0
npm install …
```
=> PLASMA-4983: Fix border checkbox SDDS-CS

packages/sdds-cs/src/components/Autocomplete/Autocomplete.config.ts, packages/sdds-cs/src/components/Button/Button.config.ts, packages/sdds-cs/src/components/Button/Button.stories.tsx, packages/sdds-cs/src/components/ButtonGroup/ButtonGroup.config.ts, packages/sdds-cs/src/components/Combobox/Combobox.config.ts, packages/sdds-cs/src/components/IconButton/IconButton.config.ts, packages/sdds-cs/src/components/Pagination/Pagination.config.ts, packages/sdds-cs/src/components/Select/Select.config.ts, packages/sdds-cs/src/components/TextArea/TextArea.config.ts, packages/sdds-cs/src/components/TextField/TextField.config.ts
- Обновлен конфиг в соответствии с дизайном
- Обновлен конфиг в соответствии с дизайном
- Обновлен конфиг в соответствии с дизайном
Button:
Textfield:
Textarea:
Select:
Autocomplete:
Combobox:
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.1-canary.1940.14719818996.0
npm install @salutejs/plasma-b2c@1.577.1-canary.1940.14719818996.0
npm install @salutejs/plasma-giga@0.304.1-canary.1940.14719818996.0
npm install @salutejs/plasma-hope@1.339.1-canary.1940.14719818996.0
npm install @salutejs/plasma-new-hope@0.321.1-canary.1940.14719818996.0
npm install @salutejs/plasma-ui@1.315.1-canary.1940.14719818996.0
npm install …
```
=> PLASMA-4778: Edit configs SDDS-CS

packages/sdds-cs/src/components/Tree/Tree.config.ts, website/sdds-cs-docs/docs/components/Typography.mdx, website/sdds-insol-docs/docs/components/Typography.mdx
- исправлен токен для `itemBackgroundColorHover` на `--surface-transparent-accent`
- добавлена документация для компонента `TextSlim`  
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.1-canary.1948.14708113539.0
npm install @salutejs/plasma-b2c@1.577.1-canary.1948.14708113539.0
npm install @salutejs/plasma-giga@0.304.1-canary.1948.14708113539.0
npm install @salutejs/plasma-hope@1.339.1-canary.1948.14708113539.0
npm install @salutejs/plasma-new-hope@0.321.1-canary.1948.14708113539.0
npm install @salutejs/plasma-ui@1.315.1-canary.1948.14708113539.0
npm install @salutejs/plasma-web@1.579.1-canary.1948.14708113539.0
npm install …
```
=> plasma-*: Small fixes

website/sdds-insol-docs/docs/components/Card.mdx
- добавлены примеры использования компонента
Добавлены примеры использования Card
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.1-canary.1928.14660799559.0
npm install @salutejs/plasma-b2c@1.577.1-canary.1928.14660799559.0
npm install @salutejs/plasma-giga@0.304.1-canary.1928.14660799559.0
npm install @salutejs/plasma-hope@1.339.1-canary.1928.14660799559.0
npm install @salutejs/plasma-new-hope@0.321.1-canary.1928.14660799559.0
npm install @salutejs/plasma-ui@1.315.1-canary.1928.14660799559.0
npm install @salutejs/plasma-web@1.579.1-canary.1928.14660799559.0
npm install @salutejs/sdds-clfd-auto@0.308.1-canary.1928.14660799559.0
npm install …
```
=> PLASMA-4754: add Card examples

packages/sdds-cs/src/components/Avatar/Avatar.config.tsx, packages/sdds-cs/src/components/Avatar/Avatar.stories.tsx
- Добавлен размер `xxl` согласно макетам
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.336.0-canary.1929.14725863541.0
npm install @salutejs/plasma-b2c@1.578.0-canary.1929.14725863541.0
npm install @salutejs/plasma-giga@0.305.0-canary.1929.14725863541.0
npm install @salutejs/plasma-hope@1.340.0-canary.1929.14725863541.0
npm install @salutejs/plasma-new-hope@0.322.0-canary.1929.14725863541.0
npm install @salutejs/plasma-ui@1.316.0-canary.1929.14725863541.0
npm install @salutejs/plasma-web@1.580.0-canary.1929.14725863541.0
npm install @salutejs/sdds-clfd-auto@0.309.0-canary.1929.14725863541.0
npm install @salutejs/sdds-cs@0.314.0-canary.1929.14725863541.0 …
```
=> PLASMA-4924: add xxl size to avatar

packages/sdds-cs/src/components/Slider/Slider.config.ts, packages/sdds-cs/src/components/Slider/Slider.stories.tsx
- исправлены токены для input в slider range вариации
- исправлены токены для фокусной рамки   
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.335.1-canary.1950.14726761043.0
npm install @salutejs/plasma-b2c@1.577.1-canary.1950.14726761043.0
npm install @salutejs/plasma-giga@0.304.1-canary.1950.14726761043.0
npm install @salutejs/plasma-hope@1.339.1-canary.1950.14726761043.0
npm install @salutejs/plasma-new-hope@0.321.1-canary.1950.14726761043.0
npm install @salutejs/plasma-ui@1.315.1-canary.1950.14726761043.0
npm install @salutejs/plasma-web@1.579.1-canary.1950.14726761043.0
npm install @salutejs/sdds-clfd-auto@0.308.1-canary.1950.14726761043.0
npm …
```
=> PLASMA-4991: fix slider range focus/input

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/utils/filterItems.ts
- исправлен баг, не позволявший вызывать коллбэк `filter` в момент полной очистки инпута;
- исправлен баг, не позволявший вызывать коллбэк `filter` в момент полной очистки инпута;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.336.0-canary.1935.14704837361.0
npm install @salutejs/plasma-b2c@1.578.0-canary.1935.14704837361.0
npm install @salutejs/plasma-giga@0.305.0-canary.1935.14704837361.0
npm install @salutejs/plasma-hope@1.340.0-canary.1935.14704837361.0
npm install @salutejs/plasma-new-hope@0.322.0-canary.1935.14704837361.0
npm install @salutejs/plasma-ui@1.316.0-canary.1935.14704837361.0
npm install …
```
=> PLASMA-4920: Исправлен баг с кастомным фильтром в Combobox

packages/plasma-new-hope/package-lock.json, packages/plasma-new-hope/package.json, packages/plasma-new-hope/src/components/Autocomplete/ui/VirtualList/VirtualList.tsx
В некоторых случаях типы не резолвятся, и выходные компоненты имеют тип `any`. Это происходит из-за того, что компилятор `tsc` не преобразовывает алиасы в процессе компиляции. Открытое [ишью](https://github.com/microsoft/TypeScript/issues/30952). Поэтому была подключена либа `tsc-alias`, она преобразует пути в корректный вид.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.337.0-canary.1955.14967306371.0
npm install @salutejs/plasma-b2c@1.579.0-canary.1955.14967306371.0
npm install @salutejs/plasma-giga@0.306.0-canary.1955.14967306371.0
npm install @salutejs/plasma-new-hope@0.323.0-canary.1955.14967306371.0
npm install …
```
=> plasma-infra: Improved ts aliases

packages/plasma-new-hope/src/components/NumberFormat/NumberFormat.tsx
- исправлено использование `ref`
исправлено использование `ref`
=> plasma-*: Fix forward ref in NumberFormat [Hotfix]

packages/plasma-asdk/src/components/Link/Link.config.tsx, packages/plasma-b2c/src/components/Link/Link.config.tsx, packages/plasma-giga/src/components/Link/Link.config.tsx, packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.styles.ts, packages/plasma-new-hope/src/components/Link/Link.tokens.ts, packages/plasma-new-hope/src/components/Link/Link.tsx, packages/plasma-new-hope/src/components/Link/Link.types.ts, packages/plasma-new-hope/src/components/Link/_disabled/base.ts, packages/plasma-new-hope/src/components/Link/_focused/base.ts, packages/plasma-new-hope/src/components/Link/_view/base.ts, packages/plasma-new-hope/src/components/Link/index.ts, packages/plasma-new-hope/src/examples/plasma_b2c/components/Link/Link.config.ts, packages/plasma-new-hope/src/examples/plasma_web/components/Link/Link.config.ts, packages/plasma-web/src/components/Link/Link.config.tsx, packages/sdds-clfd-auto/src/components/Link/Link.config.tsx, packages/sdds-cs/src/components/Link/Link.config.tsx, packages/sdds-dfa/src/components/Link/Link.config.tsx, packages/sdds-finportal/src/components/Link/Link.config.tsx, packages/sdds-insol/src/components/Link/Link.config.tsx, packages/sdds-serv/src/components/Link/Link.config.tsx
- Изменена архитектура компонента ( добавлены файлы `types`, `tokens` )
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.338.0-canary.1966.15202575775.0
npm install @salutejs/plasma-b2c@1.580.0-canary.1966.15202575775.0
npm install @salutejs/plasma-giga@0.307.0-canary.1966.15202575775.0
npm install @salutejs/plasma-new-hope@0.324.0-canary.1966.15202575775.0
npm install @salutejs/plasma-web@1.582.0-canary.1966.15202575775.0
npm install @salutejs/sdds-clfd-auto@0.311.0-canary.1966.15202575775.0
npm install @salutejs/sdds-crm@0.311.0-canary.1966.15202575775.0
npm install @salutejs/sdds-cs@0.316.0-canary.1966.15202575775.0
npm install …
```
=> PLASMA-3895: Add tokens in link

packages/plasma-b2c/src/components/Progress/Progress.config.ts, packages/plasma-b2c/src/components/Progress/Progress.stories.tsx, packages/plasma-giga/src/components/Progress/Progress.config.ts, packages/plasma-giga/src/components/Progress/Progress.stories.tsx, packages/plasma-new-hope/src/components/Progress/Progress.template-doc.mdx, packages/plasma-tokens-b2b/data/fallbackThemes.ts, packages/plasma-tokens-b2c/data/fallbackThemes.ts, packages/plasma-web/src/components/Progress/Progress.config.ts, packages/plasma-web/src/components/Progress/Progress.stories.tsx, packages/sdds-clfd-auto/src/components/Progress/Progress.config.ts, packages/sdds-clfd-auto/src/components/Progress/Progress.stories.tsx, packages/sdds-dfa/src/components/Progress/Progress.config.ts, packages/sdds-dfa/src/components/Progress/Progress.stories.tsx, packages/sdds-finportal/src/components/Progress/Progress.config.ts, packages/sdds-finportal/src/components/Progress/Progress.stories.tsx, packages/sdds-insol/src/components/Progress/Progress.config.ts, packages/sdds-insol/src/components/Progress/Progress.stories.tsx, packages/sdds-serv/src/components/Progress/Progress.config.ts, packages/sdds-serv/src/components/Progress/Progress.stories.tsx, website/plasma-b2c-docs/docs/components/Progress.mdx, website/plasma-giga-docs/docs/components/Progress.mdx, website/plasma-web-docs/docs/components/Progress.mdx, website/sdds-dfa-docs/docs/components/Progress.mdx, website/sdds-finportal-docs/docs/components/Progress.mdx, website/sdds-insol-docs/docs/components/Progress.mdx, website/sdds-serv-docs/docs/components/Progress.mdx
- Добавлен новый `view` - `info`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.338.0-canary.1975.15203972707.0
npm install @salutejs/plasma-b2c@1.580.0-canary.1975.15203972707.0
npm install @salutejs/plasma-core@1.197.0-canary.1975.15203972707.0
npm install @salutejs/plasma-giga@0.307.0-canary.1975.15203972707.0
npm install @salutejs/plasma-hope@1.341.0-canary.1975.15203972707.0
npm install @salutejs/plasma-new-hope@0.324.0-canary.1975.15203972707.0
npm install @salutejs/plasma-tokens-b2b@1.49.0-canary.1975.15203972707.0
npm install @salutejs/plasma-tokens-b2c@0.60.0-canary.1975.15203972707.0
npm install …
```
=> PLASMA-4207: add info view to progress

packages/plasma-b2c/src/components/PaginationDots/index.ts, packages/plasma-new-hope/src/components/PaginationDots/PaginationDot.tsx, packages/plasma-new-hope/src/components/PaginationDots/PaginationDots.tsx, packages/plasma-new-hope/src/components/PaginationDots/SmartPaginationDots.tsx, packages/plasma-new-hope/src/components/PaginationDots/index.ts, packages/plasma-new-hope/src/components/PaginationDots/usePaginationDots.ts, packages/plasma-new-hope/src/index.ts, packages/plasma-web/src/components/PaginationDots/index.ts
- компонент перенесен внутрь core пакет
- компонент перенесен внутрь core пакет
- компонент перенесен внутрь `new-hope`;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.339.0-canary.1970.15211531960.0
npm install @salutejs/plasma-b2c@1.581.0-canary.1970.15211531960.0
npm install @salutejs/plasma-giga@0.308.0-canary.1970.15211531960.0
npm install @salutejs/plasma-new-hope@0.325.0-canary.1970.15211531960.0
npm install @salutejs/plasma-web@1.583.0-canary.1970.15211531960.0
npm install @salutejs/sdds-clfd-auto@0.312.0-canary.1970.15211531960.0
npm install @salutejs/sdds-crm@0.312.0-canary.1970.15211531960.0
npm install …
```
=> PLASMA-5067: move PaginationDots to the new-hope 

.github/workflows/publish-latest.yml
Чтобы было понятно в какую версию вошли конкретные изменения  добавили эту логику. 
Теперь каждый merged pull request будет содержать такой комментарий
тестировал в песочнице 
https://github.com/Yakutoc/plasma-dev-stage/actions/runs/15203005721/job/42760414538
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.338.1-canary.1987.15271848472.0
npm install @salutejs/plasma-b2c@1.580.1-canary.1987.15271848472.0
npm install @salutejs/plasma-giga@0.307.1-canary.1987.15271848472.0
npm install @salutejs/plasma-hope@1.341.1-canary.1987.15271848472.0
npm install @salutejs/plasma-icons@1.217.1-canary.1987.15271848472.0
npm install …
```
=> PLASMA-4607: Добавление комментария с указанием опубликованных версий в pull request

packages/sdds-scan/src/components/Calendar/CalendarBase.config.ts, packages/sdds-scan/src/components/Calendar/CalendarDouble.config.ts, packages/sdds-scan/src/components/DatePicker/DatePicker.config.ts
исправление неправильно merge components configs для компонентов Календарь и Datepicker   
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.338.1-canary.1997.15290839769.0
npm install @salutejs/plasma-b2c@1.580.1-canary.1997.15290839769.0
npm install @salutejs/plasma-giga@0.307.1-canary.1997.15290839769.0
npm install @salutejs/plasma-hope@1.341.1-canary.1997.15290839769.0
npm install @salutejs/plasma-icons@1.217.1-canary.1997.15290839769.0
npm install @salutejs/plasma-new-hope@0.324.1-canary.1997.15290839769.0
npm install @salutejs/plasma-ui@1.317.1-canary.1997.15290839769.0
npm install @salutejs/plasma-web@1.582.1-canary.1997.15290839769.0
npm install …
```
=> chore(sdds-scan): fix components configs: calendar, datepicker

packages/plasma-new-hope/src/components/NumberFormat/NumberFormat.tsx
- исправлен проброс пропсов
Исправлен проброс пропсов
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.338.1-canary.1998.15294767801.0
npm install @salutejs/plasma-b2c@1.580.1-canary.1998.15294767801.0
npm install @salutejs/plasma-giga@0.307.1-canary.1998.15294767801.0
npm install @salutejs/plasma-hope@1.341.1-canary.1998.15294767801.0
npm install @salutejs/plasma-icons@1.217.1-canary.1998.15294767801.0
npm install @salutejs/plasma-new-hope@0.324.1-canary.1998.15294767801.0
npm install @salutejs/plasma-ui@1.317.1-canary.1998.15294767801.0
npm install @salutejs/plasma-web@1.582.1-canary.1998.15294767801.0
npm install …
```
=> PLASMA-number-formar: fix NumberFormat props pass

package-lock.json, package.json, packages/plasma-giga/package-lock.json, packages/plasma-giga/package.json, packages/plasma-tokens-b2b/package-lock.json, packages/plasma-tokens-b2b/package.json, packages/plasma-tokens-b2c/package-lock.json, packages/plasma-tokens-b2c/package.json, packages/plasma-tokens-web/package-lock.json, packages/plasma-tokens-web/package.json, packages/plasma-tokens/package-lock.json, packages/plasma-tokens/package.json, packages/themes/sdds-themes/package-lock.json, packages/themes/sdds-themes/package.json, utils/plasma-tokens-utils/package-lock.json, utils/plasma-tokens-utils/package.json, utils/plasma-tokens-utils/src/generation.test.ts, utils/plasma-tokens-utils/src/generators/generateColorThemes.test.ts, utils/plasma-tokens-utils/src/generators/generateThemeFromData.test.ts, utils/plasma-tokens-utils/src/generators/generateTypoSystem.test.ts
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.339.0-canary.1991.15256515100.0
npm install @salutejs/plasma-b2c@1.581.0-canary.1991.15256515100.0
npm install @salutejs/plasma-core@1.198.0-canary.1991.15256515100.0
npm install @salutejs/plasma-giga@0.308.0-canary.1991.15256515100.0
npm install @salutejs/plasma-hope@1.342.0-canary.1991.15256515100.0
npm install @salutejs/plasma-new-hope@0.325.0-canary.1991.15256515100.0
npm install @salutejs/plasma-tokens-b2b@1.50.0-canary.1991.15256515100.0
npm install @salutejs/plasma-tokens-b2c@0.61.0-canary.1991.15256515100.0
npm install @salutejs/plasma-tokens-web@1.65.0-canary.1991.15256515100.0
npm install …
```
=> PLASMA-4363: Bump TS@5.6.3

.github/workflows/documentation-deploy-pr.yml
небольшой фикс тайпсенс воркфлоу
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.341.0-canary.2028.15754799902.0
npm install @salutejs/plasma-b2c@1.583.0-canary.2028.15754799902.0
npm install @salutejs/plasma-giga@0.310.0-canary.2028.15754799902.0
npm install @salutejs/plasma-new-hope@0.327.0-canary.2028.15754799902.0
npm install @salutejs/plasma-ui@1.320.0-canary.2028.15754799902.0
npm install @salutejs/plasma-web@1.585.0-canary.2028.15754799902.0
npm install @salutejs/sdds-clfd-auto@0.314.0-canary.2028.15754799902.0
npm install @salutejs/sdds-crm@0.314.0-canary.2028.15754799902.0
npm install @salutejs/sdds-cs@0.319.0-canary.2028.15754799902.0
npm …
```
=> PLASMA-700: Insignificant typesense fix

packages/plasma-new-hope/src/components/Tree/Tree.styles.ts
- исправлен баг, из-за которого в некоторых случаях не отображался цвет выделенного элемента;
- исправлен баг, из-за которого в некоторых случаях не отображался цвет выделенного элемента;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.341.1-canary.2038.15856063493.0
npm install @salutejs/plasma-b2c@1.583.1-canary.2038.15856063493.0
npm install @salutejs/plasma-giga@0.310.1-canary.2038.15856063493.0
npm install @salutejs/plasma-new-hope@0.327.1-canary.2038.15856063493.0
npm install @salutejs/plasma-web@1.585.1-canary.2038.15856063493.0
npm install @salutejs/sdds-clfd-auto@0.314.1-canary.2038.15856063493.0
npm install …
```
=> PLASMA-5249: small fix in Tree

.github/workflows/ci-unit-tests.yml
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.342.0-canary.2057.15970882892.0
npm install @salutejs/plasma-b2c@1.584.0-canary.2057.15970882892.0
npm install @salutejs/plasma-core@1.200.0-canary.2057.15970882892.0
npm install @salutejs/plasma-giga@0.311.0-canary.2057.15970882892.0
npm install @salutejs/plasma-hope@1.345.0-canary.2057.15970882892.0
npm install @salutejs/plasma-new-hope@0.328.0-canary.2057.15970882892.0
npm install @salutejs/plasma-ui@1.321.0-canary.2057.15970882892.0
npm install @salutejs/plasma-web@1.586.0-canary.2057.15970882892.0
npm install @salutejs/sdds-bizcom@0.315.0-canary.2057.15970882892.0
npm install …
```
=> feat(infra): omit react-17 in unit tests

website/plasma-website/components/changelog/ChangelogDescription.styles.tsx, website/plasma-website/components/changelog/ChangelogHeader.styles.tsx, website/plasma-website/components/changelog/ChangelogPullRequestLink.styles.tsx, website/plasma-website/components/main/LinkItem/LinkItem.tsx, website/plasma-website/components/main/Product/Product.tsx, website/plasma-website/public/data/plasma-asdk.json, website/plasma-website/public/data/plasma-b2c.json, website/plasma-website/public/data/plasma-giga.json, website/plasma-website/public/data/plasma-new-hope.json, website/plasma-website/public/data/plasma-web.json, website/plasma-website/public/data/sdds-bizcom.json, website/plasma-website/public/data/sdds-crm.json, website/plasma-website/public/data/sdds-cs.json, website/plasma-website/public/data/sdds-dfa.json, website/plasma-website/public/data/sdds-finportal.json, website/plasma-website/public/data/sdds-insol.json, website/plasma-website/public/data/sdds-netology.json, website/plasma-website/public/data/sdds-scan.json, website/plasma-website/public/data/sdds-serv.json
Правки после ревью 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.343.1-canary.2073.16147553392.0
npm install @salutejs/plasma-b2c@1.585.1-canary.2073.16147553392.0
npm install @salutejs/plasma-giga@0.312.1-canary.2073.16147553392.0
npm install @salutejs/plasma-hope@1.346.1-canary.2073.16147553392.0
npm install @salutejs/plasma-icons@1.219.1-canary.2073.16147553392.0
npm install @salutejs/plasma-new-hope@0.329.1-canary.2073.16147553392.0
npm install @salutejs/plasma-ui@1.322.1-canary.2073.16147553392.0
npm install @salutejs/plasma-web@1.587.1-canary.2073.16147553392.0
npm install @salutejs/sdds-bizcom@0.317.1-canary.2073.16147553392.0
npm install …
```
=> plasma-docs: fix website UI issues 

packages/plasma-b2c/src/components/Combobox/Combobox.component-test.tsx, packages/plasma-giga/src/components/Combobox/Combobox.component-test.tsx, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx, packages/plasma-web/src/components/Combobox/Combobox.component-test.tsx, packages/sdds-cs/src/components/Combobox/Combobox.component-test.tsx, packages/sdds-insol/src/components/Combobox/Combobox.component-test.tsx
- исправлен баг, связанный с невозможностью получить актуальное значение поля ввода после ререндера;
- исправлен баг, связанный с невозможностью получить актуальное значение поля ввода после ререндера;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.345.1-canary.2101.16567377924.0
npm install @salutejs/plasma-b2c@1.587.1-canary.2101.16567377924.0
npm install @salutejs/plasma-giga@0.314.1-canary.2101.16567377924.0
npm install @salutejs/plasma-new-hope@0.331.1-canary.2101.16567377924.0
npm install @salutejs/plasma-web@1.589.1-canary.2101.16567377924.0
npm install @salutejs/sdds-bizcom@0.319.1-canary.2101.16567377924.0
npm install …
```
=> PLASMA-5525: fix issue with textValue after rerender

packages/plasma-new-hope/src/components/TextArea/TextArea.types.tsx
- `labelAriaHidden` необязательное свойство
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.345.1-canary.2108.16589504698.0
npm install @salutejs/plasma-b2c@1.587.1-canary.2108.16589504698.0
npm install @salutejs/plasma-giga@0.314.1-canary.2108.16589504698.0
npm install @salutejs/plasma-new-hope@0.331.1-canary.2108.16589504698.0
npm install @salutejs/plasma-web@1.589.1-canary.2108.16589504698.0
npm install @salutejs/sdds-bizcom@0.319.1-canary.2108.16589504698.0
npm install @salutejs/sdds-crm@0.318.1-canary.2108.16589504698.0
npm install @salutejs/sdds-cs@0.323.1-canary.2108.16589504698.0
npm install @salutejs/sdds-dfa@0.317.1-canary.2108.16589504698.0
npm …
```
=> plasma-core: hotfix 29.07.2025

packages/plasma-new-hope/src/components/TextArea/TextArea.types.tsx
- `labelAriaHidden` необязательное свойство
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.345.2-canary.2107.16589482772.0
npm install @salutejs/plasma-b2c@1.587.2-canary.2107.16589482772.0
npm install @salutejs/plasma-giga@0.314.2-canary.2107.16589482772.0
npm install @salutejs/plasma-new-hope@0.331.2-canary.2107.16589482772.0
npm install @salutejs/plasma-web@1.589.2-canary.2107.16589482772.0
npm install @salutejs/sdds-bizcom@0.319.2-canary.2107.16589482772.0
npm install @salutejs/sdds-crm@0.318.2-canary.2107.16589482772.0
npm install @salutejs/sdds-cs@0.323.2-canary.2107.16589482772.0
npm install @salutejs/sdds-dfa@0.317.2-canary.2107.16589482772.0
npm …
```
=> plasma-core: hotfix 29.07.2025 [Master]

packages/plasma-new-hope/src/components/Segment/Segment.template-doc.mdx, packages/plasma-new-hope/src/components/Tabs/tokens.ts, packages/plasma-new-hope/src/components/Tabs/ui/horizontal/HorizontalTabItem/HorizontalTabItem.styles.ts, packages/plasma-new-hope/src/components/Tabs/ui/horizontal/HorizontalTabItem/variations/_view/base.ts, packages/plasma-new-hope/src/components/Tabs/ui/vertical/VerticalTabItem/VerticalTabItem.styles.ts, packages/plasma-new-hope/src/components/Tabs/ui/vertical/VerticalTabItem/variations/_view/base.ts, packages/sdds-cs/src/components/Tabs/horizontal/HorizontalTabItem.config.ts, packages/sdds-cs/src/components/Tabs/vertical/VerticalTabItem.config.ts, website/plasma-b2c-docs/docs/components/Segment.mdx, website/plasma-giga-docs/docs/components/Segment.mdx, website/plasma-web-docs/docs/components/Segment.mdx, website/sdds-crm-docs/docs/components/Segment.mdx, website/sdds-cs-docs/docs/components/Segment.mdx, website/sdds-dfa-docs/docs/components/Segment.mdx, website/sdds-finportal-docs/docs/components/Segment.mdx, website/sdds-insol-docs/docs/components/Segment.mdx, website/sdds-netology-docs/docs/components/Segment.mdx, website/sdds-scan-docs/docs/components/Segment.mdx, website/sdds-serv-docs/docs/components/Segment.mdx
- исправлен токен, отвечающий за `cursor` при наведении на TabItem
Исправлен токен, отвечающий за `cursor` при наведении на TabItem
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.346.0-canary.2103.16644309163.0
npm install @salutejs/plasma-b2c@1.588.0-canary.2103.16644309163.0
npm install @salutejs/plasma-core@1.204.0-canary.2103.16644309163.0
npm install @salutejs/plasma-giga@0.315.0-canary.2103.16644309163.0
npm install @salutejs/plasma-hope@1.349.0-canary.2103.16644309163.0
npm install @salutejs/plasma-new-hope@0.332.0-canary.2103.16644309163.0
npm install @salutejs/plasma-tokens@1.119.0-canary.2103.16644309163.0
npm install …
```
=> PLASMA-5542: update cursor token for TabItem

packages/sdds-finportal/src/components/IconButton/IconButton.config.ts, packages/sdds-finportal/src/components/IconButton/IconButton.stories.tsx
-  добавлен размер xxs
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.345.1-canary.2119.16774012819.0
npm install @salutejs/plasma-b2c@1.587.1-canary.2119.16774012819.0
npm install @salutejs/plasma-colors@0.15.1-canary.2119.16774012819.0
npm install @salutejs/plasma-core@1.203.1-canary.2119.16774012819.0
npm install @salutejs/plasma-giga@0.314.1-canary.2119.16774012819.0
npm install @salutejs/plasma-hope@1.348.1-canary.2119.16774012819.0
npm install @salutejs/plasma-new-hope@0.331.1-canary.2119.16774012819.0
npm install @salutejs/plasma-tokens-b2b@1.52.1-canary.2119.16774012819.0
npm install @salutejs/plasma-tokens-b2c@0.63.1-canary.2119.16774012819.0 …
```
=> PLASMA-5559: Add xxs iconbutton finportal

utils/plasma-sb-utils/src/helpers/colorTokens.ts
- исправлено регулярное выражение по парсингу категорий токенов цвета
Исправлено регулярное выражение по парсингу категорий токенов цвета
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.346.0-canary.2131.16776545963.0
npm install @salutejs/plasma-b2c@1.588.0-canary.2131.16776545963.0
npm install @salutejs/plasma-colors@0.16.0-canary.2131.16776545963.0
npm install @salutejs/plasma-core@1.204.0-canary.2131.16776545963.0
npm install @salutejs/plasma-giga@0.315.0-canary.2131.16776545963.0
npm install @salutejs/plasma-hope@1.349.0-canary.2131.16776545963.0
npm install @salutejs/plasma-new-hope@0.332.0-canary.2131.16776545963.0
npm install …
```
=> PLASMA-fix-color-token: update RegExp for token category remove

packages/plasma-ui/src/components/Pickers/Picker.tsx, packages/plasma-ui/src/components/Pickers/Pickers.stories.tsx
- добавлена поддержка долгого нажатия клавиши для клавиатурной навигации
Добавлена поддержка долгого нажатия клавиши для клавиатурной навигации
**Before**:
https://github.com/user-attachments/assets/02486ac1-ee6a-4bcf-9c3b-e8243858aa2e
**After**:
https://github.com/user-attachments/assets/ca36c021-245a-44a2-9b19-91dc7ac6ac4d
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.347.0-canary.2130.16931554202.0
npm install @salutejs/plasma-b2c@1.589.0-canary.2130.16931554202.0
npm install @salutejs/plasma-giga@0.316.0-canary.2130.16931554202.0
npm install @salutejs/plasma-new-hope@0.333.0-canary.2130.16931554202.0
npm install …
```
=> PLASMA-4640: add long key press case to Pickers

website/plasma-website/components/main/DraggableContainer/DraggableContainer.styles.ts, website/plasma-website/components/main/DraggableContainer/DraggableContainer.tsx, website/plasma-website/components/main/LinkItem/LinkItem.styles.ts, website/plasma-website/components/main/LinkItem/LinkItem.tsx, website/plasma-website/components/main/Product/Product.styles.ts, website/plasma-website/components/main/Product/Product.tsx, website/plasma-website/components/roster/IconGroupHeading.tsx, website/plasma-website/components/roster/IconsList.tsx, website/plasma-website/pages/icons.tsx, website/plasma-website/pages/index.tsx, website/plasma-website/utils/constants.tsx
- исправлено поведение перетаскивания списков продуктов / групп цветов
- добавлен вывод групп для иконок
- реализован переход на группу иконок с главной страницы
**Before**:
https://github.com/user-attachments/assets/19431aec-e5ca-48db-b7a5-04095103ba2a
**After**:
https://github.com/user-attachments/assets/294d659d-bb61-432c-acf8-af0eb74e759d
Исправлено поведение перетаскивания списков продуктов / групп цветов
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.347.0-canary.2139.16929672501.0
npm install @salutejs/plasma-b2c@1.589.0-canary.2139.16929672501.0
npm install @salutejs/plasma-giga@0.316.0-canary.2139.16929672501.0
npm install …
```
=> PLASMABLDR-38: improve dragging behavior for additional info

packages/plasma-b2c/src/components/Pagination/Pagination.component-test.tsx, packages/plasma-b2c/src/components/Pagination/Pagination.stories.tsx, packages/plasma-giga/src/components/Pagination/Pagination.component-test.tsx, packages/plasma-giga/src/components/Pagination/Pagination.stories.tsx, packages/plasma-new-hope/src/components/Pagination/Pagination.tsx, packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts, packages/plasma-new-hope/src/components/Pagination/ui/PaginationSelectPerPage/PaginationSelectPerPage.tsx, packages/plasma-new-hope/src/components/Pagination/ui/PaginationSelectPerPage/PaginationSelectPerPage.types.ts, packages/plasma-new-hope/src/examples/components/Pagination/Pagination.stories.tsx, packages/plasma-web/src/components/Pagination/Pagination.component-test.tsx, packages/plasma-web/src/components/Pagination/Pagination.stories.tsx, packages/sdds-bizcom/src/components/Pagination/Pagination.stories.tsx, packages/sdds-crm/src/components/Pagination/Pagination.stories.tsx, packages/sdds-cs/src/components/Pagination/Pagination.component-test.tsx, packages/sdds-cs/src/components/Pagination/Pagination.stories.tsx, packages/sdds-dfa/src/components/Pagination/Pagination.stories.tsx, packages/sdds-finportal/src/components/Pagination/Pagination.stories.tsx, packages/sdds-insol/src/components/Pagination/Pagination.component-test.tsx, packages/sdds-insol/src/components/Pagination/Pagination.stories.tsx, packages/sdds-netology/src/components/Pagination/Pagination.stories.tsx, packages/sdds-scan/src/components/Pagination/Pagination.stories.tsx, packages/sdds-serv/src/components/Pagination/Pagination.stories.tsx
- исправлен `controlled` вариант
Исправлен `controlled` вариант
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.347.0-canary.2141.16938167273.0
npm install @salutejs/plasma-b2c@1.589.0-canary.2141.16938167273.0
npm install @salutejs/plasma-core@1.205.0-canary.2141.16938167273.0
npm install @salutejs/plasma-giga@0.316.0-canary.2141.16938167273.0
npm install @salutejs/plasma-hope@1.350.0-canary.2141.16938167273.0
npm install @salutejs/plasma-new-hope@0.333.0-canary.2141.16938167273.0
npm install @salutejs/plasma-tokens@1.120.0-canary.2141.16938167273.0
npm install @salutejs/plasma-ui@1.326.0-canary.2141.16938167273.0
npm install …
```
=> PLASMA-5619: fix controlled Pagination

packages/plasma-new-hope/package-lock.json, packages/plasma-new-hope/package.json, packages/plasma-new-hope/src/components/Popup/Popup.tsx
- убрана ошибка из консоли, связанная с отказом в новых версиях реакта от `findDomApi`.
- убрана ошибка из консоли, связанная с отказом в новых версиях реакта от `findDomApi`.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.348.0-canary.2150.16968566891.0
npm install @salutejs/plasma-b2c@1.590.0-canary.2150.16968566891.0
npm install @salutejs/plasma-giga@0.317.0-canary.2150.16968566891.0
npm install @salutejs/plasma-new-hope@0.334.0-canary.2150.16968566891.0
npm install @salutejs/plasma-web@1.592.0-canary.2150.16968566891.0
npm install @salutejs/sdds-bizcom@0.322.0-canary.2150.16968566891.0
npm install @salutejs/sdds-crm@0.321.0-canary.2150.16968566891.0 …
```
=> PLASMA-5629: idiomatic way to use draggable feature in Popup

website/plasma-website/utils/getColors.ts
* Убрано отображение палитры `warmGray` со страницы сайта
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.348.0-canary.2161.17066464673.0
npm install @salutejs/plasma-b2c@1.590.0-canary.2161.17066464673.0
npm install @salutejs/plasma-giga@0.317.0-canary.2161.17066464673.0
npm install @salutejs/plasma-new-hope@0.334.0-canary.2161.17066464673.0
npm install @salutejs/plasma-web@1.592.0-canary.2161.17066464673.0
npm install @salutejs/sdds-bizcom@0.322.0-canary.2161.17066464673.0
npm install @salutejs/sdds-crm@0.321.0-canary.2161.17066464673.0
npm install @salutejs/sdds-cs@0.326.0-canary.2161.17066464673.0
npm install …
```
=> feat(plasma-website): Remove `warmGray` palette from website page

packages/plasma-new-hope/src/components/Card/Card.styles.ts, packages/plasma-new-hope/src/components/TextField/TextField.tsx, packages/sdds-cs/src/index.ts, website/sdds-cs-docs/docs/components/Card.mdx
- Добавлены примеры использования компонента
- Добавлен в поставку
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.348.0-canary.2009.17056533125.0
npm install @salutejs/plasma-b2c@1.590.0-canary.2009.17056533125.0
npm install @salutejs/plasma-giga@0.317.0-canary.2009.17056533125.0
npm install @salutejs/plasma-new-hope@0.334.0-canary.2009.17056533125.0
npm install @salutejs/plasma-web@1.592.0-canary.2009.17056533125.0
npm install @salutejs/sdds-bizcom@0.322.0-canary.2009.17056533125.0
npm install @salutejs/sdds-crm@0.321.0-canary.2009.17056533125.0
npm install @salutejs/sdds-cs@0.326.0-canary.2009.17056533125.0
npm install …
```
=> PLASMA-4745: add examples for card

website/plasma-web-docs/.gitignore, website/plasma-web-docs/package-lock.json, website/plasma-web-docs/package.json, website/plasma-web-docs/scripts/config.mjs, website/plasma-web-docs/scripts/generateIndex.mjs, website/plasma-web-docs/scripts/generateIndexFiles.mjs, website/plasma-web-docs/scripts/generateMdxLink.mjs, website/plasma-web-docs/scripts/getValidMdxPaths.mjs
Написан кастомный скрапер для сбора индекса документации и дальнейшей отправки в сервис гиги;
=> PLASMA-5653: add doc scraper for AI-search

packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx, packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDatePopover/RangeDatePopover.tsx, packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx, packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.types.ts
- добавлена возможность передавать zIndex в выпадающий календарь
Добавлена возможность передавать zIndex в выпадающий календарь
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.349.0-canary.2181.17260189238.0
npm install @salutejs/plasma-b2c@1.591.0-canary.2181.17260189238.0
npm install @salutejs/plasma-giga@0.318.0-canary.2181.17260189238.0
npm install @salutejs/plasma-new-hope@0.335.0-canary.2181.17260189238.0
npm install @salutejs/plasma-web@1.593.0-canary.2181.17260189238.0
npm install @salutejs/sdds-bizcom@0.323.0-canary.2181.17260189238.0
npm install @salutejs/sdds-crm@0.322.0-canary.2181.17260189238.0
npm install …
```
=> PLASMA-5684: add zIndex to DatePicker

packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.tsx, packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.types.ts
- корректное выведение свойств `value` и `defaultValue` в документации к `Autocomplete`.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.349.0-canary.2176.17242735682.0
npm install @salutejs/plasma-b2c@1.591.0-canary.2176.17242735682.0
npm install @salutejs/plasma-giga@0.318.0-canary.2176.17242735682.0
npm install @salutejs/plasma-new-hope@0.335.0-canary.2176.17242735682.0
npm install @salutejs/plasma-web@1.593.0-canary.2176.17242735682.0
npm install @salutejs/sdds-bizcom@0.323.0-canary.2176.17242735682.0
npm install @salutejs/sdds-crm@0.322.0-canary.2176.17242735682.0
npm install @salutejs/sdds-cs@0.327.0-canary.2176.17242735682.0
npm install …
```
=> PLASMA-5536: update types in Autocomplete

packages/plasma-new-hope/src/components/Tooltip/Tooltip.tsx, packages/plasma-new-hope/src/components/Tooltip/Tooltip.types.ts, packages/plasma-new-hope/src/components/Tooltip/hooks/index.ts, packages/plasma-new-hope/src/components/Tooltip/hooks/useDelayedTooltip.ts
- добавлены свойства `mouseEnterDelay` и `mouseLeaveDelay` для задержки перед открытием/закрытием подсказки;
- добавлены свойства `mouseEnterDelay` и `mouseLeaveDelay` для задержки перед открытием/закрытием подсказки;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.349.0-canary.2186.17306400437.0
npm install @salutejs/plasma-b2c@1.591.0-canary.2186.17306400437.0
npm install @salutejs/plasma-giga@0.318.0-canary.2186.17306400437.0
npm install @salutejs/plasma-new-hope@0.335.0-canary.2186.17306400437.0
npm install @salutejs/plasma-ui@1.328.0-canary.2186.17306400437.0
npm install @salutejs/plasma-web@1.593.0-canary.2186.17306400437.0
npm install …
```
=> PLASMA-5598: add delay after opening Tooltip

website/plasma-b2c-docs/docs/components/Attach.mdx, website/plasma-giga-docs/docs/components/Attach.mdx, website/plasma-web-docs/docs/components/Attach.mdx, website/sdds-crm-docs/docs/components/Attach.mdx, website/sdds-insol-docs/docs/components/Attach.mdx, website/sdds-netology-docs/docs/components/Attach.mdx, website/sdds-scan-docs/docs/components/Attach.mdx, website/sdds-serv-docs/docs/components/Attach.mdx
- переработана документация компонента
- добавлены примеры взаимодействия с формой   
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.348.1-canary.2167.17422727820.0
npm install @salutejs/plasma-b2c@1.590.1-canary.2167.17422727820.0
npm install @salutejs/plasma-core@1.206.1-canary.2167.17422727820.0
npm install @salutejs/plasma-giga@0.317.1-canary.2167.17422727820.0
npm install @salutejs/plasma-hope@1.351.1-canary.2167.17422727820.0
npm install @salutejs/plasma-icons@1.222.1-canary.2167.17422727820.0
npm install @salutejs/plasma-new-hope@0.334.1-canary.2167.17422727820.0
npm install @salutejs/plasma-tokens@1.121.1-canary.2167.17422727820.0
npm install …
```
=> PLASMA-4412: Improved docs for Attach

packages/plasma-new-hope/src/components/Drawer/Drawer.styles.ts
- Добавлена новое свойство для предотвращения дергания экрана
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.348.1-canary.2074.17427595350.0
npm install @salutejs/plasma-b2c@1.590.1-canary.2074.17427595350.0
npm install @salutejs/plasma-core@1.206.1-canary.2074.17427595350.0
npm install @salutejs/plasma-giga@0.317.1-canary.2074.17427595350.0
npm install @salutejs/plasma-hope@1.351.1-canary.2074.17427595350.0
npm install @salutejs/plasma-icons@1.222.1-canary.2074.17427595350.0
npm install @salutejs/plasma-new-hope@0.334.1-canary.2074.17427595350.0
npm install @salutejs/plasma-tokens@1.121.1-canary.2074.17427595350.0
npm install …
```
=> PLASMA-4131: Add scrollbar-gutter to drawer

packages/plasma-b2c/src/components/Drawer/Drawer.component-test.tsx, packages/plasma-new-hope/src/components/Drawer/hooks/useDrawer.ts, packages/plasma-web/src/components/Drawer/Drawer.component-test.tsx
- исправлен баг, при котором `unmount` компонента не очищал свойство `overflow` у `body`;
- исправлен баг, при котором `unmount` компонента не очищал свойство `overflow` у `body`;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.350.0-canary.2208.17550534521.0
npm install @salutejs/plasma-b2c@1.592.0-canary.2208.17550534521.0
npm install @salutejs/plasma-giga@0.319.0-canary.2208.17550534521.0
npm install @salutejs/plasma-new-hope@0.336.0-canary.2208.17550534521.0
npm install @salutejs/plasma-web@1.594.0-canary.2208.17550534521.0
npm install @salutejs/sdds-bizcom@0.324.0-canary.2208.17550534521.0
npm install …
```
=> PLASMA-5770: update useDrawer hook

packages/plasma-new-hope/src/components/NumberFormat/NumberFormat.types.ts, packages/plasma-new-hope/src/components/TextField/TextField.types.ts
Мелкие правки по документации
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.349.1-canary.2207.17463055710.0
npm install @salutejs/plasma-b2c@1.591.1-canary.2207.17463055710.0
npm install @salutejs/plasma-giga@0.318.1-canary.2207.17463055710.0
npm install @salutejs/plasma-new-hope@0.335.1-canary.2207.17463055710.0
npm install @salutejs/plasma-web@1.593.1-canary.2207.17463055710.0
npm install @salutejs/sdds-bizcom@0.323.1-canary.2207.17463055710.0
npm install @salutejs/sdds-crm@0.322.1-canary.2207.17463055710.0
npm install @salutejs/sdds-cs@0.327.1-canary.2207.17463055710.0
npm install @salutejs/sdds-dfa@0.321.1-canary.2207.17463055710.0
npm install …
```
=> PLASMA-5198: Исправления в документации для компонентов `TextField, NumberFormat`  

packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx, packages/plasma-new-hope/src/components/Select/Select.tsx, packages/plasma-new-hope/src/components/TextField/TextField.tokens.ts, packages/plasma-new-hope/src/components/TextField/TextField.tsx
- при закрытии выпадающего списка происходит скролл всех чипов в начало.
- при закрытии выпадающего списка происходит скролл всех чипов в начало.
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.350.0-canary.2231.17732581275.0
npm install @salutejs/plasma-b2c@1.592.0-canary.2231.17732581275.0
npm install @salutejs/plasma-giga@0.319.0-canary.2231.17732581275.0
npm install @salutejs/plasma-new-hope@0.336.0-canary.2231.17732581275.0
npm install @salutejs/plasma-web@1.594.0-canary.2231.17732581275.0
npm install @salutejs/sdds-bizcom@0.324.0-canary.2231.17732581275.0
npm install @salutejs/sdds-crm@0.323.0-canary.2231.17732581275.0
npm install …
```
=> PLASMA-5810: add scrollable block after closing

packages/plasma-new-hope/src/components/Avatar/Avatar.types.ts
- Исправлен `type` для свойства `shape`
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.350.1-canary.2246.17847852413.0
npm install @salutejs/plasma-b2c@1.592.1-canary.2246.17847852413.0
npm install @salutejs/plasma-giga@0.319.1-canary.2246.17847852413.0
npm install @salutejs/plasma-new-hope@0.336.1-canary.2246.17847852413.0
npm install @salutejs/plasma-web@1.594.1-canary.2246.17847852413.0
npm install @salutejs/sdds-bizcom@0.324.1-canary.2246.17847852413.0
npm install @salutejs/sdds-crm@0.323.1-canary.2246.17847852413.0
npm install @salutejs/sdds-cs@0.328.1-canary.2246.17847852413.0
npm install @salutejs/sdds-dfa@0.322.1-canary.2246.17847852413.0
npm …
```
=> plasma-*: Fix avatar prop shape [Hotfix]

packages/plasma-new-hope/src/components/Tooltip/Tooltip.styles.ts
- удален лишний `pointer-events` блокирующий click на содержимом компонента   
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.350.1-canary.2249.17913864682.0
npm install @salutejs/plasma-b2c@1.592.1-canary.2249.17913864682.0
npm install @salutejs/plasma-giga@0.319.1-canary.2249.17913864682.0
npm install @salutejs/plasma-new-hope@0.336.1-canary.2249.17913864682.0
npm install @salutejs/plasma-web@1.594.1-canary.2249.17913864682.0
npm install @salutejs/sdds-bizcom@0.324.1-canary.2249.17913864682.0
npm install @salutejs/sdds-crm@0.323.1-canary.2249.17913864682.0
npm install @salutejs/sdds-cs@0.328.1-canary.2249.17913864682.0
npm install …
```
=> PLASMA-5870: Delete `pointer-events: none`

website/plasma-website/components/roster/IconsList.tsx, website/plasma-website/components/roster/SearchForm.tsx, website/plasma-website/pages/icons.tsx
- Добавлен фильтр для `depricated` иконок 
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.351.0-canary.2261.18122634710.0
npm install @salutejs/plasma-b2c@1.593.0-canary.2261.18122634710.0
npm install @salutejs/plasma-giga@0.320.0-canary.2261.18122634710.0
npm install @salutejs/plasma-new-hope@0.337.0-canary.2261.18122634710.0
npm install @salutejs/plasma-web@1.595.0-canary.2261.18122634710.0
npm install @salutejs/sdds-bizcom@0.325.0-canary.2261.18122634710.0
npm install @salutejs/sdds-crm@0.324.0-canary.2261.18122634710.0
npm install @salutejs/sdds-cs@0.329.0-canary.2261.18122634710.0
npm install @salutejs/sdds-dfa@0.323.0-canary.2261.18122634710.0
npm …
```
=> PLASMABLDR-42: Add depricted checkbox

packages/plasma-new-hope/src/components/Chip/Chip.types.ts, packages/plasma-new-hope/src/examples/components/Chip/Chip.stories.tsx, packages/plasma-new-hope/src/examples/components/Chip/Chip.transparent.config.ts, packages/plasma-new-hope/src/examples/components/Chip/Chip.ts, packages/sdds-finai/src/components/Chip/Chip.stories.tsx, packages/sdds-finai/src/components/Chip/Chip.transparent.config.ts, packages/sdds-finai/src/components/Chip/Chip.tsx
- Добавлена новая конфигурация для `transparent` вариантов
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.351.0-canary.2255.18125301788.0
npm install @salutejs/plasma-b2c@1.593.0-canary.2255.18125301788.0
npm install @salutejs/plasma-giga@0.320.0-canary.2255.18125301788.0
npm install @salutejs/plasma-new-hope@0.337.0-canary.2255.18125301788.0
npm install @salutejs/plasma-web@1.595.0-canary.2255.18125301788.0
npm install @salutejs/sdds-bizcom@0.325.0-canary.2255.18125301788.0
npm install @salutejs/sdds-crm@0.324.0-canary.2255.18125301788.0
npm install @salutejs/sdds-cs@0.329.0-canary.2255.18125301788.0
npm install …
```
=> PLASMA-5766: add chip appearence

packages/plasma-b2c/src/components/Combobox/Combobox.component-test.tsx, packages/plasma-b2c/src/components/Select/Select.component-test.tsx, packages/plasma-giga/src/components/Combobox/Combobox.component-test.tsx, packages/plasma-giga/src/components/Select/Select.component-test.tsx, packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.tsx, packages/plasma-new-hope/src/components/Select/Select.tsx, packages/plasma-web/src/components/Combobox/Combobox.component-test.tsx, packages/plasma-web/src/components/Select/Select.component-test.tsx, packages/sdds-cs/src/components/Combobox/Combobox.component-test.tsx, packages/sdds-cs/src/components/Select/Select.component-test.tsx, packages/sdds-insol/src/components/Combobox/Combobox.component-test.tsx, packages/sdds-insol/src/components/Select/Select.component-test.tsx
- исправлен баг, приводивший к некорректной работе компонента при асинхронной загрузке опций в режиме `multiple`;
- исправлен баг, приводивший к некорректной работе компонента при асинхронной загрузке опций в режиме `multiple`;
<details>
<br />
```bash
npm install @salutejs/plasma-asdk@0.352.0-canary.2268.18222576624.0
npm install @salutejs/plasma-b2c@1.594.0-canary.2268.18222576624.0
npm install @salutejs/plasma-giga@0.321.0-canary.2268.18222576624.0
npm install @salutejs/plasma-new-hope@0.338.0-canary.2268.18222576624.0
npm install @salutejs/plasma-web@1.596.0-canary.2268.18222576624.0
npm install @salutejs/sdds-bizcom@0.326.0-canary.2268.18222576624.0
npm install …
```
=> PLASMA-5939: fix async flow in Combobox

website/sdds-finai-docs/docs/components/IconButton.mdx
Добавлен недостующий пример для размера `xxs `
=> PLASMA-5785: Add xxs size for example [DOC]
